protect rvm bin scripts from failed sourcing of rvm

diff --git a/bin/rvm-exec b/bin/rvm-exec
--- a/bin/rvm-exec
+++ b/bin/rvm-exec
@@ -58,12 +58,22 @@ if [[ -n "$1" && ! -f "$1" && -n "$(echo "$1" | GREP_OPTIONS="" \grep -v '^-')" 
 fi
 
 rvm_shell_rvm_path="$(__rvm_shell_lookup_script)"
-if [[ -n "$rvm_shell_rvm_path" ]]; then
+if
+  [[ -n "$rvm_shell_rvm_path" ]]
+then
   source "$rvm_shell_rvm_path"
+  typeset -f rvm >/dev/null 2>&1 || {
+    echo "RVM not loaded, aborting." >&2
+    exit 1
+  }
   # Setup as expected.
-  if [[ -n "$rvm_shell_ruby_string" ]]; then
+  if
+    [[ -n "$rvm_shell_ruby_string" ]]
+  then
       rvm "$rvm_shell_ruby_string"
-      if [[ "$?" -gt 0 ]]; then
+      if
+        [[ "$?" -gt 0 ]]
+      then
         echo "Error: RVM was unable to use '$rvm_shell_ruby_string'" 1>&2
         exit 1
       fi
