s/aptitude/apt-get/g Many users of Debian certainly and probably other Debian-derived distros prefer 'apt-get' to 'aptitude'. For whatever reasons [Ubuntu has actually stopped shipping with 'aptitude' by default](http://www.webupd8.org/2010/06/aptitude-removed-from-ubuntu-1010.html). Without debating the technical merits of either tool, I would say this:
+ An etiquette argument: 'apt-get' works perfectly well to install packages from the command line. If 'apt-get' is found, there's no reason not to use it. There's certainly no reason to 'install' it on Ubuntu or any machine where it's not even present. Choosing a person's package manager for them is pretty much like dancing with someone's date: it's not done.
+ A more detailed but important reason: 'apt-get' and 'aptitude' now *both* support autoremoval of packages that were installed as dependencies of packages that are no longer installed. However, aptitude will attempt to immediately remove all those items, while 'apt-get' will only prompt you to do so. This is a larger issue+ A more detailed but important reason: 'apt-get' and 'aptitude' now *both* support autoremoval of packages that were installed as dependencies of packages that are no longer installed. However, aptitude will attempt to immediately remove all those items, while 'apt-get' will only prompt you to do so. This is a larger issue+ A morest](+ A more detailed but important reason: 'apt-get' and 'aptitude' now *both* support autoremoval of packages that were installed as dependencies of packages that are no longer installed. However, aptitude will attempt to immediately remove all those items, while 'apt-get' will only prompt you to do so. This is a larger issue+ A more detailed but important ret e

diff --git a/contrib/bootstrap_rails_environment b/contrib/bootstrap_rails_environment
--- a/contrib/bootstrap_rails_environment
+++ b/contrib/bootstrap_rails_environment
@@ -17,15 +17,13 @@ ruby_version="1.8.7"
 sites_path="$HOME/Sites"
 abort=false
 
-if [[ $UID -eq 0 ]] ; then
-
+if (( UID == 0 ))
+then
   printf "ERROR: This script may not be sourced as the root user."
-
   abort=true
-
 else
-
-  if [[ ! -d "$sites_path" ]]; then
+  if [[ ! -d "$sites_path" ]]
+  then
     mkdir -p "$sites_path"
   fi
 
@@ -33,56 +31,51 @@ else
 
   printf "#\n#  Bootstrapping a Rails development environment!\n#\n"
 
-  if [[ "Linux" = "$(uname)" ]]; then
-
+  if [[ $MACHTYPE = *linux* ]]
+  then
     printf "#\n#  Ensuring OS packges are installed, you will be prompted for your password.\n#\n"
-
-    if command -v aptitude || command -v apt-get ; then
-
-      sudo aptitude install build-essential bison openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev
-
-    elif command -v pacman ; then
-
+    if command -v apt-get
+    then
+      sudo apt-get install build-essential bison openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev
+    elif command -v pacman
+    then
       sudo pacman -S --noconfirm gcc patch curl bison zlib readline libxml2 libxslt git autoconf diffutils patch bison make
-
-    elif command -v yum ; then
-
+    elif command -v yum
+    then
       sudo yum install -y gcc-c++ patch readline readline-devel zlib zlib-devel libyaml-devel libffi-devel openssl-devel
-
       sudo yum install -y iconv-devel >/dev/null 2>&1 # NOTE: For centos 5.4 final iconv-devel might not be available :(
-
     fi
-
-  elif [[ "Darwin" = "$(uname)" ]]; then
-    [[ -s /Library/Developer/Shared/XcodeTools.plist ]] || {
+  elif [[ $MACHTYPE = *darwin* ]]
+  then
+    if [[ ! -s /Library/Developer/Shared/XcodeTools.plist ]]
+    then
       printf "Please Install XCode Tools before sourcing this environment bootstrap script."
       abort=true
-    }
+    fi
   fi
-
 fi
 
-if ! $abort ; then
-
+if ! $abort
+then
   printf "Ensuring that git is installed...\n"
-  if command -v git ; then
-
+  if command -v git
+  then
     printf "Found git! Moving right along.\n"
-
   else
-
     printf "=> Installing Git (git command not found)"
-
-    curl -s -L -B https://rvm.beginrescueend.com/install/git -o gitinstall
-
-    chmod +x "$PWD/gitinstall"
-
-    sudo bash "$PWD/gitinstall"
-
-    [[ -f gitinstall ]] && rm -f gitinstall
-
+    if curl -s -L -B https://rvm.beginrescueend.com/install/git -o gitinstall
+    then
+      chmod +x "$PWD/gitinstall"
+      sudo bash "$PWD/gitinstall"
+      if [[ -f gitinstall ]]
+      then
+        rm -f gitinstall
+      fi
+    else
+      printf "ERROR: There was an error while attempting to install git."
+      exit 1
+    fi
   fi
-
   printf "=> Installing RVM the Ruby enVironment Manager\n  https://rvm.beginrescueend.com/rvm/install/\n"
 
   curl -s -O -L -B https://rvm.beginrescueend.com/releases/rvm-install-head
@@ -91,7 +84,10 @@ if ! $abort ; then
 
   "$PWD/rvm-install-head"
 
-  [[ -f rvm-install-head ]] && rm -f rvm-install-head
+  if [[ -f rvm-install-head ]]
+  then
+    rm -f rvm-install-head
+  fi
 
   printf "=> Setting up RVM to load with new shells.\n"
   echo  '[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  # Load RVM into a shell session *as a function*' >> "$HOME/.bash_profile"
@@ -124,12 +120,12 @@ if ! $abort ; then
 
   gem install sqlite3 --no-rdoc --no-ri
 
-  printf "\nRails development environment bootstrapped, please enjoy Rails!\n"
+  printf "
+Rails development environment bootstrapped, please enjoy Rails!
+  ~Wayne E. Seguin <wayneeseguin@gmail.com>
 
-  printf "\n  ~Wayne E. Seguin <wayneeseguin@gmail.com>\n"
-
-  printf "P.S. You should now be able to generate a new Rails Application in ~/Sites with the command 'rails new <name>'\n"
-
+P.S. You should now be able to generate a new Rails Application in ~/Sites with the command 'rails new <name>'
+"
 fi
 
 unset ruby_version rails_version sites_path
