allow escaping in printf texts

diff --git a/scripts/extras/rails b/scripts/extras/rails
--- a/scripts/extras/rails
+++ b/scripts/extras/rails
@@ -62,7 +62,7 @@ rails_routes()
     if [[ -n "${BASH_VERSION:-}" ]] ; then
       shopt -s extglob # Extended globs
     else
-      printf "%s\n" "What the heck kind of shell are you running here???"
+      printf "%b" "What the heck kind of shell are you running here???\n"
     fi
   fi
 
@@ -102,14 +102,14 @@ rails_routes()
   cache_file="tmp/rake/routes"
 
   if ! command -v rake >/dev/null 2>&1 ; then
-    printf "%s" "ERROR: rake not found.\n" >&2
+    printf "%b" "ERROR: rake not found.\n" >&2
     return 1
   fi
 
   case $(uname) in
     Linux)  md5="md5sum" ;;
     Darwin) md5="/sbin/md5 -q" ;;
-    *)      printf "%s" "ERROR: Unknown OS Type.\n" >&2 ;  return 1 ;;
+    *)      printf "%b" "ERROR: Unknown OS Type.\n" >&2 ;  return 1 ;;
   esac
 
   md5_current=$($md5 config/routes.rb)
@@ -127,11 +127,11 @@ rails_routes()
   else
     routes=$(rake routes 2>/dev/null)
     if [[ $? -gt 0 ]]; then
-      printf "%s" "ERROR: There was an error running 'rake routes', does your application load console properly?" >&2
+      printf "%b" "ERROR: There was an error running 'rake routes', does your application load console properly?" >&2
       return 1
     else
-      printf "%s" "$md5_current" > "${cache_file}.md5"
-      printf "%s" "$routes" > "$cache_file"
+      printf "%b" "$md5_current" > "${cache_file}.md5"
+      printf "%b" "$routes" > "$cache_file"
     fi
   fi
   routes="${routes#\|\(in *\)}"
@@ -176,7 +176,7 @@ rails_routes()
   done
 
   for route in ${routes[@]} ; do
-    printf "%s" "${route}\n"
+    printf "%b" "${route}\n"
   done
 
   IFS="$orig_ifs"
@@ -240,7 +240,7 @@ r() {
       ;;
 
     usage)
-      printf "%s" "
+      printf "%b" "
 
 r - Rails shell convenience function
 
@@ -271,7 +271,7 @@ Actions:
 
   else
 
-    printf "%s" "ERROR: rails $action not found!!!"
+    printf "%b" "ERROR: rails $action not found!!!"
 
   fi
 
diff --git a/scripts/functions/logging b/scripts/functions/logging
--- a/scripts/functions/logging
+++ b/scripts/functions/logging
@@ -5,13 +5,13 @@
 # Detect wheter or not the shell is interactive by asking if stdout is a terminal
 if [[ -t 1 ]]
 then
-  eval "rvm_log()   { printf \"%s\" \"\$(tput setaf 2)\$*\$(tput sgr0)\n\" ; }"
-  eval "rvm_debug() { printf \"%s\" \"\$(tput setaf 5)DEBUG: \$*\$(tput sgr0)\n\" ; }"
-  eval "rvm_warn()  { printf \"%s\" \"\$(tput setaf 3)WARN: \$*\$(tput sgr0)\n\" ; }"
-  eval "rvm_error() { printf \"%s\" \"\$(tput setaf 1)ERROR: \$*\$(tput sgr0)\n\" >&2 ; }"
+  eval "rvm_log()   { printf \"%b\" \"\$(tput setaf 2)\$*\$(tput sgr0)\n\" ; }"
+  eval "rvm_debug() { printf \"%b\" \"\$(tput setaf 5)DEBUG: \$*\$(tput sgr0)\n\" ; }"
+  eval "rvm_warn()  { printf \"%b\" \"\$(tput setaf 3)WARN: \$*\$(tput sgr0)\n\" ; }"
+  eval "rvm_error() { printf \"%b\" \"\$(tput setaf 1)ERROR: \$*\$(tput sgr0)\n\" >&2 ; }"
 else
-  rvm_log()   { printf "%s" "$*\n" ; }
-  rvm_debug() { printf "%s" "DEBUG: $*\n" ; }
-  rvm_warn()  { printf "%s" "WARN: $*\n" ; }
-  rvm_error() { printf "%s" "ERROR: $*\n" >&2 ; }
+  rvm_log()   { printf "%b" "$*\n" ; }
+  rvm_debug() { printf "%b" "DEBUG: $*\n" ; }
+  rvm_warn()  { printf "%b" "WARN: $*\n" ; }
+  rvm_error() { printf "%b" "ERROR: $*\n" >&2 ; }
 fi
