safe printf, fix 583

diff --git a/scripts/extras/rails b/scripts/extras/rails
--- a/scripts/extras/rails
+++ b/scripts/extras/rails
@@ -102,14 +102,14 @@ rails_routes()
   cache_file="tmp/rake/routes"
 
   if ! command -v rake >/dev/null 2>&1 ; then
-    printf "ERROR: rake not found.\n" >&2
+    printf "%s" "ERROR: rake not found.\n" >&2
     return 1
   fi
 
   case $(uname) in
     Linux)  md5="md5sum" ;;
     Darwin) md5="/sbin/md5 -q" ;;
-    *)      printf "ERROR: Unknown OS Type.\n" >&2 ;  return 1 ;;
+    *)      printf "%s" "ERROR: Unknown OS Type.\n" >&2 ;  return 1 ;;
   esac
 
   md5_current=$($md5 config/routes.rb)
@@ -127,11 +127,11 @@ rails_routes()
   else
     routes=$(rake routes 2>/dev/null)
     if [[ $? -gt 0 ]]; then
-      printf "ERROR: There was an error running 'rake routes', does your application load console properly?" >&2
+      printf "%s" "ERROR: There was an error running 'rake routes', does your application load console properly?" >&2
       return 1
     else
-      printf "$md5_current" > "${cache_file}.md5"
-      printf "$routes" > "$cache_file"
+      printf "%s" "$md5_current" > "${cache_file}.md5"
+      printf "%s" "$routes" > "$cache_file"
     fi
   fi
   routes="${routes#\|\(in *\)}"
@@ -176,7 +176,7 @@ rails_routes()
   done
 
   for route in ${routes[@]} ; do
-    printf "${route}\n"
+    printf "%s" "${route}\n"
   done
 
   IFS="$orig_ifs"
@@ -240,7 +240,7 @@ r() {
       ;;
 
     usage)
-      printf "
+      printf "%s" "
 
 r - Rails shell convenience function
 
@@ -271,7 +271,7 @@ Actions:
 
   else
 
-    printf "ERROR: rails $action not found!!!"
+    printf "%s" "ERROR: rails $action not found!!!"
 
   fi
 
diff --git a/scripts/functions/installer b/scripts/functions/installer
--- a/scripts/functions/installer
+++ b/scripts/functions/installer
@@ -61,7 +61,7 @@ install_setup()
 
 install_usage()
 {
-  printf "
+  printf "%s" "
   Usage:
 
     ${0} [options]
@@ -83,7 +83,7 @@ check_rubyopt_conditions()
 {
   if [[ -n "${RUBYOPT:-""}" ]]
   then
-    printf "\nWARNING: You have RUBYOPT set in your current environment.
+    printf "%s" "\nWARNING: You have RUBYOPT set in your current environment.
 This may cause rubies to not work as you expect them to as it is not supported
 by all of them If errors show up, please try unsetting RUBYOPT first.\n"
   fi
@@ -91,7 +91,7 @@ by all of them If errors show up, please try unsetting RUBYOPT first.\n"
 
 installation_complete()
 {
-  printf "
+  printf "%s" "
   You must now complete the install by loading RVM in new shells.
 
   If you wish to use RVM in an interactive fashion in your shells then
@@ -111,7 +111,7 @@ installation_complete()
 
 display_thank_you()
 {
-  printf "
+  printf "%s" "
 ${name:-"${USER:-$(id | sed -e 's/^[^(]*(//' -e 's/).*$//')}"},
 
 If you have any questions, issues and/or ideas for improvement please
@@ -136,7 +136,7 @@ I sincerely hope that RVM helps to make your life easier and more enjoyable!!!
 
 upgrade_notes()
 {
-  printf "
+  printf "%s" "
 
 Upgrade Notes
 
@@ -167,7 +167,7 @@ Upgrade Notes
   if [[ -f /etc/profile.d/rvm.sh ]] &&
     ! grep rvm_stored_umask /etc/profile.d/rvm.sh >/dev/null
   then
-    printf "
+    printf "%s" "
   * your RVM loading script \`/etc/profile.d/rvm.sh\` is deprecated
     and causes you to have \`umask g+w\` set in your shell,
     run \`rvm get head --auto\` again to fix your scripts.
@@ -189,7 +189,7 @@ determine_install_path()
       then
         if \grep '^\s*rvm .*$' "$rvmrc" >/dev/null 2>&1
         then
-          printf "\nError: $rvmrc is for rvm settings only.\nrvm CLI may NOT be called from within $rvmrc. \nSkipping the loading of $rvmrc"
+          printf "%s" "\nError: $rvmrc is for rvm settings only.\nrvm CLI may NOT be called from within $rvmrc. \nSkipping the loading of $rvmrc"
           return 1
         else
           source "$rvmrc"
@@ -227,7 +227,7 @@ determine_install_or_upgrade()
 
 print_install_header()
 {
-  printf "
+  printf "%s" "
   RVM:  Shell scripts enabling management of multiple ruby environments.
   RTFM: https://rvm.beginrescueend.com/
   HELP: http://webchat.freenode.net/?channels=rvm (#rvm on irc.freenode.net)
@@ -236,9 +236,9 @@ print_install_header()
 
   if [[ ${upgrade_flag:-0} -eq 1 ]]
   then
-    printf "\nUpgrading the RVM installation in $rvm_path/"
+    printf "%s" "\nUpgrading the RVM installation in $rvm_path/"
   else
-    printf "\nInstalling RVM to $rvm_path/"
+    printf "%s" "\nInstalling RVM to $rvm_path/"
   fi
 }
 
@@ -503,7 +503,7 @@ automatic_profile_setup()
   true ${rvm_auto_flag:=0} ${rvm_loaded_flag:=0}
   if (( rvm_auto_flag == 1 ))
   then
-    printf "Checking rc files... ($rvm_rc_files)"
+    printf "%s" "Checking rc files... ($rvm_rc_files)"
     if (( rvm_loaded_flag == 0 ))
     then
       for rcfile in ${rvm_rc_files[@]}
@@ -518,7 +518,7 @@ automatic_profile_setup()
           if ! grep '.profile' "$rcfile" >/dev/null 2>&1
           then
             echo "    Adding profile sourcing line to $rcfile."
-            printf "
+            printf "%s" "
   # rvm install added line:
   [[ -s \"$rvm_path/.profile\" ]] && source \"$rvm_path/.profile\"
   " >> "$rcfile"
@@ -529,7 +529,7 @@ automatic_profile_setup()
         if ! grep 'source.*\/scripts\/rvm' "$rcfile" >/dev/null 2>&1
         then
           echo "    Adding rvm loading line to $rcfile."
-          printf "
+          printf "%s" "
   # rvm install added:
   [[ -s \"$rvm_scripts_path/rvm\" ]] && . \"$rvm_scripts_path/rvm\"
   " >> "$rcfile"
@@ -641,7 +641,7 @@ migrate_old_gemsets()
 
     if [[ -d "$gemset" ]] && [[ ! -d "$new_path" ]]
     then
-      printf "\n    Renaming $(basename "$gemset") to $(basename "$new_path") for new gemset separator."
+      printf "%s" "\n    Renaming $(basename "$gemset") to $(basename "$new_path") for new gemset separator."
       mv "$gemset" "$new_path"
     fi
   done
@@ -652,7 +652,7 @@ migrate_old_gemsets()
 
     if [[ -d "$gemset" && ! -d "$new_path" ]]
     then
-      printf "\n    Renaming $(basename "$gemset") to $(basename "$new_path") for new gemset separator."
+      printf "%s" "\n    Renaming $(basename "$gemset") to $(basename "$new_path") for new gemset separator."
       mv $gemset $new_path
     fi
   done
@@ -663,7 +663,7 @@ migrate_old_gemsets()
 
     if [[ -d "$gemset" && ! -d "$new_path" ]]
     then
-      printf "\n    Fixing: $(basename "$gemset") to $(basename "$new_path") for new gemset separator."
+      printf "%s" "\n    Fixing: $(basename "$gemset") to $(basename "$new_path") for new gemset separator."
       mv "$gemset" "$new_path"
     fi
   done
@@ -690,7 +690,7 @@ correct_binary_permissions()
 {
   typeset -a files
 
-  printf "\n    Correct permissions for base binaries in $rvm_bin_path..."
+  printf "%s" "\n    Correct permissions for base binaries in $rvm_bin_path..."
 
   mkdir -p "${rvm_bin_path}"
 
@@ -720,7 +720,7 @@ correct_binary_permissions()
 
 install_man_pages()
 {
-  printf "\n    Copying manpages into place.\n"
+  printf "%s" "\n    Copying manpages into place.\n"
 
   files=($(
   builtin cd "$install_source_path/man"
@@ -744,7 +744,7 @@ cleanup_tmp_files()
   ))
   if (( ${#files[@]} > 0 ))
   then
-    printf "\n    Cleanup any .swp files."
+    printf "%s" "\n    Cleanup any .swp files."
     for file in "${files[@]}"
     do
       if [[ -f "$file" ]]
@@ -773,7 +773,7 @@ display_notes()
   then
     upgrade_notes
     check_rubyopt_conditions
-    printf "\nUpgrade of RVM in $rvm_path/ is complete.\n\n"
+    printf "%s" "\nUpgrade of RVM in $rvm_path/ is complete.\n\n"
   else
     if (( ${rvm_user_install_flag:=0} == 1 ))
     then
@@ -781,7 +781,7 @@ display_notes()
     fi
 
     check_rubyopt_conditions
-    printf "\nInstallation of RVM to $rvm_path/ is complete.\n\n"
+    printf "%s" "\nInstallation of RVM to $rvm_path/ is complete.\n\n"
   fi
 }
 
@@ -886,7 +886,7 @@ system_check()
       return 0 # Accounted for, continue.
     ;;
     *)
-      printf "Installing RVM as root is currently only supported on the following known OS's (uname):\n  Linux, FreeBSD, OpenBSD, Darwin and SunOS\nWhereas your OS is reported as '$os'" >&2
+      printf "%s" "Installing RVM as root is currently only supported on the following known OS's (uname):\n  Linux, FreeBSD, OpenBSD, Darwin and SunOS\nWhereas your OS is reported as '$os'" >&2
       return 1
     ;;
   esac
@@ -913,7 +913,7 @@ setup_etc_profile()
 
   if ! [[ -s "${etc_profile_file}" ]] || (( ${rvm_auto_flag:-0} == 1 ))
   then
-    printf "#
+    printf "%s" "#
 # RVM profile
 #
 # /etc/profile.d/rvm.sh # sh extension required for loading.
@@ -977,7 +977,7 @@ fi
     if (( add_to_profile_flag )) &&
       ! grep "source ${etc_profile_file}" /etc/profile >/dev/null 2>&1
     then
-      printf "\nsource ${etc_profile_file}\n" >> /etc/profile
+      printf "%s" "\nsource ${etc_profile_file}\n" >> /etc/profile
     fi
 
     for zshrc_file in $( find /etc/ -name zshrc -type f 2>/dev/null || true )
@@ -985,7 +985,7 @@ fi
       if ! grep "source /etc/bash" "${zshrc_file}" &&
         ! grep "source /etc/profile" "${zshrc_file}"
       then
-        printf "\nsource ${etc_profile_file}\n" >> $zshrc_file
+        printf "%s" "\nsource ${etc_profile_file}\n" >> $zshrc_file
       fi
     done
   fi
@@ -1036,7 +1036,7 @@ setup_user_profile()
     then
       if [[ ! -s "${etc_profile_file}" ]]
       then
-        printf "
+        printf "%s" "
 [[ -s \"$HOME/.rvm/scripts/rvm\" ]] && source \"$HOME/.rvm/scripts/rvm\" # Load RVM into a shell session *as a function*
 " >> "$profile_file"
       fi
