Added Sanity checks to two more locations.

diff --git a/binscripts/rvm b/binscripts/rvm
--- a/binscripts/rvm
+++ b/binscripts/rvm
@@ -1,13 +1,22 @@
 #!/usr/bin/env bash
 
-if [[ -f /etc/rvmrc ]] ; then source /etc/rvmrc ; fi
-if [[ -f "$HOME/.rvmrc" ]] ; then source "$HOME/.rvmrc" ; fi
+for rvmrc in /etc/rvmrc $HOME/.rvmrc ; do
+  if [[ -f "$rvmrc" ]] ; then
+    if grep -q '^rvm .*$' $rvmrc ; then
+      echo -e "Error: $rvmrc is for rvm settings only.\nrvm CLI may NOT be called from within $rvmrc. \nSkipping the loading of $rvmrc"
+      exit 1
+    else
+      source "$rvmrc"
+    fi
+  fi
+done
+
 if [[ -z "$rvm_prefix" ]] ; then unset rvm_prefix ; fi
 if [[ -z "$rvm_path" ]] ; then unset rvm_path ; fi
 
-if [[ -z "$rvm_prefix" ]] ; then 
+if [[ -z "$rvm_prefix" ]] ; then
   if [[ "root" = "$(whoami)" ]] ; then
-    rvm_prefix="/usr/local" 
+    rvm_prefix="/usr/local"
   else
     rvm_prefix="$HOME"
   fi
