improved rvm_path detection, closes #586

diff --git a/binscripts/rvm b/binscripts/rvm
--- a/binscripts/rvm
+++ b/binscripts/rvm
@@ -27,18 +27,13 @@ fi
 export rvm_path
 if [[ -z "${rvm_path:-}" ]]
 then
-  if (( UID == 0 ))
-  then
-    rvm_path="/usr/local/rvm"
+  if (( UID == 0 )) && [[ -d "/usr/local/rvm" ]]
+  then rvm_path="/usr/local/rvm"
   elif [[ -d "${HOME}/.rvm" ]]
-  then
-    rvm_path="${HOME}/.rvm"
+  then rvm_path="${HOME}/.rvm"
   elif [[ -d "/usr/local/rvm" ]]
-  then
-    rvm_path="/usr/local/rvm"
-  else
-    echo "Can't find rvm install!" 1>&2
-    exit 1
+  then rvm_path="/usr/local/rvm"
+  else echo "Can't find rvm install!" 1>&2 ; exit 1
   fi
 fi
 
diff --git a/binscripts/rvm-shell b/binscripts/rvm-shell
--- a/binscripts/rvm-shell
+++ b/binscripts/rvm-shell
@@ -19,15 +19,17 @@ then
   done
 fi
 
+export rvm_path
 if [[ -z "${rvm_path:-}" ]]
 then
-  if (( UID == 0 ))
-  then
-    rvm_path="/usr/local/rvm"
-  else
-    rvm_path="${HOME}/.rvm"
+  if (( UID == 0 )) && [[ -d "/usr/local/rvm" ]]
+  then rvm_path="/usr/local/rvm"
+  elif [[ -d "${HOME}/.rvm" ]]
+  then rvm_path="${HOME}/.rvm"
+  elif [[ -d "/usr/local/rvm" ]]
+  then rvm_path="/usr/local/rvm"
+  else echo "Can't find rvm install!" 1>&2 ; exit 1
   fi
-  export rvm_path
 fi
 
 true ${rvm_scripts_path:="$rvm_path/scripts"}
diff --git a/scripts/base b/scripts/base
--- a/scripts/base
+++ b/scripts/base
@@ -57,29 +57,26 @@ Error:
   done
 fi
 
-#
-# Load general scripts and functions
-#
-#
-# Load the general scripts.
-# Use rvm_base_except="selector", for example, to override the loading.
-#
+export rvm_path
 if [[ -z "${rvm_path:-}" ]]
 then
-  if (( UID == 0 ))
-  then
-    rvm_path="/usr/local/rvm"
-  else
-    rvm_path="${HOME}/.rvm"
+  if (( UID == 0 )) && [[ -d "/usr/local/rvm" ]]
+  then rvm_path="/usr/local/rvm"
+  elif [[ -d "${HOME}/.rvm" ]]
+  then rvm_path="${HOME}/.rvm"
+  elif [[ -d "/usr/local/rvm" ]]
+  then rvm_path="/usr/local/rvm"
+  else echo "Can't find rvm install!" 1>&2 ; exit 1
   fi
 fi
-export rvm_path
 
 true ${rvm_scripts_path:="$rvm_path/scripts"}
 
 # Initialize all main RVM variables.
 source "$rvm_scripts_path/initialize"
 
+# Load the general scripts.
+# Use rvm_base_except="selector", for example, to override the loading.
 case " $rvm_base_except " in
   (*[[:space:]]selector[[:space:]]*)
     true # do not load.
