Implement rvm_ignore_rvmrc, to do installs without rvmrc files

diff --git a/binscripts/rvm b/binscripts/rvm
--- a/binscripts/rvm
+++ b/binscripts/rvm
@@ -1,15 +1,17 @@
 #!/usr/bin/env bash
 
-for rvmrc in /etc/rvmrc "$HOME/.rvmrc" ; do
-  if [[ -f "$rvmrc" ]] ; then
-    if grep -q '^\s*rvm .*$' "$rvmrc" ; then
-      printf "\nError: $rvmrc is for rvm settings only.\nrvm CLI may NOT be called from within $rvmrc. \nSkipping the loading of $rvmrc"
-      exit 1
-    else
-      source "$rvmrc"
+if [[ -z "$rvm_ignore_rvmrc" ]]; then
+  for rvmrc in /etc/rvmrc "$HOME/.rvmrc" ; do
+    if [[ -f "$rvmrc" ]] ; then
+      if grep -q '^\s*rvm .*$' "$rvmrc" ; then
+        printf "\nError: $rvmrc is for rvm settings only.\nrvm CLI may NOT be called from within $rvmrc. \nSkipping the loading of $rvmrc"
+        exit 1
+      else
+        source "$rvmrc"
+      fi
     fi
-  fi
-done
+  done
+fi
 
 [[ -z "$rvm_prefix" ]] && unset rvm_prefix
 [[ -z "$rvm_path" ]]   && unset rvm_path
