Improve rvm-shell to take into account .rvmrc

diff --git a/binscripts/rvm-shell b/binscripts/rvm-shell
--- a/binscripts/rvm-shell
+++ b/binscripts/rvm-shell
@@ -10,22 +10,24 @@ __rvm_shell_lookup_script() {
   done
 }
 
-# If the first argument isn't -c, remove it and set
-# it to the ruby string value.
-if [[ -n "$1" && -n "$(echo "$1" | grep -v '^-')" ]]; then
+# If the first argument isn't -c, remove it and set it to the ruby string value.
+if [[ -n "$1" && ! -f "$1" && -n "$(echo "$1" | grep -v '^-')" ]]; then
   rvm_shell_ruby_string="$1"
   shift
 fi
 
-if [[ -n "$rvm_shell_ruby_string" ]]; then
-  rvm_shell_rvm_path="$(__rvm_shell_lookup_script)"
-  if [[ -n "$rvm_shell_rvm_path" ]]; then
-    source "$rvm_shell_rvm_path"
-    rvm "$rvm_shell_ruby_string"
-    if [[ "$?" -gt 0 ]]; then
-      echo "Error: RVM was unable to use '#$rvm_shell_ruby_string'" 1>&2
-      exit 1
-    fi
+rvm_shell_rvm_path="$(__rvm_shell_lookup_script)"
+if [[ -n "$rvm_shell_rvm_path" ]]; then
+  source "$rvm_shell_rvm_path"
+  # Setup as expected.
+  if [[ -n "$rvm_shell_ruby_string" ]]; then
+      rvm "$rvm_shell_ruby_string"
+      if [[ "$?" -gt 0 ]]; then
+        echo "Error: RVM was unable to use '$rvm_shell_ruby_string'" 1>&2
+        exit 1
+      fi
+  else
+    rvm load-rvmrc >/dev/null 2>&1
   fi
 fi
 
