set -u should be outlawed :-p

diff --git a/binscripts/rvm-exec b/binscripts/rvm-exec
--- a/binscripts/rvm-exec
+++ b/binscripts/rvm-exec
@@ -2,12 +2,20 @@
 
 export HOME="${HOME%%+(\/)}" # Remove trailing slashes if they exist on HOME
 
-if [[ ${rvm_ignore_rvmrc:-0} -eq 0 ]]; then
-  for rvmrc in /etc/rvmrc "$HOME/.rvmrc" ; do
-    if [[ -f "$rvmrc" ]] ; then
-      if \grep '^\s*rvm .*$' $rvmrc >/dev/null 2>&1 ; then
-        printf "\nError: $rvmrc is for rvm settings only.\nrvm CLI may NOT be called from within $rvmrc. \nSkipping the loading of $rvmrc"
-        return 1
+if (( ${rvm_ignore_rvmrc:=0} == 0 ))
+then
+  for rvmrc in /etc/rvmrc "$HOME/.rvmrc"
+  do
+    if [[ -f "$rvmrc" ]]
+    then
+      if grep '^\s*rvm .*$' "$rvmrc" >/dev/null 2>&1
+      then
+        printf "\n  Error:
+    $rvmrc is for rvm settings only.
+    rvm CLI may NOT be called from within $rvmrc.
+    Skipping the loading of $rvmrc
+"
+        exit 1
       else
         source "$rvmrc"
       fi
@@ -15,54 +23,34 @@ if [[ ${rvm_ignore_rvmrc:-0} -eq 0 ]]; then
   done
 fi
 
-if [[ -z "${rvm_path:-}" ]] ; then
-
-  # Set the default sandboxed value.
-  # TODO: Alter the variable names to make sense
-  if [[ -z "${rvm_user_install_flag:-""}" ]]; then
-
-    if [[ $UID -eq 0 || -n "$rvm_prefix" && "$rvm_prefix" != "$HOME"/* ]]; then
-      rvm_user_install_flag=0
-    else
-      rvm_user_install_flag=1
-    fi
-
+if (( ${rvm_user_install_flag:-0} == 0 ))
+then
+  if (( UID == 0 )) || [[ "${rvm_prefix:-}" != "$HOME" ]]
+  then
+    rvm_user_install_flag=0
+  else
+    rvm_user_install_flag=1
   fi
+fi
 
-  if [[ -z "${rvm_prefix:-""}" ]] ; then
-
-    if (( rvm_user_install_flag == 0 ))
-    then
-      rvm_prefix="/usr/local/"
-    elif [[ -n "$HOME" ]]
-    then
-      rvm_prefix="$HOME/."
-    else
-      echo "No \$rvm_prefix was provided and "
-      echo "$(id | \sed -e's/^[^(]*(//' -e 's/).*//') has no \$HOME defined."
-      echo "Halting loading of RVM."
-      rvm_load_rvm=0
-    fi
-
+if [[ -z "${rvm_prefix:-""}" ]]
+then
+  if (( ${rvm_user_install_flag:=0} == 0 ))
+  then
+    rvm_prefix="/usr/local"
+  else
+    rvm_prefix="$HOME"
   fi
+fi
 
-  # Fix rvm_prefix changes.
-  [[ "${rvm_prefix}" != *[/.] && -d "${rvm_prefix/rvm/scripts}" ]]
-
-  rvm_prefix_needs_trailing_slash="$?"
-
-  if [[ "$rvm_prefix" = "/usr/local" || "$rvm_prefix_needs_trailing_slash" = "0" ]]; then
-
-    rvm_prefix="$rvm_prefix/"
-
+if [[ -z "${rvm_path:-""}" ]]
+then
+  if [[ "$rvm_prefix" = "$HOME" ]]
+  then
+    rvm_path="${rvm_prefix}/.rvm"
+  else
+    rvm_path="${rvm_prefix}/rvm"
   fi
-
-  if [[ -z "${rvm_path:-""}" ]] ; then
-    rvm_path="${rvm_prefix}rvm"
-  fi
-
-  export rvm_path="${rvm_path%%+(\/)}"
-
 fi
 
 true ${rvm_scripts_path:="$rvm_path/scripts"}
diff --git a/binscripts/rvm-installer b/binscripts/rvm-installer
--- a/binscripts/rvm-installer
+++ b/binscripts/rvm-installer
@@ -127,16 +127,54 @@ shopt -s extglob
 set -o errtrace
 set -o errexit
 
-true ${rvm_ignore_rvmrc:=0}
+if (( ${rvm_ignore_rvmrc:=0} == 0 ))
+then
+  for rvmrc in /etc/rvmrc "$HOME/.rvmrc"
+  do
+    if [[ -f "$rvmrc" ]]
+    then
+      if grep '^\s*rvm .*$' "$rvmrc" >/dev/null 2>&1
+      then
+        printf "\n  Error:
+    $rvmrc is for rvm settings only.
+    rvm CLI may NOT be called from within $rvmrc.
+    Skipping the loading of $rvmrc
+"
+        exit 1
+      else
+        source "$rvmrc"
+      fi
+    fi
+  done
+fi
 
-if [[ $UID -eq 0 ]] ; then
-  [[ $rvm_ignore_rvmrc -eq 0 && -s /etc/rvmrc ]] && source /etc/rvmrc
-  true "${rvm_path:="/usr/local/rvm"}"
-else
-  [[ $rvm_ignore_rvmrc -eq 0 && -s "$HOME/.rvmrc" ]] && source "$HOME/.rvmrc"
+if (( ${rvm_user_install_flag:=0} == 0 ))
+then
+  if (( UID == 0 )) || [[ "${rvm_prefix:-}" != "$HOME" ]]
+  then
+    rvm_user_install_flag=0
+  else
+    rvm_user_install_flag=1
+  fi
+fi
 
-  if [[ -z "${rvm_path:-}" || "${rvm_path}" = "/usr/local/rvm" ]] ; then
-    rvm_path="$HOME/.rvm"
+if [[ -z "${rvm_prefix:-""}" ]]
+then
+  if (( ${rvm_user_install_flag:=0} == 0 ))
+  then
+    rvm_prefix="/usr/local"
+  else
+    rvm_prefix="$HOME"
+  fi
+fi
+
+if [[ -z "${rvm_path:-""}" ]]
+then
+  if [[ "$rvm_prefix" = "$HOME" ]]
+  then
+    rvm_path="${rvm_prefix}/.rvm"
+  else
+    rvm_path="${rvm_prefix}/rvm"
   fi
 fi
 
diff --git a/binscripts/rvm-shell b/binscripts/rvm-shell
--- a/binscripts/rvm-shell
+++ b/binscripts/rvm-shell
@@ -2,12 +2,20 @@
 
 export HOME="${HOME%%+(\/)}" # Remove trailing slashes if they exist on HOME
 
-if [[ ${rvm_ignore_rvmrc:-0} -eq 0 ]]; then
-  for rvmrc in /etc/rvmrc "$HOME/.rvmrc" ; do
-    if [[ -f "$rvmrc" ]] ; then
-      if \grep '^\s*rvm .*$' $rvmrc >/dev/null 2>&1 ; then
-        printf "\nError: $rvmrc is for rvm settings only.\nrvm CLI may NOT be called from within $rvmrc. \nSkipping the loading of $rvmrc"
-        return 1
+if (( ${rvm_ignore_rvmrc:=0} == 0 ))
+then
+  for rvmrc in /etc/rvmrc "$HOME/.rvmrc"
+  do
+    if [[ -f "$rvmrc" ]]
+    then
+      if grep '^\s*rvm .*$' "$rvmrc" >/dev/null 2>&1
+      then
+        printf "\n  Error:
+    $rvmrc is for rvm settings only.
+    rvm CLI may NOT be called from within $rvmrc.
+    Skipping the loading of $rvmrc
+"
+        exit 1
       else
         source "$rvmrc"
       fi
@@ -15,62 +23,40 @@ if [[ ${rvm_ignore_rvmrc:-0} -eq 0 ]]; then
   done
 fi
 
-if [[ -z "${rvm_path:-}" ]] ; then
-
-  # Set the default sandboxed value.
-  # TODO: Alter the variable names to make sense
-  if [[ -z "${rvm_user_install_flag:-""}" ]]; then
-
-    if [[ $UID -eq 0 || -n "$rvm_prefix" && "$rvm_prefix" != "$HOME"/* ]]; then
-      rvm_user_install_flag=0
-    else
-      rvm_user_install_flag=1
-    fi
-
-  fi
-
-  if [[ -z "${rvm_prefix:-""}" ]] ; then
-
-    if (( rvm_user_install_flag == 0 ))
-    then
-      rvm_prefix="/usr/local/"
-    elif [[ -n "$HOME" ]]
-    then
-      rvm_prefix="$HOME/."
-    else
-      echo "No \$rvm_prefix was provided and "
-      echo "$(id | \sed -e's/^[^(]*(//' -e 's/).*//') has no \$HOME defined."
-      echo "Halting loading of RVM."
-      rvm_load_rvm=0
-    fi
-
-  fi
-
-  # Fix rvm_prefix changes.
-  if [[ "${rvm_prefix}" != *[/.] ]]
+if (( ${rvm_user_install_flag:=0} == 0 ))
+then
+  if (( UID == 0 )) || [[ "${rvm_prefix:-}" != "$HOME" ]]
   then
-    true "${rvm_prefix/rvm/scripts}"
+    rvm_user_install_flag=0
+  else
+    rvm_user_install_flag=1
   fi
+fi
 
-  rvm_prefix_needs_trailing_slash="$?"
-
-  if [[ "$rvm_prefix" = "/usr/local" || "$rvm_prefix_needs_trailing_slash" = "0" ]]
+if [[ -z "${rvm_prefix:-""}" ]]
+then
+  if (( ${rvm_user_install_flag:=0} == 0 ))
   then
-    rvm_prefix="$rvm_prefix/"
+    rvm_prefix="/usr/local"
+  else
+    rvm_prefix="$HOME"
   fi
+fi
 
-  if [[ -z "${rvm_path:-""}" ]]
+if [[ -z "${rvm_path:-""}" ]]
+then
+  if [[ "$rvm_prefix" = "$HOME" ]]
   then
-    rvm_path="${rvm_prefix}rvm"
+    rvm_path="${rvm_prefix}/.rvm"
+  else
+    rvm_path="${rvm_prefix}/rvm"
   fi
-
-  export rvm_path="${rvm_path%%+(\/)}"
-
 fi
 
 true ${rvm_scripts_path:="$rvm_path/scripts"}
 
-__rvm_shell_lookup_script() {
+__rvm_shell_lookup_script()
+{
   local relative_scripts_dir
   relative_scripts_dir="$(dirname -- "$(dirname -- "$0")")/scripts"
   for directory in "$rvm_scripts_path" "$HOME/.rvm/scripts" "/usr/local/rvm/scripts" "$relative_scripts_dir"; do
