remove fail from verify_package_pgp in rvm_installer

diff --git a/binscripts/rvm-installer b/binscripts/rvm-installer
--- a/binscripts/rvm-installer
+++ b/binscripts/rvm-installer
@@ -382,6 +382,7 @@ Could not download '${_url}'.
   }
 }
 
+# duplication marker flnglfdjkngjndkfjhsbdjgfghdsgfklgg
 rvm_install_gpg_setup()
 {
   export rvm_gpg_command
@@ -392,6 +393,7 @@ rvm_install_gpg_setup()
   [[ -n "$rvm_gpg_command" ]] || return $?
 }
 
+# duplication marker rdjgndfnghdfnhgfdhbghdbfhgbfdhbn
 verify_package_pgp()
 {
   if
@@ -399,7 +401,8 @@ verify_package_pgp()
   then
     log "GPG verified '$1'"
   else
-    fail "GPG signature verification failed for '$1' - '$3'!
+    typeset _ret=$?
+    log "GPG signature verification failed for '$1' - '$3'!
 try downloading the signatures:
 
     ${rvm_gpg_command##*/} --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
@@ -409,6 +412,7 @@ they can be compared with:
     https://rvm.io/mpapis.asc
     https://keybase.io/mpapis
 "
+    return _ret
   fi
 }
 
