Improve rvm-installer error handling & error messaging (#4731)

diff --git a/binscripts/rvm-installer b/binscripts/rvm-installer
--- a/binscripts/rvm-installer
+++ b/binscripts/rvm-installer
@@ -27,7 +27,9 @@ rvm_install_initialize()
 
 log()  { printf "%b\n" "$*"; }
 debug(){ [[ ${rvm_debug_flag:-0} -eq 0 ]] || printf "%b\n" "$*" >&2; }
-fail() { log "\nERROR: $*\n" >&2 ; exit 1 ; }
+warn() { log "WARN: $*" >&2 ; }
+fail() { fail_with_code 1 "$*" ; }
+fail_with_code() { code="$1" ; shift ; log "\nERROR: $*\n" >&2 ; exit "$code" ; }
 
 rvm_install_commands_setup()
 {
@@ -257,6 +259,7 @@ fetch_version()
       return 0
     fi
   done
+  fail_with_code 4 "Exhausted all sources trying to fetch version '$version' of RVM!"
 }
 
 # Returns a sorted list of most recent tags from a repository
@@ -278,7 +281,8 @@ fetch_versions()
       _url=https://${_domain}/api/v3/repos/${_account}/${_repo}/tags
       ;;
   esac
-  __rvm_curl -sS ${_url} |
+
+  { __rvm_curl -sS "${_url}" || warn "...the preceeding error with code $? occurred while fetching $_url" ; } |
     \awk -v RS=',|values":' -v FS='"' '$2=="name"&&$4!="rvm"{print $4}' |
     sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n -k 5,5n
 }
@@ -827,7 +831,7 @@ and re-mount partition ${partition} without the noexec option."
 
 rvm_install_select_and_get_version()
 {
-  typeset _version_release
+  typeset dir _version_release _version
 
   for dir in "$rvm_src_path" "$rvm_archives_path"
   do
@@ -838,24 +842,27 @@ rvm_install_select_and_get_version()
   case "${version}" in
     (head)
       _version_release="${branch}"
-      install_head sources[@] ${branch:-master} || exit $?
+      install_head sources[@] ${branch:-master}
       ;;
 
     (latest)
-      install_release sources[@] $(fetch_version sources[@]) || exit $?
+      _version=$(fetch_version sources[@])
+      install_release sources[@] "$_version"
       ;;
 
     (latest-minor)
-      version="$(\cat "$rvm_path/VERSION")"
-      install_release sources[@] $(fetch_version sources[@] ${version%.*}) || exit $?
+      version="$(<"$rvm_path/VERSION")"
+      _version=$(fetch_version sources[@] ${version%.*})
+      install_release sources[@] "$_version"
       ;;
 
     (latest-*)
-      install_release sources[@] $(fetch_version sources[@] ${version#latest-}) || exit $?
+      _version=$(fetch_version sources[@] ${version#latest-})
+      install_release sources[@] "$_version"
       ;;
 
     (+([[:digit:]]).+([[:digit:]]).+([[:digit:]])) # x.y.z
-      install_release sources[@] ${version} || exit $?
+      install_release sources[@] ${version}
       ;;
 
     (*)
