improve rvm_path detection for evm-auto-ruby, fix #728

diff --git a/binscripts/rvm-auto-ruby b/binscripts/rvm-auto-ruby
--- a/binscripts/rvm-auto-ruby
+++ b/binscripts/rvm-auto-ruby
@@ -1,5 +1,37 @@
 #!/usr/bin/env bash
 
+export HOME="${HOME%%+(\/)}" # Remove trailing slashes if they exist on HOME
+
+if (( ${rvm_ignore_rvmrc:=0} == 0 ))
+then
+  for rvmrc in /etc/rvmrc "$HOME/.rvmrc"
+  do
+    if [[ -f "$rvmrc" ]]
+    then
+      if \grep '^\s*rvm .*$' "$rvmrc" >/dev/null 2>&1
+      then
+        printf "%b" "\nError: $rvmrc is for rvm settings only.\nrvm CLI may NOT be called from within $rvmrc. \nSkipping the loading of $rvmrc"
+        return 1
+      else
+        source "$rvmrc"
+      fi
+    fi
+  done
+fi
+
+export rvm_path
+if [[ -z "${rvm_path:-}" ]]
+then
+  if (( UID == 0 )) && [[ -d "/usr/local/rvm" ]]
+  then rvm_path="/usr/local/rvm"
+  elif [[ -d "${HOME}/.rvm" ]]
+  then rvm_path="${HOME}/.rvm"
+  elif [[ -d "/usr/local/rvm" ]]
+  then rvm_path="/usr/local/rvm"
+  else echo "Can't find rvm install!" 1>&2 ; exit 1
+  fi
+fi
+
 true ${rvm_scripts_path:="$rvm_path/scripts"}
 true ${rvm_environments_path:="$rvm_path/environments"}
 
