improve bash version detection, update #918, also add ZSH version detection

diff --git a/binscripts/rvm-installer b/binscripts/rvm-installer
--- a/binscripts/rvm-installer
+++ b/binscripts/rvm-installer
@@ -1,15 +1,10 @@
 #!/usr/bin/env bash
 
-BASH_MAJOR_REQUIRED=3
-BASH_MINOR_REQUIRED=2
-BASH_MAJOR=${BASH_VERSION:0:1}
-BASH_MINOR=${BASH_VERSION:2:1}
-if [[ 1 != $(($BASH_MAJOR > $BASH_MAJOR_REQUIRED ||
-    $BASH_MAJOR == $BASH_MAJOR_REQUIRED &&
-        $BASH_MINOR >= $BASH_MINOR_REQUIRED)) ]]; then
-    echo -n "bash v$BASH_MAJOR_REQUIRED.$BASH_MINOR_REQUIRED required" \
-    "(you have $BASH_VERSION)"
-    exit 1
+if [[ -n "${BASH_VERSION:-}" ]] &&
+  (( 65536 * ${BASH_VERSINFO[0]} + 256 * ${BASH_VERSINFO[1]} + ${BASH_VERSINFO[2]} >= 197168 ))
+then
+  echo "BASH 3.2.48 required (you have $BASH_VERSION)"
+  exit 1
 fi
 
 shopt -s extglob
