Swithed install head script to use https, install latest script now checks md5.

diff --git a/binscripts/rvm-update-head b/binscripts/rvm-update-head
--- a/binscripts/rvm-update-head
+++ b/binscripts/rvm-update-head
@@ -25,23 +25,16 @@ if [[ -d ./rvm ]] ; then
   rm -rf ./rvm/
 fi
 
-http_url="http://github.com/wayneeseguin/rvm.git"
+git_url="git://github.com/wayneeseguin/rvm.git"
+https_url="https://github.com/wayneeseguin/rvm.git"
 
-if ! git clone "$http_url" ; then
+if ! git clone "$git_url" ; then
 
-  printf "
-ERROR: Cloning from $http_url failed,
-       perhaps your git version does not support the http protocol?
-       Trying git:// protocol now.
-"
+  printf "\nERROR: Cloning from $git_url failed, trying via https now ($https_url).\n"
 
-  git_url="git://github.com/wayneeseguin/rvm.git"
+  if ! git clone "$https_url" ; then
 
-  if ! git clone "$git_url" ; then
-
-    printf "
-ERROR: Cloning from $git_url failed, out of ideas... halting.
-"
+    printf "\nERROR: Cloning from $https_url failed, perhaps your git version does not support the https protocol?  out of ideas... halting.\n"
 
     exit 1
 
diff --git a/binscripts/rvm-update-latest b/binscripts/rvm-update-latest
--- a/binscripts/rvm-update-latest
+++ b/binscripts/rvm-update-latest
@@ -11,17 +11,36 @@ rvm_path="${rvm_path:-$HOME/.rvm}"
 cd $rvm_path/src
 
 stable_version=$(curl -B http://rvm.beginrescueend.com/releases/stable-version.txt 2>/dev/null)
+stable_md5=$(curl -B http://rvm.beginrescueend.com/releases/rvm-${stable_version}.tar.gz.md5 2>/dev/null)
 
 echo "rvm-${stable_version}"
 
 curl -L "http://rvm.beginrescueend.com/releases/rvm-${stable_version}.tar.gz" -o "rvm-${stable_version}.tar.gz"
 
+case "$(uname)" in
+  Darwin|FreeBSD)
+    archive_md5="$(/sbin/md5 -q "${archive}")"
+    ;;
+  OpenBSD)
+    archive_md5="$(/bin/md5 -q "${archive}")"
+    ;;
+  Linux|*)
+    archive_md5="$(md5sum "${archive}" | awk '{print $1}')"
+    ;;
+esac
+
+if [[ "$archive_md5" != "$stable_md5" ]]; then
+  printf "ERROR:
+  Archive package rvm-${stable_version}.tar.gz downloaded does not match it's md5 checksum ${stable_md5}.
+  Aborting RVM Installation.
+"
+  exit 1
+fi
+
 tar zxf "rvm-${stable_version}.tar.gz"
 
 cd "rvm-${stable_version}"
 
-# v v v This is a godo idea however it does not preserve the executible bit.
-# Needs more thought, perhaps a simple sed instead.
-#dos2unix scripts/* >/dev/null 2>&1
+chmod +x ./scripts/install
 
-bash scripts/install
+./scripts/install
