move check for bison to generic location and make sure rbx uses it too, closes #1631

diff --git a/scripts/functions/build_config b/scripts/functions/build_config
--- a/scripts/functions/build_config
+++ b/scripts/functions/build_config
@@ -5,7 +5,7 @@ __rvm_setup_compile_environment()
   typeset __type
   typeset -a __types
   __types=(
-    requirements osx_gcc architectures gcc47 smartos sunos openbsd
+    requirements osx_gcc architectures gcc47 bison smartos sunos openbsd
     flags_docs flags_tcltk flags_shared_static flags_threads
   )
   for __type in "${__types[@]}"
@@ -84,6 +84,22 @@ __rvm_setup_compile_environment_osx_gcc()
         ;;
     esac
   fi
+}
+
+__rvm_setup_compile_environment_bison()
+{
+  # TODO: what should we do for autolibs=1 ? should it fail or just warn when bison is missing
+  (( ${rvm_autolibs_flag:=1} > 0 )) || return 0
+  case "$1" in
+    (ruby*|ree*|rbx*)
+      __rvm_check_for_bison ||
+      {
+        result=$?
+        rvm_error "Bison required but not found. Halting."
+        return $result
+      }
+      ;;
+  esac
 }
 
 __rvm_setup_compile_environment_architectures_default()
