add code to prevent broken xcode-select link, fix #2313

diff --git a/scripts/functions/build_config b/scripts/functions/build_config
--- a/scripts/functions/build_config
+++ b/scripts/functions/build_config
@@ -5,7 +5,8 @@ __rvm_setup_compile_environment()
   typeset __type
   typeset -a __types
   __types=(
-    setup movable_early requirements movable osx_compiler architectures gcc47plus bison smartos
+    setup movable_early system_early
+    requirements movable osx_compiler architectures gcc47plus bison smartos
     openindiana sunos openbsd auto_conf_make flags_docs flags_tcltk flags_shared_static
     flags_threads compatibility_flag
   )
@@ -67,6 +68,28 @@ please install SMF and switch autolibs to it (make sure to follow any displayed 
       esac
       ;;
   esac
+}
+
+__rvm_setup_compile_environment_system_early_osx()
+{
+  # Cleanup broken devtools setup
+  typeset __xcode_dir_path
+  if
+    [[ -r "/usr/share/xcode-select/xcode_dir_path" ]] &&
+    __xcode_dir_path="$( cat /usr/share/xcode-select/xcode_dir_path 2>/dev/null )" &&
+    [[ -n "${__xcode_dir_path}" && ! -d "${__xcode_dir_path}" ]]
+  then
+    rm -f "/usr/share/xcode-select/xcode_dir_path"
+  fi
+}
+
+__rvm_setup_compile_environment_system_early()
+{
+  if
+    is_a_function __rvm_setup_compile_environment_system_early${_system_name_lowercase}
+  then
+    __rvm_setup_compile_environment_system_early_${_system_name_lowercase} "$@" || return $?
+  fi
 }
 
 #
