try to remove old bin files, fix #810

diff --git a/scripts/functions/installer b/scripts/functions/installer
--- a/scripts/functions/installer
+++ b/scripts/functions/installer
@@ -368,6 +368,8 @@ ensure_scripts_are_executable()
 
 install_binscripts()
 {
+  typeset -a files
+  typeset system_bin
   files=(rvm-prompt rvm-installer rvm rvmsudo rvm-shell rvm-smile rvm-exec rvm-auto-ruby)
 
   if [[ ! -d "${rvm_bin_path}" ]]
@@ -387,10 +389,19 @@ install_binscripts()
 
     [[ -x "${rvm_bin_path}/${file}" ]] || chmod +x "${rvm_bin_path}/${file}"
 
-    if [[ "${source_path}/binscripts" != "${rvm_bin_path}" ]]
-    then
-      cp -f "${source_path}/binscripts/${file}" "${rvm_bin_path}/${file}"
-    fi
+    # try to clean old installer files left in usual places added to PATH
+    for system_bin in ~/bin /usr/local/bin
+    do
+      if [[ "${system_bin}" != "${rvm_bin_path}" && -x "${system_bin}/${file}" ]]
+      then
+        if ! rm -f "${system_bin}/${file}" 2>/dev/null
+        then
+          printf "!!! could not remove ${system_bin}/${file}, remove it manually with:
+!!! > sudo rm -f ${system_bin}/${file}
+"
+        fi
+      fi
+    done
   done
 
   # optional binscripts
