add warning about missing shell initalization entries for RVM, cleaning logging in installation, fix #1850

diff --git a/scripts/functions/installer b/scripts/functions/installer
--- a/scripts/functions/installer
+++ b/scripts/functions/installer
@@ -59,7 +59,7 @@ install_setup()
 
 install_usage()
 {
-  printf "%b" "
+  rvm_out "
   Usage:
 
     ${0} [options]
@@ -81,7 +81,7 @@ install_usage()
 
 display_thank_you()
 {
-  printf "%b" "
+  rvm_out "
 # ${name:-"${USER:-$(id | sed -e 's/^[^(]*(//' -e 's/).*$//')}"},
 #
 #   Thank you for using RVM!
@@ -120,8 +120,8 @@ determine_install_or_upgrade()
 print_install_header()
 {
   if [[ ${upgrade_flag:-0} -eq 1 ]]
-  then printf "%b" "\nUpgrading the RVM installation in $rvm_path/\n"
-  else printf "%b" "\nInstalling RVM to $rvm_path/\n"
+  then rvm_out "\nUpgrading the RVM installation in $rvm_path/"
+  else rvm_out "\nInstalling RVM to $rvm_path/"
   fi
 }
 
@@ -148,6 +148,8 @@ load_env_preserving()
   rvm_scripts_path="${PWD%%+(\/)}/scripts"
   source "$PWD/scripts/initialize"
   source "$PWD/scripts/functions/init"
+  source "$PWD/scripts/functions/support"
+  source "$PWD/scripts/functions/logging"
   source "$PWD/scripts/version"
   __rvm_initialize
 
@@ -409,7 +411,7 @@ install_binscripts()
         [[ "${system_bin}" != "${rvm_bin_path}" && -x "${system_bin}/${file}" ]]
       then
         \rm -f "${system_bin}/${file}" 2>/dev/null ||
-        printf "%b" "!!! could not remove ${system_bin}/${file}, remove it manually with:
+        rvm_out "!!! could not remove ${system_bin}/${file}, remove it manually with:
 !!! > sudo \rm -f ${system_bin}/${file}
 "
       fi
@@ -530,7 +532,7 @@ update_gemsets_install_rvm()
     if
       (( ${#missing[@]} > 0 ))
     then
-      printf "    Installing rvm gem in ${#missing[@]} gemsets "
+      printf "%b" "    Installing rvm gem in ${#missing[@]} gemsets "
       for _iterator in "${missing[@]}"
       do
         rvm "${_iterator##*/}" do gem install rvm | awk '{printf "."}'
@@ -602,7 +604,7 @@ migrate_old_gemsets()
     if
       [[ -d "$gemset" ]] && [[ ! -d "$new_path" ]]
     then
-      printf "%b" "\n    Renaming $(basename "$gemset") to $(basename "$new_path") for new gemset separator."
+      rvm_out "    Renaming $(basename "$gemset") to $(basename "$new_path") for new gemset separator."
       \mv "$gemset" "$new_path"
     fi
   done
@@ -613,7 +615,7 @@ migrate_old_gemsets()
     if
       [[ -d "$gemset" && ! -d "$new_path" ]]
     then
-      printf "%b" "\n    Renaming $(basename "$gemset") to $(basename "$new_path") for new gemset separator."
+      rvm_out "    Renaming $(basename "$gemset") to $(basename "$new_path") for new gemset separator."
       \mv $gemset $new_path
     fi
   done
@@ -624,7 +626,7 @@ migrate_old_gemsets()
     if
       [[ -d "$gemset" && ! -d "$new_path" ]]
     then
-      printf "%b" "\n    Fixing: $(basename "$gemset") to $(basename "$new_path") for new gemset separator."
+      rvm_out "    Fixing: $(basename "$gemset") to $(basename "$new_path") for new gemset separator."
       \mv "$gemset" "$new_path"
     fi
   done
@@ -718,7 +720,7 @@ install_man_pages()
       install_fix_rights $rvm_man_path/${file%\/*}
     }
     \cp -Rf "$install_source_path/man/$file" "$rvm_man_path/$file" || \
-      printf "%b" "
+      rvm_out "
 
     Please run the installer using rvmsudo to fix file permissions
 
@@ -735,7 +737,7 @@ cleanup_tmp_files()
   if
     (( ${#files[@]} > 0 ))
   then
-    printf "%b" "\n    Cleanup any .swp files."
+    rvm_out "    Cleanup any .swp files."
     for file in "${files[@]}"
     do
       if [[ -f "$file" ]]
@@ -769,23 +771,19 @@ display_notes()
     (( upgrade_flag == 0 ))
   then
     profile_file="${user_profile_file:-${etc_profile_file:-$rvm_path/scripts/rvm}}"
-    printf "%b" "$itype of RVM in $rvm_path/ is almost complete:
-"
+    rvm_out "$itype of RVM in $rvm_path/ is almost complete:"
     if
       (( ${rvm_user_install_flag:=0} == 0 ))
     then
-      printf "%b" "
+      rvm_out "
   * First you need to add all users that will be using rvm to '${rvm_group_name}' group,
-    and logout - login again, anyone using rvm will be operating with \`umask u=rwx,g=rwx,o=rx\`.
-"
+    and logout - login again, anyone using rvm will be operating with \`umask u=rwx,g=rwx,o=rx\`."
     fi
-    printf "%b" "
+    rvm_out "
   * To start using RVM you need to run \`source ${profile_file}\`
-    in all your open shell windows, in rare cases you need to reopen all shell windows.
-"
+    in all your open shell windows, in rare cases you need to reopen all shell windows."
   else
-    printf "%b" "$itype of RVM in $rvm_path/ is complete.
-"
+    rvm_out "$itype of RVM in $rvm_path/ is complete."
   fi
 }
 
@@ -849,11 +847,11 @@ system_check()
   typeset os
   os=$(uname)
   case "$os" in
-    OpenBSD|Linux|FreeBSD|Darwin|SunOS)
+    OpenBSD|Linux|FreeBSD|Darwin|SunOS|GNU*)
       return 0 # Accounted for, continue.
     ;;
     *)
-      printf "%b" "Installing RVM as root is currently only supported on the following known OS's (uname):\n  Linux, FreeBSD, OpenBSD, Darwin and SunOS\nWhereas your OS is reported as '$os'" >&2
+      rvm_error "Installing RVM as root is currently only supported on the following known OS's (uname):\n  Linux, FreeBSD, OpenBSD, Darwin and SunOS\nWhereas your OS is reported as '$os'" >&2
       return 1
     ;;
   esac
@@ -1067,7 +1065,7 @@ pick_a_file()
   eval "${_result}+=( \"\$1\" )"
 }
 
-setup_user_profile()
+setup_user_profile_check()
 {
   (( UID > 0 )) || return 0
   if
@@ -1082,21 +1080,14 @@ setup_user_profile()
     fi
   fi
   [[ "${rvm_ignore_dotfiles_flag:-${rvm_ignore_dotfiles:-no}}" == "no"  ]] || return 0
+}
 
-  export user_profile_file
-  export -a user_login_files user_rc_files
-  typeset -a search_list target_rc target_login found_rc found_login
-  typeset etc_profile_file profile_file local_rvm_path local_rvm_path_sed
-  local_rvm_path="${rvm_path/#$HOME/\$HOME}"
-  local_rvm_path_sed="\\${local_rvm_path//\./\\.}"
-  local_rvm_path_sed="${local_rvm_path_sed//\//\/}"
-
+setup_user_profile_detect()
+{
   etc_profile_file="/etc/profile.d/rvm.sh"
-  search_list=(
-    ~/.profile
-    ~/.bashrc ~/.bash_profile ~/.bash_login
-    ~/.zshenv ~/.zprofile ~/.zshrc ~/.zlogin
-  )
+  search_list_bash=( ~/.bashrc ~/.bash_profile ~/.bash_login )
+  search_list_zsh=( ~/.zshenv ~/.zprofile ~/.zshrc ~/.zlogin )
+  search_list=( ~/.profile ${search_list_bash[@]} ${search_list_zsh[@]} )
 
   target_rc=( ~/.bashrc ~/.zshrc )
 
@@ -1125,11 +1116,38 @@ setup_user_profile()
       fi
     fi
   done
+}
 
+setup_user_profile_summary()
+{
+  eval "typeset __list_found=\"\${${1}[*]}\""
+  typeset __target="$2"
+  rvm_log "    RVM ${__target} line found in ${__list_found}."
+
+  typeset __bash_included=0
+  typeset  __zsh_included=0
+  __rvm_string_includes "${__list_found}" "${search_list_bash[@]}" || __bash_included=$?
+  __rvm_string_includes "${__list_found}" "${search_list_zsh[@]}"  ||  __zsh_included=$?
+
+  typeset __missing=""
+  if (( __bash_included>0 && __zsh_included>0  ))
+  then __missing="Bash nor ZSH"
+  elif (( __bash_included>0 ))
+  then __missing="Bash"
+  elif (( __zsh_included>0 ))
+  then __missing="ZSH"
+  fi
+  if [[ -n "${__missing}" ]]
+  then rvm_warn "    RVM ${__target} line not found for ${__missing}, run the installer with '--auto-dotfiles' to fix it."
+  fi
+}
+
+setup_user_profile_rc()
+{
   if
     (( rvm_auto_dotfiles_flag == 1 && ${#found_rc[@]} > 0 ))
   then
-    printf "%b" "    Removing rvm PATH line from ${found_rc[*]}.\n"
+    rvm_out "    Removing rvm PATH line from ${found_rc[*]}."
     for profile_file in ${found_rc[@]}
     do
       __rvm_sed_i "${profile_file}" -e '/PATH=.*'"$local_rvm_path_sed"'\/bin/ d;'
@@ -1141,7 +1159,7 @@ setup_user_profile()
   if
     (( rvm_auto_dotfiles_flag == 1 || ${#found_rc[@]} == 0 ))
   then
-    printf "%b" "    Adding rvm PATH line to ${target_rc[*]}.\n"
+    rvm_out "    Adding rvm PATH line to ${target_rc[*]}."
     for profile_file in ${target_rc[@]}
     do
       touch $profile_file
@@ -1151,13 +1169,17 @@ PATH=\$PATH:$local_rvm_path/bin # Add RVM to PATH for scripting
     done
     user_rc_files=( ${target_rc[@]} )
   else
-    printf "%b" "    RVM PATH line found in ${found_rc[*]}.\n"
+    setup_user_profile_summary found_rc "PATH"
     user_rc_files=( ${found_rc[@]} )
   fi
+}
+
+setup_user_profile_login()
+{
   if
     (( rvm_auto_dotfiles_flag == 1 && ${#found_login[@]} > 0 ))
   then
-    printf "%b" "    Removing rvm loading line from ${found_login[*]}.\n"
+    rvm_out "    Removing rvm loading line from ${found_login[*]}."
     for profile_file in ${found_login[@]}
     do
       __rvm_sed_i "${profile_file}" -e '/source.*scripts\/rvm/ d; /\. .*scripts\/rvm/ d;'
@@ -1169,7 +1191,7 @@ PATH=\$PATH:$local_rvm_path/bin # Add RVM to PATH for scripting
   if
     (( rvm_auto_dotfiles_flag == 1 || ${#found_login[@]} == 0 ))
   then
-    printf "%b" "    Adding rvm loading line to ${target_login[*]}.\n"
+    rvm_out "    Adding rvm loading line to ${target_login[*]}."
     for profile_file in ${target_login[@]}
     do
       touch $profile_file
@@ -1179,10 +1201,29 @@ PATH=\$PATH:$local_rvm_path/bin # Add RVM to PATH for scripting
     done
     user_login_files=( ${target_login[@]} )
   else
-    printf "%b" "    RVM sourcing line found in ${found_login[*]}.\n"
+    setup_user_profile_summary found_login "sourcing"
     user_login_files=( ${found_login[@]} )
   fi
-  return 0
+}
+
+setup_user_profile()
+{
+  setup_user_profile_check || return $?
+
+  export user_profile_file
+  export -a user_login_files user_rc_files
+  typeset -a search_list search_list_bash search_list_zsh
+  typeset -a target_rc target_login found_rc found_login
+  typeset etc_profile_file profile_file local_rvm_path local_rvm_path_sed
+  local_rvm_path="${rvm_path/#$HOME/\$HOME}"
+  local_rvm_path_sed="\\${local_rvm_path//\./\\.}"
+  local_rvm_path_sed="${local_rvm_path_sed//\//\/}"
+
+  setup_user_profile_detect
+  setup_user_profile_rc
+  setup_user_profile_login
+
+  true # for osx
 }
 
 root_canal()
