Replace inline tput calls with a wrapper

diff --git a/scripts/functions/logging b/scripts/functions/logging
--- a/scripts/functions/logging
+++ b/scripts/functions/logging
@@ -34,9 +34,9 @@ rvm_pretty_print()
 
 if rvm_pretty_print stdout
 then
-  eval "rvm_log()   { printf \"%b\" \"$(tput setaf 2)\$*$(tput sgr0)\n\" ; }"
-  eval "rvm_debug() { printf \"%b\" \"$(tput setaf 5)DEBUG: \$*$(tput sgr0)\n\" ; }"
-  eval "rvm_warn()  { printf \"%b\" \"$(tput setaf 3)WARN: \$*$(tput sgr0)\n\" ; }"
+  eval "rvm_log()   { printf \"%b\" \"$(__rvm_tput setaf 2)\$*$(__rvm_tput sgr0)\n\" ; }"
+  eval "rvm_debug() { printf \"%b\" \"$(__rvm_tput setaf 5)DEBUG: \$*$(__rvm_tput sgr0)\n\" ; }"
+  eval "rvm_warn()  { printf \"%b\" \"$(__rvm_tput setaf 3)WARN: \$*$(__rvm_tput sgr0)\n\" ; }"
 else
   rvm_log()   { printf "%b" "$*\n" ; }
   rvm_debug() { printf "%b" "DEBUG: $*\n" ; }
@@ -45,7 +45,7 @@ fi
 
 if rvm_pretty_print stderr
 then
-  eval "rvm_error() { printf \"%b\" \"$(tput setaf 1)ERROR: \$*$(tput sgr0)\n\" >&2 ; }"
+  eval "rvm_error() { printf \"%b\" \"$(__rvm_tput setaf 1)ERROR: \$*$(__rvm_tput sgr0)\n\" >&2 ; }"
 else
   rvm_error() { printf "%b" "ERROR: $*\n" >&2 ; }
 fi
