move checking certificates for ruby to scripts/functions/osx-ssl-certs, update #2254

diff --git a/scripts/functions/osx-ssl-certs b/scripts/functions/osx-ssl-certs
--- a/scripts/functions/osx-ssl-certs
+++ b/scripts/functions/osx-ssl-certs
@@ -136,6 +136,26 @@ __rvm_osx_ssl_certs_file_for_ruby()
   "${1:-ruby}" -ropenssl -e 'puts OpenSSL::X509::DEFAULT_CERT_FILE'
 }
 
+__rvm_osx_ssl_certs_ensure_for_ruby()
+{
+  [[ "${_system_name}" == "OSX" ]] || return 0
+  source "$rvm_scripts_path/functions/osx-ssl-certs"
+
+  typeset ssl_dir cert_file
+  cert_file="$( __rvm_osx_ssl_certs_file_for_ruby "$1" )"
+  ssl_dir="${cert_file%/*}"
+  if
+    requirements_osx_update_openssl_cert_old
+  then
+    rvm_requiremnts_fail_or_run_action 2 \
+      "Skipping update of certificates in '$cert_file'." \
+      requirements_osx_update_openssl_cert_run ||
+      true # Ignore failure - ruby is already installed
+  fi
+  true # for osx
+}
+
+
 __rvm_osx_ssl_certs_file_from_openssl()
 {
   "${1:-openssl}" version -d | __rvm_awk -F'"' '{print $2"/cert.pem"}'
