More robust generated rvmrc files, better error handling.

diff --git a/scripts/functions/rvmrc b/scripts/functions/rvmrc
--- a/scripts/functions/rvmrc
+++ b/scripts/functions/rvmrc
@@ -318,13 +318,20 @@ environment_id=\"$identifier\"
 # insert the word 'use' after --create as this triggers verbose mode.
 #
 if [[ -d \"\${rvm_path:-\$HOME/.rvm}/environments\" \\
-  && -s \"\${rvm_path:-\$HOME/.rvm}/environments/\$environment_id\" ]] ; then
+  && -s \"\${rvm_path:-\$HOME/.rvm}/environments/\$environment_id\" ]]
+then
   \\. \"\${rvm_path:-\$HOME/.rvm}/environments/\$environment_id\"
 
-  [[ -s \".rvm/hooks/after_use\" ]] && . \".rvm/hooks/after_use\"
+  if [[ -s \".rvm/hooks/after_use\" ]]
+  then
+    . \".rvm/hooks/after_use\"
+  fi
 else
   # If the environment file has not yet been created, use the RVM CLI to select.
-  rvm --create $flags \"\$environment_id\"
+  if ! rvm --create $flags \"\$environment_id\"
+  then
+    echo \"Failed to create RVM environment '${environment_id}'.\"
+  fi
 fi
 
 #
