show how to fix non login shells, fix #864

diff --git a/scripts/functions/utility b/scripts/functions/utility
--- a/scripts/functions/utility
+++ b/scripts/functions/utility
@@ -318,6 +318,27 @@ is_parent_of()
   return 1
 }
 
+rvm_is_not_a_shell_function_check()
+{
+  if [[ "${rvm_is_not_a_shell_function:-0}" == "1" ]]
+  then
+    if rvm_pretty_print stderr
+    then
+      printf "%b" "\n${rvm_notify_clr:-}RVM is not a function, selecting rubies with '${rvm_error_clr:-}rvm use ...${rvm_notify_clr:-}' will not work.${rvm_reset_clr:-}\n" >&2
+    else
+      printf "%b" "\nRVM is not a function, selecting rubies with 'rvm use ...' will not work.\n" >&2
+    fi
+    if is_parent_of gnome-terminal $$ >/dev/null
+    then
+      rvm_log "Please visit https://rvm.beginrescueend.com/integration/gnome-terminal/ for a solution.\n" >&2
+    else
+      rvm_log "You need to change your terminal settings to allow shell login.
+Please visit https://rvm.beginrescueend.com/workflow/screen/ for example.\n" >&2
+    fi
+  fi
+  return ${rvm_is_not_a_shell_function:-0}
+}
+
 __rvm_detect_xcode_version()
 {
   typeset version_file
