fix removing gemsets, update #2267

diff --git a/scripts/functions/manage/base b/scripts/functions/manage/base
--- a/scripts/functions/manage/base
+++ b/scripts/functions/manage/base
@@ -510,22 +510,36 @@ __rvm_gemset_pristine_all()
   done
 }
 
+__rvm_remove_gemsets__()
+{
+  typeset gemset
+  typeset -a gemsets
+  __rvm_read_lines gemsets <(
+    __rvm_find -L "${rvm_gems_path:-"$rvm_path/gems"}" -maxdepth 1 \
+      "${name_opt}" "${rvm_ruby_string}" -o \
+      "${name_opt}" "${rvm_ruby_string}@*"
+  )
+  for gemset in "${gemsets[@]}"
+  do
+    printf "Removing $gemset - "
+    __rvm_rm_rf "$gemset" && printf "ok\n" ||
+    {
+      typeset __res=$?
+      echo "failed\n"
+      return ${__res}
+    }
+  done
+}
+
 __rvm_remove_gemsets()
 {
-  typeset gemset gemsets
   if
     (( ${rvm_gems_flag:=0} == 1 ))
   then
-    rvm_log "Removing $rvm_ruby_string gemsets..."
-
-    gemsets=( $(__rvm_find -L "${rvm_gems_path:-"$rvm_path/gems"}" -maxdepth 1 "${name_opt}" "${rvm_ruby_string}*" -type d))
-    for gemset in "${gemsets[@]}"
-    do
-      if [[ -d "$gemset" ]]
-      then __rvm_rm_rf "$gemset"
-      fi
-    done
+    __rvm_log_command remove_gemsets "Removing $rvm_ruby_string gemsets" __rvm_remove_gemsets__ ||
+      return $?
   fi
+  true # for OSX
 }
 
 __rvm_remove_wrappers()
