add support for binary ruby, reworked fetching and packaging, extract remote file and extension building, closes #1241

diff --git a/scripts/functions/manage/base b/scripts/functions/manage/base
--- a/scripts/functions/manage/base
+++ b/scripts/functions/manage/base
@@ -265,11 +265,11 @@ __rvm_install_ruby_try_remote()
   : rvm_disable_binary_flag:${rvm_disable_binary_flag:=0}: rvm_remote_flag:${rvm_remote_flag:=0}:
   (( rvm_disable_binary_flag )) ||
   {
-    rubies=($(
-      __list_remote_rubies_for "$( __rvm_remote_server_path "${rvm_ruby_string//\./\.}\.tar\..*" )"
-    ))
-    case ${#rubies[@]} in
-      (0)
+    typeset __rvm_ruby_url
+    __rvm_ruby_url="$( __rvm_remote_server_path "${rvm_ruby_string}" )"
+    if
+      [[ -z "${__rvm_ruby_url}" ]]
+    then
         if
           (( rvm_remote_flag ))
         then
@@ -279,28 +279,16 @@ __rvm_install_ruby_try_remote()
           rvm_warn "No binary rubies available for: $(__rvm_system_path -)/${rvm_ruby_string}.
 Continuing with compilation. Please read 'rvm mount' to get more information on binary rubies."
         fi
-        ;;
-      (1)
+    else
         if
-          rvm_remote_flag=1 "${rvm_scripts_path}/external" mount "$rvm_ruby_string"
+          rvm_remote_flag=1 "${rvm_scripts_path}/external" mount "${__rvm_ruby_url}" "${rvm_ruby_string}"
         then
           return 0
         else
-          __rvm_rm_rf "$rvm_rubies_path/$rvm_ruby_string"
+          __rvm_rm_rf "$rvm_rubies_path/$rvm_ruby_string" # cleanup so standard installation works
           rvm_warn "Mounting remote ruby failed, trying to compile."
         fi
-        ;;
-      (*)
-        if
-          (( rvm_remote_flag ))
-        then
-          rvm_error "Requested binary installation but multiple rubies are available to download, this most likely is a bug, please report an issue!"
-          return 1
-        else
-          rvm_warn "More then one binary ruby found, this most likely is a bug, please report an issue!"
-        fi
-        ;;
-    esac
+    fi
   }
   return 2 # continue with compilation
 }
@@ -549,29 +537,18 @@ __rvm_fetch_ruby()
     then
       mkdir -p "${rvm_tmp_path:-/tmp}/rvm_src_$$"
 
-      case "$rvm_archive_extension" in
-        tar.gz|tgz)
-          _current_command=(
-            "$rvm_tar_command" xzf "${rvm_archives_path}/$rvm_ruby_package_file.$rvm_archive_extension" -C "${rvm_tmp_path:-/tmp}/rvm_src_$$" ${rvm_tar_options:-}
-          )
-          ;;
-        tar.bz2)
-          _current_command=(
-            "$rvm_tar_command" xjf "${rvm_archives_path}/$rvm_ruby_package_file.$rvm_archive_extension" -C "${rvm_tmp_path:-/tmp}/rvm_src_$$" ${rvm_tar_options:-}
-          )
-          ;;
-        zip)
-          _current_command=(
-            unzip -q -o "${rvm_archives_path}/$rvm_ruby_package_file" -d "${rvm_tmp_path:-/tmp}/rvm_src_$$"
-          )
+      __rvm_log_command "extract" "$rvm_ruby_string - #extracting $rvm_ruby_package_file to ${rvm_src_path}/$rvm_ruby_string" \
+        __rvm_package extract "${rvm_archives_path}/$rvm_ruby_package_file.$rvm_archive_extension" "${rvm_tmp_path:-/tmp}/rvm_src_$$" ||
+      case $? in
+        199)
+          rvm_error "\nUnrecognized archive format '$archive_format'"
+          return 199
           ;;
         *)
-          rvm_error "Unknown archive format extension '$rvm_archive_extension'.\nHalting the installation."
+          rvm_error "There has been an error while trying to extract the source. Halting the installation."
           return 1
           ;;
       esac
-      __rvm_log_command "extract" "$rvm_ruby_string - #extracting $rvm_ruby_package_file to ${rvm_src_path}/$rvm_ruby_string" \
-        "${_current_command[@]}" || return $?
 
       __rvm_rm_rf "${rvm_src_path}/$rvm_ruby_string"
 
