Added comments and a sanity check to the trap.

diff --git a/scripts/base b/scripts/base
--- a/scripts/base
+++ b/scripts/base
@@ -44,6 +44,9 @@ done
 unset scripts entry rvm_base_except
 
 if [[ ${rvm_interactive_flag} -eq 0 ]]; then
-  # Cleanup tmp on exit.
-  trap "__rvm_cleanup_tmp '$$'" 0 1 2 3 15
+  # Cleanup RVM temporary files on exit if we are loaded from a script.
+  if command -v __rvm_cleanup_tmp >/dev/null 2>&1 ; then
+    # Only cleanup if the function to do so is defined :)
+    trap "__rvm_cleanup_tmp '$$'" 0 1 2 3 15
+  fi
 fi
