Shut your trap!

diff --git a/scripts/base b/scripts/base
--- a/scripts/base
+++ b/scripts/base
@@ -43,5 +43,7 @@ done
 
 unset scripts entry rvm_base_except
 
-# Cleanup tmp on exit.
-trap "__rvm_cleanup_tmp '$$'" 0 1 2 3 15
+if [[ ${rvm_interactive_flag} -eq 0 ]]; then
+  # Cleanup tmp on exit.
+  trap "__rvm_cleanup_tmp '$$'" 0 1 2 3 15
+fi
