Completely removed rvm_interactive_flag, checking directly each time as per recommendation by e2 for zsh.

diff --git a/scripts/base b/scripts/base
--- a/scripts/base
+++ b/scripts/base
@@ -5,13 +5,6 @@
 #
 # Setup environment parameters.
 #
-# Detect wheter or not the shell is interactive, if it has not already been specified.
-if [[ -z "${rvm_interactive_flag:-}" ]]; then
-  case $- in *i*) rvm_interactive_flag=1 ;;
-               *) rvm_interactive_flag=0 ;;
-  esac
-fi
-
 [[ -z "${ZSH_VERSION:-}" ]] ; __array_start=$?
 
 #
@@ -43,10 +36,15 @@ done
 
 unset scripts entry rvm_base_except
 
-if [[ ${rvm_interactive_flag} -eq 0 ]]; then
-  # Cleanup RVM temporary files on exit if we are loaded from a script.
-  if command -v __rvm_cleanup_tmp >/dev/null 2>&1 ; then
-    # Only cleanup if the function to do so is defined :)
-    trap "__rvm_cleanup_tmp '$$'" 0 1 2 3 15
-  fi
-fi
+case $- in
+  *i*)
+    true # do nothing.
+    ;;
+  *)
+    # Cleanup RVM temporary files on exit if we are loaded from a script.
+    if command -v __rvm_cleanup_tmp >/dev/null 2>&1 ; then
+      # Only cleanup if the function to do so is defined :)
+      trap "__rvm_cleanup_tmp '$$'" 0 1 2 3 15
+    fi
+    ;;
+esac
