Properly test for interactive mode.

diff --git a/scripts/base b/scripts/base
--- a/scripts/base
+++ b/scripts/base
@@ -37,15 +37,9 @@ done
 
 unset scripts entry rvm_base_except
 
-case $- in
-  *i*)
-    true # do nothing.
-    ;;
-  *)
-    # Cleanup RVM temporary files on exit if we are loaded from a script.
-    if command -v __rvm_cleanup_tmp >/dev/null 2>&1 ; then
-      # Only cleanup if the function to do so is defined :)
-      trap "set +e; __rvm_cleanup_tmp '$$'" 0 1 2 3 15
-    fi
-    ;;
-esac
+if [[ ! -t 0 ]] && command -v __rvm_cleanup_tmp >/dev/null 2>&1
+then
+  # Cleanup RVM temporary files on exit if we are loaded from a script.
+  # Only cleanup if the function to do so is defined :)
+  trap "set +e; __rvm_cleanup_tmp '$$'" 0 1 2 3 15
+fi
