more precise implementation of chpwd and chpwd_functions from Zsh, update #2819

diff --git a/scripts/cd b/scripts/cd
--- a/scripts/cd
+++ b/scripts/cd
@@ -36,8 +36,11 @@ case "${rvm_project_rvmrc:-1}" in
         builtin "$@"
       then
         shift || true # remove the called method
-        for  __zsh_like_cd_hook in "${chpwd_functions[@]}"
-        do "$__zsh_like_cd_hook" "$@" || break # finish on first failed hook
+        for __zsh_like_cd_hook in chpwd "${chpwd_functions[@]}"
+        do
+          if typeset -v "$__zsh_like_cd_hook" >/dev/null 2>&1
+          then "$__zsh_like_cd_hook" "$@" || break # finish on first failed hook
+          fi
         done
         true
       else
