add chpwd_functions handling for bash and old zsh, fix #2819

diff --git a/scripts/cd b/scripts/cd
--- a/scripts/cd
+++ b/scripts/cd
@@ -4,69 +4,48 @@
 # disable this feature, set rvm_project_rvmrc=0 in /etc/rvmrc or $HOME/.rvmrc
 case "${rvm_project_rvmrc:-1}" in
 1|cd)
-  __rvm_setup_cd()
+  __rvm_after_cd()
   {
-    # try to use smartcd function, fallback to builtin
-    typeset __cd_prefix __command
-    __cd_prefix=""
-
-    if typeset -f smartcd >/dev/null 2>/dev/null
-    then __cd_prefix="smartcd"
-    fi
-    if typeset -f exec_scmb_expand_args >/dev/null 2>/dev/null
-    then __cd_prefix="exec_scmb_expand_args ${__cd_prefix:-builtin}"
-    fi
-    [[ -n "${__cd_prefix}" ]] || __cd_prefix="builtin"
-
-    __rvm_after_cd()
-    {
-      typeset rvm_hook
-      rvm_hook="after_cd"
-      if [[ -n "${rvm_scripts_path:-}" || -n "${rvm_path:-}" ]]
-      then source "${rvm_scripts_path:-$rvm_path/scripts}/hook"
-      fi
-    }
-
-    __rvm_cd_functions_set()
-    {
-      __rvm_do_with_env_before
-      __rvm_project_rvmrc >&2 && __rvm_after_cd || true
-      __rvm_do_with_env_after
-      return 0
-    }
-
-    __rvm_setup_cd_function()
-    {
-      typeset __cd_prefix __command
-      __cd_prefix=$1
-      __command=$2
-      eval "
-${__command}(){
-  if ${__cd_prefix} ${__command} \"\$@\"
-  then
-    [[ -n \"\${rvm_current_rvmrc:-""}\" && \"\$*\" == \".\" ]] && rvm_current_rvmrc=\"\" || true
-    __rvm_cd_functions_set
-    return 0
-  else
-    return \$?
-  fi
-}"
-    }
-
-    if
-      [[ -n "${ZSH_VERSION:-}" ]] &&
-      __rvm_version_compare "$ZSH_VERSION" -gt  4.3.4
-    then
-      # On zsh, use chpwd_functions
-      export -a chpwd_functions
-      chpwd_functions=( "${chpwd_functions[@]}" __rvm_cd_functions_set )
-    else
-      for __command in cd popd pushd
-      do __rvm_setup_cd_function "${__cd_prefix}" "${__command}"
-      done
+    typeset rvm_hook
+    rvm_hook="after_cd"
+    if [[ -n "${rvm_scripts_path:-}" || -n "${rvm_path:-}" ]]
+    then source "${rvm_scripts_path:-$rvm_path/scripts}/hook"
     fi
   }
-  __rvm_setup_cd
+  __rvm_cd_functions_set()
+  {
+    __rvm_do_with_env_before
+    __rvm_project_rvmrc >&2 && __rvm_after_cd || true
+    __rvm_do_with_env_after
+    return 0
+  }
+  export -a chpwd_functions
+  chpwd_functions=( "${chpwd_functions[@]}" __rvm_cd_functions_set )
+
+  [[ -n "${ZSH_VERSION:-}" ]] &&
+  __rvm_version_compare "$ZSH_VERSION" -gt  4.3.4 ||
+  {
+    # On bash and old zsh we need to define chpwd_functions handler
+    __zsh_like_cd()
+    {
+      typeset __zsh_like_cd_hook
+      if
+        builtin "$@"
+      then
+        shift || true # remove the called method
+        for  __zsh_like_cd_hook in "${chpwd_functions[@]}"
+        do "$__zsh_like_cd_hook" "$@" || break # finish on first failed hook
+        done
+        true
+      else
+        return $?
+      fi
+    }
+    cd()    { __zsh_like_cd cd    "$@" ; }
+    popd()  { __zsh_like_cd popd  "$@" ; }
+    pushd() { __zsh_like_cd pushd "$@" ; }
+  }
+
   # This functionality is opt-in by setting rvm_cd_complete_flag=1 in ~/.rvmrc
   # Generic bash cd completion seems to work great for most, so this is only
   # for those that have some issues with that.
