Suddenly, I feel like watching LeekSpin for an extended period of time... ( http://leekspin.com/ )

diff --git a/scripts/cli b/scripts/cli
--- a/scripts/cli
+++ b/scripts/cli
@@ -57,7 +57,7 @@ __rvm_parse_args() {
         rvm_ruby_string="$rvm_token"
         rvm_ruby_strings="$rvm_token"
         rvm_action="${rvm_action:-use}"
-        if $rvm_scripts_path/match "$1" "^[0-9]\.[0-9]" ; then rvm_ruby_version=$1 ; shift ; fi
+        if "$rvm_scripts_path"/match "$1" "^[0-9]\.[0-9]" ; then rvm_ruby_version=$1 ; shift ; fi
       ;;
 
       gemset)
@@ -84,9 +84,9 @@ __rvm_parse_args() {
           rvm_delete_flag=1
           rvm_ruby_args="$@" ; shift
           rvm_gemset_name="$1"; shift
-          if [[ ! -z "$(echo $rvm_gemset_name | \grep $rvm_gemset_separator)" ]] ; then
-            rvm_ruby_string=$(echo $rvm_gemset_name | sed 's/\(.*\)'${rvm_gemset_separator}'.*/\1/')
-            rvm_gemset_name=$(echo $rvm_gemset_name | sed 's/.*'${rvm_gemset_separator}'\(.*\)/\1/')
+          if echo "$rvm_gemset_name" | \grep -q "$rvm_gemset_separator" ; then
+            rvm_ruby_string=$(echo "$rvm_gemset_name" | sed 's/\(.*\)'${rvm_gemset_separator}'.*/\1/')
+            rvm_gemset_name=$(echo "$rvm_gemset_name" | sed 's/.*'${rvm_gemset_separator}'\(.*\)/\1/')
             if [[ "$rvm_ruby_string" != "$rvm_gemset_name" ]] ; then
               rvm_ruby_string="$rvm_ruby_string${rvm_gemset_separator}$rvm_gemset_name"
             fi
@@ -103,7 +103,7 @@ __rvm_parse_args() {
         rvm_action=$rvm_token
         rvm_gemdir_flag=1
         if [[ "system" = "$1" ]] ; then rvm_system_flag=1 ; shift ; fi
-        if [[ "user" = "$1"  ]]   ; then rvm_user_flag=1  ;  shift ; fi
+        if [[ "user" = "$1" ]]   ; then rvm_user_flag=1  ;  shift ; fi
       ;;
 
       inspect|list|info)
@@ -151,7 +151,7 @@ __rvm_parse_args() {
               rvm_action="error"
               rvm_error_message="'rvm $rvm_action' must be followed by arguments."
             elif [[ "ruby" = "$rvm_action" ]] ; then
-              if [[ -z "$(echo "$rvm_ruby_strings" | awk '/,/')" ]] ; then
+              if echo "$rvm_ruby_strings" | \grep -q ',' ; then
                 rvm_action="ruby"
                 rvm_ruby_args=""
               else
@@ -172,14 +172,14 @@ __rvm_parse_args() {
             rvm_parse_break=1
           fi
         else
-          if $rvm_scripts_path/match "$1" "^-" ; then
+          if "$rvm_scripts_path"/match "$1" "^-" ; then
             unset rvm_ruby_strings
           else
-            if $rvm_scripts_path/match "$1" "^[0-9]" ; then
-              rvm_ruby_strings=$(echo "$1" | \tr ',' ' ') ; shift
+            if "$rvm_scripts_path"/match "$1" "^[0-9]" ; then
+              rvm_ruby_strings="${1//,/ }" ; shift
               unset rvm_ruby_interpreter
             else
-              if $rvm_scripts_path/match "ruby rbx jruby macruby ree rubinius maglev mput shyouhei ironruby" "$1" ; then
+              if "$rvm_scripts_path"/match "ruby rbx jruby macruby ree rubinius maglev mput shyouhei ironruby" "$1" ; then
                 rvm_ruby_strings=$1
                 rvm_ruby_interpreter=$1
                 shift
@@ -197,7 +197,7 @@ __rvm_parse_args() {
 
       specs|tests)
         rvm_action="rake"
-        rvm_ruby_args="$(echo $rvm_token | sed 's/s$//')"
+        rvm_ruby_args="$(echo $rvm_token | sed -e 's/s$//')"
       ;;
 
       -v|--version)
@@ -215,7 +215,7 @@ __rvm_parse_args() {
 
       --ree-options)
         if [[ ! -z "$1" ]] ; then
-          export rvm_ree_options="$(echo $1 | \tr ',' ' ')" ; shift
+          export rvm_ree_options="${1//,/ }" ; shift
         else
           rvm_action="error"
           rvm_error_message="--ree-options *must* be followed by... well... options."
@@ -277,13 +277,13 @@ __rvm_parse_args() {
 
       --alias)
         if [[ -n "$1" ]]; then
-          export rvm_ruby_aliases="$(echo "$rvm_ruby_aliases $1" | \tr ',' ' ' | __rvm_strip)"
+          rvm_ruby_aliases="$(echo "${rvm_ruby_aliases//,/ } ${1//,/ }" | __rvm_strip)"
           shift
         fi
       ;;
 
       --symlink)
-        $rvm_scripts_path/log "warn" "--symlink has been removed, please see 'rvm wrapper'."
+        "$rvm_scripts_path/log" "warn" "--symlink has been removed, please see 'rvm wrapper'."
         shift
       ;;
 
@@ -297,27 +297,29 @@ __rvm_parse_args() {
         rvm_parse_break=1
       ;;
 
-      -h|--help|usage)      rvm_action=help                     ;;
       -G)                   path_variable="rvm_gems_path"     ; __rvm_set_path_variable "$1"; shift  ;;
       --source)             path_variable="rvm_src_path"      ; __rvm_set_path_variable "$1"; shift  ;;
       --archives)           path_variable="rvm_archives_path" ; __rvm_set_path_variable "$1"; shift  ;;
-      --make)               rvm_ruby_make="$1"         ; shift  ;;
-      --make-install)       rvm_ruby_make_install="$1" ; shift  ;;
-      --nice)               rvm_niceness="$1"          ; shift  ;;
-      -l|--level)           rvm_ruby_patch_level="p$1" ; shift  ;;
+      -h|--help|usage)      rvm_action=help                      ;;
+      --make)               rvm_ruby_make="$1"         ; shift   ;;
+      --make-install)       rvm_ruby_make_install="$1" ; shift   ;;
+      --nice)               rvm_niceness="$1"          ; shift   ;;
+      -l|--level)           rvm_ruby_patch_level="p$1" ; shift   ;;
       # TODO: handle this below better (if $1 is null)
-      --sdk)                rvm_sdk="$1"               ; shift  ;;
-      --archflags)          rvm_archflags="$1"         ; shift  ;;
-      --install)            rvm_install_on_use_flag=1    ;;
-      --trace)              rvm_trace_flag=1    ; set -x ;;
-      --proxy)              rvm_proxy="$1"      ; shift  ;;
-      --disable-llvm|--disable-jit) rvm_llvm_flag=0      ;;
-      --enable-llvm|--enable-jit)   rvm_llvm_flag=1      ;;
+      --sdk)                rvm_sdk="$1"               ; shift   ;;
+      --archflags)          rvm_archflags="$1"         ; shift   ;;
+      --install)            rvm_install_on_use_flag=1            ;;
+      --trace)              rvm_trace_flag=1    ; set -x         ;;
+      -q|--quiet)           rvm_quiet_flag=1                     ;;
+      -s|--silent)          rvm_silent_flag=1                    ;;
+      --proxy)              rvm_proxy="$1"      ; shift          ;;
+      --disable-llvm|--disable-jit) rvm_llvm_flag=0              ;;
+      --enable-llvm|--enable-jit)   rvm_llvm_flag=1              ;;
 
       reboot|damnit|wtf|argh|BOOM|boom|wth) $rvm_action="reboot" ;;
 
       --self|--gem|--rubygems|--reconfigure|--default|--debug|--force|--export|--summary|--latest|--yaml|--json|--archive|--shebang|--env|--path|--tail|--delete|--verbose|--import|--rvmrc|--sticky|--create|--gems|--docs)
-        export rvm_$(echo $rvm_token | sed 's#-##g')_flag=1
+        export "rvm_${rvm_token//-/}_flag"=1
       ;;
 
       --dump-environment)
@@ -355,19 +357,10 @@ __rvm_parse_args() {
         fi
       ;;
 
-      --with-*)
-        rvm_ruby_configure_flags="$rvm_ruby_configure_flags $rvm_token"
-      ;;
-      --without-*)
-        rvm_ruby_configure_flags="$rvm_ruby_configure_flags $rvm_token"
-      ;;
-      --enable-*)
-        rvm_ruby_configure_flags="$rvm_ruby_configure_flags $rvm_token"
-      ;;
-      --disable-*)
-        rvm_ruby_configure_flags="$rvm_ruby_configure_flags $rvm_token"
-      ;;
-
+      --with-*)    rvm_ruby_configure_flags="$rvm_ruby_configure_flags $rvm_token" ;;
+      --without-*) rvm_ruby_configure_flags="$rvm_ruby_configure_flags $rvm_token" ;;
+      --enable-*)  rvm_ruby_configure_flags="$rvm_ruby_configure_flags $rvm_token" ;;
+      --disable-*) rvm_ruby_configure_flags="$rvm_ruby_configure_flags $rvm_token" ;;
 
       -I|--include)
         if [[ -z "$1" ]] ; then
@@ -384,7 +377,7 @@ __rvm_parse_args() {
       *)
         if [[ -n "$rvm_token" ]] ; then
           if [[ "gemset" = "$rvm_action" ]] ; then
-            if $rvm_scripts_path/match "$rvm_token" "^.+${rvm_gemset_separator}.+$" ; then
+            if "$rvm_scripts_path/match" "$rvm_token" "^.+${rvm_gemset_separator}.+$" ; then
               rvm_gemset_name="$(echo "$rvm_token" | awk -F${rvm_gemset_separator} '{print $2}')"
               rvm_ruby_string="$(echo "$rvm_token" | awk -F${rvm_gemset_separator} '{print $1}')"
             elif [[ ! -z "$(echo "$rvm_token" | awk '/\.gems$/')" ]] ; then
@@ -399,27 +392,27 @@ __rvm_parse_args() {
             if [[ -z "$rvm_action" ]] ; then
               rvm_action="ruby" # Not sure if we really want to do this but we'll try it out.
             fi
-          elif $rvm_scripts_path/match "$rvm_token" "^${rvm_gemset_separator}" ; then
+          elif "$rvm_scripts_path/match" "$rvm_token" "^${rvm_gemset_separator}" ; then
             rvm_action="use"
             rvm_gemset_name="$(echo "$rvm_token" | awk -F${rvm_gemset_separator} '{print $2}')"
             rvm_ruby_string="$(__rvm_environment_identifier | awk -F${rvm_gemset_separator} '{print $1}')"
             rvm_ruby_strings="${rvm_ruby_string}${rvm_gemset_separator}${rvm_gemset_name}"
-          elif $rvm_scripts_path/match "$rvm_token" "^.+${rvm_gemset_separator}.+$" ; then
+          elif "$rvm_scripts_path/match" "$rvm_token" "^.+${rvm_gemset_separator}.+$" ; then
             rvm_gemset_name="$(echo "$rvm_token" | awk -F${rvm_gemset_separator} '{print $2}')"
             rvm_ruby_string="$(echo "$rvm_token" | awk -F${rvm_gemset_separator} '{print $1}')"
             rvm_ruby_strings="$rvm_token"
-          elif $rvm_scripts_path/match "$rvm_token" "^.+\\+.+$" ; then
+          elif "$rvm_scripts_path/match" "$rvm_token" "^.+\\+.+$" ; then
             rvm_ruby_alias="$(echo "$rvm_token" | awk -F+ '{print $2}')"
             rvm_ruby_string="$(echo "$rvm_token" | awk -F+ '{print $1}')"
             rvm_ruby_strings="$rvm_ruby_string"
-          elif $rvm_scripts_path/match "$rvm_token" "-" ; then
+          elif "$rvm_scripts_path/match" "$rvm_token" "-" ; then
             rvm_ruby_string="$rvm_token"
             rvm_ruby_strings="$rvm_token"
-          elif $rvm_scripts_path/match "$rvm_token" "^[0-9].[0-9]" ; then
+          elif "$rvm_scripts_path/match" "$rvm_token" "^[0-9].[0-9]" ; then
             rvm_ruby_string="$rvm_token"
             rvm_ruby_strings="$rvm_token"
             rvm_action="${rvm_action:-use}"
-          elif $rvm_scripts_path/match "$rvm_token" "^ree-" ; then
+          elif "$rvm_scripts_path/match" "$rvm_token" "^ree-" ; then
             rvm_ruby_string="$rvm_token"
             rvm_ruby_strings="$rvm_token"
             rvm_action="${rvm_action:-use}"
@@ -428,7 +421,7 @@ __rvm_parse_args() {
             rvm_ruby_strings="$rvm_token"
             rvm_action="${rvm_action:-use}"
           else
-            if $rvm_scripts_path/match "$rvm_token" "\.rb$" ; then # we have a specified ruby script
+            if "$rvm_scripts_path/match" "$rvm_token" "\.rb$" ; then # we have a specified ruby script
               rvm_ruby_args=$rvm_token
               rvm_ruby_file=$rvm_token
               if [[ -z "$rvm_action" ]] ; then
@@ -460,8 +453,8 @@ __rvm_parse_args() {
 rvm() {
   __rvm_setup
 
-  case $- in *i*) rvm_interactive=1 ;;
-              *) unset rvm_interactive ;;
+  case $- in *i*) rvm_interactive=1     ;;
+               *) unset rvm_interactive ;;
   esac ; export rvm_interactive
 
   if [[ -z "$ZSH_VERSION" ]] ; then
@@ -475,12 +468,13 @@ rvm() {
     return 1
   fi
 
-  __rvm_cleanup_variables
+  __rvm_cleanse_variables
   __rvm_load_rvmrc
   __rvm_initialize
   __rvm_parse_args "$@"
+
   export BUNDLE_PATH GEM_HOME GEM_PATH rvm_ruby_string rvm_action rvm_bin_flag rvm_debug_flag rvm_delete_flag rvm_docs_type rvm_file_name rvm_gemset_name rvm_head_flag rvm_install_on_use_flag rvm_interactive rvm_llvm_flag rvm_make_flags rvm_proxy rvm_remove_flag rvm_ruby_args rvm_ruby_configure_flags rvm_ruby_file rvm_ruby_gem_home rvm_ruby_interpreter rvm_ruby_name rvm_ruby_version rvm_system_flag rvm_trace_flag rvm_use_flag rvm_user_flag rvm_verbose_flag rvm_patch_names rvm_patch_original_pwd rvm_clang_flag rvm_install_arguments
-  export rvm_path rvm_rubies_path rvm_scripts_path rvm_archives_path rvm_src_path rvm_patches_path rvm_patches_path rvm_patchsets_path rvm_log_path rvm_bin_path rvm_gems_path rvm_config_path rvm_tmp_path rvm_hooks_path rvm_gems_cache_path rvm_gemset_separator
+  export rvm_path rvm_rubies_path rvm_scripts_path rvm_archives_path rvm_src_path rvm_patches_path rvm_patches_path rvm_patchsets_path rvm_log_path rvm_bin_path rvm_gems_path rvm_config_path rvm_tmp_path rvm_hooks_path rvm_gems_cache_path rvm_gemset_separator rvm_ruby_aliases rvm_quiet_flag rvm_silent_flag
 
   result=0
 
@@ -497,44 +491,39 @@ rvm() {
     inspect)         __rvm_inspect           ; result=$? ;;
     implode|seppuku) __rvm_implode           ; result=$? ;;
 
-    list)            $rvm_scripts_path/list $rvm_ruby_args ; result=$? ;;
+    list)  "$rvm_scripts_path"/list $rvm_ruby_args ; result=$? ;;
     # TODO: Make debug run in the current environment.
-    debug)           $rvm_scripts_path/info '' debug ; result=$? ;;
+    debug) "$rvm_scripts_path"/info '' debug ; result=$? ;;
+    help)  "$rvm_scripts_path"/help $rvm_ruby_args ; result=$? ;;
+    env)   "$rvm_scripts_path"/env "$rvm_ruby_string" ; result=$?  ;;
     info)
       if [[ "$1" == "info" ]]; then shift; fi
       if [[ -z "$rvm_ruby_args" ]] ; then
-        $rvm_scripts_path/info
+        "$rvm_scripts_path"/info
       else
-        $rvm_scripts_path/info $rvm_ruby_args
+        "$rvm_scripts_path"/info $rvm_ruby_args
       fi
       result=$?
     ;;
-    help)            $rvm_scripts_path/help     $rvm_ruby_args ; result=$? ;;
 
-    answer) __rvm_Answer_to_the_Ultimate_Question_of_Life_the_Universe_and_Everything ; result=42 ;;
+    answer)   __rvm_Answer_to_the_Ultimate_Question_of_Life_the_Universe_and_Everything ; result=42 ;;
     question) __rvm_ultimate_question ; result=42 ;;
 
-    env)
-      $rvm_scripts_path/env "$rvm_ruby_string"
-      result=$?
-    ;;
-
     wrapper)
-      $rvm_scripts_path/wrapper "$rvm_ruby_string" "$rvm_wrapper_name" $rvm_ruby_args
+      "$rvm_scripts_path"/wrapper "$rvm_ruby_string" "$rvm_wrapper_name" $rvm_ruby_args
       result=$?
       unset rvm_wrapper_name
     ;;
 
     gemdir|gemhome|gempath)
-      $rvm_scripts_path/gemsets "$rvm_action"
-      result=$?
+      "$rvm_scripts_path/gemsets" "$rvm_action" ; result=$?
     ;;
 
     ruby|gem|rake|exec)
       old_rvm_ruby_string=$rvm_ruby_string
       unset rvm_ruby_string
       export rvm_ruby_strings
-      $rvm_scripts_path/set $rvm_action $rvm_ruby_args
+      "$rvm_scripts_path/set" "$rvm_action" "$rvm_ruby_args"
       result=$?
       # Restore the state pre-sets.
       [[ -n "$old_rvm_ruby_string" ]] && rvm_ruby_string=$old_rvm_ruby_string
@@ -542,17 +531,13 @@ rvm() {
     ;;
 
     cleanup|tools|snapshot|disk-usage|repair|alias|docs|rubygems|migrate|upgrade)
-      __rvm_run_script "$rvm_action"
-      result=$?
+      __rvm_run_script "$rvm_action" ; result=$?
     ;;
 
-    rvmrc)
-      eval "__rvm_rvmrc_tools $rvm_ruby_args"
-      result="$?"
-    ;;
+    rvmrc) eval "__rvm_rvmrc_tools $rvm_ruby_args" ; result="$?" ;;
 
     gemset)
-      #if $rvm_scripts_path/match $rvm_ruby_args use ; then
+      #if "$rvm_scripts_path/match" $rvm_ruby_args use ; then
       if [[ "$rvm_use_flag" -eq 1 ]] ; then
         __rvm_gemset_select
         result=$? ; if [[ $result -eq 0 ]] ; then
@@ -560,7 +545,7 @@ rvm() {
         fi
       else
         export rvm_ruby_strings
-        $rvm_scripts_path/gemsets $rvm_ruby_args
+        "$rvm_scripts_path"/gemsets $rvm_ruby_args
         unset rvm_ruby_strings
 
         # Clear the gemset.
@@ -580,35 +565,32 @@ rvm() {
 
     monitor)
       export rvm_ruby_strings rvm_ruby_string
-      $rvm_scripts_path/monitor ; result=$?
+      "$rvm_scripts_path"/monitor ; result=$?
     ;;
-    notes)         $rvm_scripts_path/notes   ; result=$?  ;;
-    reload)        unset rvm_loaded_flag ; rvm_reload_flag=1 ;;
+
+    notes)       "$rvm_scripts_path"/notes   ; result=$?  ;;
+    reload)      unset rvm_loaded_flag ; rvm_reload_flag=1 ;;
+    tests|specs) rvm_action="rake" ; __rvm_do ; result=$? ;;
+    package)     "$rvm_scripts_path"/package $rvm_ruby_args ; result=$?  ;;
 
     fetch|install|uninstall|remove)
       if [[ -n "$rvm_ruby_strings" ]]; then
-        $rvm_scripts_path/manage "$rvm_action" "$rvm_ruby_strings"
+        "$rvm_scripts_path"/manage "$rvm_action" "$rvm_ruby_strings"
       else
-        $rvm_scripts_path/manage "$rvm_action"
+        "$rvm_scripts_path"/manage "$rvm_action"
       fi
-      result=$?
-    ;;
-    tests|specs)   rvm_action="rake" ; __rvm_do ; result=$? ;;
-
-    package)
-      $rvm_scripts_path/package $rvm_ruby_args
       result=$?
     ;;
 
     error)
-      $rvm_scripts_path/log "fail" "$rvm_error_message ( see: 'rvm usage' )"
+      "$rvm_scripts_path"/log "fail" "$rvm_error_message ( see: 'rvm usage' )"
       __rvm_pushpop
       result=1
     ;;
 
     *)
       if [[ ! -z "$rvm_action" ]] ; then
-        $rvm_scripts_path/log "fail"  "unknown action '$rvm_action'"
+        "$rvm_scripts_path/log" "fail"  "unknown action '$rvm_action'"
       else
         __rvm_usage
       fi
diff --git a/scripts/package b/scripts/package
--- a/scripts/package
+++ b/scripts/package
@@ -14,18 +14,18 @@ install_package() {
 
   if [[ ! -z "$rvm_make_flags_flag" ]] ; then __rvm_make_flags ; fi
 
-  __rvm_pushpop $rvm_src_path
+  __rvm_pushpop "$rvm_src_path"
 
-  $rvm_scripts_path/log "info" "Fetching $package-$version.$archive_format to $rvm_archives_path"
+  "$rvm_scripts_path/log" "info" "Fetching $package-$version.$archive_format to $rvm_archives_path"
 
   if [[ "$archive_format" = "tar.gz" ]] || [[ "$archive_format" = "tgz" ]] ; then
-    $rvm_scripts_path/fetch "$package_url/$package-$version.$archive_format" || (result=$? && return $result)
+    "$rvm_scripts_path/fetch" "$package_url/$package-$version.$archive_format" || (result=$? && return $result)
     __rvm_run "$package/extract" "tar zxf $rvm_archives_path/$package-$version.$archive_format -C $rvm_src_path" "Extracting $package-$version.$archive_format to $rvm_src_path"
   elif [[ "$archive_format" = "tar.bz2" ]] ; then
-    $rvm_scripts_path/fetch "$package_url/$package-$version.$archive_format" || (result=$? && return $result)
+    "$rvm_scripts_path/fetch" "$package_url/$package-$version.$archive_format" || (result=$? && return $result)
     __rvm_run "$package/extract" "tar jxf $rvm_archives_path/$package-$version.$archive_format -C $rvm_src_path" "Extracting $package-$version.$archive_format to $rvm_src_path"
   elif [[ "$archive_format" = "zip" ]] ; then
-    $rvm_scripts_path/fetch "$package_url/$package-$version.$archive_format" || (result=$? && return $result)
+    "$rvm_scripts_path/fetch" "$package_url/$package-$version.$archive_format" || (result=$? && return $result)
     __rvm_run "$package/extract" "unzip -q -o $rvm_archives_path/$package-$version.$archive_format -d $rvm_src_path/$package-$version" "Extracting $package-$version.$archive_format to $rvm_src_path"
   else
     printf "\nUnrecognized archive format '$archive_format'" ; return 1
@@ -45,7 +45,7 @@ install_package() {
   fi
 
   \touch "$rvm_config_path/packages"
-  $rvm_scripts_path/db "$rvm_config_path/packages" "${package}" "${version}"
+  "$rvm_scripts_path/db" "$rvm_config_path/packages" "${package}" "${version}"
 
   __rvm_pushpop
 }
@@ -72,10 +72,10 @@ openssl() {
   package="openssl" ; version="0.9.8n" ; archive_format="tar.gz"
   if [[ "Darwin" = "$(uname)" ]] ; then
     if [[ ! -z "$rvm_archflags" ]]; then
-      if $rvm_scripts_path/match "$rvm_archflags" "64"; then
+      if "$rvm_scripts_path/match" "$rvm_archflags" "64"; then
         hw_cpu64bit=1
       fi
-      if $rvm_scripts_path/match "$rvm_archflags" "ppc"; then
+      if "$rvm_scripts_path/match" "$rvm_archflags" "ppc"; then
         hw_machine="Power Macintosh"
       fi
     else
@@ -99,7 +99,7 @@ openssl() {
     patches="$rvm_patches_path/$package/Makefile.org.patch,$rvm_patches_path/$package/crypto-Makefile.patch"
     # Don't use -j option for make OpenSSL
     if [[ ! -z "$rvm_make_flags" ]] ; then
-      rvm_make_flags=$(echo $rvm_make_flags | sed -e "s/-j[[:space:]]*[[0-9]]*//")
+      rvm_make_flags=$(echo "$rvm_make_flags" | sed -e "s/-j[[:space:]]*[[0-9]]*//")
     fi
   else
     configure_command="./config"
@@ -181,10 +181,10 @@ if [[ ! -z "$library" ]] ; then
   if [[ " readline iconv curl openssl zlib autoconf ncurses pkgconfig gettext glib mono llvm libxml2 " =~ "$library" ]] ; then
     ${library}
   else
-    $rvm_scripts_path/log "error" "Package '${library}' is unknown."
+    "$rvm_scripts_path/log" "error" "Package '${library}' is unknown."
   fi
 else
-  $rvm_scripts_path/log "info" "Usage: 'rvm package {install,uninstall} {readline,iconv,curl,openssl,zlib,autoconf,ncurses,pkgconfig,gettext,glib,mono,llvm,libxml2}'"
+  "$rvm_scripts_path/log" "info" "Usage: 'rvm package {install,uninstall} {readline,iconv,curl,openssl,zlib,autoconf,ncurses,pkgconfig,gettext,glib,mono,llvm,libxml2}'"
   exit 1
 fi
 
diff --git a/scripts/selector b/scripts/selector
--- a/scripts/selector
+++ b/scripts/selector
@@ -37,7 +37,7 @@ __rvm_select() {
 
         unset rvm_ruby_patch_level
       else
-        $rvm_scripts_path/log "fail" "MacRuby can only be installed on a Darwin OS."
+        "$rvm_scripts_path/log" "fail" "MacRuby can only be installed on a Darwin OS."
       fi
     ;;
 
@@ -131,8 +131,8 @@ __rvm_select() {
         fi
       fi
 
-      if ! $rvm_scripts_path/match "$rvm_ruby_version" "^1\.8" ; then
-        $rvm_scripts_path/log "fail" "Unknown Ruby Enterprise Edition version: $rvm_ruby_version"
+      if ! "$rvm_scripts_path/match" "$rvm_ruby_version" "^1\.8" ; then
+        "$rvm_scripts_path/log" "fail" "Unknown Ruby Enterprise Edition version: $rvm_ruby_version"
       fi
     ;;
 
@@ -148,7 +148,7 @@ __rvm_select() {
 
     ruby)
       if [[ -z "$rvm_ruby_version" && -z "$rvm_head_flag" ]]; then
-        $rvm_scripts_path/log "fail" "Unknown ruby version: $rvm_ruby_version"
+        "$rvm_scripts_path/log" "fail" "Unknown ruby version: $rvm_ruby_version"
       else
         rvm_ruby_repo_url="${rvm_ruby_repo_url:-"$(__rvm_db "ruby_repo_url")"}"
         if [[ -z "$rvm_head_flag" ]]; then
@@ -159,7 +159,7 @@ __rvm_select() {
 
     current)
       ruby_binary="$(command -v ruby)"
-      if [[ $? -eq 0 ]] && $rvm_scripts_path/match "$ruby_binary" "rvm" ; then
+      if [[ $? -eq 0 ]] && "$rvm_scripts_path/match" "$ruby_binary" "rvm" ; then
         rvm_ruby_string="$(dirname "$ruby_binary" | xargs dirname | xargs basename)"
       else
         rvm_ruby_interpreter="system"
@@ -176,7 +176,7 @@ __rvm_select() {
         __rvm_select
       else
         if [[ -z "$rvm_ruby_string" ]] ; then
-          $rvm_scripts_path/log "fail" "Ruby implementation '$rvm_ruby_interpreter' is not known."
+          "$rvm_scripts_path/log" "fail" "Ruby implementation '$rvm_ruby_interpreter' is not known."
           return 1
         fi
       fi
@@ -249,7 +249,7 @@ __rvm_use() {
     fi
 
     if [[ ! -z "$rvm_verbose_flag" ]] ; then
-      $rvm_scripts_path/log "info" "Now using system ruby."
+      "$rvm_scripts_path/log" "info" "Now using system ruby."
     fi
 
     export rvm_ruby_string="system"
@@ -267,11 +267,11 @@ __rvm_use() {
     if [[ -z "$IRBRC" ]] ; then unset IRBRC ; fi
 
     if [[ ! -d $MY_RUBY_HOME ]] ; then
-      $rvm_scripts_path/log "warn" "$rvm_ruby_interpreter $rvm_ruby_string is not installed."
+      "$rvm_scripts_path/log" "warn" "$rvm_ruby_interpreter $rvm_ruby_string is not installed."
       if [[ ! -z "$rvm_install_on_use_flag" ]] ; then
-        $rvm_scripts_path/manage "install" "$rvm_ruby_string"
+        "$rvm_scripts_path/manage" "install" "$rvm_ruby_string"
       else
-        $rvm_scripts_path/log "info" "To install do: 'rvm install $rvm_ruby_string'"
+        "$rvm_scripts_path/log" "info" "To install do: 'rvm install $rvm_ruby_string'"
         return 1
       fi
     fi
@@ -280,7 +280,7 @@ __rvm_use() {
     __rvm_ensure_has_environment_files
 
     if [[ ! -z "$rvm_verbose_flag" ]] ; then
-      $rvm_scripts_path/log "info" "Using $(basename $GEM_HOME | \tr '-' ' ' | sed 's/'${rvm_gemset_separator}'/ with gemset /')"
+      "$rvm_scripts_path/log" "info" "Using $(basename $GEM_HOME | \tr '-' ' ' | sed 's/'${rvm_gemset_separator}'/ with gemset /')"
     fi
 
     new_path="$GEM_HOME/bin:$rvm_ruby_global_gems_path/bin:$MY_RUBY_HOME/bin:$rvm_bin_path:$(__rvm_remove_rvm_from_path ; printf $PATH)"
@@ -301,35 +301,35 @@ __rvm_use() {
   if [[ -n "$rvm_default_flag" && "default" != "$rvm_ruby_interpreter" ]] ; then
     if [[ "$rvm_selfcontained" = "0" ]] ; then
       # Sets up the default wrappers.
-      $rvm_scripts_path/wrapper "$rvm_ruby_string" --no-prefix
+      "$rvm_scripts_path/wrapper" "$rvm_ruby_string" --no-prefix
     else
-      $rvm_scripts_path/wrapper "$rvm_scripts_path" "default"
+      "$rvm_scripts_path/wrapper" "$rvm_scripts_path" "default"
     fi
     if [[ "system" = "$rvm_ruby_interpreter" ]] ; then
-      $rvm_scripts_path/alias delete default &> /dev/null
+      "$rvm_scripts_path/alias" delete default &> /dev/null
       \find "$rvm_bin_path" -name 'default_*' -maxdepth 1 -delete
-      \rm -f $rvm_config_path/default
-      \rm -f $rvm_environments_path/default
-      \rm -rf $rvm_wrappers_path/default
+      \rm -f "$rvm_config_path/default"
+      \rm -f "$rvm_environments_path/default"
+      \rm -rf "$rvm_wrappers_path/default"
     else
-      RUBY_VERSION="$($rvm_ruby_home/bin/ruby -v | sed 's#^\(.*\) (.*$#\1#')"
+      RUBY_VERSION="$("$rvm_ruby_home/bin/ruby" -v | sed 's#^\(.*\) (.*$#\1#')"
       export GEM_HOME GEM_PATH BUNDLE_PATH MY_RUBY_HOME RUBY_VERSION
-      $rvm_scripts_path/alias delete default &> /dev/null
-      $rvm_scripts_path/alias create default "$environment_id" >& /dev/null
-      ln -nfs $rvm_environments_path/$environment_id $rvm_environments_path/default
-      ln -nfs $rvm_wrappers_path/$environment_id $rvm_wrappers_path/default
+      "$rvm_scripts_path/alias" delete default &> /dev/null
+      "$rvm_scripts_path/alias" create default "$environment_id" >& /dev/null
+      ln -nfs "$rvm_environments_path/$environment_id" "$rvm_environments_path/default"
+      ln -nfs "$rvm_wrappers_path/$environment_id" "$rvm_wrappers_path/default"
     fi
   fi ; unset rvm_default_flag
 
   if [[ -n "$rvm_wrapper_name" ]] ; then
-    $rvm_scripts_path/wrapper "$environment_id" "$rvm_wrapper_name" > /dev/null 2>&1
+    "$rvm_scripts_path/wrapper" "$environment_id" "$rvm_wrapper_name" > /dev/null 2>&1
     unset rvm_wrapper_name
   fi
 
   if [[ -n "$rvm_ruby_alias" ]]; then
-    $rvm_scripts_path/log "info" "Attempting to alias $environment_id to $rvm_ruby_alias"
-    $rvm_scripts_path/alias delete "$rvm_ruby_alias" > /dev/null 2>&1
-    rvm_alias_expanded=1 $rvm_scripts_path/alias create "$rvm_ruby_alias" "$environment_id" > /dev/null 2>&1
+    "$rvm_scripts_path/log" "info" "Attempting to alias $environment_id to $rvm_ruby_alias"
+    "$rvm_scripts_path/alias" delete "$rvm_ruby_alias" > /dev/null 2>&1
+    rvm_alias_expanded=1 "$rvm_scripts_path/alias" create "$rvm_ruby_alias" "$environment_id" > /dev/null 2>&1
     unset ruby_alias rvm_ruby_alias
   fi
 
@@ -339,11 +339,11 @@ __rvm_use() {
     export MAGLEV_HOME="$rvm_ruby_home"
     export GEMSTONE_GLOBAL_DIR=$MAGLEV_HOME
     if [[ -x "$MAGLEV_HOME/gemstone/bin/gslist" ]] ; then
-      $MAGLEV_HOME/gemstone/bin/gslist -clv > /dev/null 2>&1 ; result=$?
-      if [[ $result -eq 1 ]] ; then $rvm_ruby_home/bin/maglev start ; fi
+      "$MAGLEV_HOME/gemstone/bin/gslist" -clv > /dev/null 2>&1 ; result=$?
+      if [[ $result -eq 1 ]] ; then "$rvm_ruby_home/bin/maglev" start ; fi
     fi
   fi
-  rvm_hook="after_use" ; source $rvm_scripts_path/hook
+  rvm_hook="after_use" ; source "$rvm_scripts_path/hook"
 }
 
 __rvm_ruby_string() {
@@ -373,7 +373,7 @@ __rvm_ruby_string() {
 
   __rvm_unset_ruby_variables
 
-  for string in $(echo $ruby_string | \tr '-' ' ') ; do
+  for string in $(echo "${ruby_string//-/ }") ; do
     if [[ "head" = "$string" ]] ; then
       rvm_ruby_revision="head"
       unset rvm_ruby_patch_level rvm_ruby_revision rvm_ruby_tag
@@ -386,16 +386,16 @@ __rvm_ruby_string() {
       rvm_ruby_version="nightly"
       rvm_nightly_flag=1
       break
-    elif $rvm_scripts_path/match "$string" "^preview" ; then
+    elif "$rvm_scripts_path/match" "$string" "^preview" ; then
       rvm_ruby_patch_level="$string"
-    elif $rvm_scripts_path/match "$string" "^rc[0-9]" ; then
+    elif "$rvm_scripts_path/match" "$string" "^rc[0-9]" ; then
       rvm_ruby_patch_level="$string"
-    elif $rvm_scripts_path/match "$string" "^[0-9]\.[0-9]" ; then
+    elif "$rvm_scripts_path/match" "$string" "^[0-9]\.[0-9]" ; then
       rvm_ruby_version="$string"
       unset rvm_ruby_revision rvm_ruby_tag
-    elif $rvm_scripts_path/match "$string" "^p[0-9]" ; then
+    elif "$rvm_scripts_path/match" "$string" "^p[0-9]" ; then
       rvm_ruby_patch_level="$string"
-    elif [[ -n "$rvm_ruby_version" ]] && $rvm_scripts_path/match "$string" "^[0-9][0-9]" ; then
+    elif [[ -n "$rvm_ruby_version" ]] && "$rvm_scripts_path/match" "$string" "^[0-9][0-9]" ; then
       if [[ "ree" = "$rvm_ruby_interpreter" ]] ; then
         rvm_ruby_patch_level="$string"
         unset rvm_ruby_revision
@@ -407,40 +407,40 @@ __rvm_ruby_string() {
       else
         rvm_ruby_revision="r$string"
       fi
-    elif $rvm_scripts_path/match "$string" "^r[0-9]" ; then
+    elif "$rvm_scripts_path/match" "$string" "^r[0-9]" ; then
       unset rvm_ruby_patch_level
       rvm_ruby_revision="$string"
-    elif $rvm_scripts_path/match "$string" "^s[0-9]" ; then
+    elif "$rvm_scripts_path/match" "$string" "^s[0-9]" ; then
       unset rvm_ruby_revision
       rvm_ruby_sha="$string"
-    elif $rvm_scripts_path/match "$string" "^t[v0-9]" ; then
+    elif "$rvm_scripts_path/match" "$string" "^t[v0-9]" ; then
       unset rvm_ruby_patch_level rvm_ruby_revision
       rvm_ruby_tag="$string"
-    elif $rvm_scripts_path/match "$string" "^m[0-9]" ; then
+    elif "$rvm_scripts_path/match" "$string" "^m[0-9]" ; then
       rvm_ruby_mode="$string"
-    elif $rvm_scripts_path/match "$string" "^u[a-z0-9]" ; then
+    elif "$rvm_scripts_path/match" "$string" "^u[a-z0-9]" ; then
       unset rvm_ruby_patch_level rvm_ruby_revision rvm_ruby_tag rvm_ruby_patch
       rvm_ruby_user_tag="$string"
-    elif $rvm_scripts_path/match "$string" "^b[0-9][0-9]" ; then
+    elif "$rvm_scripts_path/match" "$string" "^b[0-9][0-9]" ; then
       rvm_ruby_bits="$string"
-    elif $rvm_scripts_path/match "$string" "^n" ; then
+    elif "$rvm_scripts_path/match" "$string" "^n" ; then
       rvm_ruby_name="${string/n/}"
-    elif $rvm_scripts_path/match "ruby rbx jruby macruby ree rubinius maglev mput shyouhei ironruby " "$string " ; then
+    elif "$rvm_scripts_path/match" "ruby rbx jruby macruby ree rubinius maglev mput shyouhei ironruby " "$string " ; then
       # NOTE: The space at the end of each of the above strings is *very* important.
       rvm_ruby_interpreter="$string"
     else
-      $rvm_scripts_path/log "error" "Unknown ruby string component: '$string'"
+      "$rvm_scripts_path/log" "error" "Unknown ruby string component: '$string'"
       return 1
     fi
   done
 
   # Unspecified interpreter
   if [[ -z "$rvm_ruby_interpreter" ]] ; then
-    if $rvm_scripts_path/match "$rvm_ruby_version" "^1\.[8-9]" ; then
+    if "$rvm_scripts_path/match" "$rvm_ruby_version" "^1\.[8-9]" ; then
       rvm_ruby_interpreter="ruby"
-    elif $rvm_scripts_path/match "$rvm_ruby_version" "^0.5" ; then
+    elif "$rvm_scripts_path/match" "$rvm_ruby_version" "^0.5" ; then
       rvm_ruby_interpreter="macruby"
-    elif $rvm_scripts_path/match "$rvm_ruby_version" "^1.[2-4]" ; then
+    elif "$rvm_scripts_path/match" "$rvm_ruby_version" "^1.[2-4]" ; then
       rvm_ruby_interpreter="jruby"
     fi
   fi
@@ -513,7 +513,7 @@ __rvm_gemset_select() {
       fi
     fi
 
-    if [[ -n "$rvm_gemset_name" ]] && ! $rvm_scripts_path/match "$rvm_gemset_name" "^[0-9]\.[0-9]" ; then
+    if [[ -n "$rvm_gemset_name" ]] && ! "$rvm_scripts_path/match" "$rvm_gemset_name" "^[0-9]\.[0-9]" ; then
       rvm_ruby_gem_home="$rvm_gems_path/${rvm_ruby_string}${rvm_gemset_separator}${rvm_gemset_name}"
     else
       if [[ -n "$rvm_ruby_string" ]] && [[ "$rvm_ruby_interpreter" != "system" ]] ; then
@@ -540,7 +540,7 @@ __rvm_gemset_select() {
         rvm_ruby_gem_home="$rvm_gems_path/${rvm_ruby_string}${rvm_gemset_separator}${rvm_gemset_name}"
       fi ; unset gemset
     else
-      $rvm_scripts_path/log "error" "Gemsets can not be used with non rvm controlled rubies (currently)."
+      "$rvm_scripts_path/log" "error" "Gemsets can not be used with non rvm controlled rubies (currently)."
       return 1
     fi
   fi
@@ -548,7 +548,7 @@ __rvm_gemset_select() {
   # If the gemset does not exist, then notify the user as such and abort the action.
   if [[ -n "$rvm_gemset_name" ]] && [[ ! -d "$rvm_ruby_gem_home" ]] ; then
     if [[ "$rvm_gemset_create_on_use_flag" -ne 1 ]] && [[ "$rvm_create_flag" -ne 1 ]] && [[ "$rvm_delete_flag" -ne 1 ]] ; then
-      $rvm_scripts_path/log "error" "Gemset '$rvm_gemset_name' does not exist, rvm gemset create '$rvm_gemset_name' first."
+      "$rvm_scripts_path/log" "error" "Gemset '$rvm_gemset_name' does not exist, rvm gemset create '$rvm_gemset_name' first."
       return 1
     fi
   elif [[ "$rvm_delete_flag" -eq 1 ]] ; then
@@ -580,21 +580,21 @@ __rvm_gemset_use() {
   if [[ -n "$rvm_ruby_gem_home" ]] ; then
     if [[ ! -d "$rvm_ruby_gem_home" ]] ; then
       if [[ "$rvm_gemset_create_on_use_flag" -eq 1 ]] || [[ "$rvm_create_flag" -eq 1 ]]; then
-        $rvm_scripts_path/gemsets create $rvm_gemset_name
+        "$rvm_scripts_path/gemsets" create "$rvm_gemset_name"
       else
-        $rvm_scripts_path/log "error" "Gemset '$rvm_gemset_name' does not exist, rvm gemset create '$rvm_gemset_name' first."
+        "$rvm_scripts_path/log" "error" "Gemset '$rvm_gemset_name' does not exist, rvm gemset create '$rvm_gemset_name' first."
         return 1
       fi
     fi
 
     if [[ "$rvm_interactive" -eq 1 ]] || [[ "$rvm_verbose_flag" -eq 1 ]] ; then
-      $rvm_scripts_path/log "info" "Now using gemset '${rvm_gemset_name:-default}'"
+      "$rvm_scripts_path/log" "info" "Now using gemset '${rvm_gemset_name:-default}'"
     fi
 
-    rvm_ruby_gem_home="$(echo $GEM_HOME | sed 's/'${rvm_gemset_separator}'.*$//')${rvm_gemset_separator}${rvm_gemset_name}"
+    rvm_ruby_gem_home="$(echo "$GEM_HOME" | sed 's/'${rvm_gemset_separator}'.*$//')${rvm_gemset_separator}${rvm_gemset_name}"
     GEM_HOME="$rvm_ruby_gem_home"
     BUNDLE_PATH="$rvm_ruby_gem_home"
-    GEM_PATH="$rvm_ruby_gem_home/bin:$(echo $GEM_HOME | sed 's/'${rvm_gemset_separator}'.*$//')${rvm_gemset_separator}global/bin"
+    GEM_PATH="$rvm_ruby_gem_home/bin:$(echo "$GEM_HOME" | sed 's/'${rvm_gemset_separator}'.*$//')${rvm_gemset_separator}global/bin"
     export rvm_ruby_gem_home GEM_HOME BUNDLE_PATH GEM_PATH
 
     __rvm_use # Now ensure the selection takes effect for the environment.
@@ -604,8 +604,8 @@ __rvm_gemset_use() {
 
 __rvm_gemset_clear() {
   unset rvm_gemset_name ; shift
-  rvm_ruby_gem_home="$(echo $GEM_HOME | sed "s#${rvm_gemset_separator:-'@'}.*\$##g")"
-  rvm_ruby_global_gems_path="$(echo $GEM_HOME | sed 's/'${rvm_gemset_separator}'.*$//')${rvm_gemset_separator}global"
+  rvm_ruby_gem_home="$(echo "$GEM_HOME" | sed "s#${rvm_gemset_separator:-'@'}.*\$##g")"
+  rvm_ruby_global_gems_path="$(echo "$GEM_HOME" | sed 's/'${rvm_gemset_separator}'.*$//')${rvm_gemset_separator}global"
   GEM_HOME=$rvm_ruby_gem_home
   BUNDLE_PATH="$rvm_ruby_gem_home"
   GEM_PATH="$rvm_ruby_gem_home/bin:$rvm_ruby_global_gems_path/bin"
diff --git a/scripts/set b/scripts/set
--- a/scripts/set
+++ b/scripts/set
@@ -3,7 +3,7 @@
 source "$rvm_scripts_path/base"
 
 if [[ -z "$1" ]] ; then
-  $rvm_scripts_path/log "error" "Action must be specified."
+  "$rvm_scripts_path/log" "error" "Action must be specified."
   exit 1
 fi
 
@@ -35,7 +35,7 @@ __rvm_ruby_do() {
     elif [[ "system" = "$rvm_ruby_string" ]] && [[ -x "$(command -v $binary)" ]] ; then
       binary="$(basename $(command -v $binary) 2>/dev/null)"
     else
-      $rvm_scripts_path/log "warn" "'$binary not found for $rvm_ruby_string' either does not exist or is not executable? :("
+      "$rvm_scripts_path/log" "warn" "'$binary not found for $rvm_ruby_string' either does not exist or is not executable? :("
       __rvm_unset_ruby_variables
       return 1
     fi
@@ -48,9 +48,9 @@ __rvm_ruby_do() {
     load_path="$(dirname $(command -v $binary) 2>/dev/null):$rvm_ruby_load_path"
     # TODO: the else case below should be run if $args =~ /\.rb$/
     if [[ "ruby" = "$(basename $binary)" ]] && [[ "$rvm_benchmark_flag" -ne 1 ]] ; then
-      if $rvm_scripts_path/match "$args" "\.rb$" ; then
+      if "$rvm_scripts_path/match" "$args" "\.rb$" ; then
         if [[ -z "$prefix" ]] ; then prefix="-S" ; fi
-        if ! $rvm_scripts_path/match "$args" "$prefix" ; then
+        if ! "$rvm_scripts_path/match" "$args" "$prefix" ; then
           args="$prefix $args"
         fi
       fi
@@ -70,7 +70,7 @@ __rvm_ruby_do() {
       if [[ "$current_env" != "$current_set_ruby" ]]; then
         current_env="$current_set_ruby ($current_env)"
       fi
-      $rvm_scripts_path/log "info" "$current_env: $(ruby -v $rvm_ruby_mode | \tr "\n" ' ')\n"
+      "$rvm_scripts_path/log" "info" "$current_env: $(ruby -v $rvm_ruby_mode | \tr "\n" ' ')\n"
       unset current_env
     fi
     eval "$rvm_command"
@@ -117,7 +117,7 @@ __rvm_yaml() {
   if [[ ! -z "$ZSH_VERSION" ]] ; then array_start=1 ; else array_start=0 ; fi
   for (( index = $array_start ; index < $total + $array_start ; index++ )) ; do
     if [[ ! -z "$rvm_debug_flag" ]] ; then
-      $rvm_scripts_path/log "debug" "${rubies[$index]}: ${statuses[$index]}"
+      "$rvm_scripts_path/log" "debug" "${rubies[$index]}: ${statuses[$index]}"
     fi
     yaml="$yaml\n  \"${rubies[$index]}\": ${statuses[$index]}"
   done ; unset index array_start
@@ -139,7 +139,7 @@ __rvm_json() {
   if [[ ! -z "$ZSH_VERSION" ]] ; then array_start=1 ; else array_start=0 ; fi
   for (( index = $array_start ; index < $total + $array_start ; index++ )) ; do
     if [[ ! -z "$rvm_debug_flag" ]] ; then
-      $rvm_scripts_path/log "debug" "${rubies[$index]}: ${statuses[$index]}"
+      "$rvm_scripts_path/log" "debug" "${rubies[$index]}: ${statuses[$index]}"
     fi
     json="$json\n    {\"${rubies[$index]}\": ${statuses[$index]}}"
     if (( $index + 1 < $total + $array_start )) ; then json="$json,  " ; fi
@@ -163,8 +163,8 @@ action="$1";
 args="$*"
 
 if [[ "$action" == "ruby" ]] && echo "$args" | \grep -q  "^'--[^[:space:]]*'$" ; then
-  $rvm_scripts_path/log "warn" "You called rvm ruby with the arguments $args which look like use options."
-  $rvm_scripts_path/log "warn" "Please note that 'rvm ruby' invokes set operations instead."
+  "$rvm_scripts_path/log" "warn" "You called rvm ruby with the arguments $args which look like use options."
+  "$rvm_scripts_path/log" "warn" "Please note that 'rvm ruby' invokes set operations instead."
 fi
 
 rvm_ruby_strings="$(__rvm_expand_ruby_string "$rvm_ruby_strings")"
@@ -180,6 +180,6 @@ if [[ ! -z "$rvm_summary_flag" ]] ; then __rvm_summary ; fi
 if [[ ! -z "$rvm_yaml_flag" ]]    ; then __rvm_yaml    ; fi
 if [[ ! -z "$rvm_json_flag" ]]    ; then __rvm_json    ; fi
 
-rvm_hook="after_do" ; source $rvm_scripts_path/hook
+rvm_hook="after_do" ; source "$rvm_scripts_path/hook"
 
 exit ${#errors[*]}
diff --git a/scripts/utility b/scripts/utility
--- a/scripts/utility
+++ b/scripts/utility
@@ -48,11 +48,10 @@ __rvm_dump_environment() {
     if [[ "$dump_environment_type" == "atheis"* ]]; then
       \rm -rf "$dump_environment_file" && ln -s /dev/null "$dump_environment_file" >/dev/null 2>&1
     else
-      $rvm_scripts_path/environment-convertor "$dump_environment_type" "$(__rvm_environment_identifier)" > "$dump_environment_file"
+      "$rvm_scripts_path/environment-convertor" "$dump_environment_type" "$(__rvm_environment_identifier)" > "$dump_environment_file"
       [[ "$?" -gt 0 ]] && \rm -rf "$dump_environment_file"
     fi
-  fi
-  unset rvm_dump_environment_flag
+  fi ; unset rvm_dump_environment_flag
 }
 
 # Return a list of directories under a given base path.
@@ -148,7 +147,7 @@ __rvm_set_path_variable() {
   if [[ -d "$1" ]] ; then
     eval "${path_variable}=${1}"
   else
-    $rvm_scripts_path/log "error" "'$1' is not a valid path."
+    "$rvm_scripts_path/log" "error" "'$1' is not a valid path."
   fi ; unset path_variable
 }
 
@@ -170,9 +169,9 @@ __rvm_remove_rvm_from_path() {
 __rvm_run() {
   log_file_name="$1" ; command="$2" ; message="$3"
   if [[ -z "$rvm_ruby_log_path" ]] ; then rvm_ruby_log_path="$rvm_log_path" ; fi
-  if [[ -n "$message" ]] ; then $rvm_scripts_path/log "info" "$message" ; fi
+  if [[ -n "$message" ]] ; then "$rvm_scripts_path/log" "info" "$message" ; fi
   if [[ -n "$rvm_debug_flag" ]] ; then
-    $rvm_scripts_path/log "debug" "Executing: $command"
+    "$rvm_scripts_path/log" "debug" "Executing: $command"
   fi
 
   \mkdir -p "$(dirname "$rvm_ruby_log_path/$log_file_name.log")"
@@ -183,7 +182,7 @@ __rvm_run() {
   else
     eval "nice -n $rvm_niceness $command" >> $rvm_ruby_log_path/$log_file_name.log 2>> $rvm_ruby_log_path/$log_file_name.error.log
   fi
-  if [[ $? -gt 0 ]] ; then $rvm_scripts_path/log "error" "Error running '$command', please check $rvm_ruby_log_path/$log_file_name*.log" ; __rvm_pushpop ; return 1 ; fi
+  if [[ $? -gt 0 ]] ; then "$rvm_scripts_path/log" "error" "Error running '$command', please check $rvm_ruby_log_path/$log_file_name*.log" ; __rvm_pushpop ; return 1 ; fi
   unset log_file command
 }
 
@@ -192,9 +191,9 @@ __rvm_run_with_env() {
   log_file_name="$1" ; env_name="$2" ; command="$3" ; message="$4"
   if [[ -z "$env_name" ]]; then env_name="$(__rvm_environment_identifier)"; fi
   if [[ -z "$rvm_ruby_log_path" ]] ; then rvm_ruby_log_path="$rvm_log_path" ; fi
-  if [[ -n "$message" ]] ; then $rvm_scripts_path/log "info" "$message" ; fi
+  if [[ -n "$message" ]] ; then "$rvm_scripts_path/log" "info" "$message" ; fi
   if [[ -n "$rvm_debug_flag" ]] ; then
-    $rvm_scripts_path/log "debug" "Executing: $command in environment "$env_name""
+    "$rvm_scripts_path/log" "debug" "Executing: $command in environment "$env_name""
   fi
 
   \mkdir -p "$(dirname "$rvm_ruby_log_path/$log_file_name.log")"
@@ -205,13 +204,13 @@ __rvm_run_with_env() {
   else
     eval "nice -n $rvm_niceness __rvm_with_env '$env_name' '$command'" >> $rvm_ruby_log_path/$log_file_name.log 2>> $rvm_ruby_log_path/$log_file_name.error.log
   fi
-  if [[ $? -gt 0 ]] ; then $rvm_scripts_path/log "error" "Error running '$command' under $env_name, please check $rvm_ruby_log_path/$log_file_name*.log" ; __rvm_pushpop ; return 1 ; fi
+  if [[ $? -gt 0 ]] ; then "$rvm_scripts_path/log" "error" "Error running '$command' under $env_name, please check $rvm_ruby_log_path/$log_file_name*.log" ; __rvm_pushpop ; return 1 ; fi
   unset log_file command env_name
 }
 
 # Unset both rvm variables as well as ruby-specific variables
 # Preserve gemset if 'rvm_sticky' is set (persist gemset unless clear is explicitely called).
-__rvm_cleanup_variables() {
+__rvm_cleanse_variables() {
   __rvm_unset_ruby_variables
 
   if [[ "$rvm_sticky_flag" = "1" ]] ; then export rvm_gemset_name ; else unset rvm_gemset_name  ; fi
@@ -230,8 +229,8 @@ __rvm_with_env() {
   rvm_env_command="$(echo "$2" | sed "s/rvm /rvm $rvm_env_args /")"
   # Subshells!
   (
-    source $rvm_scripts_path/rvm
-    rvm $rvm_env_args use $1 && eval "$rvm_env_command"
+    source "$rvm_scripts_path/rvm"
+    rvm "$rvm_env_args" use $1 && eval "$rvm_env_command"
   )
   unset rvm_env_args rvm_env_command
 }
@@ -241,7 +240,7 @@ __rvm_with_env() {
 __rvm_18_compat_ruby() {
   rubies=""
   for ruby_name in $(\ls $rvm_rubies_path); do
-    if [[ ! -L "$rvm_rubies_path/$ruby_name" ]] && $rvm_scripts_path/match "$ruby_name" '^(ruby-1.8.[[:digit:]]|rbx|ree)-'; then
+    if [[ ! -L "$rvm_rubies_path/$ruby_name" ]] && "$rvm_scripts_path/match" "$ruby_name" '^(ruby-1.8.[[:digit:]]|rbx|ree)-'; then
       rubies="$rubies $ruby_name"
     fi
   done; unset ruby_name
@@ -253,20 +252,18 @@ __rvm_ensure_has_18_compat_ruby() {
   if [[ -z "$(__rvm_18_compat_ruby)" ]]; then
     # TODO: install currently doesn't return the correct status.
     local compat_result=0
-    if ! ( $rvm_scripts_path/manage install 1.8.7 ); then
-      $rvm_scripts_path/log "fail" "To proceed rvm requires a 1.8-compatible ruby is installed. We attempted to install 1.8.7 automatically but it failed."
-      $rvm_scripts_path/log "fail" "Please install it manually (or a compatible alternative) to proceed."
+    if ! ( "$rvm_scripts_path/manage" install 1.8.7 ); then
+      "$rvm_scripts_path/log" "fail" "To proceed rvm requires a 1.8-compatible ruby is installed. We attempted to install 1.8.7 automatically but it failed."
+      "$rvm_scripts_path/log" "fail" "Please install it manually (or a compatible alternative) to proceed."
       compat_result=1
-    fi
-    unset original_ruby
+    fi ; unset original_ruby
     return $compat_result
   fi
 }
 
 __rvm_inherit_trace_flag() {
   if [[ -n "$rvm_trace_flag" ]]; then
-    set -x
-    export rvm_trace_flag
+    set -x ; export rvm_trace_flag
   fi
 }
 
@@ -290,7 +287,7 @@ __rvm_set_rvmrc() {
 
     if [[ -s .rvmrc ]] ; then
       mv .rvmrc .rvmrc.$(date +%m.%d.%Y-%H:%M:%S)
-      $rvm_scripts_path/log "warning" ".rvmrc is not empty, moving aside to preserve."
+      "$rvm_scripts_path/log" "warning" ".rvmrc is not empty, moving aside to preserve."
     fi
 
     local identifier=$(__rvm_environment_identifier)
@@ -299,7 +296,7 @@ __rvm_set_rvmrc() {
 
     unset flags
   else
-    $rvm_scripts_path/log "error" ".rvmrc cannot be set in your home directory. \n The home .rvmrc is for global rvm settings only."
+    "$rvm_scripts_path/log" "error" ".rvmrc cannot be set in your home directory. \n The home .rvmrc is for global rvm settings only."
   fi
 
 }
@@ -308,7 +305,7 @@ __rvm_load_rvmrc() {
   for rvmrc in /etc/rvmrc $HOME/.rvmrc ; do
     if [[ -f "$rvmrc" ]] ; then
       if \grep -q '^\s*rvm .*$' $rvmrc ; then
-        $rvm_scripts_path/log "error" "$rvmrc is for rvm settings only.\nrvm CLI may NOT be called from within $rvmrc. \nSkipping the loading of $rvmrc"
+        "$rvm_scripts_path/log" "error" "$rvmrc is for rvm settings only.\nrvm CLI may NOT be called from within $rvmrc. \nSkipping the loading of $rvmrc"
         return 1
       else
         source "$rvmrc"
@@ -332,7 +329,7 @@ __rvm_benchmark() {
   old_rvm_ruby_string=$rvm_ruby_string
   unset rvm_ruby_string
   export rvm_ruby_strings
-  $rvm_scripts_path/set $rvm_action $rvm_ruby_args
+  "$rvm_scripts_path/set" "$rvm_action" $rvm_ruby_args
   result=$?
   # Restore the state pre-sets.
   [[ -n "$old_rvm_ruby_string" ]] && rvm_ruby_string=$old_rvm_ruby_string
@@ -341,19 +338,19 @@ __rvm_benchmark() {
 
 # Loop over the currently installed rubies and refresh their binscripts.
 __rvm_bin_scripts() {
-  for rvm_ruby_binary in $rvm_rubies_path/*/bin/ruby ; do
-  if [[ -x "$rvm_ruby_binary" ]] ; then
-    rvm_ruby_string=$(dirname "$rvm_ruby_binary" | xargs dirname | xargs basename)
-    __rvm_select
-    __rvm_bin_script
-  fi
+  for rvm_ruby_binary in "$rvm_rubies_path"/*/bin/ruby ; do
+    if [[ -x "$rvm_ruby_binary" ]] ; then
+      rvm_ruby_string=$(dirname "$rvm_ruby_binary" | xargs dirname | xargs basename)
+      __rvm_select
+      __rvm_bin_script
+    fi
   done
 }
 
 # Write the bin/ wrapper script for currently selected ruby.
 # TODO: Adjust binscript to be able to handle all rubies not just the standard interpreteres.
 __rvm_bin_script() {
-  $rvm_scripts_path/wrapper "$rvm_ruby_string"
+  "$rvm_scripts_path/wrapper" "$rvm_ruby_string"
 }
 
 # Add bin path if not present
@@ -386,7 +383,7 @@ __rvm_reset() {
   __rvm_unset_ruby_variables
 
   for system_config in system_ruby system_gem_path system_user_gem_path ; do
-    $rvm_scripts_path/db "$rvm_config_path/user" "$system_config" "delete"
+    "$rvm_scripts_path/db" "$rvm_config_path/user" "$system_config" "delete"
   done ; unset system_config variable
 
   \rm -f $rvm_bin_path/ruby $rvm_bin_path/gem $rvm_bin_path/rake $rvm_bin_path/irb $rvm_bin_path/default*
@@ -395,23 +392,23 @@ __rvm_reset() {
 # Implode removes the entire rvm installation under $rvm_path.
 __rvm_implode() {
   while : ; do
-    $rvm_scripts_path/log "warn" "Are you SURE you wish for rvm to implode? This will remove $rvm_path ? (type 'yes' or 'no')"
+    "$rvm_scripts_path/log" "warn" "Are you SURE you wish for rvm to implode? This will remove $rvm_path ? (type 'yes' or 'no')"
     read response
     if [[ "yes" = "$response" ]] ; then
       if [[ "/" = "$rvm_path" ]] ; then
-        $rvm_scripts_path/log "error" "remove '/' ?!... NO!"
+        "$rvm_scripts_path/log" "error" "remove '/' ?!... NO!"
       else
         if [[ -d "$rvm_path" ]] ; then
-          $rvm_scripts_path/log "info" "Hai! Removing $rvm_path"
+          "$rvm_scripts_path/log" "info" "Hai! Removing $rvm_path"
           \rm -rf $rvm_path/
           echo "$rvm_path has been removed."
         else
-          $rvm_scripts_path/log "info" "It appears that $rvm_path is already non existant."
+          "$rvm_scripts_path/log" "info" "It appears that $rvm_path is already non existant."
         fi
       fi
       break
     elif [[ "no" = "$response" ]] ; then
-      $rvm_scripts_path/log "info" "Cancelling implosion, no harm done :)"
+      "$rvm_scripts_path/log" "info" "Cancelling implosion, no harm done :)"
       break
     fi
   done
@@ -421,7 +418,7 @@ __rvm_implode() {
 __rvm_source_dir() {
   if [[ -z "$rvm_ruby_selected_flag" ]] ; then __rvm_select ; fi
   if [[ -z "$rvm_ruby_src_path" ]] ; then
-    $rvm_scripts_path/log "fail" "No source directory exists for the default implementation."
+    "$rvm_scripts_path/log" "fail" "No source directory exists for the default implementation."
   else
     echo "$rvm_ruby_src_path"
   fi
@@ -449,7 +446,7 @@ __rvm_update() {
   fi
   [[ -n "$rvm_bin_flag" ]] && __rvm_bin_scripts
   # Update to the latest rubygems.
-  [[ -n "$rvm_rubygems_flag" ]] && $rvm_scripts_path/rubygems current
+  [[ -n "$rvm_rubygems_flag" ]] && "$rvm_scripts_path/rubygems" current
 
   unset rvm_update_flag rvm_action rvm_self_flag rvm_ruby_revision rvm_bin_flag rvm_rubygems_flag
   __rvm_pushpop
@@ -482,14 +479,14 @@ __rvm_update_rvm() {
 }
 
 __rvm_reboot() {
-  $rvm_scripts_path/log "warn" "Do you wish to reboot rvm? ('yes', or 'no')"
+  "$rvm_scripts_path/log" "warn" "Do you wish to reboot rvm? ('yes', or 'no')"
   read response
   if [[ "yes" = "$response" ]] ; then
     builtin cd $rvm_path
     __rvm_reset
-    mv $rvm_path/archives ~/.archives
+    mv "$rvm_path/archives" "$HOME/.archives"
     if [[ "/" = "$rvm_path" ]] ; then
-      $rvm_scripts_path/log "error" "remove '/' ?!... NO!"
+      "$rvm_scripts_path/log" "error" "remove '/' ?!... NO!"
     else
       if [[ -d "$rvm_path" ]] ; then \rm -rf "$rvm_path/" ; fi
     fi
@@ -497,14 +494,14 @@ __rvm_reboot() {
     __rvm_update_rvm
     source $rvm_path/scripts/rvm
   else
-    $rvm_scripts_path/log "info" "Carry on then..."
+    "$rvm_scripts_path/log" "info" "Carry on then..."
   fi ; unset response
 }
 
 # Create the irbrc for the currently selected ruby installation.
 __rvm_irbrc() {
   if [[ -d "$rvm_ruby_home" ]] && [[ ! -s "$rvm_ruby_irbrc" ]] ; then
-    \cp $rvm_scripts_path/irbrc $rvm_ruby_irbrc
+    \cp "$rvm_scripts_path/irbrc" "$rvm_ruby_irbrc"
   fi
 }
 
@@ -540,7 +537,7 @@ __rvm_state() {
 __rvm_inspect() {
   for binary in $rvm_ruby_args ; do
     actual_file="$(command -v $binary)"
-    $rvm_scripts_path/log "info" "$actual_file:"
+    "$rvm_scripts_path/log" "info" "$actual_file:"
     if [[ -n "$rvm_shebang_flag" ]] ; then head -n 1    < "$actual_file" ; fi
     if [[ -n "$rvm_env_flag" ]]     ; then awk '/ENV/'  < "$actual_file" ; fi
     if [[ -n "$rvm_path_flag" ]]    ; then awk '/PATH/' < "$actual_file" ; fi
@@ -624,7 +621,7 @@ __rvm_ensure_has_environment_files() {
     directory_name="$rvm_wrappers_path/$wrapper_identifier"
     if [[ ! -L "$directory_name" && ! -d "$directory_name" ]]; then
       \mkdir -p "$directory_name"
-      $rvm_scripts_path/wrapper "$wrapper_identifier" &> /dev/null
+      "$rvm_scripts_path/wrapper" "$wrapper_identifier" &> /dev/null
     fi
     unset rvm_creating_default_wrappers directory_name
     done; unset wrapper_identifier
@@ -637,7 +634,7 @@ __rvm_strip() {
 }
 
 __rvm_using_gemset_globalcache() {
-  $rvm_scripts_path/db "$rvm_config_path/user" "use_gemset_globalcache" | \grep -q '^true$'
+  "$rvm_scripts_path/db" "$rvm_config_path/user" "use_gemset_globalcache" | \grep -q '^true$'
 }
 
 __rvm_current_gemcache_dir() {
@@ -684,24 +681,24 @@ __rvm_rvmrc_key() {
 
 __rvm_reset_rvmrc_trust() {
   touch "$rvm_config_path/rvmrcs"
-  $rvm_scripts_path/db "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")" "delete" >/dev/null 2>&1
+  "$rvm_scripts_path/db" "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")" "delete" >/dev/null 2>&1
 }
 
 __rvm_trust_rvmrc() {
   touch "$rvm_config_path/rvmrcs"
   __rvm_reset_rvmrc_trust "$1"
-  $rvm_scripts_path/db "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")" "1" >/dev/null 2>&1
+  "$rvm_scripts_path/db" "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")" "1" >/dev/null 2>&1
 }
 
 __rvm_untrust_rvmrc() {
   touch "$rvm_config_path/rvmrcs"
   __rvm_reset_rvmrc_trust "$1"
-  $rvm_scripts_path/db "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")" "0" >/dev/null 2>&1
+  "$rvm_scripts_path/db" "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")" "0" >/dev/null 2>&1
 }
 
 __rvm_rvmrc_stored_trust() {
   touch "$rvm_config_path/rvmrcs"
-  $rvm_scripts_path/db "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")"
+  "$rvm_scripts_path/db" "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")"
 }
 
 __rvm_rvmrc_tools() {
@@ -867,16 +864,16 @@ __rvm_environment_identifier() {
 
 __rvm_expand_ruby_string() {
   if [[ -z "$1" || "$1" = "all" ]]; then
-    $rvm_scripts_path/list strings | tr ' ' "\n" | __rvm_strip
+    "$rvm_scripts_path/list" strings | tr ' ' "\n" | __rvm_strip
   elif [[ "$1" = "all-gemsets" ]]; then
-    $rvm_scripts_path/list gemsets strings | __rvm_strip
+    "$rvm_scripts_path/list" gemsets strings | __rvm_strip
   elif [[ "$1" = "default-with-rvmrc" || "$1" = "rvmrc" ]]; then
-    $rvm_scripts_path/tools path-identifier "$PWD"
+    "$rvm_scripts_path/tools" path-identifier "$PWD"
   elif [[ "$1" == "all-rubies" || "$1" = "rubies" ]]; then
-    $rvm_scripts_path/list rubies strings | __rvm_strip
+    "$rvm_scripts_path/list" rubies strings | __rvm_strip
   elif [[ "$1" == "current-ruby" || "$1" = "gemsets" ]]; then
     local current_ruby="$(__rvm_environment_identifier | awk -F"$rvm_gemset_separator" '{print $1}')"
-    rvm_silence_logging=1 $rvm_scripts_path/gemsets list | sed "s/^/$current_ruby$rvm_gemset_separator/"  | __rvm_strip
+    rvm_silence_logging=1 "$rvm_scripts_path/gemsets" list | sed "s/^/$current_ruby$rvm_gemset_separator/"  | __rvm_strip
   elif [[ "$1" = "current" ]]; then
     __rvm_environment_identifier
   elif [[ "$1" = "aliases" ]]; then
