Trimming down more, s#rvm_scripts_path#rvm_path/scripts#g

diff --git a/scripts/cli b/scripts/cli
--- a/scripts/cli
+++ b/scripts/cli
@@ -4,7 +4,7 @@ __rvm_usage() { \less "${rvm_path:-$HOME/.rvm}/README" ; }
 
 __rvm_run_script() {
   local rvm_script_name="${1:-"$rvm_action"}"
-  eval "$rvm_scripts_path/$rvm_script_name $rvm_ruby_args"
+  eval "$rvm_path/scripts/$rvm_script_name $rvm_ruby_args"
   return $?
 }
 
@@ -66,7 +66,7 @@ __rvm_parse_args() {
         rvm_ruby_string="$rvm_token"
         rvm_ruby_strings="$rvm_token"
         rvm_action="${rvm_action:-use}"
-        if "$rvm_scripts_path"/match "$next_token" "^[0-9]\.[0-9]" ; then
+        if "$rvm_path/scripts"/match "$next_token" "^[0-9]\.[0-9]" ; then
           rvm_ruby_version=$next_token
           if [[ $# -gt 0 ]] ; then next_token="$1" ; shift ; else next_token="" ; fi
         fi
@@ -222,11 +222,11 @@ __rvm_parse_args() {
             rvm_parse_break=1
           fi
         else
-          if "$rvm_scripts_path"/match "$next_token" "^-" ; then
+          if "$rvm_path/scripts"/match "$next_token" "^-" ; then
             unset rvm_ruby_strings
 
           else
-            if "$rvm_scripts_path"/match "$next_token" "^[0-9]" ; then
+            if "$rvm_path/scripts"/match "$next_token" "^[0-9]" ; then
               rvm_ruby_strings="${1//,/ }"
               if [[ $# -gt 0 ]] ; then next_token="$1" ; shift ; else next_token="" ; fi
               unset rvm_ruby_interpreter
@@ -345,7 +345,7 @@ __rvm_parse_args() {
       ;;
 
       --symlink)
-        "$rvm_scripts_path/log" "warn" "--symlink has been removed, please see 'rvm wrapper'."
+        "$rvm_path/scripts/log" "warn" "--symlink has been removed, please see 'rvm wrapper'."
         if [[ $# -gt 0 ]] ; then next_token="$1" ; shift ; else next_token="" ; fi
       ;;
 
@@ -401,14 +401,15 @@ __rvm_parse_args() {
 
         rvm_debug_flag=1
 
-        for option in verbose errexit noclobber nounset ; do
+        for option in verbose noclobber nounset ; do
           set -o $option
         done
 
         if [[ -z "${ZSH_VERSION:-""}" ]] ; then
           set -o errtrace
-          set -o pipefail
         fi
+
+        # errexit pipefail
 
         if [[ "$rvm_token" = "--trace" ]] ; then
 
@@ -500,7 +501,7 @@ __rvm_parse_args() {
 
 
           if [[ "gemset" = "$rvm_action" ]] ; then
-            if "$rvm_scripts_path/match" "$rvm_token" "^.+${rvm_gemset_separator:-"@"}.+$" ; then
+            if "$rvm_path/scripts/match" "$rvm_token" "^.+${rvm_gemset_separator:-"@"}.+$" ; then
               rvm_gemset_name="${rvm_token/*${rvm_gemset_separator:-"@"}/}"
               rvm_ruby_string="${rvm_token/${rvm_gemset_separator:-"@"}*/}"
 
@@ -518,32 +519,32 @@ __rvm_parse_args() {
               rvm_action="ruby" # Not sure if we really want to do this but we'll try it out.
             fi
 
-          elif "$rvm_scripts_path/match" "$rvm_token" "^${rvm_gemset_separator:-"@"}" ; then
+          elif "$rvm_path/scripts/match" "$rvm_token" "^${rvm_gemset_separator:-"@"}" ; then
             rvm_action="${rvm_action:-use}"
             rvm_gemset_name="${rvm_token/*${rvm_gemset_separator:-"@"}/}"
             rvm_ruby_string="${rvm_ruby_string:-""}"
             rvm_ruby_strings="${rvm_ruby_string}${rvm_gemset_separator:-"@"}${rvm_gemset_name}"
 
-          elif "$rvm_scripts_path/match" "$rvm_token" "^.+${rvm_gemset_separator:-"@"}.+$" ; then
+          elif "$rvm_path/scripts/match" "$rvm_token" "^.+${rvm_gemset_separator:-"@"}.+$" ; then
             gemset_name="${rvm_token/*${rvm_gemset_separator:-"@"}/}"
             rvm_ruby_string="$rvm_token"
             rvm_ruby_strings="$rvm_token"
 
-          elif "$rvm_scripts_path/match" "$rvm_token" "^.+\\+.+$" ; then
+          elif "$rvm_path/scripts/match" "$rvm_token" "^.+\\+.+$" ; then
             rvm_ruby_alias="${rvm_token/*+/}"
             rvm_ruby_string="${rvm_token/+*/}"
             rvm_ruby_strings="$rvm_ruby_string"
 
-          elif "$rvm_scripts_path/match" "$rvm_token" "-" ; then
+          elif "$rvm_path/scripts/match" "$rvm_token" "-" ; then
             rvm_ruby_string="$rvm_token"
             rvm_ruby_strings="$rvm_token"
 
-          elif "$rvm_scripts_path/match" "$rvm_token" "^[0-9].[0-9]" ; then
+          elif "$rvm_path/scripts/match" "$rvm_token" "^[0-9].[0-9]" ; then
             rvm_ruby_string="$rvm_token"
             rvm_ruby_strings="$rvm_token"
             rvm_action="${rvm_action:-use}"
 
-          elif "$rvm_scripts_path/match" "$rvm_token" "^ree-" ; then
+          elif "$rvm_path/scripts/match" "$rvm_token" "^ree-" ; then
             rvm_ruby_string="$rvm_token"
             rvm_ruby_strings="$rvm_token"
             rvm_action="${rvm_action:-use}"
@@ -554,7 +555,7 @@ __rvm_parse_args() {
             rvm_action="${rvm_action:-use}"
 
           else
-            if "$rvm_scripts_path/match" "$rvm_token" ".rb$" ; then # we have a specified ruby script
+            if "$rvm_path/scripts/match" "$rvm_token" ".rb$" ; then # we have a specified ruby script
               rvm_ruby_args="$rvm_token"
               rvm_ruby_file="$rvm_token"
               if [[ -z "${rvm_action:-""}" ]] ; then rvm_action="ruby" ; fi
@@ -580,14 +581,14 @@ __rvm_parse_args() {
   while [[ $# -gt 0 ]] ; do shift ; done
 
   if [[ -n "${rvm_error_message:-""}" ]] ; then
-    "$rvm_scripts_path"/log "fail" "$rvm_error_message ( see: 'rvm usage' )"
+    "$rvm_path/scripts"/log "fail" "$rvm_error_message ( see: 'rvm usage' )"
     return 1
   fi
 }
 
 rvm() {
 
-  local next_token
+  local next_token result
 
   __rvm_setup
 
@@ -620,52 +621,51 @@ rvm() {
 
   rvm_action="${rvm_action:-usage}"
 
-  export BUNDLE_PATH GEM_HOME GEM_PATH rvm_ruby_string rvm_action rvm_bin_flag rvm_debug_flag rvm_delete_flag rvm_docs_type rvm_file_name rvm_gemset_name rvm_head_flag rvm_install_on_use_flag rvm_interactive_flag rvm_llvm_flag rvm_make_flags rvm_proxy rvm_remove_flag rvm_ruby_args rvm_configure_flags rvm_ruby_file rvm_ruby_gem_home rvm_ruby_interpreter rvm_ruby_name rvm_ruby_version rvm_system_flag rvm_trace_flag rvm_use_flag rvm_user_flag rvm_verbose_flag rvm_patch_names rvm_patch_original_pwd rvm_clang_flag rvm_install_arguments rvm_path rvm_rubies_path rvm_scripts_path rvm_archives_path rvm_src_path rvm_log_path rvm_bin_path rvm_gems_path rvm_config_path rvm_tmp_path rvm_hooks_path rvm_gems_cache_path rvm_gemset_separator rvm_ruby_aliases rvm_quiet_flag rvm_silent_flag
+  export BUNDLE_PATH GEM_HOME GEM_PATH rvm_ruby_string rvm_action rvm_bin_flag rvm_debug_flag rvm_delete_flag rvm_docs_type rvm_file_name rvm_gemset_name rvm_head_flag rvm_install_on_use_flag rvm_interactive_flag rvm_llvm_flag rvm_make_flags rvm_proxy rvm_remove_flag rvm_ruby_args rvm_configure_flags rvm_ruby_file rvm_ruby_gem_home rvm_ruby_interpreter rvm_ruby_name rvm_ruby_version rvm_system_flag rvm_trace_flag rvm_use_flag rvm_user_flag rvm_verbose_flag rvm_patch_names rvm_patch_original_pwd rvm_clang_flag rvm_install_arguments rvm_path rvm_rubies_path rvm_path/scripts rvm_archives_path rvm_src_path rvm_log_path rvm_bin_path rvm_gems_path rvm_config_path rvm_tmp_path rvm_hooks_path rvm_gems_cache_path rvm_gemset_separator rvm_ruby_aliases rvm_quiet_flag rvm_silent_flag
 
   result=0
 
   case "$rvm_action" in
-    use)             __rvm_use               ; result=$? ;;
-    srcdir)          __rvm_source_dir        ; result=$? ;;
-    strings)         __rvm_strings           ; result=$? ;;
-    version)         __rvm_version           ; result=$? ;;
-    reset)           __rvm_reset             ; result=$? ;;
-    update)          __rvm_update            ; result=$? ;;
-    reboot)          __rvm_reboot            ; result=$? ;;
-    usage)           __rvm_usage             ; result=$? ;;
-    benchmark)       __rvm_benchmark         ; result=$? ;;
-    inspect)         __rvm_inspect           ; result=$? ;;
-    implode|seppuku) __rvm_implode           ; result=$? ;;
+    use)             __rvm_use        ;;
+    srcdir)          __rvm_source_dir ;;
+    strings)         __rvm_strings    ;;
+    version)         __rvm_version    ;;
+    reset)           __rvm_reset      ;;
+    update)          __rvm_update     ;;
+    reboot)          __rvm_reboot     ;;
+    usage)           __rvm_usage      ;;
+    benchmark)       __rvm_benchmark  ;;
+    inspect)         __rvm_inspect    ;;
+    implode|seppuku) __rvm_implode    ;;
 
-    list)  "$rvm_scripts_path"/list $rvm_ruby_args ; result=$? ;;
+    list)  "$rvm_path/scripts"/list $rvm_ruby_args ;;
     # TODO: Make debug run in the current environment.
-    debug) "$rvm_scripts_path/info" '' debug ; result=$? ;;
-    help)  "$rvm_scripts_path/help" $rvm_ruby_args ; result=$? ;;
-    env)   "$rvm_scripts_path/env" "$rvm_ruby_string" ; result=$?  ;;
+    debug) "$rvm_path/scripts/info" '' debug ;;
+    help)  "$rvm_path/scripts/help" $rvm_ruby_args ;;
+    env)   "$rvm_path/scripts/env" "$rvm_ruby_string"  ;;
     info)
       if [[ $# -gt 0 ]] ; then next_token="$1" ; shift ; else next_token="" ; fi
       if [[ "$next_token" = "info" ]]; then shift; fi
-      "$rvm_scripts_path/info" $rvm_ruby_args
-      result=$?
+      "$rvm_path/scripts/info" $rvm_ruby_args
     ;;
 
     answer)   __rvm_Answer_to_the_Ultimate_Question_of_Life_the_Universe_and_Everything ; result=42 ;;
     question) __rvm_ultimate_question ; result=42 ;;
 
     wrapper)
-      "$rvm_scripts_path/wrapper" "$rvm_ruby_string" "$rvm_wrapper_name" $rvm_ruby_args
-      result=$? ; unset rvm_wrapper_name
+      "$rvm_path/scripts/wrapper" "$rvm_ruby_string" "$rvm_wrapper_name" $rvm_ruby_args
+      unset rvm_wrapper_name
     ;;
 
     gemdir|gemhome|gempath)
-      "$rvm_scripts_path/gemsets" "$rvm_action" ; result=$?
+      "$rvm_path/scripts/gemsets" "$rvm_action"
     ;;
 
     ruby|gem|rake|exec)
       old_rvm_ruby_string=$rvm_ruby_string
       unset rvm_ruby_string
       export rvm_ruby_strings
-      "$rvm_scripts_path/set" "$rvm_action" $rvm_ruby_args
+      "$rvm_path/scripts/set" "$rvm_action" $rvm_ruby_args
       result=$?
       # Restore the state pre-sets.
       [[ -n "$old_rvm_ruby_string" ]] && rvm_ruby_string=$old_rvm_ruby_string
@@ -673,22 +673,19 @@ rvm() {
     ;;
 
     cleanup|tools|snapshot|disk-usage|repair|alias|docs|rubygems|migrate|upgrade)
-      __rvm_run_script "$rvm_action" ; result=$?
+      __rvm_run_script "$rvm_action"
     ;;
 
-    rvmrc) eval "__rvm_rvmrc_tools $rvm_ruby_args" ; result=$? ;;
+    rvmrc) eval "__rvm_rvmrc_tools $rvm_ruby_args" ;;
 
     gemset)
-      #if "$rvm_scripts_path/match" $rvm_ruby_args use ; then
+      #if "$rvm_path/scripts/match" $rvm_ruby_args use ; then
       if [[ ${rvm_use_flag:-0} -eq 1 ]] ; then
-        __rvm_gemset_select
-        result=$? ; if [[ $result -eq 0 ]] ; then
-          __rvm_gemset_use
-        fi
+        __rvm_gemset_select && __rvm_gemset_use
       else
         export rvm_ruby_strings
 
-        "$rvm_scripts_path/gemsets" $rvm_ruby_args ; result=$?
+        "$rvm_path/scripts/gemsets" $rvm_ruby_args ; result=$?
 
         rvm_ruby_strings=""
 
@@ -702,46 +699,45 @@ rvm() {
             BUNDLE_PATH="$rvm_ruby_gem_home"
             GEM_PATH="$rvm_ruby_gem_home/bin:$rvm_ruby_gem_home${rvm_gemset_separator:-"@"}global/bin"
             export rvm_ruby_gem_home GEM_HOME BUNDLE_PATH GEM_PATH
-          fi ; unset gem_prefix
+          fi
+          unset gem_prefix
         fi
       fi
-      result=$?
     ;;
 
     monitor)
       export rvm_ruby_strings rvm_ruby_string
-      "$rvm_scripts_path"/monitor ; result=$?
+      "$rvm_path/scripts/monitor"
     ;;
 
-    notes)       "$rvm_scripts_path/notes"   ; result=$?  ;;
-    reload)      rvm_loaded_flag=0 ; rvm_reload_flag=1    ;;
-    tests|specs) rvm_action="rake" ; __rvm_do ; result=$? ;;
-    package)     "$rvm_scripts_path/package" $rvm_ruby_args ; result=$?  ;;
+    notes)       "$rvm_path/scripts/notes"                  ;;
+    reload)      rvm_loaded_flag=0 ; rvm_reload_flag=1      ;;
+    tests|specs) rvm_action="rake" ; __rvm_do               ;;
+    package)     "$rvm_path/scripts/package" $rvm_ruby_args ;;
 
     fetch|install|uninstall|remove)
       if [[ -n "$rvm_ruby_strings" ]]; then
-        "$rvm_scripts_path"/manage "$rvm_action" "$rvm_ruby_strings"
+        "$rvm_path/scripts"/manage "$rvm_action" "$rvm_ruby_strings"
       else
-        "$rvm_scripts_path"/manage "$rvm_action"
+        "$rvm_path/scripts"/manage "$rvm_action"
       fi
-      result=$?
     ;;
 
-    error)
-      result=1
-    ;;
+    error) false ;;
 
     *)
       if [[ -n "${rvm_action:-""}" ]] ; then
-        "$rvm_scripts_path/log" "fail"  "unknown action '$rvm_action'"
+        "$rvm_path/scripts/log" "fail"  "unknown action '$rvm_action'"
       else
         __rvm_usage
       fi
-      result=1
+      false # result
   esac
 
+  result=${result:-$?}
+
   if [[ ${rvm_reload_flag:-0} -eq 1 ]] ; then
-    source "$rvm_scripts_path/rvm"
+    source "$rvm_path/scripts/rvm"
     # Note: Not using builtin on purpose. Done so we can trigger a reload the rvmrc.
     __rvm_project_rvmrc
   fi
diff --git a/scripts/docs b/scripts/docs
--- a/scripts/docs
+++ b/scripts/docs
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 rvm_base_except="selector"
-source "$rvm_scripts_path/base"
+source "$rvm_path/scripts/base"
 
 rvm_docs_ruby_string="$(__rvm_environment_identifier | awk -F"${rvm_gemset_separator:-"@"}" '{print $1}')"
 if [[ "$rvm_docs_ruby_string" = "system" || -z "$rvm_docs_ruby_string" ]]; then
-  "$rvm_scripts_path"/log "error" "Currently 'rvm docs ...' does not work with non-rvm rubies."
+  "$rvm_path/scripts/log" "error" "Currently 'rvm docs ...' does not work with non-rvm rubies."
   exit 1
 fi
 
@@ -16,8 +16,14 @@ if [[ ! -d "$rvm_docs_path" ]] ; then
 fi
 
 usage() {
-  printf "Usage: 'rvm docs {open,generate,generate-ri,generate-rdoc}'\n"
-  exit 1
+  printf "
+
+  Usage:
+
+    rvm docs {open,generate,generate-ri,generate-rdoc}
+
+"
+  return 0
 }
 
 open_docs() {
@@ -27,10 +33,10 @@ open_docs() {
     elif command -v xdg-open >/dev/null ; then
       xdg-open "$rvm_docs_path/$rvm_docs_ruby_string/$rvm_docs_type/index.html"
     else
-      "$rvm_scripts_path"/log "error" "Neither open nor xdg-open were found, in order to open the docs one of these two are required. \n(OR you can let me know how else to open the html in your browser from comand line on your OS :) )"
+      "$rvm_path/scripts"/log "error" "Neither open nor xdg-open were found, in order to open the docs one of these two are required. \n(OR you can let me know how else to open the html in your browser from comand line on your OS :) )"
     fi
   else
-    "$rvm_scripts_path"/log "error" "$rvm_docs_type docs are missing, perhaps run 'rvm docs generate' first?"
+    "$rvm_path/scripts"/log "error" "$rvm_docs_type docs are missing, perhaps run 'rvm docs generate' first?"
   fi
 }
 
@@ -38,8 +44,8 @@ generate_ri() {
   # Generate ri docs
   (
     builtin cd "$rvm_src_path/$rvm_docs_ruby_string/"
-    "$rvm_scripts_path"/log "info" "Generating ri documentation, be aware that this could take a *long* time, and depends heavily on your system resources..."
-    "$rvm_scripts_path"/log "info" "( Errors will be logged to $rvm_log_path/$rvm_docs_ruby_string/docs.error.log )"
+    "$rvm_path/scripts/log" "info" "Generating ri documentation, be aware that this could take a *long* time, and depends heavily on your system resources..."
+    "$rvm_path/scripts/log" "info" "( Errors will be logged to $rvm_log_path/$rvm_docs_ruby_string/docs.error.log )"
     rdoc -a --ri --ri-site > /dev/null 2>> $rvm_log_path/$rvm_docs_ruby_string/docs.error.log
   )
 }
@@ -48,8 +54,8 @@ generate_rdoc() {
   (
     builtin cd "$rvm_src_path/$rvm_docs_ruby_string/"
     \rm -rf "$rvm_docs_path/$rvm_docs_ruby_string/$rvm_docs_type/"
-    "$rvm_scripts_path"/log "info" "Generating rdoc documentation, be aware that this could take a *long* time, and depends heavily on your system resources..."
-    "$rvm_scripts_path"/log "info" "( Errors will be logged to $rvm_log_path/$rvm_docs_ruby_string/docs.error.log )"
+    "$rvm_path/scripts/log" "info" "Generating rdoc documentation, be aware that this could take a *long* time, and depends heavily on your system resources..."
+    "$rvm_path/scripts/log" "info" "( Errors will be logged to $rvm_log_path/$rvm_docs_ruby_string/docs.error.log )"
     if gem list | \grep -q ^hanna ; then
       hanna -o "$rvm_docs_path/$rvm_docs_ruby_string/$rvm_docs_type" --inline-source --line-numbers --fmt=html > /dev/null 2>> "$rvm_log_path/$rvm_docs_ruby_string/docs.error.log"
     else
@@ -60,14 +66,18 @@ generate_rdoc() {
 
 args=($*)
 action="${args[0]}"
-args="$(echo ${args[@]:1}) " # Strip trailing / leading / extra spacing.
+args=($(echo ${args[@]:1})) # Strip trailing / leading / extra spacing.
 
 case "$action" in
-  open)          open_docs ;;
-  generate)      generate_ri; generate_rdoc ;;
-  generate-ri)   generate_ri ;;
-  generate-rdoc) generate_rdoc ;;
-  *)             usage ;;
+  generate)
+    generate_ri
+    generate_rdoc
+    ;;
+  open)          open_docs      ;;
+  generate-ri)   generate_ri    ;;
+  generate-rdoc) generate_rdoc  ;;
+  help)          usage          ;;
+  *)             usage ; exit 1 ;;
 esac
 
-exit $result
+exit $?
diff --git a/scripts/fetch b/scripts/fetch
--- a/scripts/fetch
+++ b/scripts/fetch
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 rvm_base_except="selector"
-source "$rvm_scripts_path/base"
+source "$rvm_path/scripts/base"
 result=0
 
 # Set it to cleanup the download on interruption.
@@ -17,19 +17,19 @@ record_md5() {
   else
     archive_md5="$(md5sum "${archive}" | awk '{print $1}')"
   fi
-  "$rvm_scripts_path/db" "$rvm_config_path/md5" "$archive" "$archive_md5"
+  "$rvm_path/scripts/db" "$rvm_config_path/md5" "$archive" "$archive_md5"
 }
 
 builtin cd "$rvm_archives_path"
 
 # args=($*) # Reserved for future use
 
-if [[ -z "$1" ]] ; then "$rvm_scripts_path/log" "fail" "BUG: $0 called without an argument :/" ; exit 1 ; fi
+if [[ -z "$1" ]] ; then "$rvm_path/scripts/log" "fail" "BUG: $0 called without an argument :/" ; exit 1 ; fi
 
 url="$1"; download=1 ; package_name="$2"
 
 if ! command -v curl > /dev/null ; then
-  "$rvm_scripts_path/log" "fail" "rvm requires curl. curl was not found in your active path."
+  "$rvm_path/scripts/log" "fail" "rvm requires curl. curl was not found in your active path."
   exit 1
 elif [[ ! -z ${rvm_proxy} ]] ; then
   fetch_command="curl -x${rvm_proxy} -L --create-dirs -C - " # -s for silent
@@ -45,22 +45,22 @@ else
   archive=$(basename "$url")
 fi
 
-if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_scripts_path/log" "debug" "Fetching $archive" ; fi
+if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_path/scripts/log" "debug" "Fetching $archive" ; fi
 
 # Check first if we have the correct archive
-archive_md5="$($rvm_scripts_path/db "$rvm_config_path/md5" "$archive" | head -n1)"
+archive_md5="$($rvm_path/scripts/db "$rvm_config_path/md5" "$archive" | head -n1)"
 if [[ -e "$archive" ]] && [[ ! -z "$archive_md5" ]] ; then
-  if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_scripts_path/log" "debug" "Found archive and its md5, testing correctness" ; fi
-  if ! "$rvm_scripts_path"/md5 "${rvm_archives_path}/${archive}" "$archive_md5" ; then
-    if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_scripts_path/log" "debug" "Archive is bad, downloading" ; fi
+  if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_path/scripts/log" "debug" "Found archive and its md5, testing correctness" ; fi
+  if ! "$rvm_path/scripts"/md5 "${rvm_archives_path}/${archive}" "$archive_md5" ; then
+    if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_path/scripts/log" "debug" "Archive is bad, downloading" ; fi
     download=1
   else
-    if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_scripts_path/log" "debug" "Archive is good, not downloading" ; fi
+    if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_path/scripts/log" "debug" "Archive is good, not downloading" ; fi
     download=0
     result=0
   fi ; unset archive_md5
 else
-  if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_scripts_path/log" "debug" "No archive or no MD5, downloading" ; fi
+  if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_path/scripts/log" "debug" "No archive or no MD5, downloading" ; fi
   download=1
 fi
 
@@ -75,18 +75,18 @@ if [[ $download -gt 0 ]] ; then
     retry=0
     try_http=0
     if [[ $result -eq 78 ]] ; then
-      "$rvm_scripts_path/log" "error" "The requested url does not exist: '$url'"
+      "$rvm_path/scripts/log" "error" "The requested url does not exist: '$url'"
       try_http=1
     elif [[ $result -eq 18 ]] ; then
-      "$rvm_scripts_path/log" "error" "Partial file. Only a part of the file was transferred. Removing partial and re-trying."
+      "$rvm_path/scripts/log" "error" "Partial file. Only a part of the file was transferred. Removing partial and re-trying."
       rm -f "$archive"
       retry=1
     elif [[ $result -eq 33 ]] ; then
-      if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_scripts_path/log" "debug" "Server does not support 'range' command, removing '$archive'" ; fi
+      if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_path/scripts/log" "debug" "Server does not support 'range' command, removing '$archive'" ; fi
       rm -f "$archive"
       retry=1
     else
-      "$rvm_scripts_path/log" "error" "There was an error, please check $rvm_ruby_log_path/*.error.log. Next we'll try to fetch via http."
+      "$rvm_path/scripts/log" "error" "There was an error, please check $rvm_ruby_log_path/*.error.log. Next we'll try to fetch via http."
       try_http=1
     fi
 
@@ -94,7 +94,7 @@ if [[ $download -gt 0 ]] ; then
       eval $fetch_command "$url"
       result=$?
       if [[ $result -gt 0 ]] ; then
-        "$rvm_scripts_path/log" "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
+        "$rvm_path/scripts/log" "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
       else
         record_md5
       fi
@@ -104,7 +104,7 @@ if [[ $download -gt 0 ]] ; then
       eval $fetch_command "$http_url"
       result=$?
       if [[ $result -gt 0 ]] ; then
-        "$rvm_scripts_path/log" "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
+        "$rvm_path/scripts/log" "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
       else
         record_md5
       fi
diff --git a/scripts/package b/scripts/package
--- a/scripts/package
+++ b/scripts/package
@@ -3,7 +3,7 @@
 if [[ "$rvm_trace_flag" -eq 2 ]] ; then set -x ; export rvm_trace_flag ; fi
 
 rvm_base_except="selector"
-source "$rvm_scripts_path/base"
+source "$rvm_path/scripts/base"
 
 # Tools to make managing ruby dependencies inside of rvm easier.
 args=($*)
@@ -20,18 +20,18 @@ install_package() {
   (
     builtin cd "$rvm_src_path"
 
-    "$rvm_scripts_path/log" "info" "Fetching $package-$version.$archive_format to $rvm_archives_path"
+    "$rvm_path/scripts/log" "info" "Fetching $package-$version.$archive_format to $rvm_archives_path"
 
     if [[ "$archive_format" = "tar.gz" ]] || [[ "$archive_format" = "tgz" ]] ; then
-      "$rvm_scripts_path/fetch" "$package_url/$package-$version.$archive_format" || (result=$? && return $result)
+      "$rvm_path/scripts/fetch" "$package_url/$package-$version.$archive_format" || (result=$? && return $result)
       __rvm_run "$package/extract" "tar zxf $rvm_archives_path/$package-$version.$archive_format -C $rvm_src_path" "Extracting $package-$version.$archive_format to $rvm_src_path"
 
     elif [[ "$archive_format" = "tar.bz2" ]] ; then
-      "$rvm_scripts_path/fetch" "$package_url/$package-$version.$archive_format" || (result=$? && return $result)
+      "$rvm_path/scripts/fetch" "$package_url/$package-$version.$archive_format" || (result=$? && return $result)
       __rvm_run "$package/extract" "tar jxf $rvm_archives_path/$package-$version.$archive_format -C $rvm_src_path" "Extracting $package-$version.$archive_format to $rvm_src_path"
 
     elif [[ "$archive_format" = "zip" ]] ; then
-      "$rvm_scripts_path/fetch" "$package_url/$package-$version.$archive_format" || (result=$? && return $result)
+      "$rvm_path/scripts/fetch" "$package_url/$package-$version.$archive_format" || (result=$? && return $result)
       __rvm_run "$package/extract" "unzip -q -o $rvm_archives_path/$package-$version.$archive_format -d $rvm_src_path/$package-$version" "Extracting $package-$version.$archive_format to $rvm_src_path"
 
     else
@@ -53,7 +53,7 @@ install_package() {
     fi
 
     \touch "$rvm_config_path/packages"
-    "$rvm_scripts_path/db" "$rvm_config_path/packages" "${package}" "${version}"
+    "$rvm_path/scripts/db" "$rvm_config_path/packages" "${package}" "${version}"
   )
 }
 
@@ -81,11 +81,11 @@ openssl() {
 
     if [[ ! -z "$rvm_archflags" ]]; then
 
-      if "$rvm_scripts_path/match" "$rvm_archflags" "64"; then
+      if "$rvm_path/scripts/match" "$rvm_archflags" "64"; then
         hw_cpu64bit=1
       fi
 
-      if "$rvm_scripts_path/match" "$rvm_archflags" "ppc"; then
+      if "$rvm_path/scripts/match" "$rvm_archflags" "ppc"; then
         hw_machine="Power Macintosh"
       fi
     else
@@ -194,16 +194,20 @@ llvm() {
 }
 
 if [[ -n "$library" ]] ; then
+
   case $library in
     readline|iconv|curl|openssl|zlib|autoconf|ncurses|pkgconfig|gettext|glib|mono|llvm|libxml2)
       ${library}
     ;;
     *)
-      "$rvm_scripts_path/log" "error" "Package '${library}' is unknown."
+      "$rvm_path/scripts/log" "error" "Package '${library}' is unknown."
     ;;
   esac
+
+  exit $?
+
 else
-  "$rvm_scripts_path/log" "info" "Usage: 'rvm package {install,uninstall} {readline,iconv,curl,openssl,zlib,autoconf,ncurses,pkgconfig,gettext,glib,mono,llvm,libxml2}'"
+  "$rvm_path/scripts/log" "info" \
+    "Usage: 'rvm package {install,uninstall} {readline,iconv,curl,openssl,zlib,autoconf,ncurses,pkgconfig,gettext,glib,mono,llvm,libxml2}'"
   exit 1
 fi
-
diff --git a/scripts/selector b/scripts/selector
--- a/scripts/selector
+++ b/scripts/selector
@@ -44,7 +44,7 @@ __rvm_select() {
         fi
         rvm_ruby_patch_level=""
       else
-        "$rvm_scripts_path/log" "fail" "MacRuby can only be installed on a Darwin OS."
+        "$rvm_path/scripts/log" "fail" "MacRuby can only be installed on a Darwin OS."
       fi
     ;;
 
@@ -151,8 +151,8 @@ __rvm_select() {
         fi
       fi
 
-      if ! "$rvm_scripts_path/match" "$rvm_ruby_version" "^1\.8" ; then
-        "$rvm_scripts_path/log" "fail" "Unknown Ruby Enterprise Edition version: $rvm_ruby_version"
+      if ! "$rvm_path/scripts/match" "$rvm_ruby_version" "^1\.8" ; then
+        "$rvm_path/scripts/log" "fail" "Unknown Ruby Enterprise Edition version: $rvm_ruby_version"
       fi
     ;;
 
@@ -168,7 +168,7 @@ __rvm_select() {
 
     ruby)
       if [[ -z "${rvm_ruby_version:-""}" && ${rvm_head_flag:-0} -eq 0 ]]; then
-        "$rvm_scripts_path/log" "fail" "Unknown ruby version: $rvm_ruby_version"
+        "$rvm_path/scripts/log" "fail" "Unknown ruby version: $rvm_ruby_version"
 
       else
         rvm_ruby_repo_url="${rvm_ruby_repo_url:-"$(__rvm_db "ruby_repo_url")"}"
@@ -182,7 +182,7 @@ __rvm_select() {
     current)
       ruby_binary="$(command -v ruby)"
 
-      if [[ $? -eq 0 ]] && "$rvm_scripts_path/match" "$ruby_binary" "rvm" ; then
+      if [[ $? -eq 0 ]] && "$rvm_path/scripts/match" "$ruby_binary" "rvm" ; then
         rvm_ruby_string="$(dirname "$ruby_binary" | xargs dirname | xargs basename)"
 
       else
@@ -201,7 +201,7 @@ __rvm_select() {
 
       else
         if [[ -z "${rvm_ruby_string:-""}" ]] ; then
-          "$rvm_scripts_path/log" "fail" "Ruby implementation '$rvm_ruby_interpreter' is not known."
+          "$rvm_path/scripts/log" "fail" "Ruby implementation '$rvm_ruby_interpreter' is not known."
           return 1
         fi
       fi
@@ -288,7 +288,7 @@ __rvm_use() {
     fi
 
     if [[ ${rvm_verbose_flag:-0} -gt 0 ]] ; then
-      "$rvm_scripts_path/log" "info" "Now using system ruby."
+      "$rvm_path/scripts/log" "info" "Now using system ruby."
     fi
 
     export rvm_ruby_string="system"
@@ -306,13 +306,13 @@ __rvm_use() {
     IRBRC=${IRBRC:-""} ; if [[ -z "$IRBRC" ]] ; then unset IRBRC ; fi
 
     if [[ ! -d "$MY_RUBY_HOME" ]] ; then
-      "$rvm_scripts_path/log" "warn" \
+      "$rvm_path/scripts/log" "warn" \
         "$rvm_ruby_interpreter $rvm_ruby_string is not installed."
 
       if [[ ${rvm_install_on_use_flag:-0} -eq 1 ]] ; then
-        "$rvm_scripts_path/manage" "install" "$rvm_ruby_string"
+        "$rvm_path/scripts/manage" "install" "$rvm_ruby_string"
       else
-        "$rvm_scripts_path/log" "info" \
+        "$rvm_path/scripts/log" "info" \
           "To install do: 'rvm install $rvm_ruby_string'"
         return 1
       fi
@@ -322,7 +322,7 @@ __rvm_use() {
     __rvm_ensure_has_environment_files
 
     [[ ${rvm_verbose_flag:-0} -gt 0 ]] && \
-      "$rvm_scripts_path/log" "info" \
+      "$rvm_path/scripts/log" "info" \
       "Using ${GEM_HOME/${rvm_gemset_separator:-'@'}/ with gemset }"
 
     new_path="$GEM_HOME/bin:$rvm_ruby_global_gems_path/bin:$MY_RUBY_HOME/bin:$rvm_bin_path:$(__rvm_remove_rvm_from_path ; printf "$PATH")"
@@ -347,13 +347,13 @@ __rvm_use() {
 
     if [[ "${rvm_selfcontained:-""}" = "0" ]] ; then
       # Sets up the default wrappers.
-      "$rvm_scripts_path/wrapper" "$rvm_ruby_string" --no-prefix
+      "$rvm_path/scripts/wrapper" "$rvm_ruby_string" --no-prefix
     else
-      "$rvm_scripts_path/wrapper" "$rvm_scripts_path" "default"
+      "$rvm_path/scripts/wrapper" "$rvm_path/scripts" "default"
     fi
 
     if [[ "system" = "$rvm_ruby_interpreter" ]] ; then
-      "$rvm_scripts_path/alias" delete default &> /dev/null
+      "$rvm_path/scripts/alias" delete default &> /dev/null
       \find "$rvm_bin_path" -name 'default_*' -maxdepth 0 -delete
       \rm -f "$rvm_config_path/default"
       \rm -f "$rvm_environments_path/default"
@@ -362,8 +362,8 @@ __rvm_use() {
     else
       RUBY_VERSION="$("$rvm_ruby_home/bin/ruby" -v | sed 's#^\(.*\) (.*$#\1#')"
       export GEM_HOME GEM_PATH BUNDLE_PATH MY_RUBY_HOME RUBY_VERSION
-      "$rvm_scripts_path/alias" delete default &> /dev/null
-      "$rvm_scripts_path/alias" create default "$environment_id" >& /dev/null
+      "$rvm_path/scripts/alias" delete default &> /dev/null
+      "$rvm_path/scripts/alias" create default "$environment_id" >& /dev/null
       \ln -nfs "$rvm_environments_path/$environment_id" "$rvm_environments_path/default"
       \ln -nfs "$rvm_wrappers_path/$environment_id" "$rvm_wrappers_path/default"
     fi
@@ -372,14 +372,14 @@ __rvm_use() {
   rvm_default_flag=0
 
   if [[ -n "${rvm_wrapper_name:-""}" ]] ; then
-    "$rvm_scripts_path/wrapper" "$environment_id" "$rvm_wrapper_name" > /dev/null 2>&1
+    "$rvm_path/scripts/wrapper" "$environment_id" "$rvm_wrapper_name" > /dev/null 2>&1
     rvm_wrapper_name=""
   fi
 
   if [[ -n "${rvm_ruby_alias:-""}" ]]; then
-    "$rvm_scripts_path/log" "info" "Attempting to alias $environment_id to $rvm_ruby_alias"
-    "$rvm_scripts_path/alias" delete "$rvm_ruby_alias" > /dev/null 2>&1
-    rvm_alias_expanded=1 "$rvm_scripts_path/alias" create "$rvm_ruby_alias" "$environment_id" > /dev/null 2>&1
+    "$rvm_path/scripts/log" "info" "Attempting to alias $environment_id to $rvm_ruby_alias"
+    "$rvm_path/scripts/alias" delete "$rvm_ruby_alias" > /dev/null 2>&1
+    rvm_alias_expanded=1 "$rvm_path/scripts/alias" create "$rvm_ruby_alias" "$environment_id" > /dev/null 2>&1
     ruby_alias="" ; rvm_ruby_alias=""
   fi
 
@@ -392,7 +392,7 @@ __rvm_use() {
     fi
   fi
 
-  rvm_hook="after_use" ; source "$rvm_scripts_path/hook"
+  rvm_hook="after_use" ; source "$rvm_path/scripts/hook"
 
   return 0
 }
@@ -424,7 +424,7 @@ __rvm_ruby_string() {
 
   # Alias'd rubies
   if [[ ${rvm_expanding_aliases:-0} -eq 0 && -n ${rvm_ruby_string:-""} ]]; then
-    if expanded_alias_name="$("$rvm_scripts_path/alias" show "$rvm_ruby_string" 2>/dev/null)" && [[ -n "$expanded_alias_name" ]] ; then
+    if expanded_alias_name="$("$rvm_path/scripts/alias" show "$rvm_ruby_string" 2>/dev/null)" && [[ -n "$expanded_alias_name" ]] ; then
       rvm_ruby_string="$expanded_alias_name"
 
     elif [[ "$rvm_ruby_string" = default ]]; then
@@ -481,7 +481,7 @@ __rvm_ruby_string() {
         rvm_ruby_patch_level="$string"
         ;;
 
-        #elif [[ -n "${rvm_ruby_version:-""}" ]] && "$rvm_scripts_path/match" "$string" "^
+        #elif [[ -n "${rvm_ruby_version:-""}" ]] && "$rvm_path/scripts/match" "$string" "^
         [[:digit:]][[:digit:]]*)
 
         case "${rvm_ruby_interpreter:-""}" in
@@ -543,7 +543,7 @@ __rvm_ruby_string() {
       ;;
 
     *)
-      "$rvm_scripts_path/log" "error" \
+      "$rvm_path/scripts/log" "error" \
         "Unknown ruby string component: '$string'"
       return 1
       ;;
@@ -679,7 +679,7 @@ __rvm_gemset_select() {
         rvm_ruby_gem_home="$rvm_gems_path/${rvm_ruby_string}${rvm_gemset_separator:-"@"}${rvm_gemset_name}"
       fi
     else
-      "$rvm_scripts_path/log" "error" "Gemsets can not be used with non rvm controlled rubies (currently)."
+      "$rvm_path/scripts/log" "error" "Gemsets can not be used with non rvm controlled rubies (currently)."
       return 1
     fi
   fi
@@ -691,7 +691,7 @@ __rvm_gemset_select() {
 
     if [[ ${rvm_gemset_create_on_use_flag:-0} -ne 1 && ${rvm_create_flag:-0} -ne 1 && ${rvm_delete_flag:-0} -ne 1 ]] ; then
 
-      "$rvm_scripts_path/log" "error" "Gemset '$rvm_gemset_name' does not exist, rvm gemset create '$rvm_gemset_name' first."
+      "$rvm_path/scripts/log" "error" "Gemset '$rvm_gemset_name' does not exist, rvm gemset create '$rvm_gemset_name' first."
 
       return 1
     fi
@@ -723,7 +723,7 @@ __rvm_gemset_select() {
 # Use a gemset specified by 'rvm_ruby_gem_home'
 __rvm_gemset_use() {
   if [[ -z "${rvm_gemset_name:-""}" ]] ; then
-    "$rvm_scripts_path/log" "error" "Gemset was not given.\n  Usage:\n    rvm gemset use <gemsetname>\n"
+    "$rvm_path/scripts/log" "error" "Gemset was not given.\n  Usage:\n    rvm gemset use <gemsetname>\n"
     return 1
   fi
 
@@ -732,15 +732,15 @@ __rvm_gemset_use() {
     if [[ ! -d "$rvm_ruby_gem_home" ]] ; then
 
       if [[ ${rvm_gemset_create_on_use_flag:-0} -eq 1 || ${rvm_create_flag:-0} -eq 1 ]] ; then
-        "$rvm_scripts_path/gemsets" create "$rvm_gemset_name"
+        "$rvm_path/scripts/gemsets" create "$rvm_gemset_name"
       else
-        "$rvm_scripts_path/log" "error" "Gemset '$rvm_gemset_name' does not exist, rvm gemset create '$rvm_gemset_name' first."
+        "$rvm_path/scripts/log" "error" "Gemset '$rvm_gemset_name' does not exist, rvm gemset create '$rvm_gemset_name' first."
         return 1
       fi
     fi
 
     if [[ ${rvm_interactive_flag:-0} -gt 0 && ${rvm_verbose_flag:-1} -ne 0 ]] ; then
-      "$rvm_scripts_path/log" "info" "Now using gemset '${rvm_gemset_name:-default}'"
+      "$rvm_path/scripts/log" "info" "Now using gemset '${rvm_gemset_name:-default}'"
     fi
 
     rvm_ruby_gem_home="${GEM_HOME//${rvm_gemset_separator:-"@"}*}${rvm_gemset_separator:-"@"}${rvm_gemset_name}"
diff --git a/scripts/set b/scripts/set
--- a/scripts/set
+++ b/scripts/set
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-source "$rvm_scripts_path/base"
+source "$rvm_path/scripts/base"
 
 __rvm_attempt_single_exec() {
   # Return if we have multiple rubies. or we're not running exec.
@@ -37,7 +37,7 @@ __rvm_ruby_do() {
       binary="$(basename $(command -v $binary) 2>/dev/null)"
 
     else
-      "$rvm_scripts_path/log" "warn" "'$binary not found for $rvm_ruby_string' either does not exist or is not executable? :("
+      "$rvm_path/scripts/log" "warn" "'$binary not found for $rvm_ruby_string' either does not exist or is not executable? :("
       __rvm_unset_ruby_variables
       return 1
     fi
@@ -51,11 +51,11 @@ __rvm_ruby_do() {
     # TODO: the else case below should be run if $args =~ /\.rb$/
     if [[ "ruby" = "$(basename $binary)" && "$rvm_benchmark_flag" -ne 1 ]] ; then
 
-      if "$rvm_scripts_path/match" "$args" "\.rb$" ; then
+      if "$rvm_path/scripts/match" "$args" "\.rb$" ; then
 
         if [[ -z "$prefix" ]] ; then prefix="-S" ; fi
 
-        if ! "$rvm_scripts_path/match" "$args" "$prefix" ; then
+        if ! "$rvm_path/scripts/match" "$args" "$prefix" ; then
           args="$prefix $args"
         fi
       fi
@@ -76,7 +76,7 @@ __rvm_ruby_do() {
       if [[ "$current_env" != "$current_set_ruby" ]]; then
         current_env="$current_set_ruby ($current_env)"
       fi
-      "$rvm_scripts_path/log" "info" "$current_env: $(ruby -v $rvm_ruby_mode | \tr "\n" ' ')\n"
+      "$rvm_path/scripts/log" "info" "$current_env: $(ruby -v $rvm_ruby_mode | \tr "\n" ' ')\n"
       unset current_env
     fi
     eval "$rvm_command"
@@ -126,7 +126,7 @@ __rvm_yaml() {
   if [[ -n "${ZSH_VERSION:-""}" ]] ; then array_start=1 ; else array_start=0 ; fi
   for (( index = $array_start ; index < $total + $array_start ; index++ )) ; do
     if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then
-      "$rvm_scripts_path/log" "debug" "${rubies[$index]}: ${statuses[$index]}"
+      "$rvm_path/scripts/log" "debug" "${rubies[$index]}: ${statuses[$index]}"
     fi
     yaml="$yaml\n  \"${rubies[$index]}\": ${statuses[$index]}"
   done ; unset index array_start
@@ -149,7 +149,7 @@ __rvm_json() {
 
   for (( index = $array_start ; index < $total + $array_start ; index++ )) ; do
     if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then
-      "$rvm_scripts_path/log" "debug" "${rubies[$index]}: ${statuses[$index]}"
+      "$rvm_path/scripts/log" "debug" "${rubies[$index]}: ${statuses[$index]}"
     fi
     json="$json\n    {\"${rubies[$index]}\": ${statuses[$index]}}"
     if (( $index + 1 < $total + $array_start )) ; then json="$json,  " ; fi
@@ -172,13 +172,13 @@ action="${args[0]}"
 args=${args[@]:1}
 
 if [[ -z "$action" ]] ; then
-  "$rvm_scripts_path/log" "error" "Action must be specified."
+  "$rvm_path/scripts/log" "error" "Action must be specified."
   exit 1
 fi
 
 if [[ "$action" == "ruby" ]] && echo "$args" | \grep -q  "^'--[^[:space:]]*'$" ; then
-  "$rvm_scripts_path/log" "warn" "You called rvm ruby with the arguments $args which look like use options."
-  "$rvm_scripts_path/log" "warn" "Please note that 'rvm ruby' invokes set operations instead."
+  "$rvm_path/scripts/log" "warn" "You called rvm ruby with the arguments $args which look like use options."
+  "$rvm_path/scripts/log" "warn" "Please note that 'rvm ruby' invokes set operations instead."
 fi
 
 rvm_ruby_strings=$(__rvm_expand_ruby_string "$rvm_ruby_strings")
@@ -195,6 +195,6 @@ if [[ ! -z "$rvm_summary_flag" ]] ; then __rvm_summary ; fi
 if [[ ! -z "$rvm_yaml_flag" ]]    ; then __rvm_yaml    ; fi
 if [[ ! -z "$rvm_json_flag" ]]    ; then __rvm_json    ; fi
 
-rvm_hook="after_do" ; source "$rvm_scripts_path/hook"
+rvm_hook="after_do" ; source "$rvm_path/scripts/hook"
 
 exit ${#errors[*]}
diff --git a/scripts/snapshot b/scripts/snapshot
--- a/scripts/snapshot
+++ b/scripts/snapshot
@@ -3,11 +3,11 @@
 unset GREP_COLOR
 unset GREP_OPTIONS
 
-source "$rvm_scripts_path/base"
+source "$rvm_path/scripts/base"
 
 __error_on_result() {
   if [[ "$1" -gt 0 ]]; then
-    "$rvm_scripts_path/log" "fail" "$2 - Aborting now."
+    "$rvm_path/scripts/log" "fail" "$2 - Aborting now."
     return 0
   else
     return 1
@@ -27,25 +27,25 @@ snapshot_save() {
   \rm -rf "$snapshot_temp_path"
   \mkdir -p "$snapshot_temp_path"
 
-  "$rvm_scripts_path/log" "info" "Backing up a list of aliases"
+  "$rvm_path/scripts/log" "info" "Backing up a list of aliases"
   \cp "$rvm_config_path/alias" "$snapshot_temp_path/"
 
-  "$rvm_scripts_path/log" "info" "Backing up your user preferences"
+  "$rvm_path/scripts/log" "info" "Backing up your user preferences"
   \cp "$rvm_config_path/user" "$snapshot_temp_path/"
 
-  "$rvm_scripts_path/log" "info" "Backing up your installed packages"
+  "$rvm_path/scripts/log" "info" "Backing up your installed packages"
   sed -e 's/-//' -e 's/^lib//' < "$rvm_config_path/packages" | awk -F= '{print $1}' | sort | uniq > "$snapshot_temp_path/packages"
 
-  "$rvm_scripts_path/log" "info" "Backing up all of your gemsets"
+  "$rvm_path/scripts/log" "info" "Backing up all of your gemsets"
   \mkdir -p "$snapshot_temp_path/gems"
 
   (
     builtin cd "$snapshot_temp_path/gems"
-    for snapshot_gemset in $("$rvm_scripts_path/list" gemsets strings) ; do
+    for snapshot_gemset in $("$rvm_path/scripts/list" gemsets strings) ; do
       __rvm_become "$snapshot_gemset"
       result="$?"
       __error_on_result "$result" "Error becoming ruby $snapshot_gemset" && return "$result"
-      "$rvm_scripts_path/gemsets" export "${snapshot_gemset}.gems" >/dev/null
+      "$rvm_path/scripts/gemsets" export "${snapshot_gemset}.gems" >/dev/null
       result="$?"
       __error_on_result "$result" "Error exporting gemset contents for $snapshot_gemset" && return "$result"
       \mkdir -p "./$snapshot_gemset/"
@@ -53,15 +53,15 @@ snapshot_save() {
     done; unset snapshot_gemset
   )
 
-  "$rvm_scripts_path/log" "info" "Backing up all of your installed rubies"
+  "$rvm_path/scripts/log" "info" "Backing up all of your installed rubies"
   echo '#!/usr/bin/env bash -e' > "$snapshot_temp_path/install-rubies.sh"
-  echo "source \"\$rvm_scripts_path/rvm\" || true" >> "$snapshot_temp_path/install-rubies.sh"
+  echo "source \"\$rvm_path/scripts/rvm\" || true" >> "$snapshot_temp_path/install-rubies.sh"
   local snapshot_ruby_name_file="$rvm_tmp_path/$$-rubies"
   local snapshot_alias_name_file="$rvm_tmp_path/$$-aliases"
   local snapshot_installable_file="$rvm_tmp_path/$$-installable"
 
-  "$rvm_scripts_path/alias" list | awk -F ' => ' '{print $1}' | sort | uniq 2>/dev/null > "$snapshot_alias_name_file"
-  "$rvm_scripts_path/list" strings | \tr ' ' '\n' | sort | uniq > "$snapshot_ruby_name_file"
+  "$rvm_path/scripts/alias" list | awk -F ' => ' '{print $1}' | sort | uniq 2>/dev/null > "$snapshot_alias_name_file"
+  "$rvm_path/scripts/list" strings | \tr ' ' '\n' | sort | uniq > "$snapshot_ruby_name_file"
   comm -2 -3 "$snapshot_ruby_name_file" "$snapshot_alias_name_file" > "$snapshot_installable_file"
   \rm -rf "$snapshot_ruby_name_file" "$snapshot_alias_name_file"
 
@@ -80,7 +80,7 @@ snapshot_save() {
 
   \rm -rf "$snapshot_installable_file"
 
-  "$rvm_scripts_path/log" "info" "Compressing snapshotting"
+  "$rvm_path/scripts/log" "info" "Compressing snapshotting"
   local destination_path="$PWD"
   (
     builtin cd "$snapshot_temp_path"
@@ -90,10 +90,10 @@ snapshot_save() {
     __error_on_result "$result" "Error creating archive $destination_path/$1.tar.gz" && return "$result"
   )
 
-  "$rvm_scripts_path/log" "info" "Cleaning up"
+  "$rvm_path/scripts/log" "info" "Cleaning up"
   \rm -rf "$snapshot_temp_path"
 
-  "$rvm_scripts_path/log" "info" "Snapshot complete"
+  "$rvm_path/scripts/log" "info" "Snapshot complete"
 }
 
 snapshot_load() {
@@ -115,7 +115,7 @@ snapshot_load() {
   \rm -rf "$snapshot_temp_path"
   \mkdir -p "$snapshot_temp_path"
 
-  "$rvm_scripts_path/log" "info" "Extracting snapshot"
+  "$rvm_path/scripts/log" "info" "Extracting snapshot"
   (
     builtin cd "$snapshot_temp_path"
     tar xzf "$snapshot_archive"
@@ -123,24 +123,24 @@ snapshot_load() {
     __error_on_result "$result" "Error extracting the archive '$snapshot_archive'" && return "$result"
   )
 
-  "$rvm_scripts_path/log" "info" "Restoring user settings"
+  "$rvm_path/scripts/log" "info" "Restoring user settings"
   \cp -f "$snapshot_temp_path/user" "$rvm_config_path/user"
 
-  "$rvm_scripts_path/log" "info" "Installing rvm-managed packages"
+  "$rvm_path/scripts/log" "info" "Installing rvm-managed packages"
   for snapshot_package in $(cat "$snapshot_temp_path/packages"); do
-    "$rvm_scripts_path/package" install "$snapshot_package"
+    "$rvm_path/scripts/package" install "$snapshot_package"
     result="$?"
     __error_on_result "$result" "Error installing package '$snapshot_package'" && return "$result"
   done; unset snapshot_package
 
-  "$rvm_scripts_path/log" "info" "Installing rubies"
+  "$rvm_path/scripts/log" "info" "Installing rubies"
   chmod +x "$snapshot_temp_path/install-rubies.sh"
   "$snapshot_temp_path/install-rubies.sh"
   result="$?"
   __error_on_result "$result" "Error importing rubies." && return "$result"
 
   export rvm_create_flag=1
-  "$rvm_scripts_path/log" "info" "Setting up gemsets"
+  "$rvm_path/scripts/log" "info" "Setting up gemsets"
   (
     builtin cd "$snapshot_temp_path/gems"
 
@@ -162,7 +162,7 @@ snapshot_load() {
       __error_on_result "$result" \
         "Error copying across cache for $snapshot_gemset" && return "$result"
 
-      "$rvm_scripts_path/gemsets" import "$snapshot_gemset" >/dev/null 2>&1
+      "$rvm_path/scripts/gemsets" import "$snapshot_gemset" >/dev/null 2>&1
       result="$?"
 
       __error_on_result "$result" \
@@ -170,25 +170,25 @@ snapshot_load() {
     done
   )
 
-  "$rvm_scripts_path/log" "info" "Restoring aliases"
+  "$rvm_path/scripts/log" "info" "Restoring aliases"
   while read -r package_info; do
     # Note: this assumes an '=' int the input...
     local alias_name="${package_info/=*}"
     local alias_ruby="${package_info/*=}"
 
-    "$rvm_scripts_path/alias" create "$alias_name" "$alias_ruby"
+    "$rvm_path/scripts/alias" create "$alias_name" "$alias_ruby"
     if [[ "$alias_name" = "default" ]]; then
-      (source "$rvm_scripts_path/rvm" && rvm use "$alias_ruby" --default) >/dev/null 2>&1
+      (source "$rvm_path/scripts/rvm" && rvm use "$alias_ruby" --default) >/dev/null 2>&1
       result="$?"
       __error_on_result "$result" "Error setting default to $alias_ruby" && return "$result"
     fi
   done < "$snapshot_temp_path/alias"
   unset package_info
 
-  "$rvm_scripts_path/log" "info" "Cleaning up load process"
+  "$rvm_path/scripts/log" "info" "Cleaning up load process"
   \rm -rf "$snapshot_temp_path"
 
-  "$rvm_scripts_path/log" "info" "Loaded snapshot from $(basename "$snapshot_archive")"
+  "$rvm_path/scripts/log" "info" "Loaded snapshot from $(basename "$snapshot_archive")"
 }
 
 snapshot_usage() {
diff --git a/scripts/utility b/scripts/utility
--- a/scripts/utility
+++ b/scripts/utility
@@ -58,7 +58,7 @@ __rvm_dump_environment() {
       \rm -f "$dump_environment_file" && ln -s /dev/null "$dump_environment_file" >/dev/null 2>&1
 
     else
-      "$rvm_scripts_path/environment-convertor" "$dump_environment_type" "$(__rvm_environment_identifier)" > "$dump_environment_file"
+      "$rvm_path/scripts/environment-convertor" "$dump_environment_type" "$(__rvm_environment_identifier)" > "$dump_environment_file"
       if [[ "$?" -gt 0 && -f "$dump_environment_file" ]] ; then
         \rm -f "$dump_environment_file"
       fi
@@ -99,11 +99,11 @@ __rvm_db() {
   variable=${2:-""}
 
   if [[ -f "$rvm_config_path/user" ]] ; then
-    value="$($rvm_scripts_path/db "$rvm_config_path/user" "$key")"
+    value="$($rvm_path/scripts/db "$rvm_config_path/user" "$key")"
   fi
 
   if [[ -z "$value" ]] ; then
-    value="$($rvm_scripts_path/db "$rvm_config_path/db" "$key")"
+    value="$($rvm_path/scripts/db "$rvm_config_path/db" "$key")"
   fi
 
   if [[ -n "$value" ]] ; then
@@ -158,7 +158,7 @@ __rvm_quote_args_with_shift() {
 __rvm_warn_on_rubyopt() {
 
   if [[ -n "${RUBYOPT:-""}" ]]; then
-    "$rvm_scripts_path"/log "warn" \
+    "$rvm_path/scripts"/log "warn" \
       "Please note: You have the RUBYOPT environment variable set and this may interfere with normal rvm operations. We sugges unsetting it."
     return 1
   else
@@ -224,10 +224,10 @@ __rvm_run() {
 
   if [[ -z "${rvm_ruby_log_path:-""}" ]] ; then rvm_ruby_log_path="$rvm_log_path" ; fi
 
-  if [[ -n "$message" ]] ; then "$rvm_scripts_path/log" "info" "$message" ; fi
+  if [[ -n "$message" ]] ; then "$rvm_path/scripts/log" "info" "$message" ; fi
 
   if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then
-    "$rvm_scripts_path/log" "debug" "Executing: $command"
+    "$rvm_path/scripts/log" "debug" "Executing: $command"
   fi
 
   \mkdir -p "$(dirname "$rvm_ruby_log_path/$log_file_name.log")"
@@ -246,7 +246,7 @@ __rvm_run() {
   local result=$?
 
   if [[ $result -gt 0 ]] ; then
-    "$rvm_scripts_path/log" "error" \
+    "$rvm_path/scripts/log" "error" \
       "Error running '$command', please check $rvm_ruby_log_path/$log_file_name*.log"
   fi
 
@@ -267,10 +267,10 @@ __rvm_run_with_env() {
 
   if [[ -z "$rvm_ruby_log_path" ]] ; then rvm_ruby_log_path="$rvm_log_path" ; fi
 
-  if [[ -n "$message" ]] ; then "$rvm_scripts_path/log" "info" "$message" ; fi
+  if [[ -n "$message" ]] ; then "$rvm_path/scripts/log" "info" "$message" ; fi
 
   if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then
-    "$rvm_scripts_path/log" "debug" "Executing: $command in environment "$env_name""
+    "$rvm_path/scripts/log" "debug" "Executing: $command in environment "$env_name""
   fi
 
   \mkdir -p "$(dirname "$rvm_ruby_log_path/$log_file_name.log")"
@@ -289,7 +289,7 @@ __rvm_run_with_env() {
   result=$?
 
   if [[ $result -gt 0 ]] ; then
-    "$rvm_scripts_path/log" "error" \
+    "$rvm_path/scripts/log" "error" \
       "Error running '$command' under $env_name, please check $rvm_ruby_log_path/$log_file_name*.log"
   fi
 
@@ -358,9 +358,9 @@ __rvm_ensure_has_18_compat_ruby() {
     # TODO: install currently doesn't return the correct status.
     local compat_result=0
 
-    if ! ( "$rvm_scripts_path/manage" install 1.8.7 ); then
+    if ! ( "$rvm_path/scripts/manage" install 1.8.7 ); then
 
-      "$rvm_scripts_path/log" "fail" \
+      "$rvm_path/scripts/log" "fail" \
         "To proceed rvm requires a 1.8-compatible ruby is installed. We attempted to install 1.8.7 automatically but it failed.\
         Please install it manually (or a compatible alternative) to proceed."
 
@@ -400,7 +400,7 @@ __rvm_set_rvmrc() {
 
     if [[ -s .rvmrc ]] ; then
       mv .rvmrc .rvmrc.$(date +%m.%d.%Y-%H:%M:%S)
-      "$rvm_scripts_path/log" "warning" ".rvmrc is not empty, moving aside to preserve."
+      "$rvm_path/scripts/log" "warning" ".rvmrc is not empty, moving aside to preserve."
     fi
 
     local identifier=$(__rvm_environment_identifier)
@@ -410,7 +410,7 @@ __rvm_set_rvmrc() {
 
     unset flags
   else
-    "$rvm_scripts_path/log" "error" ".rvmrc cannot be set in your home directory. \n The home .rvmrc is for global rvm settings only."
+    "$rvm_path/scripts/log" "error" ".rvmrc cannot be set in your home directory. \n The home .rvmrc is for global rvm settings only."
   fi
 }
 __rvm_load_rvmrc() {
@@ -420,7 +420,7 @@ __rvm_load_rvmrc() {
   for rvmrc in /etc/rvmrc $HOME/.rvmrc ; do
     if [[ -f "$rvmrc" ]] ; then
       if \grep -q '^\s*rvm .*$' $rvmrc ; then
-        "$rvm_scripts_path/log" "error" "$rvmrc is for rvm settings only.\nrvm CLI may NOT be called from within $rvmrc. \nSkipping the loading of $rvmrc"
+        "$rvm_path/scripts/log" "error" "$rvmrc is for rvm settings only.\nrvm CLI may NOT be called from within $rvmrc. \nSkipping the loading of $rvmrc"
         return 1
       else
         source "$rvmrc"
@@ -447,7 +447,7 @@ __rvm_benchmark() {
   # TODO: We can likely do this in a subshell in order to preserve the original environment?
   unset rvm_ruby_string
   export rvm_ruby_strings
-  "$rvm_scripts_path/set" "$rvm_action" $rvm_ruby_args
+  "$rvm_path/scripts/set" "$rvm_action" $rvm_ruby_args
   result=$?
   # Restore the state pre-sets.
   [[ -n "$old_rvm_ruby_string" ]] && rvm_ruby_string=$old_rvm_ruby_string
@@ -470,7 +470,7 @@ __rvm_bin_scripts() {
 # Write the bin/ wrapper script for currently selected ruby.
 # TODO: Adjust binscript to be able to handle all rubies not just the standard interpreteres.
 __rvm_bin_script() {
-  "$rvm_scripts_path/wrapper" "$rvm_ruby_string"
+  "$rvm_path/scripts/wrapper" "$rvm_ruby_string"
   return $?
 }
 
@@ -506,7 +506,7 @@ __rvm_reset() {
   __rvm_unset_ruby_variables
 
   for system_config in system_ruby system_gem_path system_user_gem_path ; do
-    "$rvm_scripts_path/db" "$rvm_config_path/user" "$system_config" "delete"
+    "$rvm_path/scripts/db" "$rvm_config_path/user" "$system_config" "delete"
   done ; unset system_config variable
 
   \rm -f $rvm_bin_path/ruby $rvm_bin_path/gem $rvm_bin_path/rake $rvm_bin_path/irb $rvm_bin_path/default*
@@ -517,25 +517,25 @@ __rvm_reset() {
 # Implode removes the entire rvm installation under $rvm_path.
 __rvm_implode() {
   while : ; do
-    "$rvm_scripts_path/log" "warn" "Are you SURE you wish for rvm to implode? This will remove $rvm_path ? (type 'yes' or 'no')"
+    "$rvm_path/scripts/log" "warn" "Are you SURE you wish for rvm to implode? This will remove $rvm_path ? (type 'yes' or 'no')"
 
     read response
 
     if [[ "yes" = "$response" ]] ; then
       if [[ "/" = "$rvm_path" ]] ; then
-        "$rvm_scripts_path/log" "error" "remove '/' ?!... Ni!"
+        "$rvm_path/scripts/log" "error" "remove '/' ?!... Ni!"
       else
         if [[ -d "$rvm_path" ]] ; then
-          "$rvm_scripts_path/log" "info" "Hai! Removing $rvm_path"
+          "$rvm_path/scripts/log" "info" "Hai! Removing $rvm_path"
           \rm -rf "$rvm_path/"
           echo "$rvm_path has been removed."
         else
-          "$rvm_scripts_path/log" "info" "It appears that $rvm_path is already non existant."
+          "$rvm_path/scripts/log" "info" "It appears that $rvm_path is already non existant."
         fi
       fi
       break
     elif [[ "no" = "$response" ]] ; then
-      "$rvm_scripts_path/log" "info" "Cancelling implosion, no harm done :)"
+      "$rvm_path/scripts/log" "info" "Cancelling implosion, no harm done :)"
       break
     fi
   done
@@ -548,7 +548,7 @@ __rvm_source_dir() {
   if [[ -z "$rvm_ruby_selected_flag" ]] ; then __rvm_select ; fi
 
   if [[ -z "$rvm_ruby_src_path" ]] ; then
-    "$rvm_scripts_path/log" "fail" "No source directory exists for the default implementation."
+    "$rvm_path/scripts/log" "fail" "No source directory exists for the default implementation."
   else
     echo "$rvm_ruby_src_path"
   fi
@@ -581,7 +581,7 @@ __rvm_update() {
     [[ ${rvm_bin_flag:-0} -eq 1 ]] && __rvm_bin_scripts
 
     # Update to the latest rubygems.
-    [[ ${rvm_rubygems_flag:-0} -eq 1 ]] && "$rvm_scripts_path/rubygems" current
+    [[ ${rvm_rubygems_flag:-0} -eq 1 ]] && "$rvm_path/scripts/rubygems" current
 
   )
   unset rvm_update_flag rvm_action rvm_self_flag rvm_ruby_revision rvm_bin_flag rvm_rubygems_flag
@@ -605,7 +605,7 @@ __rvm_update_rvm() {
     else
       stable_version="$(curl -s http://rvm.beginrescueend.com/releases/stable-version.txt)"
 
-      __rvm_run "fetch" "$rvm_scripts_path/fetch 'http://rvm.beginrescueend.com/releases/rvm-${stable_version}.tar.gz'" "fetching rvm-${stable_version}.tar.gz"
+      __rvm_run "fetch" "$rvm_path/scripts/fetch 'http://rvm.beginrescueend.com/releases/rvm-${stable_version}.tar.gz'" "fetching rvm-${stable_version}.tar.gz"
 
       __rvm_run "extract" "gunzip < \"$rvm_archives_path/rvm-${stable_version}.tar.gz\" | tar xf - -C $rvm_src_path" "Extracting rvm-${stable_version}.tar.gz ..."
 
@@ -613,13 +613,13 @@ __rvm_update_rvm() {
     fi
   )
 
-  rvm_hook="after_update" ; source "$rvm_scripts_path/hook"
+  rvm_hook="after_update" ; source "$rvm_path/scripts/hook"
 
   return 0
 }
 
 __rvm_reboot() {
-  "$rvm_scripts_path/log" "warn" "Do you wish to reboot rvm? ('yes', or 'no')"
+  "$rvm_path/scripts/log" "warn" "Do you wish to reboot rvm? ('yes', or 'no')"
 
   local response="no"
 
@@ -633,7 +633,7 @@ __rvm_reboot() {
     mv "$rvm_path/archives" "$HOME/.archives"
 
     if [[ "/" = "$rvm_path" ]] ; then
-      "$rvm_scripts_path/log" "error" "remove '/' ?!... NO!"
+      "$rvm_path/scripts/log" "error" "remove '/' ?!... NO!"
     else
       if [[ -d "$rvm_path" ]] ; then \rm -rf "$rvm_path/" ; fi
     fi
@@ -644,7 +644,7 @@ __rvm_reboot() {
 
     source "$rvm_path/scripts/rvm"
   else
-    "$rvm_scripts_path/log" "info" "Carry on then..."
+    "$rvm_path/scripts/log" "info" "Carry on then..."
   fi
 
   return 0
@@ -653,7 +653,7 @@ __rvm_reboot() {
 # Create the irbrc for the currently selected ruby installation.
 __rvm_irbrc() {
   if [[ -d "$rvm_ruby_home" && ! -s "$rvm_ruby_irbrc" ]] ; then
-    \cp "$rvm_scripts_path/irbrc" "$rvm_ruby_irbrc"
+    \cp "$rvm_path/scripts/irbrc" "$rvm_ruby_irbrc"
   fi
   return $?
 }
@@ -691,7 +691,7 @@ __rvm_inspect() {
   for binary in $rvm_ruby_args ; do
     actual_file="$(command -v $binary)"
 
-    "$rvm_scripts_path/log" "info" "$actual_file:"
+    "$rvm_path/scripts/log" "info" "$actual_file:"
 
     if [[ $rvm_shebang_flag -eq 1 ]] ; then \head -n 1    < "$actual_file" ; fi
     if [[ $rvm_env_flag -eq 1 ]]     ; then \awk '/ENV/'  < "$actual_file" ; fi
@@ -799,7 +799,7 @@ __rvm_ensure_has_environment_files() {
       if [[ ! -L "$directory_name" && ! -d "$directory_name" ]]; then
         \mkdir -p "$directory_name"
 
-        "$rvm_scripts_path/wrapper" "$wrapper_identifier" &> /dev/null
+        "$rvm_path/scripts/wrapper" "$wrapper_identifier" &> /dev/null
       fi
       rvm_creating_default_wrappers=0
     done
@@ -814,7 +814,7 @@ __rvm_strip() {
 }
 
 __rvm_using_gemset_globalcache() {
-  "$rvm_scripts_path/db" "$rvm_config_path/user" "use_gemset_globalcache" | \grep -q '^true$'
+  "$rvm_path/scripts/db" "$rvm_config_path/user" "use_gemset_globalcache" | \grep -q '^true$'
   return $?
 }
 
@@ -881,27 +881,27 @@ __rvm_rvmrc_key() {
 
 __rvm_reset_rvmrc_trust() {
   touch "$rvm_config_path/rvmrcs"
-  "$rvm_scripts_path/db" "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")" "delete" >/dev/null 2>&1
+  "$rvm_path/scripts/db" "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")" "delete" >/dev/null 2>&1
   return $?
 }
 
 __rvm_trust_rvmrc() {
   touch "$rvm_config_path/rvmrcs"
   __rvm_reset_rvmrc_trust "$1"
-  "$rvm_scripts_path/db" "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")" "1" >/dev/null 2>&1
+  "$rvm_path/scripts/db" "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")" "1" >/dev/null 2>&1
   return $?
 }
 
 __rvm_untrust_rvmrc() {
   touch "$rvm_config_path/rvmrcs"
   __rvm_reset_rvmrc_trust "$1"
-  "$rvm_scripts_path/db" "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")" "0" >/dev/null 2>&1
+  "$rvm_path/scripts/db" "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")" "0" >/dev/null 2>&1
   return $?
 }
 
 __rvm_rvmrc_stored_trust() {
   touch "$rvm_config_path/rvmrcs"
-  "$rvm_scripts_path/db" "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")"
+  "$rvm_path/scripts/db" "$rvm_config_path/rvmrcs" "$(__rvm_rvmrc_key "$1")"
   return $?
 }
 
@@ -1074,7 +1074,7 @@ __rvm_record_install() {
 
   [[ -z "$1" ]] && return
 
-  recorded_ruby_name="$($rvm_scripts_path/tools strings "$1")"
+  recorded_ruby_name="$($rvm_path/scripts/tools strings "$1")"
 
   rvm_install_record_file="$rvm_config_path/installs"
 
@@ -1098,7 +1098,7 @@ __rvm_record_install() {
 __rvm_remove_install_record() {
   local recorded_ruby_name rvm_install_record_file
 
-  recorded_ruby_name="$($rvm_scripts_path/tools strings "$1")"
+  recorded_ruby_name="$($rvm_path/scripts/tools strings "$1")"
 
   rvm_install_record_file="$rvm_config_path/installs"
 
@@ -1118,7 +1118,7 @@ __rvm_recorded_install_command() {
 
   local recorded_ruby_name recorded_ruby_match
 
-  recorded_ruby_name="$($rvm_scripts_path/tools strings "$1" | awk -F"${rvm_gemset_separator:-"@"}" '{print $1}')"
+  recorded_ruby_name="$($rvm_path/scripts/tools strings "$1" | awk -F"${rvm_gemset_separator:-"@"}" '{print $1}')"
 
   [[ -z "$recorded_ruby_name" ]] && return 1
 
@@ -1153,20 +1153,20 @@ __rvm_expand_ruby_string() {
   local string="$1"
 
   if [[ -z "$string" || "$string" = "all" ]]; then
-    "$rvm_scripts_path/list" strings | tr ' ' "\n"
+    "$rvm_path/scripts/list" strings | tr ' ' "\n"
 
   elif [[ "$string" = "all-gemsets" ]]; then
-    "$rvm_scripts_path/list" gemsets strings
+    "$rvm_path/scripts/list" gemsets strings
 
   elif [[ "$string" = "default-with-rvmrc" || "$string" = "rvmrc" ]]; then
-    "$rvm_scripts_path/tools" path-identifier "$PWD"
+    "$rvm_path/scripts/tools" path-identifier "$PWD"
 
   elif [[ "$string" == "all-rubies" || "$string" = "rubies" ]]; then
-    "$rvm_scripts_path/list" rubies strings
+    "$rvm_path/scripts/list" rubies strings
 
   elif [[ "$string" == "current-ruby" || "$string" = "gemsets" ]]; then
     local current_ruby="$(__rvm_environment_identifier | awk -F"${rvm_gemset_separator:-"@"}" '{print $string}')"
-    rvm_silence_logging=1 "$rvm_scripts_path/gemsets" list | sed "s/^/$current_ruby${rvm_gemset_separator:-"@"}/"
+    rvm_silence_logging=1 "$rvm_path/scripts/gemsets" list | sed "s/^/$current_ruby${rvm_gemset_separator:-"@"}/"
 
   elif [[ "$string" = "current" ]]; then
     __rvm_environment_identifier
