make sure certificates are up to date for binary ruby, fix #2244

diff --git a/scripts/external b/scripts/external
--- a/scripts/external
+++ b/scripts/external
@@ -147,6 +147,25 @@ external_mount_link_default_gemset()
   fi
 }
 
+__rvm_ensure_osx_ssl_certificates()
+{
+  [[ "${__system_name}" == "OSX" ]] || return 0
+  source "$rvm_scripts_path/functions/osx-ssl-certs"
+
+  typeset ssl_dir cert_file
+  cert_file="$( __rvm_osx_ssl_certs_file_for_ruby "$1" )"
+  ssl_dir="${cert_file%/*}"
+  if
+    requirements_osx_update_openssl_cert_old
+  then
+    rvm_requiremnts_fail_or_run_action 2 \
+      "Skipping update of certificates in '$cert_file'." \
+      requirements_osx_update_openssl_cert_run ||
+      true # Ignore failure - ruby is already installed
+  fi
+  true # for osx
+}
+
 external_mount()
 {
   typeset _given_path ruby_path prefix_path
@@ -204,6 +223,7 @@ external_mount()
   __rvm_ruby_config_save "$ruby_path" "$rvm_rubies_path/$rvm_ruby_string/config"
   __rvm_fix_group_permissions "$rvm_rubies_path/$rvm_ruby_string"
   __rvm_record_install "$rvm_ruby_string"
+  __rvm_ensure_osx_ssl_certificates "$ruby_path"
 }
 
 external_select_name()
@@ -527,6 +547,7 @@ external_import_setup()
   __rvm_irbrc
   __rvm_ruby_config_save "$rvm_rubies_path/$rvm_ruby_string/bin/ruby" "$rvm_rubies_path/$rvm_ruby_string/config"
   __rvm_record_install "$rvm_ruby_string"
+  __rvm_ensure_osx_ssl_certificates "$rvm_rubies_path/$rvm_ruby_string/bin/ruby"
 }
 
 external_import()
