Environment is much cleaner new. More code cleanup.

diff --git a/scripts/fetch b/scripts/fetch
--- a/scripts/fetch
+++ b/scripts/fetch
@@ -11,7 +11,7 @@ trap 'cleanup_download' 1 2 3 15
 
 cleanup_download() {
 
-  [[ -f "$archive" ]] && rm -rf "$archive"
+  [[ -f "$archive" ]] && rm -f "$archive"
 
 }
 
@@ -35,13 +35,20 @@ builtin cd "${rvm_archives_path:-"$rvm_path/archives"}"
 
 # args=($*) # Reserved for future use
 
-if [[ -z "$1" ]] ; then "$rvm_path/scripts/log" "fail" "BUG: $0 called without an argument :/" ; exit 1 ; fi
+if [[ -z "$1" ]] ; then
+
+  "$rvm_path/scripts/log" "fail" \
+    "BUG: $0 called without an argument :/"
+
+  exit 1
+fi
 
 url="$1"; download=1 ; package_name="$2"
 
 if ! command -v curl > /dev/null ; then
 
-  "$rvm_path/scripts/log" "fail" "rvm requires curl. curl was not found in your active path."
+  "$rvm_path/scripts/log" "fail" \
+    "rvm requires curl. curl was not found in your active path."
 
   exit 1
 
@@ -69,41 +76,64 @@ else
 
 fi
 
-if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_path/scripts/log" "debug" "Fetching $archive" ; fi
+if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then
+
+  "$rvm_path/scripts/log" "debug" \
+    "Fetching $archive"
+
+fi
 
 # Check first if we have the correct archive
 archive_md5="$($rvm_path/scripts/db "$rvm_path/config/md5" "$archive" | head -n1)"
 
-if [[ -e "$archive" ]] && [[ ! -z "$archive_md5" ]] ; then
+if [[ -e "$archive" && ! -z "$archive_md5" ]] ; then
 
-  if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_path/scripts/log" "debug" "Found archive and its md5, testing correctness" ; fi
+  if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then
+
+    "$rvm_path/scripts/log" "debug" \
+    "Found archive and its md5, testing correctness"
+
+  fi
 
   if ! "$rvm_path/scripts"/md5 "${rvm_archives_path:-"$rvm_path/archives"}/${archive}" "$archive_md5" ; then
 
-    if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_path/scripts/log" "debug" "Archive is bad, downloading" ; fi
+    if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then
+      "$rvm_path/scripts/log" "debug" \
+        "Archive md5 did not match, downloading"
+    fi
 
     download=1
 
   else
 
-    if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_path/scripts/log" "debug" "Archive is good, not downloading" ; fi
+    if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then
+
+      "$rvm_path/scripts/log" "debug" \
+        "Archive md5 matched, not downloading"
+
+    fi
 
     download=0
 
     result=0
 
-  fi ; unset archive_md5
+  fi
 
 else
 
-  if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_path/scripts/log" "debug" "No archive or no MD5, downloading" ; fi
+  if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then
+
+    "$rvm_path/scripts/log" "debug" \
+      "No archive or no MD5, downloading"
+
+  fi
 
   download=1
 
 fi
 
 # try to convert the ftp url to a http url
-http_url="$(echo $url | sed -e 's/ftp:/http:/' -e 's/git:/http:/')"
+http_url="$(echo "$url" | sed -e 's/ftp:/http:/' -e 's/git:/http:/')"
 
 if [[ $download -gt 0 ]] ; then
 
@@ -119,13 +149,15 @@ if [[ $download -gt 0 ]] ; then
 
     if [[ $result -eq 78 ]] ; then
 
-      "$rvm_path/scripts/log" "error" "The requested url does not exist: '$url'"
+      "$rvm_path/scripts/log" "error" \
+        "The requested url does not exist: '$url'"
 
       try_http=1
 
     elif [[ $result -eq 18 ]] ; then
 
-      "$rvm_path/scripts/log" "error" "Partial file. Only a part of the file was transferred. Removing partial and re-trying."
+      "$rvm_path/scripts/log" "error" \
+        "Partial file. Only a part of the file was transferred. Removing partial and re-trying."
 
       rm -f "$archive"
 
@@ -133,7 +165,12 @@ if [[ $download -gt 0 ]] ; then
 
     elif [[ $result -eq 33 ]] ; then
 
-      if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then "$rvm_path/scripts/log" "debug" "Server does not support 'range' command, removing '$archive'" ; fi
+      if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then
+
+        "$rvm_path/scripts/log" "debug" \
+        "Server does not support 'range' command, removing '$archive'"
+
+      fi
 
       rm -f "$archive"
 
@@ -141,7 +178,8 @@ if [[ $download -gt 0 ]] ; then
 
     else
 
-      "$rvm_path/scripts/log" "error" "There was an error, please check $rvm_ruby_log_path/*.error.log. Next we'll try to fetch via http."
+      "$rvm_path/scripts/log" "error" \
+        "There was an error, please check ${rvm_log_path:-"$rvm_path/log"}/$rvm_ruby_string/*.error.log. Next we'll try to fetch via http."
 
       try_http=1
 
@@ -153,7 +191,8 @@ if [[ $download -gt 0 ]] ; then
 
       if [[ $result -gt 0 ]] ; then
 
-        "$rvm_path/scripts/log" "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
+        "$rvm_path/scripts/log" "error" \
+          "There was an error, please check ${rvm_log_path:-"$rvm_path/log"}/$rvm_ruby_string/*.error.log"
 
       else
 
@@ -169,7 +208,8 @@ if [[ $download -gt 0 ]] ; then
 
       if [[ $result -gt 0 ]] ; then
 
-        "$rvm_path/scripts/log" "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
+        "$rvm_path/scripts/log" "error" \
+          "There was an error, please check ${rvm_log_path:-"$rvm_path/log"}/$rvm_ruby_string/*.error.log"
 
       else
 
@@ -184,6 +224,7 @@ if [[ $download -gt 0 ]] ; then
     record_md5
 
   fi
+
 fi
 
 exit $result
diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -916,17 +916,33 @@ RubyWrapper
         cp -r "${rvm_src_path:-"$rvm_path/src"}/$rvm_ruby_string/Merlin/External.LCA_RESTRICTED/Languages/Ruby/redist-libs/ruby"/* "$rvm_ruby_home/lib/ruby"
         cp -r "${rvm_src_path:-"$rvm_path/src"}/$rvm_ruby_string/Merlin/Main/Languages/Ruby/Libs"/* "$rvm_ruby_home/lib/IronRuby"
       else
-        "$rvm_path/scripts/log" "info" "Retrieving IronRuby"
+        "$rvm_path/scripts/log" "info" \
+          "Retrieving IronRuby"
 
-        "$rvm_path/scripts/fetch" "$rvm_ruby_url" "$rvm_ruby_package_file"
-        result=$? ; if [[ "$result" -gt 0 ]] ; then
-          "$rvm_path/scripts/log" "error" "There has been an error while trying to fetch the source. Halting the installation." ; return $result
+        "$rvm_path/scripts/fetch" "$rvm_ruby_url" \
+          "$rvm_ruby_package_file"
+        result=$?
+
+        if [[ "$result" -gt 0 ]] ; then
+          "$rvm_path/scripts/log" "error" \
+            "There has been an error while trying to fetch the source. Halting the installation."
+          return $result
         fi
 
         mkdir -p "${rvm_src_path:-"$rvm_path/src"}/$rvm_ruby_string" "$rvm_ruby_home"
-        unzip -o  -d "${rvm_src_path:-"$rvm_path/src"}/$rvm_ruby_string" "${rvm_archives_path:-"$rvm_path/archives"}/${rvm_ruby_package_file}" >> "$rvm_ruby_log_path/extract.log" 2>> "$rvm_ruby_log_path/extract.error.log"
-        result=$? ; if [[ "$result" -gt 1 ]] ; then
-          "$rvm_path/scripts/log" "error" "There has been an error while trying to extract $rvm_ruby_package_file. Halting the installation." ; return $result
+
+        unzip -o  -d "${rvm_src_path:-"$rvm_path/src"}/$rvm_ruby_string" \
+          "${rvm_archives_path:-"$rvm_path/archives"}/${rvm_ruby_package_file}" >> \
+          "${rvm_log_path:-"$rvm_path/log"}$rvm_ruby_string/extract.log" 2>> \
+          "${rvm_log_path:-"$rvm_path/log"}$rvm_ruby_string/extract.error.log"
+        result=$?
+
+        if [[ "$result" -gt 1 ]] ; then
+
+          "$rvm_path/scripts/log" "error" \
+            "There has been an error while trying to extract $rvm_ruby_package_file. Halting the installation."
+          return $result
+
         fi
 
         for dir in bin lib silverlight ; do
@@ -960,7 +976,9 @@ RubyWrapper
 
       builtin hash -r
 
-      __rvm_run "gems.install" "PATH=$rvm_ruby_gem_home/bin:$rvm_ruby_global_gems_path/bin:$rvm_ruby_home/bin:$PATH GEM_HOME=$rvm_ruby_gem_home GEM_PATH=$rvm_ruby_gem_home $rvm_ruby_home/bin/gem install --no-rdoc --no-ri rake $rvm_gem_options" "Installing $rvm_gem_name to $dir"
+      __rvm_run "gems.install" \
+        "PATH=$rvm_ruby_gem_home/bin:$rvm_ruby_global_gems_path/bin:$rvm_ruby_home/bin:$PATH GEM_HOME=$rvm_ruby_gem_home GEM_PATH=$rvm_ruby_gem_home $rvm_ruby_home/bin/gem install --no-rdoc --no-ri rake $rvm_gem_options" \
+        "Installing $rvm_gem_name to $dir"
     ;;
 
     mput|shyouhei)
@@ -1003,7 +1021,8 @@ RubyWrapper
       if [[ -s ./Makefile ]] && [[ -z "$rvm_reconfigure_flag" ]] ; then
 
         if [[ ${rvm_debug_flag:-0} -gt 0 ]] ; then
-          "$rvm_path/scripts/log" "debug" "Skipping configure step, Makefile exists so configure must have already been run."
+          "$rvm_path/scripts/log" "debug" \
+            "Skipping configure step, Makefile exists so configure must have already been run."
         fi
 
       elif [[ -n "$rvm_ruby_configure" ]] ; then
@@ -1058,7 +1077,8 @@ RubyWrapper
         return $result
       fi
 
-      "$rvm_path/scripts/log" "info" "Installation of $rvm_ruby_string is complete."
+      "$rvm_path/scripts/log" "info" \
+        "Installation of $rvm_ruby_string is complete."
 
       export GEM_HOME="$rvm_ruby_gem_home"
       export GEM_PATH="$rvm_ruby_gem_path"
