Remove archives if interrupted mid-download

diff --git a/scripts/fetch b/scripts/fetch
--- a/scripts/fetch
+++ b/scripts/fetch
@@ -3,6 +3,13 @@
 rvm_base_except="selector"
 source "$rvm_scripts_path/base"
 
+# Set it to cleanup the download on interruption.
+trap 'cleanup_download' 1 2 3 15
+
+cleanup_download() {
+  [[ -f "$archive" ]] && rm -rf "$archive"
+}
+
 record_md5() {
   if [[ "Darwin" = "$(uname)" ]] || [[ "FreeBSD" = "$(uname)" ]]; then
     archive_md5="$(/sbin/md5 -q "${archive}")"
@@ -87,5 +94,4 @@ if [[ $download -gt 0 ]] ; then
     record_md5
   fi
 fi
-
 exit $result
