added code to fallback to http:// if git:// or ftp:// fails.  This allows rvm to work behind corporate firewalls with http only access to the internet

diff --git a/scripts/fetch b/scripts/fetch
--- a/scripts/fetch
+++ b/scripts/fetch
@@ -61,14 +61,20 @@ else
   download=1
 fi
 
+# try to convert the ftp url to a http url
+http_url="$(echo $url | sed -e 's/ftp:/http:/')"
+
+
 if [[ $download -gt 0 ]] ; then
   rm -f $archive
   eval $fetch_command "$url"
   result=$?
   if [[ $result -gt 0 ]] ; then
     retry=0
+		try_http=0
     if [[ $result -eq 78 ]] ; then
       $rvm_scripts_path/log "error" "The requested url does not exist: '$url'"
+			try_http=1
     elif [[ $result -eq 18 ]] ; then
       $rvm_scripts_path/log "error" "Partial file. Only a part of the file was transferred. Removing partial and re-trying."
       rm -f "$archive"
@@ -78,7 +84,8 @@ if [[ $download -gt 0 ]] ; then
       rm -f "$archive"
       retry=1
     else
-      $rvm_scripts_path/log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
+      $rvm_scripts_path/log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log. Next we'll try to fetch via http."
+			try_http=1
     fi
 
     if [[ $retry -eq 1 ]] ; then
@@ -90,6 +97,17 @@ if [[ $download -gt 0 ]] ; then
         record_md5
       fi
     fi
+
+    if [[ $try_http -eq 1 ]] ; then
+      eval $fetch_command "$http_url"
+      result=$?
+      if [[ $result -gt 0 ]] ; then
+        $rvm_scripts_path/log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
+      else
+        record_md5
+      fi
+    fi
+
   else
     record_md5
   fi
diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -716,6 +716,11 @@ __rvm_fetch_from_github() {
     rm -rf "$rvm_ruby_repo_path"
     builtin cd "$rvm_home"
     __rvm_run "$1.repo" "git clone --depth 1 $rvm_ruby_repo_url $rvm_ruby_repo_path" "Cloning $rvm_ruby_repo_url"
+		result=$? ; if [[ "$result" -gt 0 ]] ; then
+			rvm_ruby_repo_http_url="$(echo $rvm_ruby_repo_url | sed -e 's/git:/http:/')"
+			$rvm_scripts_path/log "info" "Could not fetch $rvm_ruby_repo_url - trying $rvm_ruby_repo_http_url"
+			__rvm_run "$1.repo" "git clone --depth 1 $rvm_ruby_repo_http_url $rvm_ruby_repo_path" "Cloning $rvm_ruby_repo_http_url"			
+		fi
   else
     local branch="${2:-"master"}"
     builtin cd "$rvm_ruby_repo_path"
@@ -803,10 +808,15 @@ __rvm_fetch_ruby() {
         fi
       else
         rm -rf "$rvm_ruby_repo_path"
+				rvm_ruby_repo_http_url="$(echo $rvm_ruby_repo_url | sed -e 's/git:/http:/')"
         $rvm_scripts_path/log "info" "Cloning from $rvm_ruby_repo_url, this may take a while depending on your connection..."
         git clone --depth 1 "$rvm_ruby_repo_url" "$rvm_ruby_repo_path"
         result=$? ; if [[ "$result" -gt 0 ]] ; then
-          $rvm_scripts_path/log "error" "There has been an error while trying to fetch the repository. Aborting the installation." ; __rvm_pushpop ; return $result
+					$rvm_scripts_path/log "info" "Cloning from $rvm_ruby_repo_http_url, this may take a while depending on your connection..."
+					git clone --depth 1 "$rvm_ruby_repo_http_url" "$rvm_ruby_repo_path"
+					result=$? ; if [[ "$result" -gt 0 ]] ; then
+						$rvm_scripts_path/log "error" "There has been an error while trying to fetch the repository. Aborting the installation." ; __rvm_pushpop ; return $result
+					fi
         fi
       fi
     else
