Ironruby might work now.

diff --git a/scripts/fetch b/scripts/fetch
--- a/scripts/fetch
+++ b/scripts/fetch
@@ -13,20 +13,27 @@ record_md5() {
   $rvm_scripts_path/db "$rvm_config_path/md5" "$archive" "$archive_md5"
 }
 
-if ! which curl &> /dev/null; then
-  $rvm_scripts_path/log "fail" "rvm requires curl, which does not seem to exist in your path :("
-  exit 1
-elif [[ ! -z ${rvm_proxy} ]] ; then
-  fetch_command="curl -x${rvm_proxy} -O -L --create-dirs -C - " # -s for silent
-else
-  fetch_command="curl -O -L --create-dirs -C - " # -s for silent
-fi
-
 builtin cd "$rvm_archives_path"
 
 if [[ -z "$1" ]] ; then $rvm_scripts_path/log "fail" "BUG: $0 called without an argument :/" ; exit 1 ; fi
 
-archive=$(basename "$1") ; downlaod=1
+archive=$(basename "$1") ; download=1 ; package_name="$2"
+
+if ! which curl &> /dev/null; then
+  $rvm_scripts_path/log "fail" "rvm requires curl, which does not seem to exist in your path :("
+  exit 1
+elif [[ ! -z ${rvm_proxy} ]] ; then
+  fetch_command="curl -x${rvm_proxy} -L --create-dirs -C - " # -s for silent
+else
+  fetch_command="curl -L --create-dirs -C - " # -s for silent
+fi
+
+if [[ ! -z "$package_name" ]] ; then
+  fetch_command="${fetch_command} -o ${package_name} "
+else
+  fetch_command="${fetch_command} -O "
+fi
+
 
 if [[ ! -z "$rvm_debug_flag" ]] ; then $rvm_scripts_path/log "debug" "Fetching $archive" ; fi
 
