Bugfix: rvm gemset copy now works as intended.

diff --git a/scripts/gemsets b/scripts/gemsets
--- a/scripts/gemsets
+++ b/scripts/gemsets
@@ -358,7 +358,8 @@ gemset_copy()
   args[$__array_start]="" ; args=(${args[@]})
 
   if [[ -z "$destination_ruby" || -z "$source_ruby" ]] ; then
-    "$rvm_path/scripts/log" "error" "Source and destination must be specified: 'rvm gemset copy X Y'"
+    "$rvm_path/scripts/log" "error"\
+      "Source and destination must be specified: 'rvm gemset copy X Y'"
     return 1
   fi
 
@@ -368,7 +369,7 @@ gemset_copy()
     export rvm_create_flag=1
     { __rvm_ruby_string && __rvm_gemset_select; } 2> /dev/null
   )
-    result=$?
+  result=$?
 
   if [[ $result -ne 0 ]]; then
     "$rvm_path/scripts/log" "error" \
@@ -382,9 +383,9 @@ gemset_copy()
   #   rvm gemset copy gemseta gemsetb       # Currenty Ruby, gemseta exists.
   #   rvm gemset copy gemseta 1.8.7@gemsetb # Currenty Ruby@gemseta, current ruby@gemseta exists.
 
-  source_path="$(rvm_silence_logging=1 rvm "$source_ruby" gem env gemdir)"
+  source_path="${rvm_gems_path:-"$rvm_path/gems"}/$source_ruby"
 
-  destination_path="$(rvm_create_flag=1 rvm_silence_logging=1 rvm "$destination_ruby" gem env gemdir)"
+  destination_path="${rvm_gems_path:-"$rvm_path/gems"}/$destination_ruby"
 
   if [[ -z "$source_path" || ! -d "$source_path" ]]; then
     "$rvm_path/scripts/log" "error" \
