Merging in patch by iLikePi.

diff --git a/scripts/gemsets b/scripts/gemsets
--- a/scripts/gemsets
+++ b/scripts/gemsets
@@ -362,6 +362,19 @@ gemset_copy()
     return 1
   fi
 
+  # Verify the destination gemset exists before attempting to use it.
+  (
+    rvm_ruby_string="$destination_ruby"
+    { __rvm_ruby_string && __rvm_gemset_select; } 2> /dev/null
+  )
+    result=$?
+
+  if [[ $result -ne 0 ]]; then
+    "$rvm_path/scripts/log" "error" \
+      "Destination gemset '$destination_ruby' does not yet exist."
+    return 1
+  fi
+
   # TODO: Account for more possibilities:
   #   rvm gemset copy 1.9.2 @gemsetb        # From 1.9.2 default to current ruby, 1.9.2 exists.
   #   rvm gemset copy @gemseta @gemsetb     # Current ruby, gemseta exists.
