Bugfix: gemsync actually works now. Thanks bosie.

diff --git a/scripts/gemsync b/scripts/gemsync
--- a/scripts/gemsync
+++ b/scripts/gemsync
@@ -7,11 +7,11 @@
 #
 source ~/.bash_profile # load rvm
 
-from_string=`echo "$@" | sed 's/--/;/g' | tr ';' "\n" | awk '/from/ {print}'`
-to_string=`echo "$@" | sed 's/--/;/g' | tr ';' "\n" | awk '/to/ {print}'`
+from_string=`echo "$@" | sed 's/--/;/g' | tr ';' "\n" | awk '/from/ {print}' | sed 's/from//'`
+to_string=`echo "$@" | sed 's/--/;/g' | tr ';' "\n" | awk '/to/ {print}' | sed 's/to//'`
 
 if [ -z "$from_string" ] ; then echo "Invalid arguments. Missing --from <ruby selector>" ; exit 1 ; fi
-if [ -z "$from_string" ] ; then echo "Invalid arguments. Missing --to <ruby selector>" ; exit 1 ; fi
+if [ -z "$to_string" ] ; then echo "Invalid arguments. Missing --to <ruby selector>" ; exit 1 ; fi
 
  # first we use where we want.
 rvm $to_string
