Added gem check to gems select

diff --git a/scripts/gems b/scripts/gems
--- a/scripts/gems
+++ b/scripts/gems
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 
 __rvm_gems_select() {
+  if ! which gem ; then
+    $rvm_scripts_path/log "error" "'gem' was not found, cannot perform gem actions."
+    return 1
+  fi
+
   if [[ -z "$rvm_gem_set_name" ]] ; then
     if [[ ! -z "$GEM_HOME" ]] ; then
       rvm_gem_set_name=$(echo $GEM_HOME | xargs basename | awk -F'%' '{print $2}')
@@ -20,7 +25,7 @@ __rvm_gems_select() {
       elif [[ ! -z "$GEM_HOME" ]] ; then
         rvm_ruby_gem_home="$GEM_HOME"
       else
-        $rvm_scripts_path/log "error" "Cannot select gem home, something definitely wrong :/"
+        $rvm_scripts_path/log "error" "Cannot select gem home, something is very wrong :/"
       fi
     fi
     if [[ -z "$rvm_gem_set_name" ]] ; then unset rvm_gem_set_name ; fi
