ignore empty gemsets in gemset pristine, fix #680

diff --git a/scripts/gemsets b/scripts/gemsets
--- a/scripts/gemsets
+++ b/scripts/gemsets
@@ -894,8 +894,14 @@ gemset_pristine()
 {
   if ( unset -f gem ; command -v gem > /dev/null )
   then
-    gem pristine --all
-    return $?
+    if gem list | sed '/\*\*\*/ d ; /^$/ d' | grep '.*' >/dev/null
+    then
+      gem pristine --all
+      return $?
+    else
+      # pristine fails if no gems available, this breaks few internal rvm commands
+      true
+    fi
   else
     rvm_error "'gem' command not found in PATH"
     return 1
