Returns are now through utility and some of gemsets

diff --git a/scripts/gemsets b/scripts/gemsets
--- a/scripts/gemsets
+++ b/scripts/gemsets
@@ -385,6 +385,7 @@ gemset_info() {
   else
     gem env $action
   fi
+  return $?
 }
 
 gemset_prune() {
@@ -399,18 +400,25 @@ gemset_prune() {
       cached_gem_name="${gem_name}-${version}.gem"
       cached_file_path="${live_cache_path}/${cached_gem_name}"
       if [[ -f "$cached_file_path" ]]; then
-        mv "$cached_file_path" "${temporary_cache_path}/${cached_gem_name}"
+        \mv "$cached_file_path" "${temporary_cache_path}/${cached_gem_name}"
       fi
     done
   done < <(gem list --versions)
   "$rvm_scripts_path/log" "info" "Removing live cache and restoring temporary cache..."
   # Switch the cache back.
   \rm -rf "$live_cache_path"
-  mv "$temporary_cache_path" "$live_cache_path"
+  \mv "$temporary_cache_path" "$live_cache_path"
+  return 0
 }
 
 gemset_pristine() {
-  gem pristine --all
+  if command -v gem > /dev/null ; then
+    gem pristine --all
+    return $?
+  else
+    "$rvm_scripts_path/log" "error" "'gem' command not found in PATH"
+    return 1
+  fi
 }
 
 # Loads the default gemsets for the current interpreter and gemset.
@@ -431,7 +439,10 @@ gemset_initial() {
       fi
     fi
   done
+
   "$rvm_scripts_path/log" "info" "Installation of gems for $(__rvm_environment_identifier) is complete."
+
+  return 0
 }
 
 unset GEM_PATH
