Bugfix: rvm get latest, variable correction.

diff --git a/scripts/get b/scripts/get
--- a/scripts/get
+++ b/scripts/get
@@ -25,7 +25,7 @@ Options:
 
 get_latest()
 {
-  local version_url stable_version
+  local version_url stable_version archive
 
   version_url="http://rvm.beginrescueend.com/releases/stable-version.txt"
 
@@ -34,21 +34,49 @@ get_latest()
   "$rvm_path/scripts/log" "info" "\nOriginal installed RVM version:"
   (__rvm_version)
 
+  [[ ! -d "$rvm_path/src" ]] && mkdir -p "$rvm_path/src/"
+  [[ ! -d "$rvm_path/archives" ]] && mkdir -p "$rvm_path/archives/"
+
+  # NOTE: This is the content as in binscripts/rvm-update-latest
+
+  stable_version=$(curl -B http://rvm.beginrescueend.com/releases/stable-version.txt 2>/dev/null)
+  stable_md5=$(curl -B http://rvm.beginrescueend.com/releases/rvm-${stable_version}.tar.gz.md5 2>/dev/null)
+
+  echo "rvm-${stable_version}"
+
+  archive="$rvm_path/archives/rvm-${stable_version}.tar.gz"
+
+  curl -L "http://rvm.beginrescueend.com/releases/rvm-${stable_version}.tar.gz" \
+    -o "$archive"
+
+  case "$(uname)" in
+    Darwin|FreeBSD)
+      archive_md5="$(/sbin/md5 -q "${archive}")"
+      ;;
+    OpenBSD)
+      archive_md5="$(/bin/md5 -q "${archive}")"
+      ;;
+    Linux|*)
+      archive_md5="$(md5sum "${archive}" | awk '{print $1}')"
+      ;;
+  esac
+
+  if [[ "$archive_md5" != "$stable_md5" ]]; then
+    printf "ERROR:
+    Archive package rvm-${stable_version}.tar.gz downloaded does not match it's md5 checksum ${stable_md5}.
+    Aborting RVM Installation.
+  "
+    exit 1
+  fi
+
+  tar zxf "${rvm_path}/archives/rvm-${stable_version}.tar.gz" -C "$rvm_path/src/"
 
   (
+    cd "$rvm_path/src/rvm-${stable_version}"
 
-  __rvm_run "fetch" \
-    "$rvm_path/scripts/fetch 'http://rvm.beginrescueend.com/releases/rvm-${stable_version}.tar.gz'" \
-    "fetching rvm-${stable_version}.tar.gz"
+    chmod +x ./scripts/install
 
-  __rvm_run "extract" \
-    "gunzip < \"${rvm_archives_path:-"$rvm_path/archives"}/rvm-${stable_version}.tar.gz\" | tar xf - -C ${rvm_src_path:-"$rvm_path/src"}" \
-    "Extracting rvm-${stable_version}.tar.gz ..."
-
-  __rvm_run "install" \
-    "builtin cd ${rvm_src_path:-"$rvm_path/src"}/rvm-${stable_version}/; ./install" \
-    "Installing rvm-${stable_version}..."
-
+    ./scripts/install
   )
 
   "$rvm_path/scripts/log" "info" "\nInstalled RVM version:"
@@ -82,8 +110,8 @@ get_head()
     else
 
       builtin cd "${rvm_src_path:-"$rvm_path/src"}" && \
-        ( git clone https://github.com/wayneeseguin/rvm.git || \
-        git clone --depth 1 git://github.com/wayneeseguin/rvm.git ) && \
+        ( git clone --depth 1 git://github.com/wayneeseguin/rvm.git || \
+          git clone https://github.com/wayneeseguin/rvm.git )&& \
         builtin cd rvm/ && ./scripts/install
     fi
   )
