More installer fixes.

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -12,17 +12,14 @@ then
   export rvm_trace_flag=1
 fi
 
-_path="${_rvm_path}"
-export rvm_path="$PWD"
-source "$PWD/scripts/rvm"
 source "$PWD/scripts/functions/installer"
-export rvm_path="${_path}"
+determine_install_path
+determine_install_or_upgrade
+# source "$PWD/scripts/rvm"
 
 #
 # RVM Installer
 #
-determine_install_path
-determine_install_or_upgrade
 install_setup
 
 # Parse RVM Installer CLI arguments.
@@ -71,6 +68,12 @@ do
       ;;
   esac
 done
+
+if [[ -z "${rvm_path:-}" ]]
+then
+  echo "ERROR: rvm_path is empty, halting installation."
+  exit 1
+fi
 
 export rvm_prefix rvm_path rvm_debug_flag rvm_trace_flag
 
