Abort macruby-head installation if install_source exited with error code.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -116,6 +116,9 @@ __rvm_install_ruby() {
           __rvm_db "${rvm_ruby_interpreter}_repo_url" "rvm_url"
           rvm_ruby_repo_url=$rvm_url
           __rvm_install_source $*
+          result=$? ; if [[ "$result" -gt 0 ]] ; then
+            $rvm_scripts_path/log "error" "There has been an error while trying to install from source. Aborting the installation." ; return $result
+          fi
         else # if [[ "nightly" = "$rvm_ruby_version" ]] ; then
           macruby_path="/usr/local/bin"
           # TODO: Separated nightly from head.
