Bugfix: 'rvm install macruby' now installs 0.5 instead of nightly build.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -118,10 +118,9 @@ __rvm_install_ruby() {
           result=$? ; if [[ "$result" -gt 0 ]] ; then
             $rvm_scripts_path/log "error" "There has been an error while trying to install from source. Aborting the installation." ; return $result
           fi
-        else # if [[ "nightly" = "$rvm_ruby_version" ]] ; then
+        elif [[ "nightly" = "$rvm_ruby_version" ]] ; then
           macruby_path="/usr/local/bin"
           # TODO: Separated nightly from head.
-          __rvm_db "macruby_nightly_url" "rvm_url"
           $rvm_scripts_path/log "info" "Retrieving the latest nightly macruby build..."
           $rvm_scripts_path/fetch "$rvm_url"
           result=$? ; if [[ "$result" -gt 0 ]] ; then
@@ -129,6 +128,16 @@ __rvm_install_ruby() {
           fi
           mv "$rvm_archives_path/macruby_nightly-latest.pkg" "$rvm_archives_path/macruby_nightly.pkg"
           __rvm_run "macruby/extract" "sudo installer -pkg '$rvm_archives_path/macruby_nightly.pkg' -target '/'"
+          mkdir -p "$rvm_ruby_home/bin"
+        else # if [[ "nightly" = "$rvm_ruby_version" ]] ; then
+          macruby_path="/usr/local/bin"
+          # TODO: Separated nightly from head.
+          $rvm_scripts_path/log "info" "Retrieving the latest nightly macruby build..."
+          $rvm_scripts_path/fetch "$rvm_url"
+          result=$? ; if [[ "$result" -gt 0 ]] ; then
+            $rvm_scripts_path/log "error" "There has been an error while trying to fetch the source. Aborting the installation." ; __rvm_pushpop ; return $result
+          fi
+          __rvm_run "macruby/extract" "sudo installer -pkg '$rvm_archives_path/$rvm_ruby_package_file.pkg' -target '/'"
           mkdir -p "$rvm_ruby_home/bin"
         fi
 
