More MagLev tweaking. Now workign on getting 'maglev-head' working proper.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -384,9 +384,9 @@ RubyWrapper
 
       $rvm_scripts_path/log "info" "Running MagLev prereqs checking script."
       $rvm_scripts_path/maglev
-        result=$? ; if [[ "$result" -gt 0 ]] ; then
-          $rvm_scripts_path/log "error" "Prerequisite checks have failed. Aborting the installation." ; __rvm_pushpop ; return $result
-        fi
+      result=$? ; if [[ "$result" -gt 0 ]] ; then
+        $rvm_scripts_path/log "error" "Prerequisite checks have failed. Aborting the installation." ; __rvm_pushpop ; return $result
+      fi
 
       mkdir -p "$rvm_ruby_log_path"
       __rvm_pushpop $rvm_src_path
@@ -397,6 +397,12 @@ RubyWrapper
         result=$? ; if [[ "$result" -gt 0 ]] ; then
           $rvm_scripts_path/log "error" "There has been an error while trying to fetch the source. Aborting the installation." ; __rvm_pushpop ; return $result
         fi
+      fi
+
+      if [[ ! -z "$rvm_head_flag" ]] ; then
+        cd $rvm_ruby_src_path
+        rvm_gemstone_package_file="GemStone-$(grep ^GEMSTONE version.txt | cut -f2 -d-).$(uname -sm | tr ' ' '-')"
+        rvm_gemstone_url="${rvm_gemstone_url:-"$maglev_url/${rvm_gemstone_package_file}.${rvm_archive_extension}"}"
       fi
 
       $rvm_scripts_path/log "info" "Downloading the gemstone package, this may take a while depending on your connection..."
@@ -436,6 +442,7 @@ RubyWrapper
       done ; unset binary
 
       builtin cd "$rvm_ruby_home"
+      mkdir -p locks backups log data
 
       #ln -fs "$rvm_ruby_home/$(echo $rvm_gemstone_package_file | awk -F'.' '{print $1}')" "$rvm_ruby_home/gemstone"
 
