For now always nab gemstone.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -399,12 +399,10 @@ RubyWrapper
         fi
       fi
 
-      if [[ "$rvm_head_flag" -eq 1 ]] ; then
-        $rvm_scripts_path/log "info" "Downloading the gemstone package, this may take a while depending on your connection..."
-        $rvm_scripts_path/fetch "$rvm_gemstone_url"
-        result=$? ; if [[ "$result" -gt 0 ]] ; then
-          $rvm_scripts_path/log "error" "There has been an error while trying to fetch the gemstone package. Aborting the installation." ; __rvm_pushpop ; return $result
-        fi
+      $rvm_scripts_path/log "info" "Downloading the gemstone package, this may take a while depending on your connection..."
+      $rvm_scripts_path/fetch "$rvm_gemstone_url"
+      result=$? ; if [[ "$result" -gt 0 ]] ; then
+        $rvm_scripts_path/log "error" "There has been an error while trying to fetch the gemstone package. Aborting the installation." ; __rvm_pushpop ; return $result
       fi
 
       builtin cd "$rvm_src_path"
@@ -413,11 +411,9 @@ RubyWrapper
 
       builtin cd "$rvm_ruby_src_path"
 
-      if [[ "$rvm_head_flag" -eq 1 ]] ; then
-        __rvm_run "gemstone.extract" "cat $rvm_archives_path/$rvm_gemstone_package_file | gunzip | tar xzf - -C $rvm_ruby_src_path"
-        result=$? ; if [[ "$result" -gt 0 ]] ; then
-          $rvm_scripts_path/log "error" "There has been an error while trying to extract the gemstone package. Aborting the installation." ; __rvm_pushpop ; return $result
-        fi
+      __rvm_run "gemstone.extract" "cat $rvm_archives_path/$rvm_gemstone_package_file | gunzip | tar xzf - -C $rvm_ruby_src_path"
+      result=$? ; if [[ "$result" -gt 0 ]] ; then
+        $rvm_scripts_path/log "error" "There has been an error while trying to extract the gemstone package. Aborting the installation." ; __rvm_pushpop ; return $result
       fi
 
       mv "$rvm_gemstone_package_file" "gemstone"
