More cleanup on scripts/manage.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -208,7 +208,7 @@ __rvm_install_source() {
 
     local configure_command="./configure --prefix=$rvm_ruby_home ${db_configure_flags:-""} ${rvm_configure_flags:-""} ${configure_parameters:-""}"
 
-    __rvm_run "configure" "$configure_command" "#configuring $rvm_ruby_string"
+    __rvm_run "configure" "$configure_command" "$rvm_ruby_string - #configuring "
     result=$?
 
     if [[ "$result" -gt 0 ]] ; then
@@ -224,7 +224,7 @@ __rvm_install_source() {
 
   rvm_ruby_make=${rvm_ruby_make:-"make"}
 
-  __rvm_run "make" "$rvm_ruby_make ${rvm_make_flags:-""}" "#compiling $rvm_ruby_string"
+  __rvm_run "make" "$rvm_ruby_make ${rvm_make_flags:-""}" "$rvm_ruby_string - #compiling "
   result=$?
 
   if [[ "$result" -gt 0 ]] ; then
@@ -239,7 +239,7 @@ __rvm_install_source() {
 
   rvm_ruby_make_install=${rvm_ruby_make_install:-"make install"}
 
-  __rvm_run "install" "$rvm_ruby_make_install" "#installing $rvm_ruby_string"
+  __rvm_run "install" "$rvm_ruby_make_install" "$rvm_ruby_string - #installing "
   result=$?
 
   if [[ "$result" -gt 0 ]] ; then
@@ -261,7 +261,7 @@ __rvm_install_source() {
   __rvm_post_install
 
   "$rvm_scripts_path/log" "info" \
-    "#complete install of $rvm_ruby_string"
+    "Install of $rvm_ruby_string - #complete "
 
   return 0
 }
@@ -413,9 +413,11 @@ RubyWrapper
             "It appears that the archive has already been extracted. Skipping extract (use --force to force re-download and extract)."
 
         else
-          "$rvm_scripts_path/log" "#fetching $rvm_ruby_package_file"
+          "$rvm_scripts_path/log" \
+            "$rvm_ruby_string - #fetching ($rvm_ruby_package_file)"
 
-          "$rvm_scripts_path/fetch" "$rvm_ruby_url"
+          "$rvm_scripts_path/fetch" \
+            "$rvm_ruby_url"
           result=$?
 
           if [[ "$result" -gt 0 ]] ; then
@@ -426,8 +428,7 @@ RubyWrapper
 
           rm -rf "$rvm_ruby_src_path"
 
-          __rvm_run "extract" "gunzip < \"$rvm_archives_path/$rvm_ruby_package_file.$rvm_archive_extension\" | tar xf - -C $rvm_src_path" "#extracting $rvm_ruby_package_file to $rvm_ruby_src_path"
-
+          __rvm_run "extract" "gunzip < \"$rvm_archives_path/$rvm_ruby_package_file.$rvm_archive_extension\" | tar xf - -C $rvm_src_path" "$rvm_ruby_string - #extracting $rvm_ruby_package_file to $rvm_ruby_src_path"
           result=$?
 
           if [[ "$result" -gt 0 ]] ; then
@@ -463,7 +464,7 @@ RubyWrapper
           return $result
         fi
 
-        __rvm_run "install" "./installer -a $rvm_rubies_path/$rvm_ruby_string $rvm_ree_options $db_configure_flags $rvm_configure_flags" "#installing $rvm_ruby_string"
+        __rvm_run "install" "./installer -a $rvm_rubies_path/$rvm_ruby_string $rvm_ree_options $db_configure_flags $rvm_configure_flags" "$rvm_ruby_string - #installing "
         result=$?
 
         if [[ "$result" -gt 0 ]] ; then
@@ -496,7 +497,7 @@ RubyWrapper
 
     rbx|rubinius)
 
-      "$rvm_scripts_path/log" "info" "#dependency installation"
+      "$rvm_scripts_path/log" "info" "$rvm_ruby_string installing #dependencies "
 
       # Ensure we have a 1.8.7 compatible ruby installed.
       __rvm_ensure_has_18_compat_ruby || return 1
@@ -514,7 +515,7 @@ RubyWrapper
 
       if [[ -n "$(echo $rvm_ruby_version | awk '/^1\.0/')" ]] && [[ $rvm_head_flag -eq 0 ]] ; then
 
-        "$rvm_scripts_path/log" "info" "#downloading $rvm_ruby_package_file, this may take a while depending on your connection..."
+        "$rvm_scripts_path/log" "info" "$rvm_ruby_string #downloading ($rvm_ruby_package_file), this may take a while depending on your connection..."
 
         "$rvm_scripts_path/fetch" "$rvm_ruby_url"
         result=$?
@@ -661,7 +662,7 @@ RubyWrapper
       builtin cd "$rvm_ruby_src_path"
 
       if [[ ${rvm_head_flag:-0} -eq 1 ]] ; then
-        __rvm_run "ant.dist" "ant dist" "#ant dist"
+        __rvm_run "ant.dist" "ant dist" "$rvm_ruby_string - #ant dist"
       fi
 
       mkdir -p "$rvm_ruby_home/bin/"
@@ -683,7 +684,7 @@ RubyWrapper
 
       rm -rf "$rvm_ruby_home"
 
-      __rvm_run "install" "/bin/cp -Rf $rvm_ruby_src_path $rvm_ruby_home" "#installing JRuby to $rvm_ruby_home"
+      __rvm_run "install" "/bin/cp -Rf $rvm_ruby_src_path $rvm_ruby_home" "$rvm_ruby_string - #installing to $rvm_ruby_home"
 
       (
         builtin cd "$rvm_ruby_home/bin/"
@@ -1131,7 +1132,7 @@ __rvm_fetch_from_github() {
 __rvm_fetch_ruby() {
   [[ ${rvm_ruby_selected_flag:-0} -eq 0 ]] && __rvm_select
 
-  "$rvm_scripts_path/log" "info" "#fetching ${rvm_ruby_string}"
+  "$rvm_scripts_path/log" "info" "$rvm_ruby_string #fetching "
 
   if [[ ${rvm_head_flag:-0} -eq 0 && -z "${rvm_ruby_tag:-""}" && -z "${rvm_ruby_revision:-""}" ]] ; then
 
@@ -1165,7 +1166,8 @@ __rvm_fetch_ruby() {
           ;;
       esac
 
-      "$rvm_scripts_path/log" "info" "#downloading ${rvm_ruby_package_file}, this may take a while depending on your connection..."
+      "$rvm_scripts_path/log" "info" \
+        "$rvm_ruby_string - #downloading ${rvm_ruby_package_file}, this may take a while depending on your connection..."
 
       "$rvm_scripts_path/fetch" "${rvm_ruby_url}"
       result=$?
@@ -1187,11 +1189,13 @@ __rvm_fetch_ruby() {
 
       case "$rvm_archive_extension" in
         tar.gz|tgz)
-          __rvm_run "extract" "gunzip < \"$rvm_archives_path/$rvm_ruby_package_file.$rvm_archive_extension\" | tar xf - -C /tmp/rvm_src_$$" "#extracting $rvm_ruby_package_file to $rvm_ruby_src_path"
+          __rvm_run "extract" "gunzip < \"$rvm_archives_path/$rvm_ruby_package_file.$rvm_archive_extension\" | tar xf - -C /tmp/rvm_src_$$" "$rvm_ruby_string - #extracting $rvm_ruby_package_file to $rvm_ruby_src_path"
           result=$?
 
           if [[ "$result" -gt 0 ]] ; then
-            "$rvm_scripts_path/log" "error" "There has been an error while trying to extract the source. Aborting the installation." ; return $result
+            "$rvm_scripts_path/log" "error" \
+              "There has been an error while trying to extract the source. Aborting the installation."
+            return $result
           fi
           ;;
         zip)
@@ -1199,21 +1203,24 @@ __rvm_fetch_ruby() {
           result=$?
 
           if [[ "$result" -gt 0 ]] ; then
-            "$rvm_scripts_path/log" "error" "There has been an error while trying to extract $rvm_ruby_package_file. Aborting the installation."
+            "$rvm_scripts_path/log" "error" \
+              "There has been an error while trying to extract $rvm_ruby_package_file. Aborting the installation."
             return $result
           fi
           ;;
         tar.bz2)
-          __rvm_run "extract" "bunzip2 < \"$rvm_archives_path/$rvm_ruby_package_file.$rvm_archive_extension\" | tar xf - -C /tmp/rvm_src_$$" "#extracting $rvm_ruby_package_file to $rvm_ruby_src_path"
+          __rvm_run "extract" "bunzip2 < \"$rvm_archives_path/$rvm_ruby_package_file.$rvm_archive_extension\" | tar xf - -C /tmp/rvm_src_$$" "$rvm_ruby_string - #extracting $rvm_ruby_package_file to $rvm_ruby_src_path"
           result=$?
 
           if [[ "$result" -gt 0 ]] ; then
-            "$rvm_scripts_path/log" "error" "There has been an error while trying to extract the source. Aborting the installation."
+            "$rvm_scripts_path/log" "error" \
+              "There has been an error while trying to extract the source. Aborting the installation."
             return $result
           fi
           ;;
         *)
-          "$rvm_scripts_path/log" "error" "Unknown archive format extension '$rvm_archive_extension'. Aborting the installation."
+          "$rvm_scripts_path/log" "error" \
+            "Unknown archive format extension '$rvm_archive_extension'. Aborting the installation."
           return 1
           ;;
       esac
@@ -1224,10 +1231,14 @@ __rvm_fetch_ruby() {
         mv "$rvm_src_path/$(echo "$rvm_ruby_string" | sed -e 's/-n.*//')" "$rvm_ruby_src_path"
       fi
 
+      "$rvm_ruby_string - #extracted to $rvm_ruby_src_path"
+
     else
-      "$rvm_scripts_path/log" "info" "#extracting $rvm_ruby_string to $rvm_ruby_src_path (already extracted)" ; return 0
+      "$rvm_scripts_path/log" "info" \
+        "$rvm_ruby_string - #extracted to $rvm_ruby_src_path (already extracted)"
     fi
 
+    return 0
   else
 
     mkdir -p "$rvm_repo_path"
@@ -1240,7 +1251,8 @@ __rvm_fetch_ruby() {
 
         if [[ -z "$rvm_ruby_revision" ]] ; then
 
-          "$rvm_scripts_path/log" "info" "Pulling from $rvm_ruby_repo_url, this may take a while depending on your connection..."
+          "$rvm_scripts_path/log" "info" \
+            "Pulling from $rvm_ruby_repo_url, this may take a while depending on your connection..."
 
           git pull origin master --force
 
@@ -1366,7 +1378,7 @@ __rvm_check_default() {
   local current_ruby_interpreter="$(echo "$rvm_ruby_string" | awk -F"${rvm_gemset_separator:-"@"}" '{print $1}')"
 
   if [[ -n "$current_ruby_interpreter" && "$current_ruby_interpreter" = "$default_ruby_interpreter" ]]; then
-    __rvm_run_with_env 'default.restore'  'system' 'rvm use system --default' 'Removing default ruby interpreter'
+    __rvm_run_with_env 'default.restore' 'system' 'rvm use system --default' 'Removing default ruby interpreter'
   fi
 }
 
@@ -1382,7 +1394,8 @@ __rvm_uninstall_ruby() {
 
         rm -rf $dir/$rvm_ruby_string
       else
-        "$rvm_scripts_path/log" "info" "$dir/$rvm_ruby_string has already been removed."
+        "$rvm_scripts_path/log" "info" \
+          "$dir/$rvm_ruby_string has already been removed."
       fi
 
       if [[ -e "$rvm_bin_path/$rvm_ruby_string" ]] ; then
@@ -1397,7 +1410,8 @@ __rvm_uninstall_ruby() {
     __rvm_check_default
 
   else
-    "$rvm_scripts_path/log" "fail" "Cannot uninstall unknown package '$rvm_ruby_string'"
+    "$rvm_scripts_path/log" "fail" \
+      "Cannot uninstall unknown package '$rvm_ruby_string'"
   fi
 
   unset rvm_uninstall_flag
@@ -1527,12 +1541,15 @@ __rvm_remove_binaries() {
 }
 
 __rvm_post_install() {
+
+  local rvm_ruby_aliases ruby_alias binary
+
   if [[ "$rvm_ruby_interpreter" != "jruby" ]] ; then
 
     binaries=${binaries:-(gem irb erb ri rdoc testrb rake)}
 
     "$rvm_scripts_path/log" "info" \
-      "#shebangs adjustment for $rvm_ruby_string ($binaries)."
+      "$rvm_ruby_string adjusting #shebangs for ($binaries)."
 
     for binary in "${binaries[@]}" ; do
 
@@ -1553,11 +1570,12 @@ __rvm_post_install() {
 
         chmod +x "$rvm_ruby_home/bin/$binary"
       fi
-    done ; unset binary binaries
+    done
+    unset binaries
   fi
 
   # Import the initial gemsets.
-  __rvm_run_with_env "gemsets.initial" "$rvm_ruby_string" "'$rvm_scripts_path/gemsets' initial" "#importing initial gems"
+  __rvm_run_with_env "gemsets.initial" "$rvm_ruby_string" "'$rvm_scripts_path/gemsets' initial" "$rvm_ruby_string - #importing default gemsets ($rvm_path/gemsets/)"
 
   __rvm_irbrc
 
@@ -1565,26 +1583,37 @@ __rvm_post_install() {
 
   if [[ -n "$rvm_ruby_aliases" ]]; then
     "$rvm_scripts_path/log" "info" "Setting up aliases for $rvm_ruby_string"
+
     while read -r ruby_alias; do
+
       "$rvm_scripts_path/log" info "Aliasing $rvm_ruby_string to $ruby_alias"
+
       "$rvm_scripts_path/alias" delete "$ruby_alias" > /dev/null 2>&1
+
       "$rvm_scripts_path/alias" create "$ruby_alias" "$rvm_ruby_string" > /dev/null 2>&1
+
     done < <(echo "$rvm_ruby_string" | \tr ' ' '\n' | sort -u)
-    unset rvm_ruby_aliases ruby_alias
   fi
 }
 
 __rvm_generate_default_docs() {
+
   if [[ "$rvm_docs_flag" = "1" && "$rvm_ruby_interpreter" != "macruby" ]]; then
+
     __rvm_run_with_env "docs.generate" "$rvm_ruby_string" "rvm docs generate-ri" "Attempting to generate ri documentation..."
   fi
 }
 
 __rvm_rubygems_setup() {
+
+  local home path dir directory_name version_number ruby_lib_gem_path
+
   if [[ -n "$(echo "$rvm_ruby_version" | awk '/^1\.9/')" ]] || [[ -n "$(echo "$rvm_ruby_interpreter" | awk '/^mput/')" ]] ; then
     install=0
+
   elif [[ "$rvm_ruby_string" = "ruby-head" ]] ; then
     install=0
+
   else
     install=1
   fi
@@ -1602,9 +1631,12 @@ __rvm_rubygems_setup() {
     home="$GEM_HOME" ; path="$GEM_PATH" # Save
 
     for dir in $rvm_ruby_global_gems_path $rvm_ruby_gem_home ; do
+
       export GEM_HOME="$dir" ; export GEM_PATH="$dir" ; export BUNDLE_PATH="$dir"
-      __rvm_run "rubygems.update" "$rvm_ruby_home/bin/gem update --system" "#rubygems update for $dir"
-    done ; unset home path dir
+
+      __rvm_run "rubygems.update" "$rvm_ruby_home/bin/gem update --system" "$rvm_ruby_string - updating #rubygems for $dir"
+
+    done
 
     GEM_HOME="$home" ; GEM_PATH="$path" ; BUNDLE_PATH="$home"
     export GEM_HOME GEM_PATH BUNDLE_PATH
@@ -1618,6 +1650,7 @@ __rvm_rubygems_setup() {
     version_number="${rvm_ruby_release_version}.${rvm_ruby_major_version}"
 
     if [[ "$version_number" == "." ]]; then
+
       # TODO: Investigate this if statement, something feels not quite right.
       version_number="$(builtin cd "$directory_name" ; find . -maxdepth 1 -mindepth 1 -type f | \grep '^[[:digit:]].[[:digit:]]\(.[[:digit:]]\)\?' | head -n1)"
       version_number="${version_number//.\/}"
@@ -1632,8 +1665,6 @@ __rvm_rubygems_setup() {
       ruby_lib_gem_path="${directory_name}/${version_number}"
     fi
 
-    unset directory_name version_number
-
   elif [[ -n "$(echo "$rvm_ruby_interpreter" | awk '/^rbx|jruby/')" ]] ; then
 
     # Hands off rubygems for rbx & jruby
@@ -1644,12 +1675,14 @@ __rvm_rubygems_setup() {
     ruby_lib_gem_path="$rvm_ruby_home/lib/ruby/gems/jruby"
 
   else
-    "$rvm_scripts_path/log" "info" "#rubygems installing to $rvm_ruby_string"
+    "$rvm_scripts_path/log" "info" "$rvm_ruby_string - #rubygems installing to $rvm_ruby_string"
+
     rvm_rubygems_version="$(__rvm_db "${rvm_ruby_interpreter}_rubygems_version")"
     rvm_rubygems_version="${rvm_rubygems_version:-"$(__rvm_db "rubygems_version")"}"
     rvm_rubygems_url=$(__rvm_db "rubygems_${rvm_rubygems_version}_url")
     rvm_gem_package_name="rubygems-$rvm_rubygems_version"
     rvm_gem_url="$rvm_rubygems_url/$rvm_gem_package_name.tgz"
+
     # Sanity check... If setup.rb is missing from the rubygems source path,
     # something went wrong. Cleanup, aisle 3!
     if [[ ! -f "$rvm_src_path/$rvm_gem_package_name/setup.rb" ]]; then
@@ -1657,12 +1690,19 @@ __rvm_rubygems_setup() {
     fi
 
     if [[ ! -d "$rvm_src_path/$rvm_gem_package_name" ]] ; then
+
       "$rvm_scripts_path/log" "info" "Retrieving $rvm_gem_package_name"
+
       "$rvm_scripts_path/fetch" "$rvm_gem_url"
-      result=$? ; if [[ "$result" -gt 0 ]] ; then
-        "$rvm_scripts_path/log" "error" "There has been an error while trying to fetch the source. Aborting the installation." ; return $result
+      result=$?
+
+      if [[ "$result" -gt 0 ]] ; then
+        "$rvm_scripts_path/log" "error" \
+          "There has been an error while trying to fetch the source. Aborting the installation." ; return $result
       fi
+
       mkdir -p "$rvm_src_path/$rvm_gem_package_name"
+
       __rvm_run "rubygems.extract" "gunzip < \"$rvm_archives_path/$rvm_gem_package_name.tgz\" | tar xf - -C $rvm_src_path" "Extracting $rvm_gem_package_name ..."
     fi
 
@@ -1671,7 +1711,7 @@ __rvm_rubygems_setup() {
     __rvm_run "rubygems.install" "GEM_PATH=$rvm_ruby_gem_path GEM_HOME=$rvm_ruby_gem_home BUNDLE_PATH=$rvm_ruby_gem_home $rvm_ruby_home/bin/ruby $rvm_src_path/$rvm_gem_package_name/setup.rb"
     result=$?
     if [[ $result -gt 0 ]] ; then
-      "$rvm_scripts_path/log" "warning" "#warning Installation of rubygems $rvm_ruby_package_name did not complete successfully."
+      "$rvm_scripts_path/log" "warning" "$rvm_ruby_string - #warning Installation of rubygems $rvm_ruby_package_name did not complete successfully."
     fi
 
     __rvm_inject_ruby_shebang "$rvm_ruby_home/bin/gem"
@@ -1687,14 +1727,14 @@ __rvm_rubygems_setup() {
     # Add ruby's gem path to ruby's lib direcotry.
 
     if [[ -d "$ruby_lib_gem_path" ]] ; then
-      \rm -rf "$ruby_lib_gem_path"
+      rm -rf "$ruby_lib_gem_path"
     fi
 
     mkdir -p ${ruby_lib_gem_path%\/*}
 
     ln -nfs "$rvm_ruby_gem_home" "$ruby_lib_gem_path"
 
-  fi; unset ruby_lib_gem_path
+  fi
 
   if [[ -s "$rvm_ruby_src_path/bin/rdoc" ]] ; then
     __rvm_inject_ruby_shebang "$rvm_ruby_src_path/bin/rdoc"
@@ -1708,28 +1748,44 @@ __rvm_rubygems_setup() {
 }
 
 __rvm_inject_ruby_shebang() {
+
+  local actual_file
+
   __rvm_actual_file $1
 
   if [[ -f "$actual_file" ]] ; then
     sed -e '1,1s=.*=#!'"/usr/bin/env ruby=" ${actual_file} > "${actual_file}.new"
+
     mv "${actual_file}.new" "${actual_file}" ; chmod +x "$actual_file"
-  fi ; unset actual_file
+  fi
 }
 
 __rvm_inject_gem_env() {
+
+  local actual_file string
+
   __rvm_actual_file $1
+
   if [[ -f "$actual_file" ]] ; then
+
     if [[ -n "$(head -n 1 $actual_file | awk '/[j]*ruby/')" ]] ; then
+
       string="ENV['GEM_HOME']=ENV['GEM_HOME'] || '$rvm_ruby_gem_home'\nENV['GEM_PATH']=ENV['GEM_PATH'] || '$rvm_ruby_gem_path'\nENV['PATH']='$rvm_ruby_gem_home/bin:$rvm_ruby_global_gems_path/bin:$rvm_ruby_home/bin:' + ENV['PATH']\nENV['BUNDLE_PATH']=ENV['BUNDLE_PATH'] || '$rvm_ruby_gem_home'\n"
+
     elif [[ -n "$(head -n 1 $actual_file | awk '/bash/')" ]] ; then
+
       string="GEM_HOME=\${GEM_HOME:-'$rvm_ruby_gem_home'}\nGEM_PATH=\${GEM_PATH:-'$rvm_ruby_gem_path'}\nPATH=$rvm_ruby_gem_home/bin:$rvm_ruby_global_gems_path/bin:$rvm_ruby_home/bin:\$PATH\nBUNDLE_PATH=\${BUNDLE_PATH:-'$rvm_ruby_gem_home'}\n"
+
     fi
+
     if [[ -n "$string" ]] ; then
+
       awk "NR==2 {print \"$string\"} {print}" "$actual_file" > "$actual_file.new"
+
       mv $actual_file.new $actual_file ; chmod +x "$actual_file"
-      unset string
+
     fi
-  fi ; unset actual_file
+  fi
 }
 
 __rvm_actual_file() {
