Made progress on IronRuby during coderpath interview.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -520,18 +520,18 @@ RubyWrapper
           if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
       else
         $rvm_scripts_path/log "info" "Retrieving IronRuby"
+
         $rvm_scripts_path/fetch "$rvm_url" "$rvm_ruby_package_file"
         result=$? ; if [[ "$result" -gt 0 ]] ; then
           $rvm_scripts_path/log "error" "There has been an error while trying to fetch the source. Aborting the installation." ; __rvm_pushpop ; return $result
         fi
 
-        __rvm_run "extract" "tar zxf $rvm_archives_path/$rvm_ruby_package_file -C $rvm_src_path" "Extracting $rvm_ruby_package_file ..."
-        result=$? ; if [[ "$result" -gt 0 ]] ; then
+        rm -rf "${rvm_src_path}/${rvm_ruby_string}/"
+        $rvm_scripts_path/log "info"  "Extracting $rvm_ruby_package_file ..."
+        unzip -o  -d ${rvm_src_path}/${rvm_ruby_string} ${rvm_archives_path}/${rvm_ruby_package_file} >> "$rvm_ruby_log_path/extract.log" 2>> "$rvm_ruby_log_path/extract.error.log"
+        result=$? ; if [[ "$result" -gt 1 ]] ; then
           $rvm_scripts_path/log "error" "There has been an error while trying to extract the source. Aborting the installation." ; __rvm_pushpop ; return $result
         fi
-
-        rm -rf $rvm_ruby_src_path
-        mv $rvm_src_path/$rvm_ruby_package_name $rvm_ruby_src_path
 
         #mv $rvm_ruby_home/ironruby/* $rvm_ruby_home
         #rm -rf $rvm_ruby_home/ironruby
