re-feature: Added back the sourcing of .profile if it exists. Began cleaning up bash scripts.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-if [[ "$rvm_trace_flag" -eq 1 ]] ; then set -x ; export rvm_trace_flag ; fi
+(( rvm_trace_flag )) &&  set -x && export rvm_trace_flag
 
 original_ruby_version=$rvm_ruby_version
 original_ruby_string=$rvm_ruby_string
@@ -10,26 +10,25 @@ source $rvm_scripts_path/rvm
 trap "rm -f $rvm_path/tmp/$$* > /dev/null 2>&1 ; exit" 0 1 2 3 15
 
 __rvm_install_source() {
-  if [[ -z "$rvm_ruby_selected_flag" ]] ; then __rvm_select $* ; fi
+  (( $rvm_ruby_selected_flag )) ||  __rvm_select $*
   $rvm_scripts_path/log "info" "Installing Ruby from source to: $rvm_ruby_home"
   mkdir -p "$rvm_ruby_log_path"
   __rvm_pushpop "$rvm_src_path"
   if [[ ! -z "$rvm_force_flag" ]] ; then rm -rf "$rvm_ruby_home" "$rvm_ruby_src_path" ; fi
 
   result=0
-  __rvm_fetch_ruby
-  if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+  __rvm_fetch_ruby || (result=$? && return $result)
 
-  builtin cd $rvm_ruby_src_path
-  if [[ $? -gt 0 ]] ; then result=$? ; $rvm_scripts_path/log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; __rvm_pushpop ; return $result ; fi
+  builtin cd $rvm_ruby_src_path || (result=$? ; $rvm_scripts_path/log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; __rvm_pushpop ; return $result)
 
   if [[ -d "${rvm_path}/usr/bin" ]] ; then export PATH="${rvm_path}/usr/bin:${PATH}" ; fi
 
   if [[ -z "$rvm_ruby_configure" ]] && [[ ! -s "$rvm_ruby_src_path/configure" ]] ; then
-    rvm_autoconf="$(which autoconf 2>/dev/null)"
-    if [[ $? -gt 0 ]] ; then $rvm_scripts_path/log "fail" "rvm expects autoconf" ; result=$? ; return $result ; fi
-    __rvm_run "autoconf" "$rvm_autoconf" "Running autoconf"
-    # if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi # Don't barf on autoconf fail...
+    if which -s autoconf ; then
+      __rvm_run "autoconf" "autoconf" "Running autoconf"
+    else
+      $rvm_scripts_path/log "fail" "rvm expects autoconf"  result=$? ; return $result
+    fi
   fi
 
   if [[ "1.8.5" = "$rvm_ruby_version" ]] ; then
@@ -45,11 +44,9 @@ __rvm_install_source() {
   if [[ -s ./Makefile ]] && [[ -z "$rvm_reconfigure_flag" ]] ; then
     (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "Skipping configure step, Makefile exists so configure must have already been run."
   elif [[ ! -z "$rvm_ruby_configure" ]] ; then
-    __rvm_run "configure" "$rvm_ruby_configure"
-    if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+    __rvm_run "configure" "$rvm_ruby_configure" || (result=$? && return $result)
   elif [[ -s ./configure ]] ; then
-    __rvm_run "configure" "./configure --prefix=$rvm_ruby_home $rvm_ruby_configure_flags $configure_parameters" "Configuring $rvm_ruby_string, this may take a while depending on your cpu(s)..."
-    if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+    __rvm_run "configure" "./configure --prefix=$rvm_ruby_home $rvm_ruby_configure_flags $configure_parameters" "Configuring $rvm_ruby_string, this may take a while depending on your cpu(s)..." || (result=$? && return $result)
     unset configure_parameters
   else
     $rvm_scripts_path/log "error" "Skipping configure step, 'configure' script does not exist, did autoconf not run successfully?"
@@ -62,12 +59,10 @@ __rvm_install_source() {
   fi
 
   rvm_ruby_make=${rvm_ruby_make:-"make"}
-  __rvm_run "make" "$rvm_ruby_make $rvm_make_flags" "Compiling $rvm_ruby_string, this may take a while, depending on your cpu(s)..."
-  if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+  __rvm_run "make" "$rvm_ruby_make $rvm_make_flags" "Compiling $rvm_ruby_string, this may take a while, depending on your cpu(s)..." || (result=$? && return $result)
 
   rvm_ruby_make_install=${rvm_ruby_make_install:-"make install"}
-  __rvm_run "install" "$rvm_ruby_make_install" "Installing $rvm_ruby_string"
-  if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+  __rvm_run "install" "$rvm_ruby_make_install" "Installing $rvm_ruby_string" || (result=$? && return $result)
 
   $rvm_scripts_path/log "info" "Installation of $rvm_ruby_string is complete."
 
@@ -83,8 +78,9 @@ __rvm_install_source() {
 
 __rvm_install_ruby() {
 
-  if [[ -z "$rvm_ruby_selected_flag" ]]  ; then __rvm_select $* ; fi
-  if [[ ! -z "$RUBYOPT" ]]     ; then ruby_options="$RUBYOPT" ; unset RUBYOPT ; fi
+  (( $rvm_ruby_selected_flag )) ||  __rvm_select $*
+
+  if [[ ! -z "$RUBYOPT" ]] ; then ruby_options="$RUBYOPT" ; unset RUBYOPT ; fi
 
   case "$rvm_ruby_interpreter" in
     macruby)
@@ -104,8 +100,7 @@ __rvm_install_ruby() {
           # TODO: Separated nightly from head.
           __rvm_db "macruby_nightly_url" "rvm_url"
           $rvm_scripts_path/log "info" "Retrieving the latest nightly macruby build..."
-          $rvm_scripts_path/fetch "$rvm_url"
-          result=$? ; if [[ "$result" -gt 0 ]] ; then return $result ; fi
+          $rvm_scripts_path/fetch "$rvm_url" || (result=$? && return $result)
           mv "$rvm_archives_path/macruby_nightly-latest.pkg" "$rvm_archives_path/macruby_nightly.pkg"
           __rvm_run "macruby/extract" "sudo installer -pkg '$rvm_path/archives/macruby_nightly.pkg' -target '/'"
           mkdir -p "$rvm_ruby_home/bin"
@@ -148,11 +143,9 @@ RubyWrapper
           $rvm_scripts_path/log "It appears that the archive has already been extracted. Skipping extract (use --force to force re-download and extract)."
         else
           $rvm_scripts_path/log "Downloading $rvm_ruby_package_file, this may take a while depending on your connection..."
-          $rvm_scripts_path/fetch "$rvm_url"
-          result=$? ; if [[ "$result" -gt 0 ]] ; then return $result ; fi
+          $rvm_scripts_path/fetch "$rvm_url" || (result=$? && return $result)
           rm -rf "$rvm_ruby_src_path"
-          __rvm_run "extract" "tar xzf $rvm_archives_path/$rvm_ruby_package_file.tar.gz -C $rvm_src_path" "Extracting $rvm_ruby_package_file..."
-          if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+          __rvm_run "extract" "tar xzf $rvm_archives_path/$rvm_ruby_package_file.tar.gz -C $rvm_src_path" "Extracting $rvm_ruby_package_file..." || (result=$? && return $result)
           mv "$rvm_src_path/$rvm_ruby_package_file" "$rvm_ruby_src_path"
         fi
         builtin cd "$rvm_ruby_src_path"
@@ -167,8 +160,7 @@ RubyWrapper
           rvm_ree_options="${rvm_ree_options} --no-tcmalloc"
         fi
 
-        __rvm_run "install" "./installer -a $rvm_path/$rvm_ruby_interpreter-$rvm_ruby_version-$rvm_ruby_patch_level $rvm_ree_options --dont-install-useful-gems $rvm_ruby_configure_flags" "Installing $rvm_ruby_string, this may take a while, depending on your cpu(s)..." # --no-tcmalloc
-        if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+        __rvm_run "install" "./installer -a $rvm_path/$rvm_ruby_interpreter-$rvm_ruby_version-$rvm_ruby_patch_level $rvm_ree_options --dont-install-useful-gems $rvm_ruby_configure_flags" "Installing $rvm_ruby_string, this may take a while, depending on your cpu(s)..." || (result=$? && return $result)
         chmod +x $rvm_ruby_home/bin/*
 
         __rvm_rubygems_setup
@@ -211,11 +203,9 @@ RubyWrapper
       if [[ ! -z "$(echo $rvm_ruby_version | awk '/^1\.0/')" ]] && [[ -z "$rvm_head_flag" ]] ; then
         if [[ ! -f "$rvm_archives_path/$rvm_ruby_package_file.tar.gz" ]] ; then
           $rvm_scripts_path/log "info" "Downloading $rvm_ruby_file, this may take a while depending on your connection..."
-          $rvm_scripts_path/fetch "$rvm_url"
-          result=$? ; if [[ "$result" -gt 0 ]] ; then return $result ; fi
+          $rvm_scripts_path/fetch "$rvm_url" || (result=$? && return $result)
         fi
-        __rvm_run "extract" "tar xzf $rvm_archives_path/$rvm_ruby_file.tar.gz -C $rvm_src_path" "Extracting $rvm_ruby_file.tar.gz ..."
-        if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+        __rvm_run "extract" "tar xzf $rvm_archives_path/$rvm_ruby_file.tar.gz -C $rvm_src_path" "Extracting $rvm_ruby_file.tar.gz ..." || (result=$? && return $result)
         mv $rvm_src_path/rubinius-$rvm_ruby_version $rvm_ruby_src_path
       else
         __rvm_db "rubinius_repo_url" "rvm_ruby_repo_url"
@@ -306,21 +296,17 @@ RubyWrapper
     ;;
 
     jruby)
-      if [[ -z "$(which java 2>/dev/null)" ]] ; then
+      if ! which -s java ; then
         echo -e "java must be installed and in your path in order to install JRuby." ; return 1
       fi
 
       mkdir -p "$rvm_ruby_log_path"  "$rvm_ruby_src_path"
       __rvm_pushpop $rvm_src_path
-
-      __rvm_fetch_ruby
-      if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
-
+      __rvm_fetch_ruby || (result=$? && return $result)
       __rvm_run "extract" "tar xzf $rvm_archives_path/$rvm_ruby_package_file.tar.gz -C $rvm_src_path" "Extracting $rvm_ruby_package_file ..."
-      if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
 
       builtin cd "$rvm_ruby_src_path"
-      if [[ "$rvm_head_flag" -eq 1 ]] || [[ ! -z "$rvm_ruby_revision" ]] ; then ant dist ; fi
+      (( $rvm_head_flag )) && (( $rvm_ruby_version )) && ant dist
 
       mkdir -p "$rvm_ruby_home/bin/"
       __rvm_run "nailgun" "builtin cd "$rvm_ruby_src_path/tool/nailgun" && ./configure --prefix=$rvm_ruby_home && make $rvm_make_flags"
@@ -352,13 +338,12 @@ RubyWrapper
     ;;
 
     ironruby|ir)
-      if [[ -z "$(which mono 2>/dev/null)" ]] ; then
+      if ! which -s mono ; then
         echo -e "mono must be installed and in your path in order to install IronRuby." ; return 1
       fi
 
       $rvm_scripts_path/log "info" "Retrieving IronRuby"
-      $rvm_scripts_path/fetch "$rvm_url"
-      result=$? ; if [[ "$result" -gt 0 ]] ; then return $result ; fi
+      $rvm_scripts_path/fetch "$rvm_url" || (result=$? && return $result)
 
       __rvm_run "extract" "unzip $rvm_archives_path/$rvm_ruby_package_file ironruby/bin/* ironruby/lib/* -d $rvm_ruby_home" "Extracting $rvm_ruby_package_file ..."
       mv $rvm_ruby_home/ironruby/* $rvm_ruby_home
@@ -415,10 +400,11 @@ RubyWrapper
       fi
 
       if [[ ! -s "$rvm_ruby_src_path/configure" ]] ; then
-          rvm_autoconf="$(which autoconf 2>/dev/null)"
-          if [[ $? -gt 0 ]] ; then $rvm_scripts_path/log "fail" "rvm expects autoconf" ; result=$? ; return $result ; fi
-          __rvm_run "autoconf" "$rvm_autoconf" "Running autoconf"
-          # if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi # Don't barf on autoconf fail...
+        if which -s autoconf ; then
+          __rvm_run "autoconf" "autoconf" "Running autoconf"
+        else
+          $rvm_scripts_path/log "fail" "rvm expects autoconf" ; result=$? ; return $result
+        fi
       fi
 
       if [[ -s ./Makefile ]] && [[ -z "$rvm_reconfigure_flag" ]] ; then
@@ -426,20 +412,17 @@ RubyWrapper
       elif [[ ! -z "rvm_ruby_configure" ]] ; then
           $rvm_ruby_configure
       elif [[ -s ./configure ]] ; then
-          __rvm_run "configure" "./configure --prefix=$rvm_ruby_home $rvm_ruby_configure_flags $configure_parameters" "Configuring $rvm_ruby_string using $rvm_ruby_configure_flags, this may take a while depending on your cpu(s)..."
-          if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+          __rvm_run "configure" "./configure --prefix=$rvm_ruby_home $rvm_ruby_configure_flags $configure_parameters" "Configuring $rvm_ruby_string using $rvm_ruby_configure_flags, this may take a while depending on your cpu(s)..." || (result=$? && return $result)
           unset configure_parameters
       else
           $rvm_scripts_path/log "error" "Skipping configure step, 'configure' script does not exist, did autoconf not run successfully?"
       fi
 
       rvm_ruby_make=${rvm_ruby_make:-"/usr/bin/make"}
-      __rvm_run "make" "$rvm_ruby_make $rvm_make_flags" "Compiling $rvm_ruby_string, this may take a while, depending on your cpu(s)..."
-      if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+      __rvm_run "make" "$rvm_ruby_make $rvm_make_flags" "Compiling $rvm_ruby_string, this may take a while, depending on your cpu(s)..." || (result=$? && return $result)
 
       rvm_ruby_make_install=${rvm_ruby_make_install:-"/usr/bin/make install"}
-      __rvm_run "install" "$rvm_ruby_make_install" "Installing $rvm_ruby_string"
-      if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+      __rvm_run "install" "$rvm_ruby_make_install" "Installing $rvm_ruby_string" || (result=$? && return $result)
 
       $rvm_scripts_path/log "info" "Installation of $rvm_ruby_string is complete."
 
@@ -470,7 +453,7 @@ RubyWrapper
 }
 
 __rvm_fetch_ruby() {
-  if [[ -z "$rvm_ruby_selected_flag" ]] ; then __rvm_select $* ; fi
+  (( $rvm_ruby_selected_flag )) ||  __rvm_select $*
 
   if [[ -z "$rvm_head_flag" ]] && [[ -z "$rvm_ruby_tag" ]] && [[ -z "$rvm_ruby_revision" ]] ; then
     rvm_ruby_package_name="${rvm_ruby_package_name:-"$rvm_ruby_string"}"
@@ -487,31 +470,26 @@ __rvm_fetch_ruby() {
         rvm_url="$(__rvm_db "${rvm_ruby_interpreter}_url")/$rvm_ruby_package_file.$rvm_archive_extension"
       fi
       $rvm_scripts_path/log "info" "Downloading $rvm_ruby_package_file, this may take a while depending on your connection..."
-      $rvm_scripts_path/fetch "$rvm_url"
-      result=$? ; if [[ "$result" -gt 0 ]] ; then return $result ; fi
+      $rvm_scripts_path/fetch "$rvm_url" || (result=$? && return $result)
     fi
-    __rvm_run "extract" "tar xzf $rvm_archives_path/$rvm_ruby_package_file.$rvm_archive_extension -C $rvm_src_path" "Extracting $rvm_ruby_package_file ..."
-    if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+    __rvm_run "extract" "tar xzf $rvm_archives_path/$rvm_ruby_package_file.$rvm_archive_extension -C $rvm_src_path" "Extracting $rvm_ruby_package_file ..." || (result=$? && return $result)
   else
     if [[ ! -z "$(echo $rvm_url | awk '/^git/')" ]] ; then
       if [[ -d "$rvm_ruby_src_path/.git" ]] ; then
         builtin cd $rvm_ruby_src_path
         if [[ -z "$rvm_ruby_revision" ]] ; then
           $rvm_scripts_path/log "info" "Pulling from $rvm_ruby_repo_url, this may take a while depending on your connection..."
-          git pull origin master
-          if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+          git pull origin master || (result=$? && return $result)
         else
           if [[ -z "$rvm_ruby_sha" ]] ; then
             git checkout HEAD
           else
             git checkout $(echo $rvm_ruby_sha | sed 's#^s##')
-          fi
-          if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+          fi || (result=$? && return $result)
         fi
       else
         $rvm_scripts_path/log "info" "Cloning from $rvm_ruby_repo_url, this may take a while depending on your connection..."
-        git clone --depth 1 $rvm_ruby_repo_url $rvm_ruby_src_path
-        if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+        git clone --depth 1 $rvm_ruby_repo_url $rvm_ruby_src_path || (result=$? && return $result)
       fi
     else
       if [[ ! -z "$rvm_head_flag" ]] || [[  "trunk" = "$rvm_ruby_revision" ]] ; then
@@ -537,14 +515,13 @@ __rvm_fetch_ruby() {
       else
         rm -rf $rvm_ruby_src_path
         __rvm_run "svn.checkout" "svn checkout -q ${rvm_rev/-r/-r } $rvm_url $rvm_ruby_src_path"
-      fi
-      if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
+      fi || (result=$? && return $result)
     fi
   fi
 }
 
 __rvm_uninstall_ruby() {
-  if [[ -z "$rvm_ruby_selected_flag" ]] ; then __rvm_select $* ; fi
+  (( $rvm_ruby_selected_flag )) ||  __rvm_select $*
 
   if [[ ! -z "$rvm_ruby_string" ]] ; then
     for dir in $rvm_path ; do
@@ -561,11 +538,11 @@ __rvm_uninstall_ruby() {
     rm -rf $rvm_gem_path/$rvm_ruby_interpreter/$rvm_ruby_version*/
   else
     $rvm_scripts_path/log "fail" "Cannot uninstall unknown package '$rvm_ruby_string'"
-  fi
+  fi ; unset rvm_uninstall_flag
 }
 
 __rvm_remove_ruby() {
-  if [[ -z "$rvm_ruby_selected_flag" ]] ; then __rvm_select ; fi
+  (( $rvm_ruby_selected_flag )) ||  __rvm_select $*
 
   if [[ ! -z "$rvm_ruby_string" ]] ; then
     for dir in $rvm_src_path $rvm_path ; do
@@ -581,7 +558,7 @@ __rvm_remove_ruby() {
     done ; unset dir
   else
     $rvm_scripts_path/log "fail" "Cannot uninstall unknown package '$rvm_ruby_string'"
-  fi
+  fi ; unset rvm_remove_flag
 }
 
 __rvm_post_install() {
@@ -638,8 +615,7 @@ __rvm_rubygems_setup() {
     if [[ ! -f "$rvm_src_path/$rvm_gem_package_name/setup.rb" ]]; then rm -rf "$rvm_src_path/$rvm_gem_package_name" ; fi
     if [[ ! -d "$rvm_src_path/$rvm_gem_package_name" ]] ; then
       $rvm_scripts_path/log "info" "Retrieving $rvm_gem_package_name"
-      $rvm_scripts_path/fetch "$rvm_gem_url"
-      result=$? ; if [[ "$result" -gt 0 ]] ; then return $result ; fi
+      $rvm_scripts_path/fetch "$rvm_gem_url" || (result=$? && return $result)
       mkdir -p "$rvm_src_path/$rvm_gem_package_name"
       __rvm_run "rubygems.extract" "tar zxf $rvm_archives_path/$rvm_gem_package_name.tgz -C $rvm_src_path" "Extracting $rvm_gem_package_name"
     fi
@@ -682,7 +658,7 @@ __rvm_inject_gem_env() {
 }
 
 __rvm_actual_file() {
-  if [[ -L $1 ]] ; then         # If the file is a symlink,
+  if [[ -L $1 ]] ; then          # If the file is a symlink,
     actual_file="$(readlink $1)" # read the link target so we can preserve it.
   else
     actual_file="$1"
@@ -690,9 +666,10 @@ __rvm_actual_file() {
 }
 
 __rvm_manage_rubies() {
-  #__rvm_state
   rubies=() ; successes=() ; errors=() ; statuses=()
+
   unset rvm_gem_set_name rvm_ruby_selected_flag
+
   rvm_ruby_gem_home=$(echo $rvm_ruby_gem_home | awk -F'%' '{print $1}')
   rvm_ruby_string=$(echo $rvm_ruby_string | awk -F'%' '{print $1}')
 
@@ -725,11 +702,10 @@ __rvm_manage_rubies() {
       $rvm_scripts_path/log "warn" 'Really? Install all? See "rvm list --all" and limit the selection to something more sane please :)'
     fi
   fi
-  #__rvm_state
 
-  if [[ ! -z "$rvm_summary_flag" ]] ; then __rvm_summary ; fi
-  if [[ ! -z "$rvm_yaml_flag" ]]   ; then __rvm_yaml    ; fi
-  if [[ ! -z "$rvm_json_flag" ]]   ; then __rvm_json    ; fi
+  (( $rvm_summary_flag )) && __rvm_summary
+  (( $rvm_yaml_flag ))    && __rvm_yaml
+  (( $rvm_json_flag ))    && __rvm_json
 }
 
 rvm_action="$1" ; rubies_string="$2"
