Added an ERROR message with an exit when JAVA 1.3 / 1.4 detected for jruby install

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -714,8 +714,12 @@ RubyWrapper
       if [[ "Darwin" = "$(uname)" ]] ; then
         java_version=$(java -version 2>&1  | awk -F'"' '/ version /{print $2}')
         case "$java_version" in
-          1.4.*|1.5.*)
-            printf "\n\nWARNING: A very outdated JAVA version is being used ($java_version), it is strongly recommended that you upgrade to the latest version before using JRuby.\n\n"
+          1.5.*)
+            printf "\n\nWARNING: A very outdated JAVA version is being used ($java_version), it is strongly recommended that you upgrade to the latest version.\n\n"
+            ;;
+          1.3.*|1.4.*)
+            printf "\n\nERROR: Unsupported JAVA version $java_version. In order to install and use JRuby you must upgrade to the latest JAVA version.\n\n"
+            exit 1
             ;;
         esac
       fi
