Install now exits on failed patch. Error command output tweaked.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -69,7 +69,10 @@ __rvm_install_source() {
 
   if [[ ! -z "$rvm_ruby_patch" ]] ; then
     for patch in $(echo $rvm_ruby_patch | tr ',' ' ') ; do
-      patch -p0 -f < $patch
+      __rvm_run "patch" "patch -p0 -f < $patch" "Applying patch '$patch'..."
+      if [[ $? -gt 0 ]] ; then
+        $rvm_scripts_path/log "error" "Patch $patch did not apply cleanly... back to the patching board :(" ; exit 1
+      fi
     done
   fi
 
diff --git a/scripts/utility b/scripts/utility
--- a/scripts/utility
+++ b/scripts/utility
@@ -139,7 +139,7 @@ __rvm_run() {
   else
     eval "nice -n $rvm_niceness $command" >> $rvm_ruby_log_path/$log_file_name.log 2>> $rvm_ruby_log_path/$log_file_name.error.log
   fi
-  if [[ $? -gt 0 ]] ; then $rvm_scripts_path/log "error" "Error running '$command', please check $rvm_ruby_log_path/$log_file_name.error.log" ; __rvm_pushpop ; return 1 ; fi
+  if [[ $? -gt 0 ]] ; then $rvm_scripts_path/log "error" "Error running '$command', please check $rvm_ruby_log_path/$log_file_name*.log" ; __rvm_pushpop ; return 1 ; fi
   unset log_file command
 }
 
