Only extract gemstone on head.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -411,9 +411,11 @@ RubyWrapper
 
       builtin cd "$rvm_ruby_src_path"
 
-      __rvm_run "gemstone.extract" "unzip -q -o $rvm_archives_path/$rvm_gemstone_package_file -d $rvm_ruby_src_path"
-      result=$? ; if [[ "$result" -gt 0 ]] ; then
-        $rvm_scripts_path/log "error" "There has been an error while trying to extract the gemstone package. Aborting the installation." ; __rvm_pushpop ; return $result
+      if [[ "$rvm_head_flag" -eq 1 ]] ; then
+        __rvm_run "gemstone.extract" "unzip -q -o $rvm_archives_path/$rvm_gemstone_package_file -d $rvm_ruby_src_path"
+        result=$? ; if [[ "$result" -gt 0 ]] ; then
+          $rvm_scripts_path/log "error" "There has been an error while trying to extract the gemstone package. Aborting the installation." ; __rvm_pushpop ; return $result
+        fi
       fi
 
       mv "$rvm_gemstone_package_file" "gemstone"
