Switched tar extractions to work on Solaris. Updated install doc.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -176,7 +176,8 @@ RubyWrapper
           fi
 
           rm -rf "$rvm_ruby_src_path"
-          __rvm_run "extract" "tar xzf $rvm_archives_path/$rvm_ruby_package_file.tar.gz -C $rvm_src_path" "Extracting $rvm_ruby_package_file..."
+          __rvm_run "extract" "cat $rvm_archives_path/$rvm_ruby_package_file.$rvm_archive_extension | gunzip | tar xzf - -C $rvm_src_path" "Extracting $rvm_ruby_package_file ..."
+
           result=$? ; if [[ "$result" -gt 0 ]] ; then
             $rvm_scripts_path/log "error" "There has been an error while trying to extract the source. Aborting the installation." ; __rvm_pushpop ; return $result
           fi
@@ -249,10 +250,11 @@ RubyWrapper
             $rvm_scripts_path/log "error" "There has been an error while trying to fetch the source. Aborting the installation." ; __rvm_pushpop ; return $result
           fi
         fi
-        __rvm_run "extract" "tar xzf $rvm_archives_path/$(basename $rvm_url) -C $rvm_src_path" "Extracting $(basename $rvm_url) ..."
-          result=$? ; if [[ "$result" -gt 0 ]] ; then
-            $rvm_scripts_path/log "error" "There has been an error while trying to extract the source. Aborting the installation." ; __rvm_pushpop ; return $result
-          fi
+        __rvm_run "extract" "cat $rvm_archives_path/$(basename $rvm_url) | gunzip | tar xzf - -C $rvm_src_path" "Extracting $rvm_ruby_package_file ..."
+
+        result=$? ; if [[ "$result" -gt 0 ]] ; then
+          $rvm_scripts_path/log "error" "There has been an error while trying to extract the source. Aborting the installation." ; __rvm_pushpop ; return $result
+        fi
         mv "$rvm_src_path/rubinius-$rvm_ruby_version-${rvm_ruby_patch_level/^p//}" $rvm_ruby_src_path
       else
         __rvm_db "rubinius_repo_url" "rvm_ruby_repo_url"
@@ -412,7 +414,7 @@ RubyWrapper
       builtin cd "$rvm_ruby_src_path"
 
       if [[ "$rvm_head_flag" -eq 1 ]] ; then
-        __rvm_run "gemstone.extract" "unzip -q -o $rvm_archives_path/$rvm_gemstone_package_file -d $rvm_ruby_src_path"
+        __rvm_run "gemstone.extract" "cat $rvm_archives_path/$rvm_gemstone_package_file | gunzip | tar xzf - -C $rvm_ruby_src_path"
         result=$? ; if [[ "$result" -gt 0 ]] ; then
           $rvm_scripts_path/log "error" "There has been an error while trying to extract the gemstone package. Aborting the installation." ; __rvm_pushpop ; return $result
         fi
@@ -650,8 +652,8 @@ __rvm_fetch_ruby() {
 
     # Only re-extract if forced.
     if [[ ! -d "$rvm_src_path/$rvm_ruby_string" ]] || [[ ! -z "$rvm_force_flag" ]] ; then
-      if [[ "tar.gz" = "$rvm_archive_extension" ]] ; then
-        __rvm_run "extract" "tar xzf $rvm_archives_path/$rvm_ruby_package_file.$rvm_archive_extension -C $rvm_src_path" "Extracting $rvm_ruby_package_file ..."
+      if [[ "tar.gz" = "$rvm_archive_extension" ]] || [[ "tgz" = "$rvm_archive_extension" ]] ; then
+        __rvm_run "extract" "cat $rvm_archives_path/$rvm_ruby_package_file.$rvm_archive_extension | gunzip | tar xzf - -C $rvm_src_path" "Extracting $rvm_ruby_package_file ..."
         result=$? ; if [[ "$result" -gt 0 ]] ; then
           $rvm_scripts_path/log "error" "There has been an error while trying to extract the source. Aborting the installation." ; __rvm_pushpop ; return $result
         fi
@@ -827,7 +829,7 @@ __rvm_rubygems_setup() {
         $rvm_scripts_path/log "error" "There has been an error while trying to fetch the source. Aborting the installation." ; __rvm_pushpop ; return $result
       fi
       mkdir -p "$rvm_src_path/$rvm_gem_package_name"
-      __rvm_run "rubygems.extract" "tar zxf $rvm_archives_path/$rvm_gem_package_name.tgz -C $rvm_src_path" "Extracting $rvm_gem_package_name"
+      __rvm_run "rubygems.extract" "cat $rvm_archives_path/$rvm_gem_package_name.tgz | gunzip | tar xzf - -C $rvm_src_path" "Extracting $rvm_gem_package_name ..."
     fi
     builtin cd "$rvm_src_path/$rvm_gem_package_name"
     __rvm_run "rubygems.install" "GEM_PATH=$rvm_gem_path GEM_HOME=$rvm_ruby_gem_home $rvm_ruby_home/bin/ruby $rvm_src_path/$rvm_gem_package_name/setup.rb" "Installing rubygems for $rvm_ruby_home/bin/ruby"
