Tweak bison detection.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -15,12 +15,18 @@ __rvm_check_for_clang() {
 
 # Checks for bison, returns zero iff it is found
 __rvm_check_for_bison() {
+  local result
+
   if [[ ${rvm_head_flag:-0} -gt 0 ]]; then
-    if ! command -v bison >/dev/null ; then
-      "$rvm_scripts_path/log" "fail" "\nbison is not available in your path. \nPlease ensure bison is installed before compiling from head.\n"
-      return 1
+    command -v bison > /dev/null
+    result=$?
+    if [[ $? -gt 0 ]] ; then
+      "$rvm_scripts_path/log" "fail" \
+        "\nbison is not available in your path. \nPlease ensure bison is installed before compiling from head.\n"
     fi
   fi
+
+  return $result
 }
 
 # Emits a number of patches to STDOUT, each on a new name
@@ -1038,9 +1044,7 @@ RubyWrapper
     ruby)
 
       __rvm_check_for_bison # && Run like hell...
-      result=$?
-
-      if [[ "$result" -gt 0 ]] ; then return $result ; fi
+      if [[ $? -gt 0 ]] ; then return $result ; fi
 
       if [[ ${rvm_make_flags_flag:-0} -eq 1 ]] ; then __rvm_make_flags ; fi
 
