Only download gemstone for -head version.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -397,10 +397,12 @@ RubyWrapper
         fi
       fi
 
-      $rvm_scripts_path/log "info" "Downloading the gemstone package, this may take a while depending on your connection..."
-      $rvm_scripts_path/fetch "$rvm_gemstone_url"
-      result=$? ; if [[ "$result" -gt 0 ]] ; then
-        $rvm_scripts_path/log "error" "There has been an error while trying to fetch the gemstone package. Aborting the installation." ; __rvm_pushpop ; return $result
+      if [[ "$rvm_head_flag" -eq 1 ]] ; then
+        $rvm_scripts_path/log "info" "Downloading the gemstone package, this may take a while depending on your connection..."
+        $rvm_scripts_path/fetch "$rvm_gemstone_url"
+        result=$? ; if [[ "$result" -gt 0 ]] ; then
+          $rvm_scripts_path/log "error" "There has been an error while trying to fetch the gemstone package. Aborting the installation." ; __rvm_pushpop ; return $result
+        fi
       fi
 
       builtin cd "$rvm_src_path"
@@ -415,6 +417,7 @@ RubyWrapper
       fi
 
       mv "$rvm_gemstone_package_file" "gemstone"
+      chmod -R 777 gemstone # for now.
 
       __rvm_pushpop
 
