Make that more of a sanity check until I track this bug.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -59,10 +59,12 @@ __rvm_apply_patches() {
     fi
     full_patch_path="$(__rvm_lookup_full_patch_path "$patch_name")"
     # Expand paths, and for those we found we then apply the patches.
-    if [[ -f "$full_patch_path" ]]; then
-      __rvm_run "patch.apply.${patch_name/*\/}" "patch -F$patch_fuzziness -p$patch_level -f <\"$full_patch_path\"" "Applying patch '$patch_name' (located at $full_patch_path)"
-      # Detect failed patches
-      [[ "$?" -gt 0 ]] && patch_result=1
+    if [[ -n "$full_patch_path" ]]; then
+      if [[ -f "$full_patch_path" ]] ; then
+        __rvm_run "patch.apply.${patch_name/*\/}" "patch -F$patch_fuzziness -p$patch_level -f <\"$full_patch_path\"" "Applying patch '$patch_name' (located at $full_patch_path)"
+        # Detect failed patches
+        [[ "$?" -gt 0 ]] && patch_result=1
+      fi
     else
       "$rvm_scripts_path/log" "warn" "Patch '$patch_name' not found."
       patch_result=1
