Feature: --branch for use with git head repositories.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -1419,6 +1419,31 @@ __rvm_fetch_ruby()
         fi
       fi
 
+      if [[ -z "$rvm_ruby_repo_branch" ]]; then
+        rvm_ruby_repo_branch="master"
+      fi
+
+      (
+        remote="origin"
+
+        cd "${rvm_repos_path:-"$rvm_path/repos"}/$rvm_ruby_string"
+
+        if [[ -z "$(git branch | awk "/$rvm_ruby_repo_branch$/")" ]] ; then
+
+          git checkout -b "$rvm_ruby_repo_branch" --track "$remote/$rvm_ruby_repo_branch" 2>/dev/null
+
+        elif [[ -z "$(git branch | awk "/\* $rvm_ruby_repo_branch$/")" ]] ; then
+
+          if ! git checkout $rvm_ruby_repo_branch 2>/dev/null ; then
+
+            "$rvm_path/scripts/log" "error" \
+              "Branch $remote/$rvm_ruby_repo_branch not found."
+
+          fi
+
+        fi
+      )
+
     else
       if [[ -n "${rvm_ruby_tag:-""}" ]] ; then
         # TODO: Check if tag v is valid
