Check for bison when installing ruby head

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -11,6 +11,18 @@ trap "rm -rf ${rvm_tmp_path}/$$* > /dev/null 2>&1 ; exit" 0 1 2 3 15
 
 if [[ ! -z "$rvm_trace_flag" ]] ; then set -x ; export rvm_trace_flag ; fi
 
+# Checks for bison, returns zero iff it is found
+__rvm_check_for_bison() {
+  if [[ "$rvm_head_flag" -gt 0 ]]; then
+    command -v bison >/dev/null
+    if [[ "$?" -gt 0 ]]; then
+      $rvm_scripts_path/log "fail" "bison is not available in your path. Please ensure it exists before compiling from head."
+      printf "\n"
+      return 1
+    fi
+  fi
+}
+
 __rvm_install_source() {
   if [[ -z "$rvm_ruby_selected_flag" ]] ; then __rvm_select ; fi
 
@@ -670,6 +682,7 @@ RubyWrapper
     ;;
 
     ruby)
+      __rvm_check_for_bison
       if [[ "rvm_make_flags_flag" -eq 1 ]] ; then __rvm_make_flags ; fi
       __rvm_install_source $*
     ;;
