Added some exit points to rbx install for error cases.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -253,7 +253,6 @@ RubyWrapper
           result=$? ; if [[ "$result" -gt 0 ]] ; then
             $rvm_scripts_path/log "error" "There has been an error while trying to extract the source. Aborting the installation." ; __rvm_pushpop ; return $result
           fi
-
         mv "$rvm_src_path/rubinius-$rvm_ruby_version-${rvm_ruby_patch_level/^p//}" $rvm_ruby_src_path
       else
         __rvm_db "rubinius_repo_url" "rvm_ruby_repo_url"
@@ -265,6 +264,9 @@ RubyWrapper
         else
           builtin cd "$rvm_ruby_src_path"
           __rvm_run "rbx.repo" "git pull origin master" "Pulling from origin master"
+        fi
+        result=$? ; if [[ "$result" -gt 0 ]] ; then
+          $rvm_scripts_path/log "error" "There has been an error while fetching the rbx git repo. Aborting the installation." ; __rvm_pushpop ; return $result
         fi
       fi
 
@@ -283,6 +285,9 @@ RubyWrapper
         fi
       fi
       __rvm_run "configure" "$rvm_ruby_configure" "$message"
+      result=$? ; if [[ "$result" -gt 0 ]] ; then
+        $rvm_scripts_path/log "error" "There has been an error while running '$rvm_ruby_configure'. Aborting the installation." ; __rvm_pushpop ; return $result
+      fi
 
       if [[ "$rvm_trace_flag" -eq 1 ]] ; then
         rvm_ruby_make="$rvm_bin_path/rvm 1.8.7 rake install --trace" ; message="Compiling rbx"
@@ -290,6 +295,9 @@ RubyWrapper
         rvm_ruby_make="$rvm_bin_path/rvm 1.8.7 rake install" ; message="Compiling rbx"
       fi
       __rvm_run "rake" "$rvm_ruby_make" "$message"
+      result=$? ; if [[ "$result" -gt 0 ]] ; then
+        $rvm_scripts_path/log "error" "There has been an error while running '$rvm_ruby_configure'. Aborting the installation." ; __rvm_pushpop ; return $result
+      fi
 
       binaries="ruby irb" # Trick to work in more shells :)
       for binary_name in $(echo $binaries) ; do
