Bugfix: 'rvm install rbx' now properly downloads the source when the archive is not correct.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -267,12 +267,10 @@ RubyWrapper
       PATH=$rvm_bin_path:$PATH ; export PATH
 
       if [[ ! -z "$(echo $rvm_ruby_version | awk '/^1\.0/')" ]] && [[ -z "$rvm_head_flag" ]] ; then
-        if [[ ! -f "$rvm_archives_path/$rvm_ruby_package_file" ]] ; then
-          $rvm_scripts_path/log "info" "Downloading $rvm_ruby_file, this may take a while depending on your connection..."
-          $rvm_scripts_path/fetch "$rvm_url"
-          result=$? ; if [[ "$result" -gt 0 ]] ; then
-            $rvm_scripts_path/log "error" "There has been an error while trying to fetch the source. Aborting the installation." ; __rvm_pushpop ; return $result
-          fi
+        $rvm_scripts_path/log "info" "Downloading $rvm_ruby_file, this may take a while depending on your connection..."
+        $rvm_scripts_path/fetch "$rvm_url"
+        result=$? ; if [[ "$result" -gt 0 ]] ; then
+          $rvm_scripts_path/log "error" "There has been an error while trying to fetch the source. Aborting the installation." ; __rvm_pushpop ; return $result
         fi
         __rvm_run "extract" "cat $rvm_archives_path/$(basename $rvm_ruby_package_file) | gunzip | tar xf - -C $rvm_src_path" "Extracting $rvm_ruby_package_file ..."
 
