FIX: missing codes to apply patches
I made some mistake while merging original master code.

diff --git a/scripts/package b/scripts/package
--- a/scripts/package
+++ b/scripts/package
@@ -60,6 +60,15 @@ install_package()
 
     builtin cd "$src_path/$package-$version"
 
+    if [[ ! -z "$patches" ]] ; then
+      for patch in $(echo $patches | tr ',' ' ') ; do
+        __rvm_run "$package/patch" "patch -p0 -f < $patch" "Applying patch '$patch'..."
+        if [[ $? -gt 0 ]] ; then
+          $rvm_scripts_path/log "error" "Patch $patch did not apply cleanly... back to the patching board :(" ; exit 1
+        fi
+      done
+    fi
+
     __rvm_run "$package/configure" \
       "${configure:-"./configure --prefix=${prefix_path:-"$usr_path"}"} $configure_flags" \
       "Configuring $package in $src_path/$package-$version."
