Rounded out new package feature.

diff --git a/scripts/package b/scripts/package
--- a/scripts/package
+++ b/scripts/package
@@ -7,11 +7,10 @@
 source $rvm_scripts_path/initialize
 source $rvm_scripts_path/utility
 
-action=$1 ; shift ; library=$1 ; shift ; args="$*"
+trap "rm -f $rvm_tmp_path/$$* > /dev/null 2>&1 ; exit" 0 1 2 3 15
+if [[ ! -z "$rvm_trace_flag" ]] ; then set -x ; export rvm_trace_flag ; fi
 
-if [[ -z "$action" ]] ; then
-  echo "Usage: package {install,uninstall} {openssl,zlib,readline,iconv,ncurses}"
-fi
+action="$1" ; shift ; library="$1" ; shift ; args="$*"
 
 install_package() {
 
@@ -140,6 +139,12 @@ llvm() {
   __rvm_pushpop
 }
 
-
-${action}
-
+if [[ ! -z "$library" ]] && is_a_function  ${library} ; then
+  ${library}
+else
+  if [[ ! -z "$library" ]] ; then
+    $rvm_scripts_path/log "error" "Package '${library}' is unknown."
+  fi
+  $rvm_scripts_path/log "info" "Usage: 'rvm package {install,uninstall} {openssl,zlib,readline,iconv,ncurses}'"
+  exit 1
+fi
