Rubygems 1.4.1

diff --git a/scripts/rubygems b/scripts/rubygems
--- a/scripts/rubygems
+++ b/scripts/rubygems
@@ -36,7 +36,7 @@ rubygems_setup()
 
     rubygems_dir="$(ruby -rrbconfig -e "puts Config::CONFIG.values_at('sitelibdir','vendorlibdir').detect {|path| File.directory?(File.join(path, 'rubygems')) }.to_s")"
 
-    if [[ -n "$rubygems_dir" && -d "$rubygems_dir" ]]; then
+    if [[ -n "$rubygems_dir" && -d "$rubygems_dir" ]] ; then
 
       # Remove common files installed by ruby gems.
       \rm -rf "${rubygems_dir}/ubygems.rb" "${rubygems_dir}/rubygems.rb" \
@@ -44,7 +44,8 @@ rubygems_setup()
 
     fi
 
-    "$rvm_path/scripts/log" "info" "Installing rubygems dedicated to $rvm_ruby_string..."
+    "$rvm_path/scripts/log" "info" \
+      "Installing rubygems dedicated to $rvm_ruby_string..."
 
     rvm_rubygems_version="$version"
     rvm_gem_package_name="rubygems-$rvm_rubygems_version"
@@ -149,6 +150,15 @@ if [[ "$version" = "current" ]]; then
   version="$(__rvm_db "${rvm_ruby_interpreter}_rubygems_version")"
 
   version="${rvm_rubygems_version:-"$(__rvm_db "rubygems_version")"}"
+
+fi
+
+if ! command -v ruby | grep -q "rvm" ; then
+
+  "$rvm_path/scripts/log" "error" \
+    "Rubygems version may only be set for an RVM MRI based Ruby, please select one and rerun."
+
+  exit 1
 
 fi
 
