Significantly cut down on trace noise.

diff --git a/scripts/ruby-installer b/scripts/ruby-installer
--- a/scripts/ruby-installer
+++ b/scripts/ruby-installer
@@ -2,7 +2,7 @@
 
 __rvm_install_source() {
   if [[ -z "$rvm_ruby_selected_flag" ]] ; then __rvm_select $* ; fi
-  __rvm_log "info" "Installing Ruby from source to: $rvm_ruby_home"
+  $rvm_scripts_path/log "info" "Installing Ruby from source to: $rvm_ruby_home"
   mkdir -p "$rvm_ruby_log_path"
 
   __rvm_pushpop "$rvm_src_path"
@@ -16,7 +16,7 @@ __rvm_install_source() {
   if [[ -z "$rvm_head_flag" ]] && [[ -z "$rvm_ruby_tag" ]] && [[ -z "$rvm_ruby_revision" ]] ; then
     if [[ ! -f "$rvm_archives_path/$rvm_ruby_package_name.tar.gz" ]] ; then
       rvm_url="${rvm_url:-"ftp://ftp.ruby-lang.org/pub/ruby/1.$rvm_major_version/$rvm_ruby_package_name.tar.gz"}"
-      __rvm_log "info" "Downloading $rvm_ruby_package_name, this may take a while depending on your connection..."
+      $rvm_scripts_path/log "info" "Downloading $rvm_ruby_package_name, this may take a while depending on your connection..."
       __rvm_fetch "$rvm_url"
       if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
     fi
@@ -28,7 +28,7 @@ __rvm_install_source() {
       if [[ -d "$rvm_ruby_src_path/.git" ]] ; then
         cd $rvm_ruby_src_path
         if [[ -z "$rvm_ruby_revision" ]] ; then
-          __rvm_log "info" "Pulling from $rvm_ruby_repo_url, this may take a while depending on your connection..."
+          $rvm_scripts_path/log "info" "Pulling from $rvm_ruby_repo_url, this may take a while depending on your connection..."
           git pull origin master
           if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
         else
@@ -40,7 +40,7 @@ __rvm_install_source() {
           if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
         fi
       else
-        __rvm_log "info" "Cloning from $rvm_ruby_repo_url, this may take a while depending on your connection..."
+        $rvm_scripts_path/log "info" "Cloning from $rvm_ruby_repo_url, this may take a while depending on your connection..."
         git clone --depth 1 $rvm_ruby_repo_url $rvm_ruby_src_path
         if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
       fi
@@ -59,10 +59,10 @@ __rvm_install_source() {
 
       if [[ -d "$rvm_ruby_src_path/.svn" ]] ; then
         cd $rvm_ruby_src_path
-        __rvm_log "info" "Updating ruby from $rvm_url"
+        $rvm_scripts_path/log "info" "Updating ruby from $rvm_url"
         __rvm_run "svn.update" "svn update"
         if [[ ! -z "$rvm_rev" ]] ; then
-          __rvm_log "info" "Checking out revision ${rvm_rev/-r/-r } from $rvm_url"
+          $rvm_scripts_path/log "info" "Checking out revision ${rvm_rev/-r/-r } from $rvm_url"
           __rvm_run "svn.checkout" "svn update -q ${rvm_rev/-r/-r }"
         fi
       else
@@ -74,17 +74,17 @@ __rvm_install_source() {
   fi
 
   cd $rvm_ruby_src_path
-  if [[ $? -gt 0 ]] ; then result=$? ; __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; __rvm_pushpop ; return $result ; fi
+  if [[ $? -gt 0 ]] ; then result=$? ; $rvm_scripts_path/log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; __rvm_pushpop ; return $result ; fi
 
   if [[ -z "$rvm_ruby_configure" ]] && [[ ! -s "$rvm_ruby_src_path/configure" ]] ; then
     rvm_autoconf="$(which autoconf)"
-    if [[ $? -gt 0 ]] ; then __rvm_log "fail" "rvm expects autoconf" ; result=$? ; return $result ; fi
+    if [[ $? -gt 0 ]] ; then $rvm_scripts_path/log "fail" "rvm expects autoconf" ; result=$? ; return $result ; fi
     __rvm_run "autoconf" "$rvm_autoconf" "Running autoconf"
     # if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi # Don't barf on autoconf fail...
   fi
 
   if [[ -s ./Makefile ]] && [[ -z "$rvm_reconfigure_flag" ]] ; then
-    __rvm_log "debug" "Skipping configure step, Makefile exists so configure must have already been run."
+    (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "Skipping configure step, Makefile exists so configure must have already been run."
   elif [[ ! -z "$rvm_ruby_configure" ]] ; then
     __rvm_run "configure" "$rvm_ruby_configure"
     if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
@@ -93,7 +93,7 @@ __rvm_install_source() {
     if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
     unset configure_parameters
   else
-    __rvm_log "error" "Skipping configure step, 'configure' script does not exist, did autoconf not run successfully?"
+    $rvm_scripts_path/log "error" "Skipping configure step, 'configure' script does not exist, did autoconf not run successfully?"
   fi
 
   rvm_ruby_make=${rvm_ruby_make:-"/usr/bin/make"}
@@ -104,7 +104,7 @@ __rvm_install_source() {
   __rvm_run "install" "$rvm_ruby_make_install" "Installing $rvm_ruby_package_name"
   if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
 
-  __rvm_log "info" "Installation of $rvm_ruby_package_name is complete."
+  $rvm_scripts_path/log "info" "Installation of $rvm_ruby_package_name is complete."
 
   GEM_HOME="$rvm_ruby_gem_home" ; export GEM_HOME
   GEM_PATH="$rvm_ruby_gem_home" ; export GEM_PATH
@@ -138,7 +138,7 @@ __rvm_install_ruby() {
           macruby_path="/usr/local/bin"
           # TODO: Separated nightly from head.
           rvm_url="$(__rvm_db "macruby_nightly_url")"
-          __rvm_log "info" "Retrieving the latest nightly macruby build..."
+          $rvm_scripts_path/log "info" "Retrieving the latest nightly macruby build..."
           __rvm_fetch "$rvm_url"
           mv "$rvm_archives_path/macruby_nightly-latest.pkg" "$rvm_archives_path/macruby_nightly.pkg"
           __rvm_run "macruby/extract" "sudo installer -pkg '$rvm_path/archives/macruby_nightly.pkg' -target '/'"
@@ -169,19 +169,19 @@ RubyWrapper
         done
         __rvm_irbrc
       else
-        __rvm_log "fail" "MacRuby can only be installed on a Darwin OS."
+        $rvm_scripts_path/log "fail" "MacRuby can only be installed on a Darwin OS."
       fi
     ;;
 
     ree)
       if [[ ! -z "$(echo $rvm_ruby_version | awk '/^1\.8/')" ]] && [[ -z "$rvm_head_flag" ]] ; then
         rvm_url="$(__rvm_db "ree_${rvm_ruby_version}_url")/$rvm_ruby_package_file.tar.gz"
-        __rvm_log "info" "Installing Ruby Enterprise Edition from source to: $rvm_ruby_home"
+        $rvm_scripts_path/log "info" "Installing Ruby Enterprise Edition from source to: $rvm_ruby_home"
         __rvm_pushpop "$rvm_src_path"
         if [[ -z "$rvm_force_flag" ]] && [[ -d "$rvm_ruby_src_path" ]] && [[ ! -x "$rvm_ruby_src_path/installer" ]] ; then
-          __rvm_log "It appears that the archive has already been extracted. Skipping extract (use --force to force re-download and extract)."
+          $rvm_scripts_path/log "It appears that the archive has already been extracted. Skipping extract (use --force to force re-download and extract)."
         else
-          __rvm_log "Downloading $rvm_ruby_package_file, this may take a while depending on your connection..."
+          $rvm_scripts_path/log "Downloading $rvm_ruby_package_file, this may take a while depending on your connection..."
           __rvm_fetch "$rvm_url"
           if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
           rm -rf "$rvm_ruby_src_path"
@@ -220,7 +220,7 @@ RubyWrapper
       else
         rvm_url="$(__rvm_db "ree_${rvm_ruby_version}_repo_url")"
         if [[ -z "$rvm_url" ]] ; then
-          __rvm_log "fail" "rvm does not know the rvm repo url for 'ree_${rvm_ruby_version}'"
+          $rvm_scripts_path/log "fail" "rvm does not know the rvm repo url for 'ree_${rvm_ruby_version}'"
           result=1
         else
           rvm_ruby_repo_url=$rvm_url
@@ -231,7 +231,7 @@ RubyWrapper
     ;;
 
     rbx|rubinius)
-      __rvm_log "info" "Installing pre-requisites"
+      $rvm_scripts_path/log "info" "Installing pre-requisites"
       # prereqs, 1.8.6+ + rake. Yes this could all be one line... not pushing our luck.
       echo "$(export rvm_install_on_use_flag=1 ; rvm 1.8.7)" # This should install if missing.
       # TODO: use 'rvm gems load' here:
@@ -336,7 +336,7 @@ RubyWrapper
         if [[ -d "$rvm_ruby_src_path/.git" ]] ; then
           cd "$rvm_ruby_src_path"
           if [[ -z "$rvm_ruby_revision" ]] ; then
-            __rvm_log "info" "Pulling from $rvm_ruby_repo_url, this may take a while depending on your connection..."
+            $rvm_scripts_path/log "info" "Pulling from $rvm_ruby_repo_url, this may take a while depending on your connection..."
             git pull origin master
             if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
           else
@@ -349,7 +349,7 @@ RubyWrapper
           fi
         else
           rm -rf "$rvm_ruby_src_path"
-          __rvm_log "info" "Cloning from $rvm_ruby_repo_url, this may take a while depending on your connection..."
+          $rvm_scripts_path/log "info" "Cloning from $rvm_ruby_repo_url, this may take a while depending on your connection..."
           git clone --depth 1 "$rvm_ruby_repo_url" "$rvm_ruby_src_path"
           if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
         fi
@@ -358,9 +358,9 @@ RubyWrapper
         ant dist
       else
         if [[ -z "$rvm_force_flag" ]] && [[ -f $rvm_package_file ]] && [[ -s $rvm_package_file ]] ; then
-          __rvm_log "info" "It appears that $rvm_package_file has already been downloaded, skipping. Use --force to force re-download."
+          $rvm_scripts_path/log "info" "It appears that $rvm_package_file has already been downloaded, skipping. Use --force to force re-download."
         else
-          __rvm_log "info" "Downloading $rvm_package_file, this may take a while depending on your connection..."
+          $rvm_scripts_path/log "info" "Downloading $rvm_package_file, this may take a while depending on your connection..."
           __rvm_fetch "$rvm_url"
         fi
         __rvm_run "extract" "tar zxf $rvm_archives_path/$rvm_package_file.tar.gz -C $rvm_src_path" "Extracting $rvm_package_file..."
@@ -427,13 +427,13 @@ RubyWrapper
 
       if [[ ! -s "$rvm_ruby_src_path/configure" ]] ; then
           rvm_autoconf="$(which autoconf)"
-          if [[ $? -gt 0 ]] ; then __rvm_log "fail" "rvm expects autoconf" ; result=$? ; return $result ; fi
+          if [[ $? -gt 0 ]] ; then $rvm_scripts_path/log "fail" "rvm expects autoconf" ; result=$? ; return $result ; fi
           __rvm_run "autoconf" "$rvm_autoconf" "Running autoconf"
           # if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi # Don't barf on autoconf fail...
       fi
 
       if [[ -s ./Makefile ]] && [[ -z "$rvm_reconfigure_flag" ]] ; then
-          __rvm_log "debug" "Skipping configure step, Makefile exists so configure must have already been run."
+          (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "Skipping configure step, Makefile exists so configure must have already been run."
       elif [[ ! -z "rvm_ruby_configure" ]] ; then
           $rvm_ruby_configure
       elif [[ -s ./configure ]] ; then
@@ -441,7 +441,7 @@ RubyWrapper
           if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
           unset configure_parameters
       else
-          __rvm_log "error" "Skipping configure step, 'configure' script does not exist, did autoconf not run successfully?"
+          $rvm_scripts_path/log "error" "Skipping configure step, 'configure' script does not exist, did autoconf not run successfully?"
       fi
 
       rvm_ruby_make=${rvm_ruby_make:-"/usr/bin/make"}
@@ -452,7 +452,7 @@ RubyWrapper
       __rvm_run "install" "$rvm_ruby_make_install" "Installing $rvm_ruby_package_name"
       if [[ $? -gt 0 ]] ; then result=$? ; return $result ; fi
 
-      __rvm_log "info" "Installation of $rvm_ruby_package_name is complete."
+      $rvm_scripts_path/log "info" "Installation of $rvm_ruby_package_name is complete."
 
       GEM_HOME="$rvm_ruby_gem_home" ; export GEM_HOME
       GEM_PATH="$rvm_ruby_gem_home" ; export GEM_PATH
@@ -470,10 +470,10 @@ RubyWrapper
     ;;
 
     default)
-      __rvm_log "fail" "must specify a ruby interpreter to install."
+      $rvm_scripts_path/log "fail" "must specify a ruby interpreter to install."
     ;;
 
-    *) __rvm_log "fail" "Ruby interpreter '$rvm_ruby_interpreter' is not known."
+    *) $rvm_scripts_path/log "fail" "Ruby interpreter '$rvm_ruby_interpreter' is not known."
 
   esac
 
@@ -509,7 +509,7 @@ __rvm_manage_rubies() {
         fi
       done < <(\ls $rvm_path/*/bin/ruby 2> /dev/null)
     else
-      __rvm_log "warn" 'Really? Install all? See "rvm list --all" and limit the selection to something more sane please :)'
+      $rvm_scripts_path/log "warn" 'Really? Install all? See "rvm list --all" and limit the selection to something more sane please :)'
     fi
   fi
   __rvm_state
@@ -525,10 +525,10 @@ __rvm_uninstall_ruby() {
   if [[ ! -z "$rvm_ruby_package_name" ]] ; then
     for dir in $rvm_path ; do
       if [[ -d $dir/$rvm_ruby_package_name ]] ; then
-        __rvm_log "info" "Removing $dir/$rvm_ruby_package_name..."
+        $rvm_scripts_path/log "info" "Removing $dir/$rvm_ruby_package_name..."
         rm -rf $dir/$rvm_ruby_package_name
       else
-        __rvm_log "info" "$dir/$rvm_ruby_package_name has already been removed."
+        $rvm_scripts_path/log "info" "$dir/$rvm_ruby_package_name has already been removed."
       fi
       if [[ -e $rvm_bin_path/$rvm_ruby_package_name ]] ; then
         rm -f $rvm_bin_path/$rvm_ruby_package_name
@@ -536,7 +536,7 @@ __rvm_uninstall_ruby() {
     done ; unset dir
     rm -rf $rvm_gem_path/$rvm_ruby_interpreter/$rvm_ruby_version*/
   else
-    __rvm_log "fail" "Cannot uninstall unknown package '$rvm_ruby_package_name'"
+    $rvm_scripts_path/log "fail" "Cannot uninstall unknown package '$rvm_ruby_package_name'"
   fi
 }
 
@@ -546,17 +546,17 @@ __rvm_remove_ruby() {
   if [[ ! -z "$rvm_ruby_string" ]] ; then
     for dir in $rvm_src_path $rvm_path ; do
       if [[ -d $dir/$rvm_ruby_string ]] ; then
-        __rvm_log "info" "Removing $dir/$rvm_ruby_string..."
+        $rvm_scripts_path/log "info" "Removing $dir/$rvm_ruby_string..."
         rm -rf $dir/$rvm_ruby_package_name
       else
-        __rvm_log "info" "it seems that $dir/$rvm_ruby_string is already non existent."
+        $rvm_scripts_path/log "info" "it seems that $dir/$rvm_ruby_string is already non existent."
       fi
       if [[ -e $rvm_bin_path/$rvm_ruby_string ]] ; then
         rm -f $rvm_bin_path/$rvm_ruby_string
       fi
     done ; unset dir
   else
-    __rvm_log "fail" "Cannot uninstall unknown package '$rvm_ruby_package_name'"
+    $rvm_scripts_path/log "fail" "Cannot uninstall unknown package '$rvm_ruby_package_name'"
   fi
 }
 
@@ -575,13 +575,13 @@ __rvm_post_install() {
     fi
   done ; unset binary binaries
 
-  __rvm_log "info" "Installing gems for $rvm_ruby_package_name."
+  $rvm_scripts_path/log "info" "Installing gems for $rvm_ruby_package_name."
 
   for rvm_gem_name in rake ; do
     __rvm_run "gems.install" "$rvm_ruby_home/bin/gem install $rvm_gem_name --no-rdoc --no-ri -q" "Installing $rvm_gem_name"
   done ; unset rvm_gem_name
 
-  __rvm_log "info" "Installation of gems for $rvm_ruby_package_name is complete."
+  $rvm_scripts_path/log "info" "Installation of gems for $rvm_ruby_package_name is complete."
 
   binary=rake
   if [[ -x $rvm_ruby_gem_home/bin/$binary ]] ; then
@@ -604,16 +604,16 @@ __rvm_rubygems_setup() {
     __rvm_inject_gem_env "$rvm_ruby_home/bin/gem"
 
   elif [[ ! -z "$(echo $rvm_ruby_interpreter | awk '/^rbx|jruby/')" ]] ; then
-    __rvm_log "debug" "Skipping rubygems update for $rvm_ruby_version"
+    (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "Skipping rubygems update for $rvm_ruby_version"
   else
-    __rvm_log "info" "Installing rubygems dedicated to $rvm_ruby_package_name..."
+    $rvm_scripts_path/log "info" "Installing rubygems dedicated to $rvm_ruby_package_name..."
     rvm_gem_package_name="rubygems-1.3.5"
     rvm_gem_url="http://rubyforge.org/frs/download.php/60718/$rvm_gem_package_name.tgz"
 
     # Sanity check...
     if [[ ! -f "$rvm_src_path/$rvm_gem_package_name/setup.rb" ]]; then rm -rf "$rvm_src_path/$rvm_gem_package_name" ; fi
     if [[ ! -d "$rvm_src_path/$rvm_gem_package_name" ]] ; then
-      __rvm_log "info" "Retrieving $rvm_gem_package_name"
+      $rvm_scripts_path/log "info" "Retrieving $rvm_gem_package_name"
       __rvm_fetch "$rvm_gem_url"
       mkdir -p "$rvm_src_path/$rvm_gem_package_name"
       __rvm_run "rubygems.extract" "tar zxf $rvm_archives_path/$rvm_gem_package_name.tgz -C $rvm_src_path" "Extracting $rvm_gem_package_name"
@@ -622,9 +622,9 @@ __rvm_rubygems_setup() {
     __rvm_run "rubygems.install" "GEM_PATH=$rvm_gem_path GEM_HOME=$rvm_ruby_gem_home $rvm_ruby_home/bin/ruby $rvm_src_path/$rvm_gem_package_name/setup.rb" "Installing rubygems for $rvm_ruby_home/bin/ruby"
     result=$?
     if [[ $result -eq 0 ]] ; then
-      __rvm_log "info" "Installation of rubygems $rvm_ruby_package_name completed successfully."
+      $rvm_scripts_path/log "info" "Installation of rubygems $rvm_ruby_package_name completed successfully."
     else
-      __rvm_log "warning" "Installation of rubygems $rvm_ruby_package_name did not complete successfully."
+      $rvm_scripts_path/log "warning" "Installation of rubygems $rvm_ruby_package_name did not complete successfully."
     fi
     __rvm_inject_ruby_shebang "$rvm_ruby_home/bin/gem"
   fi
diff --git a/scripts/utility b/scripts/utility
--- a/scripts/utility
+++ b/scripts/utility
@@ -34,22 +34,22 @@ Info
 }
 
 __rvm_debug() {
-  __rvm_log "debug" "PATH:\n$(echo $PATH | awk -F":" '{print $1":"$2":"$3":"$4":"$5}')"
-  __rvm_log "debug" "uname -a: $(uname -a)"
+  $rvm_scripts_path/log "debug" "PATH:\n$(echo $PATH | awk -F":" '{print $1":"$2":"$3":"$4":"$5}')"
+  $rvm_scripts_path/log "debug" "uname -a: $(uname -a)"
 
   if [[ "Darwin" = "$(uname)" ]] ; then
-    __rvm_log "debug" "uname -r: $(uname -r)"
-    __rvm_log "debug" "uname -m: $(uname -m)"
-    __rvm_log "debug" "sw_vers: $(sw_vers | tr "\n" ',')"
-    __rvm_log "debug" "ARCHFLAGS: $ARCHFLAGS"
-    __rvm_log "debug" "LDFLAGS: $LDFLAGS"
-    __rvm_log "debug" "CFLAGS: $CFLAGS"
-    __rvm_log "debug" "/Developer/SDKs/*:$(basename -a /Developer/SDKs/* | tr "\n" ',')"
+    $rvm_scripts_path/log "debug" "uname -r: $(uname -r)"
+    $rvm_scripts_path/log "debug" "uname -m: $(uname -m)"
+    $rvm_scripts_path/log "debug" "sw_vers: $(sw_vers | tr "\n" ',')"
+    $rvm_scripts_path/log "debug" "ARCHFLAGS: $ARCHFLAGS"
+    $rvm_scripts_path/log "debug" "LDFLAGS: $LDFLAGS"
+    $rvm_scripts_path/log "debug" "CFLAGS: $CFLAGS"
+    $rvm_scripts_path/log "debug" "/Developer/SDKs/*:$(basename -a /Developer/SDKs/* | tr "\n" ',')"
   fi
 
   for file_name in $(echo $rc_files) ; do
     if [[ -s "$file_name" ]] ; then
-      __rvm_log "debug" "$file_name:\n$(grep 'rvm' $file_name)"
+      $rvm_scripts_path/log "debug" "$file_name:\n$(grep 'rvm' $file_name)"
     fi
   done
 
@@ -61,32 +61,11 @@ __rvm_debug() {
 
   for file_name in $(echo $debug_files); do
     if [[ -f "$file_name" ]] && [[ -s "$file_name" ]] ; then
-      __rvm_log "debug" "$file_name (filtered):\n$(cat $file_name | awk '!/assword|_key/')\n"
+      $rvm_scripts_path/log "debug" "$file_name (filtered):\n$(cat $file_name | awk '!/assword|_key/')\n"
     fi
   done
 
-  __rvm_log "debug" "gem sources:\n$(gem sources | awk '/gems/')"
-
-  if [[ -f "$rvm_path/bin/rvm" ]] ; then
-    __rvm_log "error" "rvm script in bin! \n$(\ls -laht $rvm_path/bin/rvm)"
-  fi
-}
-
-# Logging functions based on level
-# TODO: Allow specification of a base file name to output to.
-__rvm_log() {
-  if [[ ! -z "$2" ]] ; then level=$1 ; shift ; else level="info" ; fi
-  message=$1
-  case "$level" in
-    debug) shift ;
-      ((rvm_debug_flag)) && echo -e "$(tput setaf 5)<d>$(tput sgr0) $message $(tput setaf 5)</d> $(tput sgr0) "
-    ;;
-    info)  shift ; echo -e "$(tput setaf 2)<i>$(tput sgr0) $message $(tput setaf 2)</i> $(tput sgr0) " ;;
-    warn)  shift ; echo -e "$(tput setaf 3)<w>$(tput sgr0) $message $(tput setaf 3)</w> $(tput sgr0) " ;;
-    error) shift ; echo -e "$(tput setaf 1)<e>$(tput sgr0) $message $(tput setaf 1)</e> $(tput sgr0) " ;;
-    fail)  shift ; echo -e "$(tput setaf 1)<f>$(tput sgr0) $message $(tput setaf 1)</f> $(tput sgr0) " ; __rvm_pushpop ; return 1 ;;
-    *) echo -e "$message"
-  esac
+  $rvm_scripts_path/log "debug" "gem sources:\n$(gem sources | awk '/gems/')"
 }
 
 if [[ ! -z "$ZSH_VERSION" ]] ; then __shell_array_start=1 ; else __shell_array_start=0 ; fi
@@ -115,8 +94,8 @@ __rvm_run() {
   rvm_ruby_log_path="${rvm_ruby_log_path:-$rvm_path/log}"
   mkdir -p $(dirname "$rvm_ruby_log_path/$log_file_name.log")
 
-  if [[ ! -z "$message" ]] ; then __rvm_log "info" "$message" ; fi
-  __rvm_log "debug" "Executing: $command"
+  if [[ ! -z "$message" ]] ; then $rvm_scripts_path/log "info" "$message" ; fi
+  (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "Executing: $command"
   touch "$rvm_ruby_log_path/$log_file_name.log" "$rvm_ruby_log_path/$log_file_name.error.log" # for zsh :(
   echo "[$(date +'%Y-%m-%d %H:%M:%S')] $command" | tee "$rvm_ruby_log_path/$log_file_name.log" > "$rvm_ruby_log_path/$log_file_name.error.log"
   if [[ -z "$rvm_niceness" ]] || [[ "0" = "$rvm_niceness" ]] ; then
@@ -124,7 +103,7 @@ __rvm_run() {
   else
     eval "nice -n $rvm_niceness \$($command)" >> $rvm_ruby_log_path/$log_file_name.log 2>> $rvm_ruby_log_path/$log_file_name.error.log
   fi
-  if [[ $? -gt 0 ]] ; then __rvm_log "error" "Error running '$command', please check $rvm_ruby_log_path/$log_file_name.error.log" ; __rvm_pushpop ; return 1 ; fi
+  if [[ $? -gt 0 ]] ; then $rvm_scripts_path/log "error" "Error running '$command', please check $rvm_ruby_log_path/$log_file_name.error.log" ; __rvm_pushpop ; return 1 ; fi
   unset log_file command
 }
 
@@ -175,20 +154,20 @@ __rvm_fetch() {
   __rvm_pushpop $rvm_archives_path
   if [[ -z "$1" ]] ; then log "fail" "BUG: __rvm_fetch called without an argument :/" ; return 1 ; fi
   archive=$(basename "$1") ; downlaod=1
-  __rvm_log "debug" "Fetching $archive"
+  (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "Fetching $archive"
   # Check first if we have the correct archive
   if [[ -e "$archive" ]] && [[ -e "$archive.md5" ]] ; then
-    __rvm_log "debug" "Found archive and its md5, testing correctness"
+    (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "Found archive and its md5, testing correctness"
     if [[ $(md5sum --status -c "$archive.md5") -gt 0 ]] ; then
-      __rvm_log "debug" "Archive is bad, downloading"
+      (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "Archive is bad, downloading"
       download=1
     else
-      __rvm_log "debug" "Archive is good, not downloading"
+      (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "Archive is good, not downloading"
       download=0
       result=0
     fi
   else
-    __rvm_log "debug" "No archive or no MD5, downloading"
+    (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "No archive or no MD5, downloading"
     download=1
   fi
   if [[ $download -gt 0 ]] ; then
@@ -197,24 +176,24 @@ __rvm_fetch() {
     if [[ $result -gt 0 ]] ; then
       retry=0
       if [[ $result -eq 78 ]] ; then
-        __rvm_log "error" "The requested url does not exist: '$1'"
+        $rvm_scripts_path/log "error" "The requested url does not exist: '$1'"
       elif [[ $result -eq 18 ]] ; then
-        __rvm_log "error" "Partial file. Only a part of the file was transferred. Removing partial and re-trying."
+        $rvm_scripts_path/log "error" "Partial file. Only a part of the file was transferred. Removing partial and re-trying."
         rm -f "$archive"
         retry=1
       elif [[ $result -eq 33 ]] ; then
-        __rvm_log "debug" "Server does not support 'range' command, removing '$archive'"
+        (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "Server does not support 'range' command, removing '$archive'"
         rm -f "$archive"
         retry=1
       else
-        __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
+        $rvm_scripts_path/log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
       fi
 
       if [[ $retry -eq 1 ]] ; then
         eval $rvm_fetch "$1"
         result=$?
         if [[ $result -gt 0 ]] ; then
-          __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
+          $rvm_scripts_path/log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
         fi
       fi
 
@@ -245,7 +224,7 @@ __rvm_load_defaults() {
   if [[ ! -z "$rvm_system_ruby" ]] ; then
     rvm_system_ruby=$(which ruby)
     if [[ $? -ne 0 ]] ; then
-      __rvm_log "info" "System ruby not found, no db will be stored."
+      $rvm_scripts_path/log "info" "System ruby not found, no db will be stored."
     else
       __rvm_db "system_ruby" "$rvm_system_ruby"
 
@@ -285,23 +264,23 @@ __rvm_reset() {
 
 __rvm_implode() {
   while : ; do
-    __rvm_log "warn" "Are you SURE you wish for rvm to implode? This will remove $rvm_path ? (type 'yes' or 'no')"
+    $rvm_scripts_path/log "warn" "Are you SURE you wish for rvm to implode? This will remove $rvm_path ? (type 'yes' or 'no')"
     read response
     if [[ "yes" = "$response" ]] ; then
       if [[ "/" = "$rvm_path" ]] ; then
-        __rvm_log "error" "remove '/' ?!... NO!"
+        $rvm_scripts_path/log "error" "remove '/' ?!... NO!"
       else
         if [[ -d "$rvm_path" ]] ; then
-          __rvm_log "info" "Hai! Removing $rvm_path"
+          $rvm_scripts_path/log "info" "Hai! Removing $rvm_path"
           rm -rf $rvm_path/
-          __rvm_log "info" "$rvm_path has been removed."
+          $rvm_scripts_path/log "info" "$rvm_path has been removed."
         else
-          __rvm_log "info" "It appears that $rvm_path is already non existant."
+          $rvm_scripts_path/log "info" "It appears that $rvm_path is already non existant."
         fi
       fi
       break
     elif [[ "no" = "$response" ]] ; then
-      __rvm_log "info" "Cancelling implosion, no harm done :)"
+      $rvm_scripts_path/log "info" "Cancelling implosion, no harm done :)"
       break
     fi
   done
@@ -310,7 +289,7 @@ __rvm_implode() {
 __rvm_source_dir() {
   if [[ -z "$rvm_ruby_selected_flag" ]] ; then __rvm_select $* ; fi
   if [[ -z "$rvm_ruby_src_path" ]] ; then
-    __rvm_log "fail" "No source directory exists for the default implementation."
+    $rvm_scripts_path/log "fail" "No source directory exists for the default implementation."
   else
     echo "$rvm_ruby_src_path"
   fi
@@ -320,7 +299,7 @@ __rvm_source_dir() {
 # TODO: Merge this into 'rvm sync'
 __rvm_gemdup() {
   if [[ -z "$rvm_ruby_selected_flag" ]] ; then __rvm_select $* ; fi
-  __rvm_log "debug" "$rvm_ruby_interpreter"
+  (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "$rvm_ruby_interpreter"
   if [[ "default" = "$rvm_ruby_interpreter" ]] ; then
     # TODO: $rvm_path/default first, then system user
     rvm_source_gem_path="$rvm_system_user_gem_path"
@@ -349,7 +328,7 @@ __rvm_gem_sync() {
     done
     unset rvm_gem_name_version rvm_gem_name rvm_gem_version
   else
-    __rvm_log "fail" "Unknown ruby selected :("
+    $rvm_scripts_path/log "fail" "Unknown ruby selected :("
     result=1
   fi
 }
@@ -360,7 +339,7 @@ __rvm_db() {
   key="$1" ; shift
 
   if [[ -z "$key" ]] ; then
-    __rvm_log "fail" "__rvm_db must be called with at least one argument: __rvm_db key [value]"
+    $rvm_scripts_path/log "fail" "__rvm_db must be called with at least one argument: __rvm_db key [value]"
   else
     value="$*"
     if [[ "unset" = "$value" ]] || [[ "delete" = "$value" ]] ; then
@@ -529,14 +508,14 @@ __rvm_update_rvm() {
 }
 
 __rvm_reboot() {
-  __rvm_log "warn" "Do you wish to reset rvm? ('yes', or 'no')"
+  $rvm_scripts_path/log "warn" "Do you wish to reset rvm? ('yes', or 'no')"
   read response
   if [[ "yes" = "$response" ]] ; then
     cd $rvm_path
     __rvm_reset
     mv $rvm_path/archives ~/.archives
     if [[ "/" = "$rvm_path" ]] ; then
-      __rvm_log "error" "remove '/' ?!... NO!"
+      $rvm_scripts_path/log "error" "remove '/' ?!... NO!"
     else
       if [[ -d "$rvm_path" ]] ; then rm -rf "$rvm_path/" ; fi
     fi
@@ -544,7 +523,7 @@ __rvm_reboot() {
     __rvm_update_rvm
     source $rvm_path/scripts/rvm
   else
-    __rvm_log "info" "Carry on then..."
+    $rvm_scripts_path/log "info" "Carry on then..."
   fi ; unset response
 }
 
@@ -557,7 +536,7 @@ __rvm_ruby_do() {
   elif [[ "system" = "$rvm_ruby_string" ]] && [[ -x "$(which $binary)" ]] ; then
     binary="$(which $binary)"
   else
-    __rvm_log "warn" "'$binary not found for $rvm_ruby_string' either does not exist or is not executable? :("
+    $rvm_scripts_path/log "warn" "'$binary not found for $rvm_ruby_string' either does not exist or is not executable? :("
     __rvm_unset_ruby_variables
     return 1
   fi
@@ -656,7 +635,7 @@ __rvm_yaml() {
   total=${#rubies[*]}
   if [[ ! -z "$ZSH_VERSION" ]] ; then array_start=1 ; else array_start=0 ; fi
   for (( index = $array_start ; index < $total + $array_start ; index++ )) ; do
-    __rvm_log "debug" "${rubies[$index]}: ${statuses[$index]}"
+    (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "${rubies[$index]}: ${statuses[$index]}"
     yaml="$yaml\n  \"${rubies[$index]}\": ${statuses[$index]}"
   done ; unset index array_start
   mkdir -p log
@@ -675,7 +654,7 @@ __rvm_json() {
   total=${#rubies[*]}
   if [[ ! -z "$ZSH_VERSION" ]] ; then array_start=1 ; else array_start=0 ; fi
   for (( index = $array_start ; index < $total + $array_start ; index++ )) ; do
-    __rvm_log "debug" "${rubies[$index]}: ${statuses[$index]}"
+    (($rvm_debug_flag)) && $rvm_scripts_path/log "debug" "${rubies[$index]}: ${statuses[$index]}"
     json="$json\n    {\"${rubies[$index]}\": ${statuses[$index]}}"
     if (( $index + 1 < $total + $array_start )) ; then json="$json,  " ; fi
   done ; unset index array_start
@@ -733,7 +712,7 @@ __rvm_state() {
 __rvm_inspect() {
   for binary in $rvm_ruby_args ; do
     actual_file=$(which $binary)
-    __rvm_log "info" "$actual_file:"
+    $rvm_scripts_path/log "info" "$actual_file:"
     if [[ ! -z "$rvm_shebang_flag" ]] ; then cat $actual_file | head -n 1    ; fi
     if [[ ! -z "$rvm_env_flag" ]]     ; then cat $actual_file | awk '/ENV/'  ; fi
     if [[ ! -z "$rvm_path_flag" ]]    ; then cat $actual_file | awk '/PATH/' ; fi
@@ -751,7 +730,7 @@ __rvm_readline_install() {
   __rvm_pushpop $rvm_src_path
   package="readline" ; version="5.2" ; archive_format="tar.gz"
   # TODO: Figure out how to list, grab and apply the patches
-  __rvm_log "info" "Retrieving $package-$version.$archive_format"
+  $rvm_scripts_path/log "info" "Retrieving $package-$version.$archive_format"
   __rvm_fetch "ftp://ftp.gnu.org/gnu/readline/$package-$version.$archive_format"
   __rvm_run "$package/extract" "tar zxf $rvm_archives_path/$package-$version.$archive_format -C $rvm_src_path" "Extracting $package-$version.$archive_format"
   cd "$rvm_src_path/$package-$version"
@@ -773,7 +752,7 @@ __rvm_iconv_install() {
   __rvm_make_flags
   __rvm_pushpop $rvm_src_path
   package="libiconv" ; version=1.13.1 ; archive_format="tar.gz"
-  __rvm_log "info" "Retrieving $package-$version.$archive_format"
+  $rvm_scripts_path/log "info" "Retrieving $package-$version.$archive_format"
   __rvm_fetch "http://ftp.gnu.org/pub/gnu/libiconv/$package-$version.$archive_format"
   __rvm_run "$package/extract" "tar zxf $rvm_archives_path/$package-$version.$archive_format -C $rvm_src_path" "Extracting $package-$version.$archive_format"
   cd "$rvm_src_path/$package-$version"
@@ -787,7 +766,7 @@ __rvm_curl_install() {
   __rvm_make_flags
   __rvm_pushpop $rvm_src_path
   package="curl" ; version=7.19.7 ; archive_format="tar.gz"
-  __rvm_log "info" "Retrieving $package-$version.$archive_format"
+  $rvm_scripts_path/log "info" "Retrieving $package-$version.$archive_format"
   __rvm_fetch "http://curl.haxx.se/download/$package-$version.$archive_format"
   __rvm_run "$package/extract" "tar zxf $rvm_archives_path/$package-$version.$archive_format -C $rvm_src_path" "Extracting $package-$version.$archive_format"
   cd "$rvm_src_path/$package-$version"
@@ -807,7 +786,7 @@ __rvm_openssl_install() {
     fi
   __rvm_pushpop $rvm_src_path
   package="openssl" ; version="0.9.8k" ; archive_format="tar.gz"
-  __rvm_log "info" "Retrieving $package-$version.$archive_format"
+  $rvm_scripts_path/log "info" "Retrieving $package-$version.$archive_format"
   __rvm_fetch "http://www.openssl.org/source/$package-$version.tar.gz"
   __rvm_run "$package/extract" "tar zxf $rvm_archives_path/$package-$version.$archive_format -C $rvm_src_path" "Extracting $package-$version.$archive_format"
   cd "$rvm_src_path/$package-$version"
@@ -821,7 +800,7 @@ __rvm_zlib_install() {
   __rvm_make_flags
   __rvm_pushpop $rvm_src_path
   package="zlib" ; version="1.2.3" ; archive_format="tar.gz"
-  __rvm_log "info" "Retrieving $package-$version.$archive_format"
+  $rvm_scripts_path/log "info" "Retrieving $package-$version.$archive_format"
   __rvm_fetch "http://www.zlib.net/$package-$version.tar.gz"
   __rvm_run "$package/extract" "tar zxf $rvm_archives_path/$package-$version.$archive_format -C $rvm_src_path" "Extracting $package-$version.$archive_format"
   cd "$rvm_src_path/$package-$version"
@@ -835,7 +814,7 @@ __rvm_ncurses_install() {
   __rvm_make_flags
   __rvm_pushpop $rvm_src_path
   package="ncurses" ; version="5.7" ; archive_format="tar.gz"
-  __rvm_log "info" "Retrieving $package"
+  $rvm_scripts_path/log "info" "Retrieving $package"
   __rvm_fetch "ftp://invisible-island.net/ncurses/ncurses.tar.gz"
   __rvm_run "$package/extract" "tar zxf $rvm_archives_path/$package.$archive_format -C $rvm_src_path" "Extracting $package.$archive_format"
   cd "$rvm_src_path/$package-$version"
