extra code to also validate gemfiles content

diff --git a/scripts/rubygems b/scripts/rubygems
--- a/scripts/rubygems
+++ b/scripts/rubygems
@@ -209,14 +209,60 @@ builtin command -v ruby > /dev/null || {
   exit 1
 }
 
-# Adapted from: https://gist.github.com/4678189
+rubygems_validate_gemfile_extract()
+(
+  \mkdir -p "$2/gem" &&
+  \tar -C "$2" -xf "$1" --touch &&
+  \cd "$2" &&
+  \gzip -d "metadata.gz" &&
+  \tar -C gem -xzf "data.tar.gz" --touch &&
+  \rm "data.tar.gz" ||
+  {
+    typeset ret=$?
+    rvm_error "Error extracting '$1' to '$2'."
+    rm -rf "${rvm_tmp_path}/rg$$"
+    return $ret
+  }
+)
 
+# Adapted from: https://gist.github.com/4678778
+rubygems_validate_gemfile()
+(
+  gem_file="$1"
+  gem__url="$2"
+  downloaded_file="${gem_file##*/}"
+  dir_local_copy="${downloaded_file%.gem}--local"
+  dir_remote_copy="${downloaded_file%.gem}-remote"
+
+  mkdir -p "${rvm_tmp_path}/rg$$"
+  cd "${rvm_tmp_path}/rg$$"
+
+  curl -fsS3 "$gem__url" -o "$downloaded_file" &&
+  [[ -f "$downloaded_file" ]] ||
+  {
+    typeset ret=$?
+    rvm_error "Could not download '$gem__url'."
+    rm -rf "${rvm_tmp_path}/rg$$"
+    return $ret
+  }
+
+  rubygems_validate_gemfile_extract "$gem_file"        "$dir_local_copy"  || return $?
+  rubygems_validate_gemfile_extract "$downloaded_file" "$dir_remote_copy" || return $?
+
+  # compare
+  diff -ru "$dir_local_copy" "$dir_remote_copy"
+
+  # cleanup
+  rm -rf "${rvm_tmp_path}/rg$$"
+)
+
+# Adapted from: https://gist.github.com/4678189
 rubygems_validate()
 {
   which openssl > /dev/null ||
     rubygems_fatal_error "'openssl' was not found, please install it."
 
-  typeset gemdir gemfile gem loc rem
+  typeset gemdir gemfile url gem loc rem log
   typeset -a gemdirs
 
   rvm_log  "Validating RubyGems... This will take a while..."
@@ -235,18 +281,25 @@ rubygems_validate()
   do
     for gem in "$gemdir"/*.gem
     do
-      gemfile=$(basename $gem)
+      gemfile="${gem##*/}"
+      url="https://d2chzxaqi4y7f8.cloudfront.net/gems/$gemfile"
       printf "%b" "${rvm_notify_clr}${gem}${rvm_reset_clr}"
 
       loc=$(openssl md5 $gem |cut -d" " -f2)
-      rem=$(curl -3 -s -D - -X HEAD -H 'Connection:close' https://d2chzxaqi4y7f8.cloudfront.net/gems/$gemfile | grep 'ETag' | cut -d'"' -f2)
+      rem=$(curl -3 -s -D - -X HEAD -H 'Connection:close' "$url" | grep 'ETag' | cut -d'"' -f2)
 
-      [[ $loc == $rem ]] || printf "%b" "${rvm_error_clr} mismatch, local: $loc, remote: $rem${rvm_reset_clr}"
+      [[ $loc == $rem ]] ||
+      {
+        printf "%b" " "
+        log="${rvm_log_path}/$gemfile.diff"
+        rubygems_validate_gemfile "$gem" "$url" > "$log"
+        printf "%b" "${rvm_error_clr}mismatch, local: $loc, remote: $rem${rvm_reset_clr}, differences recorded in '$log'"
+      }
       printf "%b" ", "
     done
   done
 
-  rvm_log "Done verifying gems."
+  rvm_log "\nDone verifying gems."
 }
 
 #
@@ -254,6 +307,7 @@ rubygems_validate()
 #
 export version
 version="$1"
+shift
 
 [[ -n "$version" ]] || {
   rvm_error "Usage: rvm rubygems [x.y.z|latest-x.y|latest|remove]"
@@ -264,8 +318,8 @@ can_switch_rubygems ||
 rubygems_fatal_error "RVM can not install rubygems for maglev and older jruby, select other ruby and try again." $?
 
 case "$version" in
-  remove|link|validate)
-    rubygems_$version
+  remove|link|validate|validate_gemfile)
+    rubygems_$version "$@"
     ;;
   *)
     rubygems_setup
