Added --force option for install.

diff --git a/scripts/rvm b/scripts/rvm
--- a/scripts/rvm
+++ b/scripts/rvm
@@ -89,6 +89,7 @@ function __rvm_usage {
     -m|--gem-set    - Use a named gem set instead of the default set.
     --rm-gem-set    - Remove a named gem set
     --jit           - Enable JIT for the Rubinius build
+    --force         - Force install, removes old install & source directories.
     --debug|--trace - Toggle debug mode on for very verbose output.
 
   Resources:
@@ -242,6 +243,11 @@ function __rvm_install-source {
 
   pushd $rvm_source_path > /dev/null
 
+  if [ ! -z "$rvm_force" ] ; then
+    rm -rf $rvm_install_path/$rvm_ruby_package_name
+    rm -rf $rvm_source_path/$rvm_ruby_package_name
+  fi
+
   if [ -z "$rvm_ruby_tag" -a -z "$rvm_ruby_rev" ] ; then
     if [ ! -d $rvm_source_path/$rvm_ruby_package_name ]  ; then
       rvm_url="${rvm_url:-"ftp://ftp.ruby-lang.org/pub/ruby/1.$rvm_major_version/$rvm_ruby_package_name.tar.gz"}"
@@ -253,7 +259,6 @@ function __rvm_install-source {
       mkdir -p $rvm_source_path/$rvm_ruby_package_name
       nice -n $rvm_niceness tar xzf $rvm_archives_path/$rvm_ruby_package_name.tar.gz -C $rvm_source_path
     fi
-    cd $rvm_source_path/$rvm_ruby_package_name
   else
     if [ -z "$rvm_ruby_rev" ] ; then
       # TODO: Check if tag v is valid
@@ -268,28 +273,32 @@ function __rvm_install-source {
         rvm_rev="-r $rvm_ruby_rev"
       fi
     fi
-    __rvm_log "info" "\tRetrieving Ruby from $rvm_url"
-    mkdir -p $rvm_source_path/$rvm_ruby_package_name
-    # TODO: Instead of always forcing, check if it's already svn for correct url and simply check out required revision
 
-        cd $rvm_install_path/$rvm_ruby_package_name
+    __rvm_log "info" "\tRetrieving Ruby from $rvm_url"
     if [ ! -z "`echo $rvm_url | grep '^git'`" ] ; then
-      if [ -d $rvm_install_path/$rvm_ruby_package_name ] ; then
-        rm -rf $rvm_install_path/$rvm_ruby_package_name
+      if [ -d "$rvm_source_path/$rvm_ruby_package_name/.git" ] ; then
+        cd $rvm_source_path/$rvm_ruby_package_name
+        if [ -z "$rvm_ruby_rev" ] ; then
+          git pull origin master
+        else
+          git checkout ${rvm_ruby_rev:-HEAD}
+        fi
+      else
+        git clone --depth 1 $rvm_ruby_repo_url $rvm_source_path/$rvm_ruby_package_name
       fi
-      git clone --depth 1 $rvm_ruby_repo_url $rvm_install_path/$rvm_ruby_package_name
     else
-      if [ -d "$rvm_install_path/$rvm_ruby_package_name/.svn" ] ; then
-        cd $rvm_install_path/$rvm_ruby_package_name
+      if [ -d "$rvm_source_path/$rvm_ruby_package_name/.svn" ] ; then
+        cd $rvm_source_path/$rvm_ruby_package_name
         svn checkout -q $rvm_rev
       else
         svn checkout -q $rvm_rev --force $rvm_url $rvm_source_path/$rvm_ruby_package_name
       fi
     fi
-    cd $rvm_source_path/$rvm_ruby_package_name
-    if [ ! -s Makefile -a -z "$rvm_ruby_configure"] ; then autoconf ; fi
   fi
-
+  cd $rvm_source_path/$rvm_ruby_package_name
+  if [ $? -gt 0 ] ; then __rvm_log "error" "There was an error, please check $rvm_log_path/$rvm_ruby_package_name/*.error.log" ; return 1 ; fi
+  if [ ! -s $rvm_source_path/$rvm_ruby_package_name/Makefile -a "$rvm_ruby_interpreter" = "ruby" ] ; then autoconf ; fi
+  if [ $? -gt 0 ] ; then __rvm_log "error" "There was an error, please check $rvm_log_path/$rvm_ruby_package_name/*.error.log" ; return 1 ; fi
   if [ -s ./configure ] ; then
     __rvm_log "info" "\tConfiguring $rvm_ruby_package_name using ${rvm_ruby_configure:-"--enable-shared"}, this may take a while depending on your cpu(s)..."
     nice -n $rvm_niceness ./configure --prefix=$rvm_install_path/$rvm_ruby_package_name ${rvm_ruby_configure:-"--enable-shared"} > $rvm_log_path/$rvm_ruby_package_name/configure.log 2> $rvm_log_path/$rvm_ruby_package_name/configure.error.log
@@ -327,6 +336,7 @@ RubyWrapper
   echo "$ruby_wrapper" > $rvm_bin_path/$rvm_ruby_package_name
   unset ruby_wrapper
   chmod +x $rvm_bin_path/$rvm_ruby_package_name
+  __rvm_log "info" "Installation of $rvm_ruby_package_name is complete."
 
   __rvm_log "info" "\tInstalling rubygems dedicated to $rvm_ruby_package_name..."
   rvm_gem_package_name="rubygems-1.3.5"
@@ -344,7 +354,13 @@ RubyWrapper
 
   nice -n $rvm_niceness $rvm_install_path/$rvm_ruby_package_name/bin/ruby $rvm_source_path/$rvm_gem_package_name/setup.rb > $rvm_log_path/$rvm_ruby_package_name/rubygems.install.log 2> $rvm_log_path/$rvm_ruby_package_name/rubygems.install.error.log
   popd > /dev/null
-  __rvm_log "info" "Installation of $rvm_ruby_package_name complete."
+
+  sed -i.orig "2i\\
+ENV[\"GEM_HOME\"]=\"$rvm_gem_home\"
+
+" $rvm_install_path/$rvm_ruby_package_name/bin/gem
+
+  __rvm_log "info" "Installation of rubygems for $rvm_ruby_package_name is complete."
 
   for rvm_gem_name in rake ; do
     __rvm_log "info" "Installing $rvm_gem_name"
@@ -875,7 +891,7 @@ function __rvm_cache {
 }
 
 function __rvm_cleanup-variables {
-  unset rvm_selected rvm_action rvm_ruby_interpreter rvm_ruby_patch_level rvm_ruby_version rvm_irbrc_file rvm_ruby_irbrc rvm_source_path rvm_install_path rvm_debug rvm_prefix_path rvm_ruby_package_name rvm_gem_path rvm_command rvm_error_message IRBRC rvm_ruby_home rvm_ruby_binary rvm_gem_set_name rvm_delete_flag rvm_ruby_tag rvm_ruby_rev rvm_url rvm_ruby_make rvm_ruby_make_install rvm_config_path rvm_bin_path
+  unset rvm_selected rvm_action rvm_ruby_interpreter rvm_ruby_patch_level rvm_ruby_version rvm_irbrc_file rvm_ruby_irbrc rvm_source_path rvm_install_path rvm_debug rvm_prefix_path rvm_ruby_package_name rvm_gem_path rvm_command rvm_error_message IRBRC rvm_ruby_home rvm_ruby_binary rvm_gem_set_name rvm_delete_flag rvm_ruby_tag rvm_ruby_rev rvm_url rvm_ruby_make rvm_ruby_make_install rvm_config_path rvm_bin_path rvm_force
 }
 
 function __rvm_get-user-defaults {
@@ -999,6 +1015,7 @@ function __rvm_parse-args {
       -h|--help)         rvm_action=help           ; shift ;;
       -d|--default)      rvm_set_default=1                 ;;
       --trace|--debug)   rvm_debug=1                       ;;
+      --force)           rvm_force=1                       ;;
       -m|--gem-set)      rvm_gem_set_name="$1"     ; shift ;;
          --rm-gem-set)   rvm_gem_set_name_rm="$1"  ; shift ;;
          --jit)          rvm_rubinius_jit="RBX_LLVM=1"     ;;
