Adjusted default system checks to check if ruby is installed, thanks Maz. Bugfix: log_file_name... is a variable :)

diff --git a/scripts/rvm b/scripts/rvm
--- a/scripts/rvm
+++ b/scripts/rvm
@@ -164,13 +164,24 @@ function __rvm_set-defaults {
   if [ -s $rvm_install_path/default_user_gem_path ] ; then
     rvm_default_user_gem_path=`cat $rvm_install_path/default_user_gem_path`
   else
-    ruby -r rubygems -e "puts Gem::default_path.compact.first" > $rvm_install_path/default_user_gem_path
+    which ruby > /dev/null
+    if [ $? -ne 0 ] ; then
+      __rvm_log "info" "System ruby not found, assuming no system installed ruby."
+    else
+      ruby -r rubygems -e "puts Gem::default_path.compact.first" > $rvm_install_path/default_user_gem_path
+    fi
   fi
 
   if [ -s $rvm_install_path/default_system_gem_path ] ; then
     rvm_default_system_gem_path=`cat $rvm_install_path/default_system_gem_path`
   else
-    ruby -r rubygems -e "puts Gem::default_path.compact[1] || Gem::default_path.compact.first" > $rvm_install_path/default_system_gem_path
+    which ruby > /dev/null
+    if [ $? -ne 0 ] ; then
+      __rvm_log "info" "System ruby not found, assuming no system installed ruby."
+    else
+      ruby -r rubygems -e "puts Gem::default_path.compact[1] || Gem::default_path.compact.first" > $rvm_install_path/default_system_gem_path
+    else
+    fi
   fi
 
   if [ -s $rvm_install_path/default_system_ruby ] ; then
@@ -249,8 +260,8 @@ function __rvm_run {
   log_file_name="1" ; shift
   command="$*"
   if [ $rvm_debug ] ; then __rvm_log "debug" "Executing: $command" ; fi
-  eval "nice -n $rvm_niceness $command" > $rvm_ruby_log_path/log_file_name.log 2> $rvm_ruby_log_path/log_file_name.error.log
-  if [ $? -gt 0 ] ; then __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/log_file_name.error.log" ; popd 2> /dev/null ; return 1 ; fi
+  eval "nice -n $rvm_niceness $command" > $rvm_ruby_log_path/$log_file_name.log 2> $rvm_ruby_log_path/$log_file_name.error.log
+  if [ $? -gt 0 ] ; then __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/$log_file_name.error.log" ; popd 2> /dev/null ; return 1 ; fi
   unset log_file command
 }
 
