loading default and proejct ruby on rvm startup, update #2531

diff --git a/scripts/rvm b/scripts/rvm
--- a/scripts/rvm
+++ b/scripts/rvm
@@ -112,9 +112,11 @@ else
   rvm_loaded_flag=0
 fi
 
-if (( ${rvm_loaded_flag:=0} == 0 )) || (( ${rvm_reload_flag:=0} == 1 ))
+if
+  (( ${rvm_loaded_flag:=0} == 0 )) || (( ${rvm_reload_flag:=0} == 1 ))
 then
-  if [[ -n "${rvm_path}" && -d "$rvm_path" ]]
+  if
+    [[ -n "${rvm_path}" && -d "$rvm_path" ]]
   then
     true ${rvm_scripts_path:="$rvm_path/scripts"}
 
@@ -141,28 +143,30 @@ then
       builtin command -v ruby | __rvm_grep -v "${rvm_path}" >/dev/null ||
       builtin command -v ruby | __rvm_grep "${rvm_path}/bin/ruby$" >/dev/null
     then
-      if
-        [[ -s "$rvm_environments_path/default" && "${rvm_action}" != "switch" ]]
-      then
-        __rvm_load_environment "default"
-      elif
-        [[ -s "$rvm_path/environments/default" ]]
-      then
-        source "$rvm_path/environments/default"
+      if [[ -s "$rvm_path/environments/default" ]]
+      then source "$rvm_path/environments/default"
       fi
       if
-        [[ "${PWD%/}" != "${HOME%/}" ]] &&
-        __rvm_project_dir_check .
+        [[ -t 0 && ${rvm_project_rvmrc:-1} -gt 0 ]] &&
+        ! __function_on_stack __rvm_project_rvmrc
       then
-        __rvm_rvmrc_tools try_to_read_ruby . ||
-        __rvm_parse_args_error_finding_project_file
+        # Reload the rvmrc, use promptless ensuring shell processes does not
+        # prompt if .rvmrc trust value is not stored, revert to default on fail
+        if
+          rvm_current_rvmrc=""
+          rvm_project_rvmrc_default=1 rvm_promptless=1 __rvm_project_rvmrc
+        then
+          rvm_hook=after_cd
+          source "${rvm_scripts_path:-${rvm_path}/scripts}/hook"
+        fi
       fi
     fi
 
     # Makes sure rvm_bin_path is in PATH atleast once.
     __rvm_conditionally_add_bin_path
 
-    if (( ${rvm_reload_flag:=0} == 1 ))
+    if
+      (( ${rvm_reload_flag:=0} == 1 ))
     then
       [[ "${rvm_auto_reload_flag:-0}" == 2 ]] || printf "%b" 'RVM reloaded!\n'
       # make sure we clean env on reload
@@ -171,28 +175,9 @@ then
     fi
 
     rvm_loaded_flag=1
+    __rvm_teardown
   else
     printf "%b" "\n\$rvm_path ($rvm_path) does not exist."
   fi
-  unset rvm_prefix_needs_trailing_slash rvm_gems_cache_path \
-    rvm_gems_path rvm_project_rvmrc_default rvm_gemset_separator rvm_reload_flag
-else
-  source "${rvm_scripts_path:="$rvm_path/scripts"}/initialize"
-  __rvm_setup
-  __rvm_fix_path_from_gem_path
-  __rvm_clean_path
+  unset rvm_prefix_needs_trailing_slash rvm_gems_cache_path rvm_gems_path rvm_project_rvmrc_default rvm_gemset_separator rvm_reload_flag
 fi
-
-if [[ -t 0 && ${rvm_project_rvmrc:-1} -gt 0 ]] &&
-  rvm_is_a_shell_function no_warning &&
-  ! __function_on_stack __rvm_project_rvmrc &&
-  typeset -f __rvm_project_rvmrc >/dev/null 2>&1
-then
-  # Reload the rvmrc, use promptless ensuring shell processes does not
-  # prompt if .rvmrc trust value is not stored.
-  rvm_promptless=1 __rvm_project_rvmrc
-  rvm_hook=after_cd
-  source "${rvm_scripts_path:-${rvm_path}/scripts}/hook"
-fi
-
-__rvm_teardown
