rvm <selector> -S <scriptname.rb> now works. Bugfix: ree now uses -C args passed in, Thanks chewie71.

diff --git a/scripts/rvm-utility b/scripts/rvm-utility
--- a/scripts/rvm-utility
+++ b/scripts/rvm-utility
@@ -69,9 +69,9 @@ function __rvm_usage {
     -r|--rev        - Specify the repository revision # to use or 'head' for
 
     -P|--prefix     - Sets the prefix path for installs to be installed to
-    -B|--bin        - Specify path for binaries to be placed
-    -S|--source     - Specify src directory to use
-    -A|--archive    - Specify archive directory to use (tabralls / zips)
+       --bin        - Specify path for binaries to be placed
+       --source     - Specify src directory to use
+       --archive    - Specify archive directory to use (tabralls / zips)
     -G|--gems       - Specify root gem path to use
     -C|--configure  - Specify custom configure options, comma separated
                       default: --enable-shared=true
@@ -84,6 +84,7 @@ function __rvm_usage {
     -h|--help       - Emit this output and exit
     -d|--default    - Set the default Ruby to a specified version
     -m|--gem-set    - Use a named gem set instead of the default set.
+    -S|--script     - Specify a script file to attempt to load and run (rubydo)
     --all           - Used with 'rvm list' to list "most" installable versions.
     --rm-gem-set    - Remove a named gem set
     --jit           - Enable JIT for the Rubinius build
@@ -185,7 +186,7 @@ function __rvm_run {
 }
 
 function __rvm_cleanup-variables {
-  unset rvm_selected rvm_action rvm_ruby_interpreter rvm_ruby_patch_level rvm_ruby_version rvm_irbrc_file rvm_ruby_irbrc rvm_source_path rvm_path rvm_debug rvm_prefix_path rvm_ruby_package_name rvm_gem_path rvm_command rvm_error_message rvm_ruby_home rvm_ruby_binary rvm_gem_set_name rvm_delete_flag rvm_ruby_tag rvm_ruby_rev rvm_url rvm_ruby_make rvm_ruby_make_install rvm_config_path rvm_bin_path rvm_force rvm_all rvm_re_configure
+  unset rvm_selected rvm_action rvm_ruby_interpreter rvm_ruby_patch_level rvm_ruby_version rvm_irbrc_file rvm_ruby_irbrc rvm_source_path rvm_path rvm_debug rvm_prefix_path rvm_ruby_package_name rvm_gem_path rvm_command rvm_error_message rvm_ruby_home rvm_ruby_binary rvm_gem_set_name rvm_delete_flag rvm_ruby_tag rvm_ruby_rev rvm_url rvm_ruby_make rvm_ruby_make_install rvm_config_path rvm_bin_path rvm_force rvm_all rvm_re_configure rvm_do_summary
 }
 
 # TODO: root user loadng of /etc/rvmrc
@@ -195,10 +196,11 @@ function __rvm_load-rvmrc {
 
 function __rvm_bin_scripts {
   if [ -z "$rvm_selected" ] ; then __rvm_select $* ; fi
-
-ruby_wrapper=$(cat <<-RubyWrapper
+ruby_wrapper=$(cat <<RubyWrapper
 #!/bin/bash
-puts "rvm installed ruby binaries should *not* be run as the root user (yet): http://rvm.beginrescueend.com/faq/" if (`whoami`.strip == "root")
+if [ "`whoami`" = "root" ] ; then
+  echo "rvm installed ruby binaries should *not* be run as the root user, yet: http://rvm.beginrescueend.com/faq/"
+fi
 GEM_HOME=$rvm_gem_home ; export GEM_HOME
 MY_RUBY_HOME=$rvm_ruby_home ; export MY_RUBY_HOME
 PATH=$rvm_ruby_home/bin:$rvm_gem_home/bin:\$PATH ; export PATH
@@ -579,6 +581,7 @@ function __rvm_reload {
 }
 
 function __rvm_do {
+  successes=() ; errors=()
   if [ ! -z "$rvm_ruby_version" ] ; then
     rvm_ruby_versions=$(echo $rvm_ruby_version | tr ',' ' ')
     for rvm_ruby_version in $rvm_ruby_versions ; do
@@ -593,8 +596,13 @@ function __rvm_do {
       __rvm_select $rvm_ruby_interpreter $rvm_ruby_version
       binary=`echo $rvm_action | sed 's/do$//'`
       rvm_command="$rvm_ruby_home/bin/$binary $rvm_ruby_args"
-      echo "$(basename $rvm_ruby_home/bin/$binary):"
+      echo "$(dirname $rvm_ruby_home/bin/$binary | xargs dirname | xargs basename): $($rvm_ruby_home/bin/$binary -v)"
       eval $rvm_command
+      if [ $? = 0 ]; then
+        successes[${#successes[*]}]=$name
+      else
+        errors[${#errors[*]}]=$name
+      fi
       unset rvm_ruby_interpreter rvm_ruby_patch_level rvm_ruby_version rvm_ruby_package_name rvm_ruby_home rvm_ruby_irbrc rvm_ruby_binary
     done
   else # all
@@ -604,8 +612,23 @@ function __rvm_do {
         rvm_command="$rvm_ruby_binary $rvm_ruby_args"
         echo "$(basename $rvm_ruby_binary):"
         eval $rvm_command
+        if [ $? = 0 ]; then
+          successes[${#successes[*]}]=$name
+        else
+          errors[${#errors[*]}]=$name
+        fi
       fi
     done
+  fi
+
+  if [ ! -z "$rvm_do_summary" ] ; then
+    echo "Successful: ${successes[@]}"
+    echo "Errors: ${errors[@]}"
+    unset binary successes errors rvm_do_summary
+    return ${#errors[@]}
+  else
+    unset binary successes errors rvm_do_summary
+    return 0
   fi
 }
 
@@ -634,3 +657,4 @@ Config
   fi
 
 }
+
