Bugfix: patch level. Check for non-existant url and issue error message if so.

diff --git a/scripts/rvm-utility b/scripts/rvm-utility
--- a/scripts/rvm-utility
+++ b/scripts/rvm-utility
@@ -133,9 +133,16 @@ function __rvm_fetch {
 
   pushd $rvm_archives_path > /dev/null
   eval $rvm_fetch "$1"
-  if [ $? -gt 0 ] ; then __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; popd > /dev/null ; return 1 ; fi
+  status=$?
+  if [ $status -gt 0 ] ; then
+    if [ $status -eq 78 ] ; then
+      __rvm_log "error" "The requested url does not exist: '$1'"
+    else
+      __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
+    fi
+  fi
   popd 2> /dev/null
-
+  return $status
 }
 
 function __rvm_load-defaults {
