--summary now works with -S.

diff --git a/scripts/rvm-utility b/scripts/rvm-utility
--- a/scripts/rvm-utility
+++ b/scripts/rvm-utility
@@ -596,36 +596,38 @@ function __rvm_do {
       __rvm_select $rvm_ruby_interpreter $rvm_ruby_version
       binary=`echo $rvm_action | sed 's/do$//'`
       rvm_command="$rvm_ruby_home/bin/$binary $rvm_ruby_args"
-      echo "$(dirname $rvm_ruby_home/bin/$binary | xargs dirname | xargs basename): $($rvm_ruby_home/bin/$binary -v)"
+      rvm_ruby_string="$(dirname $rvm_ruby_home/bin/$binary | xargs dirname | xargs basename)"
+      echo "$rvm_ruby_string: $($rvm_ruby_home/bin/$binary -v)"
       eval $rvm_command
-      if [ $? = 0 ]; then
-        successes[${#successes[*]}]=$name
+      if [ $? -eq 0 ]; then
+        successes[${#successes[*]}]=$rvm_ruby_string
       else
-        errors[${#errors[*]}]=$name
+        errors[${#errors[*]}]=$rvm_ruby_string
       fi
-      unset rvm_ruby_interpreter rvm_ruby_patch_level rvm_ruby_version rvm_ruby_package_name rvm_ruby_home rvm_ruby_irbrc rvm_ruby_binary
+      unset rvm_ruby_interpreter rvm_ruby_patch_level rvm_ruby_version rvm_ruby_package_name rvm_ruby_home rvm_ruby_irbrc rvm_ruby_binary rvm_ruby_string
     done
   else # all
     rvm_ruby_versions=`/bin/ls $rvm_bin_path/ruby-*`
     for rvm_ruby_binary in $rvm_ruby_versions ; do
       if [ -x $rvm_ruby_binary ] ; then
         rvm_command="$rvm_ruby_binary $rvm_ruby_args"
+        rvm_ruby_string="$(dirname $rvm_ruby_home/bin/$binary | xargs dirname | xargs basename)"
         echo "$(basename $rvm_ruby_binary):"
         eval $rvm_command
-        if [ $? = 0 ]; then
-          successes[${#successes[*]}]=$name
+        if [ $? -eq 0 ]; then
+          successes[${#successes[*]}]=$rvm_ruby_string
         else
-          errors[${#errors[*]}]=$name
+          errors[${#errors[*]}]=$rvm_ruby_string
         fi
       fi
     done
   fi
 
   if [ ! -z "$rvm_summary" ] ; then
-    echo "Successful: $(echo $successes[@])"
-    echo "Errors: $(echo $errors[@])"
-    unset binary successes errors rvm_summary
-    return ${#errors[@]}
+    echo -e "\nsuccessful (${#successes[*]}) : [ $(echo "${successes[*]}" | sed 's/ /, /g') ]"
+    echo -e "\nerrors (${#errors[*]}) : [ $(echo "${errors[*]}" | sed 's/ /, /g') ]\n"
+    # unset binary successes errors rvm_summary
+    return ${#errors[*]}
   else
     unset binary successes errors rvm_summary
     return 0
