Bugfix: rbx install. Bugfix: Check if user has unzip for jruby installs and show warning if not. Minor site updates.

diff --git a/scripts/rvm-ruby-installer b/scripts/rvm-ruby-installer
--- a/scripts/rvm-ruby-installer
+++ b/scripts/rvm-ruby-installer
@@ -234,7 +234,9 @@ function __rvm_install-ruby {
       ;;
 
     rbx|rubinius)
-      __rvm_reset # Requires 1.8 to install due to parsetree. TOOD: Check for 1.8 + parse-tree
+      # TODO: check if system is 1.8.X otherwise use rvm's 1.8.X and check for parsetree, install if missing
+      unset GEM_HOME MY_RUBY_HOME IRBRC
+      PATH="$rvm_default_path" ; export PATH
       rvm_ruby_repo_url=$rvm_rubinius_repo_url
       rvm_ruby_configure=""
       rvm_ruby_make="rake"
@@ -274,7 +276,12 @@ function __rvm_install-ruby {
           __rvm_log "info" "\tDownloading $rvm_package_file, this may take a while depending on your connection..."
           __rvm_fetch $rvm_url
           __rvm_log "info" "\tExtracting $rvm_package_file..."
-          __rvm_run "extract" unzip -q $rvm_archives_path/$rvm_package_file.zip -d $rvm_source_path
+          rvm_unzip=`which unzip`
+          if [ $? -ne 0 ] ; then
+            __rvm_log "error" "\t'unzip' was not found in your PATH. jRuby official release comes as a .zip file, hence 'unzip' is required to extract it. Please install 'unzip' and try again."
+          else
+            __rvm_run "extract" unzip -q $rvm_archives_path/$rvm_package_file.zip -d $rvm_source_path
+          fi
           cd $rvm_ruby_src_path
         fi
       fi
