if [ 'zsh' = 'daft' ] ; do sed -i s/status/result/g ; done

diff --git a/scripts/rvm-ruby-installer b/scripts/rvm-ruby-installer
--- a/scripts/rvm-ruby-installer
+++ b/scripts/rvm-ruby-installer
@@ -4,7 +4,7 @@ function __rvm_install-source {
 
   if [ -z "$rvm_selected" ] ; then __rvm_select $* ; fi
 
-  status=0
+  result=0
   __rvm_log "info" "Installing Ruby from source to: $rvm_ruby_home"
   mkdir -p $rvm_ruby_log_path
 
@@ -20,11 +20,11 @@ function __rvm_install-source {
       rvm_url="${rvm_url:-"ftp://ftp.ruby-lang.org/pub/ruby/1.$rvm_major_version/$rvm_ruby_package_name.tar.gz"}"
       __rvm_log "info" "\tDownloading $rvm_ruby_package_name, this may take a while depending on your connection..."
       __rvm_fetch $rvm_url
-      if [ $? -gt 0 ] ; then status=$? ; return $status ; fi
+      if [ $? -gt 0 ] ; then result=$? ; return $result ; fi
       __rvm_log "info" "\tExtracting $rvm_ruby_package_name ..."
       mkdir -p $rvm_ruby_src_path # Is this line necessary considering -C below?    v
       __rvm_run "extract" tar xzf $rvm_archives_path/$rvm_ruby_package_name.tar.gz -C $rvm_source_path
-      if [ $? -gt 0 ] ; then status=$? ; return $status ; fi
+      if [ $? -gt 0 ] ; then result=$? ; return $result ; fi
     fi
   else
     __rvm_log "info" "\tRetrieving Ruby from $rvm_url"
@@ -33,14 +33,14 @@ function __rvm_install-source {
         cd $rvm_ruby_src_path
         if [ -z "$rvm_ruby_rev" ] ; then
           git pull origin master
-          if [ $? -gt 0 ] ; then status=$? ; return $status ; fi
+          if [ $? -gt 0 ] ; then result=$? ; return $result ; fi
         else
           git checkout ${rvm_ruby_rev:-HEAD}
-          if [ $? -gt 0 ] ; then status=$? ; return $status ; fi
+          if [ $? -gt 0 ] ; then result=$? ; return $result ; fi
         fi
       else
         git clone --depth 1 $rvm_ruby_repo_url $rvm_ruby_src_path
-        if [ $? -gt 0 ] ; then status=$? ; return $status ; fi
+        if [ $? -gt 0 ] ; then result=$? ; return $result ; fi
       fi
     else
       if [ -z "$rvm_ruby_rev" ] ; then
@@ -67,21 +67,21 @@ function __rvm_install-source {
       else
         svn checkout -q $rvm_rev --force $rvm_url $rvm_ruby_src_path
       fi
-      if [ $? -gt 0 ] ; then status=$? ; return $status ; fi
+      if [ $? -gt 0 ] ; then result=$? ; return $result ; fi
     fi
   fi
 
   cd $rvm_ruby_src_path
-  if [ $? -gt 0 ] ; then status=$? ; __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; popd > /dev/null ; return $status ; fi
+  if [ $? -gt 0 ] ; then result=$? ; __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; popd > /dev/null ; return $result ; fi
 
   # Readline
   if [ ! -d $rvm_path/usr/include/readline ] ; then __rvm_readline_install ; fi
 
   if [ ! -s "$rvm_ruby_src_path/configure" -a "$rvm_ruby_interpreter" = "ruby" ] ; then
     rvm_autoconf=`which autoconf`
-    if [ $? -gt 0 ] ; then __rvm_log "fail" "rvm expects autoconf" ; status=$? ; return $status ; fi
+    if [ $? -gt 0 ] ; then __rvm_log "fail" "rvm expects autoconf" ; result=$? ; return $result ; fi
     __rvm_run "autoconf" $rvm_autoconf
-    if [ $? -gt 0 ] ; then status=$? ; return $status ; fi
+    if [ $? -gt 0 ] ; then result=$? ; return $result ; fi
   fi
 
   if [ -s ./Makefile -a -z "$rvm_re_configure" ] ; then
@@ -96,7 +96,7 @@ function __rvm_install-source {
     fi
     __rvm_run "configure" "./configure --prefix=$rvm_ruby_home --enable-shared=true $rvm_ruby_configure $parameters"
     unset parameters
-    if [ $? -gt 0 ] ; then status=$? ; return $status ; fi
+    if [ $? -gt 0 ] ; then result=$? ; return $result ; fi
   else
     __rvm_log "error" "\tSkipping configure step, 'configure' script does not exist, did autoconf not run successfully?"
   fi
@@ -107,7 +107,7 @@ function __rvm_install-source {
   else
     __rvm_run "make" $rvm_ruby_make
   fi
-  if [ $? -gt 0 ] ; then status=$? ; return $status ; fi
+  if [ $? -gt 0 ] ; then result=$? ; return $result ; fi
 
   if [ -z "$rvm_ruby_make" ] ; then
     __rvm_log "info" "\tInstalling $rvm_ruby_package_name"
@@ -115,7 +115,7 @@ function __rvm_install-source {
   else
     __rvm_run "install" $rvm_ruby_make_install
   fi
-  if [ $? -gt 0 ] ; then status=$? ; return $status ; fi
+  if [ $? -gt 0 ] ; then result=$? ; return $result ; fi
 
   __rvm_run "chmod.bin" chmod +x $rvm_ruby_home/bin/*
   __rvm_bin_script
@@ -381,11 +381,11 @@ function __rvm_rubygems_setup {
     #sed -i.orig "s/require_paths\.join/require_paths.to_a.join/" $rvm_source_path/$rvm_gem_package_name/lib/rubygems/gem_path_searcher.rb
     #rm -f $rvm_source_path/$rvm_gem_package_name/lib/rubygems/gem_path_searcher.rb.orig
     __rvm_run "rubygems.install" GEM_HOME=$rvm_gem_path GEM_HOME=$rvm_gem_home $rvm_ruby_home/bin/ruby $rvm_source_path/$rvm_gem_package_name/setup.rb
-    status=$?
-    if [ $status -eq 0 ] ; then
+    result=$?
+    if [ $result -eq 0 ] ; then
       __rvm_log "info" "Installation of rubygems $rvm_ruby_package_name completed successfully."
     fi
-    if [ $status -eq 0 ] ; then status=$? ; fi
+    if [ $result -eq 0 ] ; then result=$? ; fi
   else
     # 1.9 has it's own built gem command, let's adjust the shebang line.
     mv $rvm_ruby_src_path/bin/gem $rvm_ruby_src_path/bin/gem.orig
@@ -394,6 +394,6 @@ function __rvm_rubygems_setup {
     __rvm_run "rubygems.update" $rvm_ruby_home/bin/gem update --system
   fi
 
-  return $status
+  return $result
 }
 
