moving forward with readline.

diff --git a/scripts/rvm-ruby-installer b/scripts/rvm-ruby-installer
--- a/scripts/rvm-ruby-installer
+++ b/scripts/rvm-ruby-installer
@@ -72,7 +72,7 @@ function __rvm_install-source {
   fi
 
   cd $rvm_ruby_src_path
-  if [ $? -gt 0 ] ; then __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; popd 2> /dev/null ; return 1 ; fi
+  if [ $? -gt 0 ] ; then __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; popd > /dev/null ; return 1 ; fi
 
   if [ ! -s "$rvm_ruby_src_path/configure" -a "$rvm_ruby_interpreter" = "ruby" ] ; then
     rvm_autoconf=`which autoconf`
@@ -81,7 +81,7 @@ function __rvm_install-source {
     if [ $status -eq 0 ] ; then status=$? ; fi
   fi
 
-  if [ $? -gt 0 ] ; then __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; popd 2> /dev/null ; return 1 ; fi
+  if [ $? -gt 0 ] ; then __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; popd > /dev/null ; return 1 ; fi
 
   if [ -s ./Makefile -a -z "$rvm_re_configure" ] ; then
     __rvm_log "warn" "\tSkipping configure step, Makefile exists so configure must have already been run."
@@ -125,7 +125,7 @@ function __rvm_install-source {
     cat $rvm_ruby_src_path/bin/gem.orig | sed -e "s=!# */usr/bin/env ruby=!#/usr/bin/$rvm_ruby_home/bin/ruby=" > $rvm_ruby_src_path/bin/gem
     chmod +x $rvm_ruby_home/bin/gem
   fi
-  popd 2> /dev/null
+  popd > /dev/null
 
   __rvm_post_install
 }
@@ -180,7 +180,7 @@ function __rvm_install-ruby {
       else
         __rvm_log "info" "\tDownloading $rvm_ruby_package_name, this may take a while depending on your connection..."
         __rvm_fetch $rvm_url
-        if [ $? -gt 0 ] ; then __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; popd 2> /dev/null ; return 1 ; fi
+        if [ $? -gt 0 ] ; then __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; popd > /dev/null ; return 1 ; fi
         __rvm_log "info" "\tExtracting $rvm_ruby_package_name..."
         mkdir -p $rvm_ruby_src_path
         __rvm_run "extract" tar xzf $rvm_archives_path/$rvm_ruby_package_name.tar.gz -C $rvm_source_path
@@ -212,7 +212,7 @@ function __rvm_install-ruby {
 
       __rvm_run "rubygems.install" $rvm_ruby_home/bin/ruby $rvm_source_path/$rvm_gem_package_name/setup.rb
       __rvm_log "info" "Installation of $rvm_ruby_package_name complete."
-      popd 2> /dev/null
+      popd > /dev/null
 
       for rvm_gem_name in rake ; do
         __rvm_log "info" "Installing $rvm_gem_name"
@@ -281,7 +281,7 @@ function __rvm_install-ruby {
       mkdir -p $rvm_ruby_home/bin/
       __rvm_run "sync" rsync -ag $rvm_ruby_src_path/ $rvm_ruby_home/
       __rvm_run "nailgun" cd $rvm_ruby_src_path/tool/nailgun && make $rvm_make_flags
-      popd 2> /dev/null
+      popd > /dev/null
       chmod +x $rvm_ruby_home/bin/*
       for binary in jruby jgem jirb ; do
         ln -fs $rvm_ruby_home/bin/$binary $rvm_ruby_home/bin/${binary#j}
diff --git a/scripts/rvm-utility b/scripts/rvm-utility
--- a/scripts/rvm-utility
+++ b/scripts/rvm-utility
@@ -5,7 +5,7 @@ function __rvm_meta {
   rvm_meta_author_email="wayneeseguin@gmail.com"
   rvm_meta_website="http://rvm.beginrescueend.com/"
   rvm_meta_version="`cat $rvm_path/VERSION.yml | tail -n 3 | sed 's/^.*: //g' | tr "\n" '.' | sed 's/\.$//'`"
-  rvm_meta_updated="2009.09.10"
+  rvm_meta_updated="2009.09.14"
 }
 
 function __rvm_version { __rvm_meta ; echo "rvm $rvm_meta_version ($rvm_meta_updated) [$rvm_meta_website]" ; }
@@ -176,6 +176,7 @@ function __rvm_gi { gem install -q --no-rdoc --no-ri $* ; }
 function __rvm_run {
   log_file_name="$1" ; shift
   command="$*"
+  rvm_ruby_log_path=${rvm_ruby_log_path:-$rvm_path/log}
   mkdir -p $rvm_ruby_log_path
   if [ $rvm_debug ] ; then __rvm_log "debug" "Executing: $command" ; fi
   touch $rvm_ruby_log_path/$log_file_name.log $rvm_ruby_log_path/$log_file_name.error.log # for zsh :(
@@ -233,7 +234,7 @@ function __rvm_fetch {
 
   pushd $rvm_archives_path > /dev/null
   eval $rvm_fetch "$1"
-  if [ $? -gt 0 ] ; then __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; popd 2> /dev/null ; return 1 ; fi
+  if [ $? -gt 0 ] ; then __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log" ; popd > /dev/null ; return 1 ; fi
   popd 2> /dev/null
 
 }
@@ -811,9 +812,11 @@ function __rvm_readline_install {
   version=5.2
   # TODO: Figure out how to list, grab and apply the patches
   __rvm_fetch "ftp://ftp.gnu.org/gnu/readline/$package-$version.tar.gz"
-  tar zxf $rvm_archives_path/$package-$version.tar.gz -C $rvm_path/src/ && cd $rvm_path/src/$package-$version
-  ./configure --prefix=$rvm_path/usr --disable-shared
-  make clean && make && make install
+  __rvm_run "extract" tar zxf $rvm_archives_path/$package-$version.tar.gz -C $rvm_path/src/
+  cd $rvm_path/src/$package-$version
+  __rvm_run "configure" ./configure --prefix=$rvm_path/usr --disable-dependency-tracking --disable-static --enable-shared
+  __rvm_run "$package.make" make
+  __rvm_run "$package.make.install" make install
   popd > /dev/null
 }
 
@@ -823,8 +826,12 @@ function __rvm_iconv_install {
   package=libiconv
   version=1.13.1
   __rvm_fetch "http://ftp.gnu.org/pub/gnu/libiconv/$package-$version.tar.gz"
-  tar zxf $rvm_archives_path/$package-$version.tar.gz -C $rvm_dir/src/ && cd $rvm_path/src/$package-$version
-  ./configure --prefix=$rvm_path/usr --disable-shared && make -j2 && make install
+  __rvm_run "$package.extract" tar zxf $rvm_archives_path/$package-$version.tar.gz -C $rvm_dir/src/
+  cd $rvm_path/src/$package-$version
+  __rvm_run "$package.configure" ./configure --prefix=$rvm_path/usr --disable-shared
+  __rvm_run "$package.make" make
+  __rvm_run "$package.make.install" make install
+
   popd > /dev/null
 }
 
