Performance improvement centered around the selector.

diff --git a/scripts/selector b/scripts/selector
--- a/scripts/selector
+++ b/scripts/selector
@@ -157,8 +157,9 @@ __rvm_select()
         fi
       fi
 
-      if ! "$rvm_path/scripts/match" "$rvm_ruby_version" "^1\.8" ; then
-        "$rvm_path/scripts/log" "fail" "Unknown Ruby Enterprise Edition version: $rvm_ruby_version"
+      if ! match "$rvm_ruby_version" "1\.8*" ; then
+        "$rvm_path/scripts/log" "fail" \
+          "Unknown Ruby Enterprise Edition version: $rvm_ruby_version"
       fi
     ;;
 
@@ -188,7 +189,7 @@ __rvm_select()
     current)
       ruby_binary="$(command -v ruby)"
 
-      if [[ $? -eq 0 ]] && "$rvm_path/scripts/match" "$ruby_binary" "rvm" ; then
+      if [[ $? -eq 0 ]] && match "$ruby_binary" "*rvm*" ; then
         rvm_ruby_string="$(dirname "$ruby_binary" | xargs dirname | xargs basename)"
 
       else
@@ -574,7 +575,7 @@ __rvm_ruby_string()
               "Unknown ruby interpreter version: '$string'"
             return 1
             ;;
-          esac
+        esac
 
         ;;
 
@@ -582,8 +583,7 @@ __rvm_ruby_string()
         rvm_ruby_patch_level="$string"
         ;;
 
-        #elif [[ -n "${rvm_ruby_version:-""}" ]] && "$rvm_path/scripts/match" "$string" "^
-        [[:digit:]][[:digit:]]*)
+      [[:digit:]][[:digit:]]*)
 
         case "${rvm_ruby_interpreter:-""}" in
           ree)
