Bugfix: rvm gemset copy a@b c@d

diff --git a/scripts/set b/scripts/set
--- a/scripts/set
+++ b/scripts/set
@@ -2,11 +2,6 @@
 
 source "$rvm_scripts_path/base"
 
-if [[ -z "$1" ]] ; then
-  "$rvm_scripts_path/log" "error" "Action must be specified."
-  exit 1
-fi
-
 __rvm_attempt_single_exec() {
   # Return if we have multiple rubies. or we're not running exec.
   local ruby_string_lines="$(printf "$rvm_ruby_strings" | wc -l | __rvm_strip)"
@@ -140,11 +135,11 @@ __rvm_yaml() {
 
 # Output the summary in a json format.
 __rvm_json() {
-  json="{"
-  json="$json\n  \"totals\": { \"rubies\": ${#rubies[*]}, \"successes\": ${#successes[*]}, \"errors\": ${#errors[*]} },"
-  json="$json\n  \"successful\": [$(echo \"${successes[*]}\" | sed 's# #", "#g' | sed 's#\"\"##')],"
-  json="$json\n  \"errors\": [$(echo \"${errors[*]}\" | sed 's# #", "#g' | sed 's#\"\"##')],"
-  json="$json\n  \"rubies\": {"
+  json="{
+\"totals\": { \"rubies\": ${#rubies[*]}, \"successes\": ${#successes[*]}, \"errors\": ${#errors[*]} },
+\"successful\": [$(echo \"${successes[*]}\" | sed 's# #", "#g' | sed 's#\"\"##')],
+\"errors\": [$(echo \"${errors[*]}\" | sed 's# #", "#g' | sed 's#\"\"##')],
+\"rubies\": { "
 
   total=${#rubies[*]}
   if [[ -n "${ZSH_VERSION:-""}" ]] ; then array_start=1 ; else array_start=0 ; fi
@@ -173,6 +168,11 @@ args=($*)
 action="${args[0]}"
 args=${args[@]:1}
 
+if [[ -z "$action" ]] ; then
+  "$rvm_scripts_path/log" "error" "Action must be specified."
+  exit 1
+fi
+
 if [[ "$action" == "ruby" ]] && echo "$args" | \grep -q  "^'--[^[:space:]]*'$" ; then
   "$rvm_scripts_path/log" "warn" "You called rvm ruby with the arguments $args which look like use options."
   "$rvm_scripts_path/log" "warn" "Please note that 'rvm ruby' invokes set operations instead."
@@ -185,7 +185,7 @@ __rvm_attempt_single_exec
 
 for current_set_ruby in ${rvm_ruby_strings} ; do
   __rvm_ruby_do
-done; unset current_set_ruby
+done
 
 if [[ ! -z "$rvm_summary_flag" ]] ; then __rvm_summary ; fi
 if [[ ! -z "$rvm_yaml_flag" ]]    ; then __rvm_yaml    ; fi
