Blasted aliases.

diff --git a/scripts/utility b/scripts/utility
--- a/scripts/utility
+++ b/scripts/utility
@@ -46,10 +46,10 @@ __rvm_dump_environment() {
   local dump_environment_type="$(echo "$rvm_dump_environment_flag" | awk -F, '{print $2}')"
   if [[ -n "$dump_environment_file" && -n "$dump_environment_type" ]]; then
     if [[ "$dump_environment_type" == "atheis"* ]]; then
-      rm -rf "$dump_environment_file" && ln -s /dev/null "$dump_environment_file" >/dev/null 2>&1
+      \rm -rf "$dump_environment_file" && ln -s /dev/null "$dump_environment_file" >/dev/null 2>&1
     else
       $rvm_scripts_path/environment-convertor "$dump_environment_type" "$(__rvm_environment_identifier)" > "$dump_environment_file"
-      [[ "$?" -gt 0 ]] && rm -rf "$dump_environment_file"
+      [[ "$?" -gt 0 ]] && \rm -rf "$dump_environment_file"
     fi
   fi
   unset rvm_dump_environment_flag
@@ -173,8 +173,8 @@ __rvm_run() {
     $rvm_scripts_path/log "debug" "Executing: $command"
   fi
 
-  mkdir -p "$(dirname "$rvm_ruby_log_path/$log_file_name.log")"
-  touch "$rvm_ruby_log_path/$log_file_name.log" "$rvm_ruby_log_path/$log_file_name.error.log" # for zsh :(
+  \mkdir -p "$(dirname "$rvm_ruby_log_path/$log_file_name.log")"
+  \touch "$rvm_ruby_log_path/$log_file_name.log" "$rvm_ruby_log_path/$log_file_name.error.log" # for zsh :(
   echo "[$(date +'%Y-%m-%d %H:%M:%S')] $command" | tee "$rvm_ruby_log_path/$log_file_name.log" >> "$rvm_ruby_log_path/$log_file_name.error.log"
   if [[ -z "$rvm_niceness" ]] || [[ "0" = "$rvm_niceness" ]] ; then
     eval "$command" >> "$rvm_ruby_log_path/$log_file_name.log" 2>> "$rvm_ruby_log_path/$log_file_name.error.log"
@@ -195,8 +195,8 @@ __rvm_run_with_env() {
     $rvm_scripts_path/log "debug" "Executing: $command in environment "$env_name""
   fi
 
-  mkdir -p "$(dirname "$rvm_ruby_log_path/$log_file_name.log")"
-  touch "$rvm_ruby_log_path/$log_file_name.log" "$rvm_ruby_log_path/$log_file_name.error.log" # for zsh :(
+  \mkdir -p "$(dirname "$rvm_ruby_log_path/$log_file_name.log")"
+  \touch "$rvm_ruby_log_path/$log_file_name.log" "$rvm_ruby_log_path/$log_file_name.error.log" # for zsh :(
   echo "[$(date +'%Y-%m-%d %H:%M:%S')] $command # under $env_name" | tee "$rvm_ruby_log_path/$log_file_name.log" >> "$rvm_ruby_log_path/$log_file_name.error.log"
   if [[ -z "$rvm_niceness" ]] || [[ "0" = "$rvm_niceness" ]] ; then
     eval "__rvm_with_env '$env_name' '$command'" >> "$rvm_ruby_log_path/$log_file_name.log" 2>> "$rvm_ruby_log_path/$log_file_name.error.log"
@@ -273,7 +273,7 @@ __rvm_inherit_trace_flag() {
 __rvm_cleanup_temp_for() {
   [[ -z "$1" ]] && return 1
   if [[ -d "$rvm_tmp_path/" ]]; then
-    rm -rf "$rvm_tmp_path/$1"* >/dev/null 2>&1
+    \rm -rf "$rvm_tmp_path/$1"* >/dev/null 2>&1
   fi
   exit
 }
@@ -360,13 +360,13 @@ __rvm_reset() {
   PATH="$(echo $PATH | \tr ':' '\n' | awk '$0 !~ /rvm/' | paste -sd : -)"
   PATH="$rvm_bin_path:$PATH" ; export PATH
 
-  for flag in default passenger editor ; do rm -f "$rvm_bin_path"/${flag}_* ; done
+  for flag in default passenger editor ; do \rm -f "$rvm_bin_path"/${flag}_* ; done
   unset flag
 
   for file in system default ; do
-    [[ -f "${rvm_path}/${file}" ]] && rm -f "$rvm_path/${file}"
-    [[ -f "${rvm_config_path}/${file}" ]] && rm -f "$rvm_config_path/${file}"
-    [[ -f "${rvm_environments_path}/${file}" ]] && rm -f "$rvm_environments_path/${file}"
+    [[ -f "${rvm_path}/${file}" ]] && \rm -f "$rvm_path/${file}"
+    [[ -f "${rvm_config_path}/${file}" ]] && \rm -f "$rvm_config_path/${file}"
+    [[ -f "${rvm_environments_path}/${file}" ]] && \rm -f "$rvm_environments_path/${file}"
   done; unset file
 
   # Go back to a clean state.
@@ -377,7 +377,7 @@ __rvm_reset() {
     $rvm_scripts_path/db "$rvm_config_path/user" "$system_config" "delete"
   done ; unset system_config variable
 
-  rm -f $rvm_bin_path/ruby $rvm_bin_path/gem $rvm_bin_path/rake $rvm_bin_path/irb $rvm_bin_path/default*
+  \rm -f $rvm_bin_path/ruby $rvm_bin_path/gem $rvm_bin_path/rake $rvm_bin_path/irb $rvm_bin_path/default*
 }
 
 # Implode removes the entire rvm installation under $rvm_path.
@@ -391,7 +391,7 @@ __rvm_implode() {
       else
         if [[ -d "$rvm_path" ]] ; then
           $rvm_scripts_path/log "info" "Hai! Removing $rvm_path"
-          rm -rf $rvm_path/
+          \rm -rf $rvm_path/
           echo "$rvm_path has been removed."
         else
           $rvm_scripts_path/log "info" "It appears that $rvm_path is already non existant."
@@ -427,7 +427,7 @@ __rvm_initialize() {
     export PATH
   fi
 
-  mkdir -p "$rvm_src_path" "$rvm_bin_path" "$rvm_archives_path" "$rvm_gems_path" "$rvm_tmp_path" "$rvm_repo_path"
+  \mkdir -p "$rvm_src_path" "$rvm_bin_path" "$rvm_archives_path" "$rvm_gems_path" "$rvm_tmp_path" "$rvm_repo_path"
 }
 
 # Update rubygems or binscripts based on CLI selection.
@@ -448,7 +448,7 @@ __rvm_update() {
 # Update rvm using rubygems
 # If --head was specified, update from git repository master branch.
 __rvm_update_rvm() {
-  mkdir -p "$rvm_src_path"
+  \mkdir -p "$rvm_src_path"
   __rvm_pushpop "$rvm_src_path"
 
   if [[ "$rvm_head_flag" == "1" ]] ; then
@@ -481,7 +481,7 @@ __rvm_reboot() {
     if [[ "/" = "$rvm_path" ]] ; then
       $rvm_scripts_path/log "error" "remove '/' ?!... NO!"
     else
-      if [[ -d "$rvm_path" ]] ; then rm -rf "$rvm_path/" ; fi
+      if [[ -d "$rvm_path" ]] ; then \rm -rf "$rvm_path/" ; fi
     fi
     gem install rvm $rvm_gem_options
     __rvm_update_rvm
@@ -494,7 +494,7 @@ __rvm_reboot() {
 # Create the irbrc for the currently selected ruby installation.
 __rvm_irbrc() {
   if [[ -d "$rvm_ruby_home" ]] && [[ ! -s "$rvm_ruby_irbrc" ]] ; then
-    cp $rvm_scripts_path/irbrc $rvm_ruby_irbrc
+    \cp $rvm_scripts_path/irbrc $rvm_ruby_irbrc
   fi
 }
 
@@ -593,14 +593,14 @@ __rvm_ensure_has_environment_files() {
 
   # Ensure system is a blank file.
   if [[ "$environment_identifier" == "system" ]]; then
-    rm -f "$file_name" 2>&1 | grep -v 'rm: cannot remove .* Permission denied'
-    mkdir -p "$(dirname "$file_name")"
-    touch "$file_name" 2>&1 | grep -v 'touch: cannot touch .* Permission denied'
+    \rm -f "$file_name" 2>&1 | grep -v 'rm: cannot remove .* Permission denied'
+    \mkdir -p "$(dirname "$file_name")"
+    \touch "$file_name" 2>&1 | grep -v 'touch: cannot touch .* Permission denied'
     return
   fi
 
   if [[ ! -s "$file_name" ]] ; then
-    mkdir -p "${rvm_environments_path}"
+    \mkdir -p "${rvm_environments_path}"
     echo "export PATH=\"${rvm_ruby_gem_home}/bin:${rvm_ruby_global_gems_path}/bin:${rvm_ruby_home}/bin:${rvm_bin_path}:\$PATH\"" > $file_name
     for variable in RUBY_VERSION GEM_HOME GEM_PATH BUNDLE_PATH MY_RUBY_HOME IRBRC rvm_ruby_string rvm_gemset_name MAGLEV_HOME ; do
       eval "export $variable"
@@ -620,7 +620,7 @@ __rvm_ensure_has_environment_files() {
     rvm_creating_default_wrappers=1
     directory_name="$rvm_wrappers_path/$wrapper_identifier"
     if [[ ! -L "$directory_name" && ! -d "$directory_name" ]]; then
-      mkdir -p "$directory_name"
+      \mkdir -p "$directory_name"
       $rvm_scripts_path/wrapper "$wrapper_identifier" &> /dev/null
     fi
     unset rvm_creating_default_wrappers directory_name
@@ -695,11 +695,11 @@ __rvm_record_install() {
   local recorded_ruby_name="$($rvm_scripts_path/tools strings "$1")"
   local rvm_install_record_file="$rvm_config_path/installs"
   local rvm_install_command="$(echo "$recorded_ruby_name $rvm_install_arguments" | __rvm_strip)"
-  touch "$rvm_install_record_file"
-  rm -f "$rvm_install_record_file.tmp"
+  \touch "$rvm_install_record_file"
+  \rm -f "$rvm_install_record_file.tmp"
   cat "$rvm_install_record_file" | grep -v "^$recorded_ruby_name " > "$rvm_install_record_file.tmp"
   echo "$rvm_install_command" >> "$rvm_install_record_file.tmp"
-  rm -f "$rvm_install_record_file"
+  \rm -f "$rvm_install_record_file"
   mv "$rvm_install_record_file.tmp" "$rvm_install_record_file"
 }
 
@@ -709,7 +709,7 @@ __rvm_remove_install_record() {
   if [[ -s "$rvm_install_record_file" ]]; then
     mv "$rvm_install_record_file" "$rvm_install_record_file.tmp"
     cat "$rvm_install_record_file.tmp" | grep -v "^$recorded_ruby_name " > "$rvm_install_record_file"
-    rm -f "$rvm_install_record_file.tmp"
+    \rm -f "$rvm_install_record_file.tmp"
   fi
 }
 
