More slow progress making things more robust.

diff --git a/scripts/utility b/scripts/utility
--- a/scripts/utility
+++ b/scripts/utility
@@ -135,9 +135,7 @@ __rvm_warn_on_rubyopt() {
 __rvm_strings() {
   local strings=""
   for rvm_ruby_string in $(echo ${rvm_ruby_args:-$rvm_ruby_string}) ; do
-    #__rvm_ruby_string
     strings="$strings $(__rvm_select ; echo $rvm_ruby_string)"
-    # [[ $? -gt 0 ]] && return 1
   done
   echo $strings
   return 0
@@ -176,45 +174,71 @@ __rvm_remove_rvm_from_path() {
 
 # Run a specified command and log it.
 __rvm_run() {
-  log_file_name="$1" ; command="$2" ; message="$3"
+  local log_file_name="$1"
+  local command="$2"
+  local message="$3"
+
   if [[ -z "$rvm_ruby_log_path" ]] ; then rvm_ruby_log_path="$rvm_log_path" ; fi
+
   if [[ -n "$message" ]] ; then "$rvm_scripts_path/log" "info" "$message" ; fi
+
   if [[ -n "$rvm_debug_flag" ]] ; then
     "$rvm_scripts_path/log" "debug" "Executing: $command"
   fi
 
   \mkdir -p "$(dirname "$rvm_ruby_log_path/$log_file_name.log")"
+
   \touch "$rvm_ruby_log_path/$log_file_name.log" "$rvm_ruby_log_path/$log_file_name.error.log" # for zsh :(
-  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $command" | tee "$rvm_ruby_log_path/$log_file_name.log" >> "$rvm_ruby_log_path/$log_file_name.error.log"
+
+  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $command" | \tee "$rvm_ruby_log_path/$log_file_name.log" >> "$rvm_ruby_log_path/$log_file_name.error.log"
+
   if [[ -z "$rvm_niceness" ]] || [[ "0" = "$rvm_niceness" ]] ; then
     eval "$command" >> "$rvm_ruby_log_path/$log_file_name.log" 2>> "$rvm_ruby_log_path/$log_file_name.error.log"
   else
     eval "nice -n $rvm_niceness $command" >> $rvm_ruby_log_path/$log_file_name.log 2>> $rvm_ruby_log_path/$log_file_name.error.log
+  fi ; local result=$?
+
+  if [[ $result -gt 0 ]] ; then
+    "$rvm_scripts_path/log" "error" "Error running '$command', please check $rvm_ruby_log_path/$log_file_name*.log" ; __rvm_pushpop
   fi
-  if [[ $? -gt 0 ]] ; then "$rvm_scripts_path/log" "error" "Error running '$command', please check $rvm_ruby_log_path/$log_file_name*.log" ; __rvm_pushpop ; return 1 ; fi
-  unset log_file command
+
+  return $result
 }
 
 # Runs a command in a given env.
 __rvm_run_with_env() {
-  log_file_name="$1" ; env_name="$2" ; command="$3" ; message="$4"
+  local log_file_name="$1"
+  local env_name="$2"
+  local command="$3"
+  local message="$4"
+
   if [[ -z "$env_name" ]]; then env_name="$(__rvm_environment_identifier)"; fi
+
   if [[ -z "$rvm_ruby_log_path" ]] ; then rvm_ruby_log_path="$rvm_log_path" ; fi
+
   if [[ -n "$message" ]] ; then "$rvm_scripts_path/log" "info" "$message" ; fi
+
   if [[ -n "$rvm_debug_flag" ]] ; then
     "$rvm_scripts_path/log" "debug" "Executing: $command in environment "$env_name""
   fi
 
   \mkdir -p "$(dirname "$rvm_ruby_log_path/$log_file_name.log")"
+
   \touch "$rvm_ruby_log_path/$log_file_name.log" "$rvm_ruby_log_path/$log_file_name.error.log" # for zsh :(
+
   echo "[$(date +'%Y-%m-%d %H:%M:%S')] $command # under $env_name" | tee "$rvm_ruby_log_path/$log_file_name.log" >> "$rvm_ruby_log_path/$log_file_name.error.log"
+
   if [[ -z "$rvm_niceness" ]] || [[ "0" = "$rvm_niceness" ]] ; then
     eval "__rvm_with_env '$env_name' '$command'" >> "$rvm_ruby_log_path/$log_file_name.log" 2>> "$rvm_ruby_log_path/$log_file_name.error.log"
   else
     eval "nice -n $rvm_niceness __rvm_with_env '$env_name' '$command'" >> $rvm_ruby_log_path/$log_file_name.log 2>> $rvm_ruby_log_path/$log_file_name.error.log
+  fi ; result=$?
+
+  if [[ $result -gt 0 ]] ; then
+    "$rvm_scripts_path/log" "error" "Error running '$command' under $env_name, please check $rvm_ruby_log_path/$log_file_name*.log" ; __rvm_pushpop
   fi
-  if [[ $? -gt 0 ]] ; then "$rvm_scripts_path/log" "error" "Error running '$command' under $env_name, please check $rvm_ruby_log_path/$log_file_name*.log" ; __rvm_pushpop ; return 1 ; fi
-  unset log_file command env_name
+
+  return $result
 }
 
 # Unset both rvm variables as well as ruby-specific variables
@@ -247,14 +271,16 @@ __rvm_with_env() {
 # Returns the first 1.8.7-compatible (partly) ruby for use
 # with things like rbx etc which require a ruby be installed.
 __rvm_18_compat_ruby() {
-  rubies=""
+  local rubies=""
   for ruby_name in $(\ls "$rvm_rubies_path"); do
     if [[ ! -L "$rvm_rubies_path/$ruby_name" ]] && [[ "$ruby_name" =~ 1.8. || "$ruby_name" =~ rbx- || "$ruby_name" =~ ree- ]] ; then
       rubies="$rubies $ruby_name"
     fi
   done; unset ruby_name
+
   echo "$rubies" | sed 's/^ //' | \tr ' ' '\n' | sort | tail -n1
-  unset rubies
+
+  return 0
 }
 
 __rvm_ensure_has_18_compat_ruby() {
@@ -266,23 +292,32 @@ __rvm_ensure_has_18_compat_ruby() {
       "$rvm_scripts_path/log" "fail" "Please install it manually (or a compatible alternative) to proceed."
       compat_result=1
     fi ; unset original_ruby
+    # TODO: Why are we unsetting original_ruby here
     return $compat_result
   fi
+
+  return 0
 }
 
 __rvm_inherit_trace_flag() {
   if [[ -n "$rvm_trace_flag" ]]; then
     set -x ; export rvm_trace_flag
   fi
+  return 0
 }
 
 # Cleans up temp folders for a given prefix,
 # typically the current process id.
 __rvm_cleanup_temp_for() {
-  [[ -z "$1" ]] && return 1
+  local prefix="$1"
+
+  [[ -z "$prefix" ]] && return 1
+
   if [[ -d "$rvm_tmp_path/" ]]; then
-    \rm -rf "$rvm_tmp_path/$1"* >/dev/null 2>&1
-  fi ; exit
+    \rm -rf "$rvm_tmp_path/$prefix"* >/dev/null 2>&1
+  fi
+
+  exit
 }
 
 __rvm_cleanup_temp_on_exit() {
@@ -299,6 +334,7 @@ __rvm_set_rvmrc() {
     fi
 
     local identifier=$(__rvm_environment_identifier)
+
     printf "if [[ -n \"\$rvm_environments_path\" && -s \"\$rvm_environments_path/$identifier\" ]] ; then\n  \\. \"\$rvm_environments_path/$identifier\"" > .rvmrc
     printf "\nelse\n  rvm --create $flags \"$identifier\"\nfi" >> .rvmrc
 
@@ -308,7 +344,8 @@ __rvm_set_rvmrc() {
   fi
 }
 __rvm_load_rvmrc() {
-  [[ -z "$rvm_ignore_rvmrc" ]] && return
+  [[ -z "$rvm_ignore_rvmrc" ]] && return 0
+
   for rvmrc in /etc/rvmrc $HOME/.rvmrc ; do
     if [[ -f "$rvmrc" ]] ; then
       if \grep -q '^\s*rvm .*$' $rvmrc ; then
@@ -319,6 +356,8 @@ __rvm_load_rvmrc() {
       fi
     fi
   done
+
+  return 0
 }
 
 # Wrap the specified ruby code file in a Benchmark.bmbm block and execute it.
@@ -333,14 +372,16 @@ __rvm_benchmark() {
   rvm_action="ruby"
   if [[ -n "$rvm_debug_flag" ]] ; then printf "\n$rvm_tmp_path/$$.rb:\n$(cat $rvm_tmp_path/$$.rb)" ; fi
   # Override ruby string stuff, pass through.
-  old_rvm_ruby_string=$rvm_ruby_string
+  local old_rvm_ruby_string=$rvm_ruby_string
+  # TODO: We can likely do this in a subshell in order to preserve the original environment?
   unset rvm_ruby_string
   export rvm_ruby_strings
   "$rvm_scripts_path/set" "$rvm_action" $rvm_ruby_args
   result=$?
   # Restore the state pre-sets.
   [[ -n "$old_rvm_ruby_string" ]] && rvm_ruby_string=$old_rvm_ruby_string
-  unset old_rvm_ruby_string
+
+  return $result
 }
 
 # Loop over the currently installed rubies and refresh their binscripts.
@@ -352,12 +393,14 @@ __rvm_bin_scripts() {
       __rvm_bin_script
     fi
   done
+  return 0
 }
 
 # Write the bin/ wrapper script for currently selected ruby.
 # TODO: Adjust binscript to be able to handle all rubies not just the standard interpreteres.
 __rvm_bin_script() {
   "$rvm_scripts_path/wrapper" "$rvm_ruby_string"
+  return $?
 }
 
 # Add bin path if not present
@@ -366,18 +409,20 @@ __rvm_conditionally_add_bin_path() {
     PATH="${rvm_bin_path}:$PATH"
     builtin hash -r
   fi
+  return 0
 }
 
 # Reset any rvm gathered information about the system and its state.
 # rvm will refresh the stored information the next time it is called after reset.
 __rvm_reset() {
-  __rvm_remove_rvm_from_path
-  __rvm_conditionally_add_bin_path
-  export PATH
+  __rvm_remove_rvm_from_path ; __rvm_conditionally_add_bin_path ; export PATH
+
   builtin hash -r
 
-  for flag in default passenger editor ; do \rm -f "$rvm_bin_path"/${flag}_* ; done
-  unset flag
+  local flag=""
+  for flag in default passenger editor ; do
+    \rm -f "$rvm_bin_path"/${flag}_*
+  done
 
   for file in system default ; do
     [[ -f "${rvm_path}/${file}" ]] && \rm -f "$rvm_path/${file}"
@@ -394,13 +439,17 @@ __rvm_reset() {
   done ; unset system_config variable
 
   \rm -f $rvm_bin_path/ruby $rvm_bin_path/gem $rvm_bin_path/rake $rvm_bin_path/irb $rvm_bin_path/default*
+
+  return 0
 }
 
 # Implode removes the entire rvm installation under $rvm_path.
 __rvm_implode() {
   while : ; do
     "$rvm_scripts_path/log" "warn" "Are you SURE you wish for rvm to implode? This will remove $rvm_path ? (type 'yes' or 'no')"
+
     read response
+
     if [[ "yes" = "$response" ]] ; then
       if [[ "/" = "$rvm_path" ]] ; then
         "$rvm_scripts_path/log" "error" "remove '/' ?!... Ni!"
@@ -419,16 +468,21 @@ __rvm_implode() {
       break
     fi
   done
+
+  return 0
 }
 
 # Output the current ruby's rvm source path.
 __rvm_source_dir() {
   if [[ -z "$rvm_ruby_selected_flag" ]] ; then __rvm_select ; fi
+
   if [[ -z "$rvm_ruby_src_path" ]] ; then
     "$rvm_scripts_path/log" "fail" "No source directory exists for the default implementation."
   else
     echo "$rvm_ruby_src_path"
   fi
+
+  return 0
 }
 
 # Initialize rvm, ensuring that the path and directories are as expected.
@@ -436,33 +490,40 @@ __rvm_initialize() {
   rvm_ruby_load_path="."
   rvm_ruby_require=""
 
-  __rvm_clean_path
-
-  __rvm_conditionally_add_bin_path
-  export PATH
+  __rvm_clean_path ; __rvm_conditionally_add_bin_path ; export PATH
 
   \mkdir -p "$rvm_src_path" "$rvm_bin_path" "$rvm_archives_path" "$rvm_gems_path" "$rvm_tmp_path" "$rvm_repo_path"
+
+  return 0
 }
 
 # Update rubygems or binscripts based on CLI selection.
 __rvm_update() {
   __rvm_pushpop $rvm_path
+
   if [[ "$rvm_head_flag" == "1" ]] || [[ -n "$rvm_self_flag" ]] || [[ "update" = "$rvm_action" ]] || [[ -n "$rvm_update_flag" ]] ; then
     __rvm_version
     __rvm_update_rvm
   fi
+
   [[ -n "$rvm_bin_flag" ]] && __rvm_bin_scripts
+
   # Update to the latest rubygems.
   [[ -n "$rvm_rubygems_flag" ]] && "$rvm_scripts_path/rubygems" current
 
   unset rvm_update_flag rvm_action rvm_self_flag rvm_ruby_revision rvm_bin_flag rvm_rubygems_flag
+
   __rvm_pushpop
+
+  return 0
 }
 
 # Update rvm using rubygems
 # If --head was specified, update from git repository master branch.
 __rvm_update_rvm() {
+
   \mkdir -p "$rvm_src_path"
+
   __rvm_pushpop "$rvm_src_path"
 
   if [[ "$rvm_head_flag" == "1" ]] ; then
@@ -482,27 +543,42 @@ __rvm_update_rvm() {
   fi
 
   __rvm_pushpop
+
   rvm_hook="after_update" ; source "$rvm_scripts_path/hook"
+
+  return 0
 }
 
 __rvm_reboot() {
   "$rvm_scripts_path/log" "warn" "Do you wish to reboot rvm? ('yes', or 'no')"
+
+  local response="no"
+
   read response
+
   if [[ "yes" = "$response" ]] ; then
     builtin cd $rvm_path
+
     __rvm_reset
+
     mv "$rvm_path/archives" "$HOME/.archives"
+
     if [[ "/" = "$rvm_path" ]] ; then
       "$rvm_scripts_path/log" "error" "remove '/' ?!... NO!"
     else
       if [[ -d "$rvm_path" ]] ; then \rm -rf "$rvm_path/" ; fi
     fi
+
     gem install rvm $rvm_gem_options
+
     __rvm_update_rvm
+
     source $rvm_path/scripts/rvm
   else
     "$rvm_scripts_path/log" "info" "Carry on then..."
-  fi ; unset response
+  fi
+
+  return 0
 }
 
 # Create the irbrc for the currently selected ruby installation.
@@ -510,6 +586,8 @@ __rvm_irbrc() {
   if [[ -d "$rvm_ruby_home" ]] && [[ ! -s "$rvm_ruby_irbrc" ]] ; then
     \cp "$rvm_scripts_path/irbrc" "$rvm_ruby_irbrc"
   fi
+
+  return 0
 }
 
 # Push or Pop a directory based on zero or one directory argument provided.
@@ -519,6 +597,8 @@ __rvm_pushpop() {
   else
     pushd "$1" > /dev/null 2>&1
   fi
+
+  return $?
 }
 
 # Save or restore the rvm's state. This is a toggle action.
@@ -538,13 +618,19 @@ __rvm_state() {
     __rvm_use
     unset rvm_state
   fi
+
+  return 0
 }
 
 # Output an inspection of selected 'binary' scripts, based on CLI selection.
 __rvm_inspect() {
+
   for binary in $rvm_ruby_args ; do
+
     actual_file="$(command -v $binary)"
+
     "$rvm_scripts_path/log" "info" "$actual_file:"
+
     if [[ -n "$rvm_shebang_flag" ]] ; then head -n 1    < "$actual_file" ; fi
     if [[ -n "$rvm_env_flag" ]]     ; then awk '/ENV/'  < "$actual_file" ; fi
     if [[ -n "$rvm_path_flag" ]]    ; then awk '/PATH/' < "$actual_file" ; fi
@@ -552,6 +638,8 @@ __rvm_inspect() {
     if [[ -n "$rvm_tail_flag" ]]    ; then tail -n 5    < "$actual_file" ; fi
     if [[ -n "$rvm_all_flag" ]]     ; then cat $actual_file              ; fi
   done
+
+  return 0
 }
 
 # Attempt to override the Darwin build settings for rubies
@@ -585,6 +673,8 @@ __rvm_make_flags() {
       # CXXFLAGS="-mmacosx-version-min="$(sw_vers -productVersion | awk -F'.' '{print $1"."$2}')" -isysroot /Developer/SDKs/$rvm_sdk " ; export CXXFLAGS
     fi
   fi
+
+  return 0
 }
 
 __rvm_mono_env() {
@@ -595,23 +685,35 @@ __rvm_mono_env() {
   export PKG_CONFIG_PATH="$rvm_usr_path/lib/pkgconfig:$PKG_CONFIG_PATH"
   PATH="$rvm_usr_path/bin:$PATH"
   builtin hash -r
+
+  return 0
 }
 
 __rvm_become() {
-  [[ -n "$1" ]] && rvm_ruby_string="$1"
+  local string="$1"
+
+  [[ -n "$string" ]] && rvm_ruby_string="$string"
+
   { __rvm_ruby_string && __rvm_select && __rvm_use; } > /dev/null 2>&1
+
+  return 0
 }
 
 __rvm_ensure_has_environment_files() {
   local environment_identifier="$(__rvm_environment_identifier)"
+
   local file_name="${rvm_environments_path}/$environment_identifier"
 
   if [[ ! -s "$file_name" ]] ; then
     \mkdir -p "${rvm_environments_path}"
+
     echo "export PATH=\"${rvm_ruby_gem_home}/bin:${rvm_ruby_global_gems_path}/bin:${rvm_ruby_home}/bin:${rvm_bin_path}:\$PATH\"" > "$file_name"
+
     for variable in RUBY_VERSION GEM_HOME GEM_PATH BUNDLE_PATH MY_RUBY_HOME IRBRC rvm_ruby_string rvm_gemset_name MAGLEV_HOME ; do
       eval "export $variable"
+
       eval "value=\$${variable}"
+
       if [[ -n "$value" ]] ; then
         printf "${variable}='$value'\nexport ${variable}\n" >> "$file_name"
       else
@@ -620,28 +722,36 @@ __rvm_ensure_has_environment_files() {
     done ; unset variable value
   fi ; unset file_name
 
+  local directory_name=""
+  local wrapper_identifier=""
   # Next, ensure we have default wrapper files. Also, prevent it from recursing.
   if [[ -z "$rvm_creating_default_wrappers" ]]; then
     # We need to generate wrappers for both the default gemset and the global gemset.
     for wrapper_identifier in "$environment_identifier" "${environment_identifier}@global" ; do
-    rvm_creating_default_wrappers=1
-    directory_name="$rvm_wrappers_path/$wrapper_identifier"
-    if [[ ! -L "$directory_name" && ! -d "$directory_name" ]]; then
-      \mkdir -p "$directory_name"
-      "$rvm_scripts_path/wrapper" "$wrapper_identifier" &> /dev/null
-    fi
-    unset rvm_creating_default_wrappers directory_name
-    done; unset wrapper_identifier
+
+      rvm_creating_default_wrappers=1
+
+      directory_name="$rvm_wrappers_path/$wrapper_identifier"
+
+      if [[ ! -L "$directory_name" && ! -d "$directory_name" ]]; then
+        \mkdir -p "$directory_name"
+
+        "$rvm_scripts_path/wrapper" "$wrapper_identifier" &> /dev/null
+      fi
+      unset rvm_creating_default_wrappers
+    done
   fi
 }
 
 # Strip whitespace and normalize it all.
 __rvm_strip() {
   sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/[[:space:]]\{1,\}/ /g'
+  return 0
 }
 
 __rvm_using_gemset_globalcache() {
   "$rvm_scripts_path/db" "$rvm_config_path/user" "use_gemset_globalcache" | \grep -q '^true$'
+  return 0
 }
 
 __rvm_current_gemcache_dir() {
@@ -650,40 +760,59 @@ __rvm_current_gemcache_dir() {
   else
     echo "${rvm_ruby_gem_home:-"$GEM_HOME"}/cache"
   fi
+  return 0
 }
 
 __rvm_Answer_to_the_Ultimate_Question_of_Life_the_Universe_and_Everything() {
   for index in {1..750} ; do sleep 0.25 ; echo -n '.' ; done ; printf "%d" 0x2A ; echo
+  return 0
 }
 
 __rvm_ultimate_question() {
-  printf "\nI do not know the Ultimate Question, "
-  printf "\nhowever I can help you build a more "
-  printf "\npowerful Ruby which can compute the "
-  printf "\nUltimate Question.\n"
+  printf "
+  I do not know the Ultimate Question,
+  however I can help you build a more
+  powerful Ruby which can compute the
+  Ultimate Question.
+  "
+  return 0
 }
 
 __rvm_load_env_file() {
-  if [[ -f "$rvm_environments_path/$1" ]]; then
+  local string="$1"
+  if [[ -f "$rvm_environments_path/$string" ]]; then
     # Restore the path to it's state minus rvm
     __rvm_remove_rvm_from_path
-    \. "$rvm_environments_path/$1"
+
+    # source the environment file
+    \. "$rvm_environments_path/$string"
+
+    # clear the PATH cache
     builtin hash -r
+  elif [[ -n "$string" ]] ; then
+    rvm "$string"
   else
-    rvm use "$1" >/dev/null 2>&1
+    : # TODO: This should have some error handling in the context.
   fi
+  return 0
 }
 
 __rvm_md5_for() {
   if command -v md5 > /dev/null; then
     echo "$1" | md5
-  else
+  elif command -v md5sum > /dev/null ; then
     echo "$1" | md5sum | awk '{print $1}'
+  else
+    "$rvm_path/scripts/log" "error" "Neither md5 nor md5sum were found in the PATH"
+    return 1
   fi
+
+  return 0
 }
 
 __rvm_rvmrc_key() {
   __rvm_md5_for "$1"
+  return $?
 }
 
 __rvm_reset_rvmrc_trust() {
