Feature: 'rvm install jruby 1.4.1; rvm use jruby 1.4.0. Bugfix: Do not let the dog chase it's tail :)

diff --git a/scripts/utility b/scripts/utility
--- a/scripts/utility
+++ b/scripts/utility
@@ -161,6 +161,7 @@ function __rvm_fetch {
     __rvm_log "debug" "No archive or no MD5, downloading"
     download=1
   fi
+
   if [ $download -gt 0 ] ; then
     eval $rvm_fetch "$1"
     result=$?
@@ -170,13 +171,18 @@ function __rvm_fetch {
       elif [ $result -eq 33 ] ; then
         __rvm_log "debug" "Server does not support 'range' command, removing '$archive'"
         rm -f $archive
-        __rvm_fetch "$1"
+        eval $rvm_fetch "$1"
+        result=$?
+        if [ $result -gt 0 ] ; then
+          __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
+        fi
       else
         __rvm_log "error" "There was an error, please check $rvm_ruby_log_path/*.error.log"
       fi
     fi
     __rvm_pushpop
   fi
+
   unset archive
   unset download
   return $result
