sgr0 is safer than setaf 9.

diff --git a/scripts/utility b/scripts/utility
--- a/scripts/utility
+++ b/scripts/utility
@@ -84,10 +84,10 @@ fi
 
 # Logging functions
 if [[ ${rvm_interactive_flag:-0} -eq 1 ]]; then
-  eval "rvm_log()   { printf \"\$(tput setaf 2)\$*\$(tput setaf 9)\n\" ; }"
-  eval "rvm_debug() { printf \"\$(tput setaf 5)DEBUG: \$*\$(tput setaf 9)\n\" ; }"
-  eval "rvm_warn()  { printf \"\$(tput setaf 3)WARN: \$*\$(tput setaf 9)\n\" ; }"
-  eval "rvm_error() { printf \"\$(tput setaf 1)ERROR: \$*\$(tput setaf 9)\n\" >&2 ; }"
+  eval "rvm_log()   { printf \"\$(tput setaf 2)\$*\$(tput sgr0)\n\" ; }"
+  eval "rvm_debug() { printf \"\$(tput setaf 5)DEBUG: \$*\$(tput sgr0)\n\" ; }"
+  eval "rvm_warn()  { printf \"\$(tput setaf 3)WARN: \$*\$(tput sgr0)\n\" ; }"
+  eval "rvm_error() { printf \"\$(tput setaf 1)ERROR: \$*\$(tput sgr0)\n\" >&2 ; }"
 else
   rvm_log()   { printf "$*\n" ; }
   rvm_debug() { printf "DEBUG: $*\n" ; }
