Implement rvm snapshot {save,load}

diff --git a/scripts/utility b/scripts/utility
--- a/scripts/utility
+++ b/scripts/utility
@@ -217,9 +217,9 @@ __rvm_ensure_has_18_compat_ruby() {
   if [[ -z "$(__rvm_18_compat_ruby)" ]]; then
     # TODO: install currently doesn't return the correct status.
     local compat_result=0
-    if ! ( rvm install 1.8.7 ); then
-      $rvm_scripts_path/log "fatal" "To proceed rvm requires a 1.8-compatible ruby is installed. We attempted to install 1.8.7 automatically but it failed."
-      $rvm_scripts_path/log "fatal" "Please install it manually (or a compatible alternative) to proceed."
+    if ! ( $rvm_scripts_path/manage install 1.8.7 ); then
+      $rvm_scripts_path/log "fail" "To proceed rvm requires a 1.8-compatible ruby is installed. We attempted to install 1.8.7 automatically but it failed."
+      $rvm_scripts_path/log "fail" "Please install it manually (or a compatible alternative) to proceed."
       compat_result=1
     fi
     unset original_ruby
