Altered logging function definitions.

diff --git a/scripts/utility b/scripts/utility
--- a/scripts/utility
+++ b/scripts/utility
@@ -84,17 +84,10 @@ fi
 
 # Logging functions
 if [[ ${rvm_interactive_flag:-0} -eq 1 ]]; then
-  color_normal="$(tput setaf 9)"
-  color_red="$(tput setaf 1)"
-  color_green="$(tput setaf 2)"
-  color_magenta="$(tput setaf 5)"
-  color_yellow="$(tput setaf 3)"
-
-  eval "rvm_log()   { printf \"${color_green}\$*${color_normal}\n\" ; }"
-  eval "rvm_debug() { printf \"${color_magenta}DEBUG: \$*${color_normal}\n\" ; }"
-  eval "rvm_warn()  { printf \"${color_yellow}WARN: \$*${color_normal}\n\" ; }"
-  eval "rvm_error() { printf \"${color_red}ERROR: \$*${color_normal}\n\" >&2 ; }"
-  unset color_green color_magenta color_yellow color_red color_normal
+  eval "rvm_log()   { printf \"\$(tput setaf 2)\$*\$(tput setaf 9)\n\" ; }"
+  eval "rvm_debug() { printf \"\$(tput setaf 5)DEBUG: \$*\$(tput setaf 9)\n\" ; }"
+  eval "rvm_warn()  { printf \"\$(tput setaf 3)WARN: \$*\$(tput setaf 9)\n\" ; }"
+  eval "rvm_error() { printf \"\$(tput setaf 1)ERROR: \$*\$(tput setaf 9)\n\" >&2 ; }"
 else
   rvm_log()   { printf "$*\n" ; }
   rvm_debug() { printf "DEBUG: $*\n" ; }
