Very slowly cleaning everything up.

diff --git a/scripts/wrapper b/scripts/wrapper
--- a/scripts/wrapper
+++ b/scripts/wrapper
@@ -14,14 +14,15 @@ wrap() {
   \mkdir -p "$(dirname "$file_name")"
   \rm -f "$file_name"
 
-  echo "#!/usr/bin/env sh" > "$file_name"
-  echo "if [ -s \"${rvm_environments_path}/${environment_identifier}\" ] ; then" >> "$file_name"
-  echo "  \\. \"${rvm_environments_path}/${environment_identifier}\"" >> "$file_name"
-  echo "  exec $binary_name \"\$@\"" >> "$file_name"
-  echo "else" >> $file_name
-  echo "  echo \"ERROR: Missing RVM environment file: '${rvm_environments_path}/${environment_identifier}'\"" >> $file_name
-  echo "  exit 1" >> $file_name
-  echo "fi" >> $file_name
+  printf "#!/usr/bin/env sh\n
+if [ -s \"${rvm_environments_path}/${environment_identifier}\" ] ; then
+  \\. \"${rvm_environments_path}/${environment_identifier}\"
+  exec $binary_name \"\$@\"
+else
+  echo \"ERROR: Missing RVM environment file: '${rvm_environments_path}/${environment_identifier}'\"
+  exit 1
+fi
+  " > $file_name
 
   if [[ -f $file_name ]] ; then chmod +x $file_name ; fi
 }
@@ -53,18 +54,12 @@ usage() {
 }
 
 # Empty ruby string: show usage and exit.
-
-if [[ -z "$1" ]]; then
-  usage
-  exit 1
-fi
+if [[ -z "$1" ]]; then usage ; exit 1 ; fi
 
 ruby_string="$1"; shift
-
 override_check=0
 prefix="$1"
 [[ "$#" -gt 0 ]] && shift
-
 binaries="$(echo "$@" | __rvm_strip)"
 
 # Default the list of binaries to those we use regularily.
