Attempting to debug the wrapper regeneration.

diff --git a/scripts/wrapper b/scripts/wrapper
--- a/scripts/wrapper
+++ b/scripts/wrapper
@@ -43,7 +43,7 @@ if [[ -s \"$path/environments/${environment_identifier}\" ]] ; then
   \\. \"$path/environments/${environment_identifier}\"
   exec $binary_name \"\$@\"
 else
-  echo \"ERROR: Missing RVM environment file: '$path/environments/${environment_identifier}'\"
+  echo \"ERROR: Missing RVM environment file: '$path/environments/${environment_identifier}'\" >&2
   exit 1
 fi
   " > "$file_name"
@@ -57,7 +57,7 @@ fi
   else
 
     "$rvm_path/scripts/log" "error" \
-      "wrap() : file_name unset variable."
+      "wrap() : file_name unkown variable for wrap()."
 
     return 1
 
