Refactor the generated wrappers

diff --git a/scripts/wrapper b/scripts/wrapper
--- a/scripts/wrapper
+++ b/scripts/wrapper
@@ -20,13 +20,14 @@ wrap() {
   mkdir -p "$(dirname "$file_name")"
   rm -f "$file_name"
 
-  printf "#!/usr/bin/env sh\n" > "$file_name"
-  printf "if [ -s \"${rvm_environments_path}/${environment_identifier}\" ] ; then\n" >> "$file_name"
-  printf "  . \"${rvm_environments_path}/${environment_identifier}\"\n" >> "$file_name"
-  printf "  exec $binary_name \"\$@\"\n" >> "$file_name"
-  printf "else" >> $file_name
-  printf "  printf \"ERROR: Missing RVM environment file:\n '${rvm_environments_path}/${environment_identifier}'\n\" ; exit 1" >> $file_name
-  printf "fi" >> $file_name
+  echo "#!/usr/bin/env sh" > "$file_name"
+  echo "if [ -s \"${rvm_environments_path}/${environment_identifier}\" ] ; then" >> "$file_name"
+  echo "  . \"${rvm_environments_path}/${environment_identifier}\"" >> "$file_name"
+  echo "  exec $binary_name \"\$@\"" >> "$file_name"
+  echo "else" >> $file_name
+  echo "  echo \"ERROR: Missing RVM environment file: '${rvm_environments_path}/${environment_identifier}'\"" >> $file_name
+  echo "  exit 1" >> $file_name
+  echo "fi" >> $file_name
 
   if [[ -f $file_name ]] ; then chmod +x $file_name ; fi
 }
